### ISSUE TITLE
Prevent automatically jumping to location list when errors are returned by a maker

### ISSUE THREAD

**Issue by pmalek** [neomake/neomake#1004]
I am using neomake with pylint for python code, with pylint being run on `BufWritePost` and it really bothers me when by cursor gets automatically moved to location list which opens after I get results from pylint. I tried to look for a similar issue but couldn't find one (is that the issue https://github.com/neomake/neomake/issues/313 ?)

### Expected behavior

Get the location list with errors, warnings etc. show up but leave the cursor where it's at.

#### Neomake debug information
Async support: 1
Current filetype: python

##### Enabled makers
For the current filetype (with :Neomake):
 - pylint
   postprocess: function('neomake#makers#ft#python#PylintEntryProcess')
   errorformat: '%A%f:%l:%c:%t: %m,%A%f:%l: %m,%A%f:(%l): %m,%-Z%p^%.%#,%-G%.%#'
   args: ['--output-format=text', '--msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg}"', '--reports=no']
   get_argv: function('376', {'get_argv': function('376')})
   exe: 'pylint'
NOTE: you can define g:neomake_python_enabled_makers to configure it (or b:neomake_python_enabled_makers).

For the project (with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_open_list = 1
g:neomake_error_sign = {'texthl': 'ErrorMsg', 'text': 'E>'}
g:neomake_place_signs = 1
g:neomake_message_sign = {'texthl': 'NeomakeMessageSign', 'text': 'I>'}
g:neomake_python_enabled_makers = ['pylint']
g:neomake_warning_sign = {'texthl': 'NeomakeWarningSign', 'text': 'W>'}


shell: /usr/local/bin/zsh
shellcmdflag: -c
Windows: 0
```

#### :version
```

NVIM v0.2.0-484-g5527754f9
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/USER/programming/git/neovim/build/config -I/home/USER/programming/git/neovim/src -I/home/USER/programming/git/neovim/.deps/usr/include -I/home/USER/programming/git/neovim/.deps/usr/include -I/home/USER/programming/git/neovim/.deps/usr/include -I/home/USER/programming/git/neovim/.deps/usr/include -I/home/USER/programming/git/neovim/.deps/usr/include -I/home/USER/programming/git/neovim/.deps/usr/include -I/usr/include -I/home/USER/programming/git/neovim/build/src/nvim/auto -I/home/USER/programming/git/neovim/build/include
Compiled by USER@icanseeyou

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/USER/bin/nvim/share/nvim"

```

#### :messages
```
NVIM v0.2.0-484-g5527754f9
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/USER/programming/git/neovim/build/config -I/home/USER/programming/git/neovim/src -I/home/USER/programming/git/neovim/.deps/usr/include -I/home/USER/programming/git/neovim/.deps/usr/include -I/home/USER/programming/git/neovim/.deps/usr/include -I/home/USER/programming/git/neovim/.deps/usr/include -I/home/USER/programming/git/neovim/.deps/usr/include -I/home/USER/programming/git/neovim/.deps/usr/include -I/usr/include -I/home/USER/programming/git/neovim/build/src/nvim/auto -I/home/USER/programming/git/neovim/build/include
NVIM v0.2.0-484-g5527754f9
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/USER/programming/git/neovim/build/config -I/home/USER/programming/git/neovim/src -I/home/USER/programming/git/neovim/.deps/usr/include -I/home/USER/programming/git/neovim/.deps/usr/include -I/home/USER/programming/git/neovim/.deps/usr/include -I/home/USER/programming/git/neovim/.deps/usr/include -I/home/USER/programming/git/neovim/.deps/usr/include -I/home/USER/programming/git/neovim/.deps/usr/include -I/usr/include -I/home/USER/programming/git/neovim/build/src/nvim/auto -I/home/USER/programming/git/neovim/build/include
```

**Comment by blueyed** [comment]
`let g:neomake_open_list = 2` ?

**Comment by pmalek** [comment]
Omg, that's exactly it! Thanks a lot. I tried to go through help carefully but it seems that I missed it anyway. This can be closed then.

**Comment by blueyed** [comment]
Yeah, it's kind of a weird setting.. nobody is using `1` for it probably.
I can see for it to make sense when manually invoking `:Neomake`, but not with autocommands.

**Comment by jpulec** [comment]
Not sure if this is an issue with neomake or neovim, but this appears to no longer work as of neovim 0.2. Even with `g:neomake_open_list=2` the cursor now jumps to the location list after a maker has run.

**Comment by blueyed** [comment]
@jpulec 
Are you using vim-qf by chance?  See https://github.com/neomake/neomake/issues/1097 then.
Otherwise please create a new issue with steps to reproduce it.

**Comment by jpulec** [comment]
@blueyed Ah. Yep. I am. Thanks for the info. I'll see that issue.
