### ISSUE TITLE
function neomake#Sh's second argument callback not work

### ISSUE THREAD

**Issue by tracyone** [neomake/neomake#1013]
ubuntu 16.04 vim 8.0 1-300

I tried to use function neomake#Sh to run external command

here is the example

```vim
function! AfterExit(job_status)
    echom "callback"
endfunction

 autocmd User NeomakeJobFinished call OnNeomakeFinished()

call neomake#Sh('touch test_file', function('AfterExit'))

```

test_file have been created successfully, but string "callback" not showing in `:message`

**Comment by blueyed** [comment]
@tracyone 
So it worked after all?

**Comment by tracyone** [comment]
No.

I try to make a plugin base on neomake.

I found another way...

[neomake-multiprocess](https://github.com/tracyone/neomake-multiprocess)

**Comment by blueyed** [comment]
I fixed it anyway.. ;)
https://github.com/neomake/neomake/pull/1018
