### ISSUE TITLE
How to just reset warnings without fixing it?

### ISSUE THREAD

**Issue by unclechu** [neomake/neomake#1021]
I'm looking for same behavior like `:SyntasticReset`

**Comment by blueyed** [comment]
Not easily possible AFAIK through a command.
We should add it.
What should it do? Reset the signs and highlights only, or more?

**Comment by unclechu** [comment]
@blueyed It should get me to state before I run any checking/linting etc, I mean not to previous state of previous checking result, but it should remove any footprints that it ever been checked by Neomake. So it should remove any warnings/errors from 'quickfix' and its marks at lines.

**Comment by blueyed** [comment]
Closing in favor of #1342.
