### ISSUE TITLE
Command to hide signs

### ISSUE THREAD

**Issue by mastertinner** [neomake/neomake#1028]
I'm using Neomake with Junegunn's [Goyo](https://github.com/junegunn/goyo.vim). When I enter Goyo, I would like to hide the Neomake signs. Is there a certain command to hide the signs? I tried `let g:neomake_place_signs=0` and `NeomakeCancelJobs` but neither of them would do the trick...

**Comment by blueyed** [comment]
`let g:neomake_place_signs=0` would only not create new signs, but keep existing ones.

Related: https://github.com/neomake/neomake/issues/1021

**Comment by mastertinner** [comment]
Thanks for your quick reply, @blueyed. The two issues are indeed related. For my use case, I think it would be sufficient if either we had a `:NeomakeReset` command or if `let g:neomake_place_signs=0` would also hide existing signs.

**Comment by mhinz** [comment]
If your Vim is recent enough, you can also `:set signcolumn=no`. If I remember correctly, Goyo exposed events like `GoyoEnter` and `GoyoClose` (the name might be slightly different). Combining both with an autocmd should do what you want.

**Comment by mastertinner** [comment]
Thanks, @mhinz! When running `:set signcolumn=no`, I get `E518: Unknown option: signcolumn=no`. What does work for me however, is `:sign unplace *`. So now I registered this command with `GoyoEnter` and the `:Neomake` command with `GoyoClose`. This works well.

```vim
autocmd! User GoyoEnter nested call <SID>goyo_enter()
autocmd! User GoyoLeave nested call <SID>goyo_leave()
function! s:goyo_enter()
  let g:neomake_place_signs=0
  sign unplace *
endfunction
function! s:goyo_leave()
  let g:neomake_place_signs=1
  Neomake
endfunction
```

Thanks a lot for your help!
