### ISSUE TITLE
Shellcheck not working

### ISSUE THREAD

**Issue by mastertinner** [neomake/neomake#1029]
In my current setup, Neomake somehow doesn't work with ShellCheck. Neomake is working correctly with other file types (e.g. TypeScript, Markdown or Go) and their linters. It shows signs and error messages correctly. With `.sh` files, however, there are no signs or error messages. If I open the following file in vim and run `:Neomake`, nothing happens. If I run `shellcheck -fgcc file.sh` on it however, it outputs a couple of errors.

File:

```shell
#!/bin/sh

if a
```

Direct commands:

```shell
$ shellcheck -fgcc file.sh
file.sh:3:1: error: Couldn't parse this if expression. [SC1073]
file.sh:4:1: error: Expected 'then'. [SC1050]
file.sh:4:1: error: Expected 'then'. Fix any mentioned problems and try again. [SC1072]
```

I'm using macOS `10.12.3` with Neovim `0.1.7`, ShellCheck `0.4.5` and the latest Neomake. Here are my dotfiles for reference: https://github.com/mastertinner/dotfiles/tree/master/vim

Here are the `:messages`:

```txt
Neomake [2808.958]: Running makers: sh, shellcheck
Neomake [2808.960]: [20] Starting async job: ['/bin/sh', '-n', '/Users/Tobi/Desktop/file.sh']
Neomake [2808.964]: [20] Starting async job: ['shellcheck', '-fgcc', '/Users/Tobi/Desktop/file.sh']
Neomake [2808.968]: [20.71] stderr: sh: ['/Users/Tobi/Desktop/file.sh: line 4: syntax error: unexpected end of file', '']
Neomake [2810.105]: [20.71] exit: sh: 2
Neomake [2810.105]: [20.71] sh: processing 1 lines of output.
Neomake [2810.106]: File-level errors cleaned in buffer 1
Neomake [2810.107]: Skipping User autocmd NeomakeCountsChanged: no hooks.
Neomake [2810.108]: [20.71] sh: completed with exit code 2.
Neomake [2810.108]: [20.71] Cleaning jobinfo
Neomake [2810.108]: Skipping User autocmd NeomakeJobFinished: no hooks.
Neomake [2810.109]: [20.72] stderr: shellcheck: ['/Users/Tobi/Desktop/file.sh: /Users/Tobi/Desktop/file.sh: openBinaryFile']
Neomake [2810.688]: [20.72] stderr: shellcheck: [': does not exist (No such file or directory)', '']
Neomake [2810.690]: [20.72] exit: shellcheck: 2
Neomake [2810.690]: [20.72] shellcheck: processing 1 lines of output.
Neomake [2810.691]: Skipping User autocmd NeomakeCountsChanged: no hooks.
Neomake [2810.692]: [20.72] shellcheck: completed with exit code 2.
Neomake [2810.692]: [20.72] Cleaning jobinfo
Neomake [2810.692]: Skipping User autocmd NeomakeJobFinished: no hooks.
Neomake [2810.693]: Skipping User autocmd NeomakeFinished: no hooks.
```

### Output of the ":verb NeomakeInfo" command

```txt
#### Neomake debug information
Async support: 1
Current filetype: sh

##### Enabled makers
For the current filetype (with :Neomake):
 - sh
   errorformat: '%f: line %l: %m,%f: %l: %m'
   args: ['-n']
   get_argv: function('272')
   exe: '/bin/sh'
 - shellcheck
   errorformat: '%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%I%f:%l:%c: Note: %m'
   args: ['-fgcc']
   get_argv: function('272')
   exe: 'shellcheck'
NOTE: you can define g:neomake_sh_enabled_makers to configure it (or b:neomake_sh_enabled_makers).

For the project (with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
'''
g:neomake_place_signs = 1
g:neomake_verbose = 3

shell: /bin/zsh
shellcmdflag: -c
Windows: 0
'''

#### :version
'''
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protect
or-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20170209-7185-ko65dh/neovim-0.1.7/build/config -I/tmp/neovim-20170209-7185-ko65dh/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include
 -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr
/include -I/tmp/neovim-20170209-7185-ko65dh/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20170209-7185-ko65dh/neovim-0.1.7/build/include
Compiled by Tobi@Booko-Macchiato-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.7/share/nvim"
'''
```

**Comment by blueyed** [comment]
The error is:

> Neomake [2810.109]: [20.72] stderr: shellcheck: ['/Users/Tobi/Desktop/file.sh: /Users/Tobi/Desktop/file.sh: openBinaryFile']
Neomake [2810.688]: [20.72] stderr: shellcheck: [': does not exist (No such file or directory)', '']
Neomake [2810.690]: [20.72] exit: shellcheck: 2

`openBinaryFile` seems to be the Haskell method used by shellcheck?!
Is it related to your current working dir?

**Comment by mastertinner** [comment]
Thanks for your reply, @blueyed. I tried it on two different machines (with the same configuration) for different files in different directories. Also, I tried opening the file itself with `vim file.sh` and opening vim from the parent directory with `vim` and then opening the file from inside of vim with `:e file.sh`. For all of these, I got the same result...

**Comment by blueyed** [comment]
@mastertinner 
Does `:!shellcheck -fgcc file.sh` work from Neovim?

I get this:
```
:!shellcheck -fgcc file.sh

file.sh:3:1: error: Couldn't parse this if expression. [SC1073]
file.sh:4:1: error: Expected 'then'. [SC1050]
file.sh:4:1: error: Expected 'then'. Fix any mentioned problems and try again. [SC1072]
shell returned 1
```

**Comment by mastertinner** [comment]
Good idea, @blueyed. Yes, that works.

**Comment by blueyed** [comment]
It's a strange issue still, and I have no more clues from my remote point of view.. :/

**Comment by mastertinner** [comment]
Thanks for investigating, @blueyed! So on your machine, you weren't able to reproduce the behavior? It would already help me to know that it's a local problem of mine.

**Comment by blueyed** [comment]
Yes, it works for me.

**Comment by kozross** [comment]
I am getting this exact same problem as well.

**Comment by blueyed** [comment]
@kozross 
Can you provide the output of `:verbose NeomakeInfo` after you have tried to lint a shell file, please?

**Comment by kozross** [comment]
@blueyed It seems I was a bit premature - the file was quite large, and the errors could only be found *much* later. Sorry for the wolf-cry; it works as intended.

**Comment by blueyed** [comment]
@mastertinner 
Any new insights?

I'm going to make `shellcheck` report unexpected output in https://github.com/neomake/neomake/pull/1348 (to be merged once green), so please try it afterwards again - in case this is still an issue.

**Comment by mastertinner** [comment]
It does work now. Thanks, @blueyed!

**Comment by keith** [comment]
I'm seeing this shellcheck issue now as well. It seems like deleting the `cwd` arg fixes it for me https://github.com/neomake/neomake/blob/6c4f364c77c90b78b9c844ff243536c9ac9e73cb/autoload/neomake/makers/ft/sh.vim#L15

**Comment by blueyed** [comment]
@keith 
There have been cwd-related changes lately.
Are you using latest master?

It works for me normally, but I get "Neomake: Failed to remove temporary file: "t/.t.sh@neomake_14222_2.sh"." when using it with tempfiles.. :/
So there is certainly some issue in this regard.
Please consider creating a new issue for yours - I will look into it later then.

**Comment by keith** [comment]
I am on the latest master, of vim as well. Seems like it's intermittent though. If I can reproduce it consistently I'll file a new issue.

**Comment by blueyed** [comment]
Thanks.

Could not reproduce what I've seen before myself, might not have used master though:

> I get "Neomake: Failed to remove temporary file

**Comment by blueyed** [comment]
WIP: https://github.com/neomake/neomake/pull/1992 - although the issue is not clear here, there was room for improvement anyway.. ;)
