### ISSUE TITLE
Skip checks for buffers of buftype 'nofile', etc.

### ISSUE THREAD

**Issue by bohrshaw** [neomake/neomake#1031]
When I execute `:w alternate_file` on a buffer of buftype 'nofile', I got an error message "file is not readable", which should not happen.

**Comment by blueyed** [comment]
@bohrshaw 
How do you invoke Neomake?
On `BufWritePost`?

Please provide steps to reproduce the issue.

**Comment by bohrshaw** [comment]
I rushed to report this :(  and I can't reproduce this now. May close this issue.

**Comment by blueyed** [comment]
Feel free to re-open in case you find out something new.
