### ISSUE TITLE
Add Dockerfile linting with hadolint

### ISSUE THREAD

**Issue by chauncey-garrett** [neomake/neomake#1038]
Add a Dockerfile filetype that supports linting with hadolint:

https://github.com/lukasmartinelli/hadolint

**Comment by blueyed** [comment]
Makes sense.
Please consider creating a PR.

**Comment by blueyed** [comment]
ALE has something that we could use: https://github.com/w0rp/ale/blob/master/ale_linters/dockerfile/hadolint.vim

**Comment by blueyed** [comment]
See https://github.com/neomake/neomake/pull/1995#discussion_r199931542 for more discussion about using Docker itself to run the maker (hadolint/hadolint image).
