### ISSUE TITLE
Neomake uses jshint instead of eslint

### ISSUE THREAD

**Issue by JiriChara** [neomake/neomake#1042]
### Issue
I have updated Neomake from 06f0d7 to b31a33 and now even though I have:

```
let g:neomake_javascript_enabled_makers = ['eslint']
```

neomake shows me jshint errors instead os eslint errors. I have reverted back to this commit `06f0d7` and all works fine again.

### Expected behavior

Neomake should show eslint errors instead of jshint errors when `let g:neomake_javascript_enabled_makers = ['eslint']`is set.

### Steps to reproduce

1. Add `let g:neomake_javascript_enabled_makers = ['eslint']` to $VIMRC
2. Open a JavaScript file
3. Neomake displays jshint errors instead of eslint errors

This issue is not reproducible on version `06f0d7`, but `b31a33` is affected.

![2017-02-27-082622_812x479_scrot](https://cloud.githubusercontent.com/assets/668763/23352342/dc0366c2-fcc6-11e6-8b1b-776c59cfb608.png)

```
let g:neomake_javascript_enabled_makers = ['eslint']
let makers = neomake#GetEnabledMakers('javascript')
echom string(map(makers, 'v:val.exe'))
```
returns `['eslint']`

#### Neomake debug information
Async support: 1
Current filetype: javascript.jsx

##### Enabled makers
For the current filetype (with :Neomake):
 - jshint
   errorformat: '%A%f: line %l\, col %v\, %m \(%t%*\d\)'
   args: ['--verbose']
   get_argv: function('324', {'get_argv': function('324')})
   exe: 'jsxhint'
   auto_enabled: 1
 - eslint
   errorformat: '%E%f: line %l\, col %c\, Error - %m,%W%f: line %l\, col %c\, Warning - %m'
   args: ['-f', 'compact']
   get_argv: function('324', {'get_argv': function('324')})
   exe: '/home/jiri/Projects/chara.vip/node_modules/.bin/eslint'
   auto_enabled: 1
 - eslint
   errorformat: '%E%f: line %l\, col %c\, Error - %m,%W%f: line %l\, col %c\, Warning - %m'
   args: ['-f', 'compact']
   get_argv: function('324', {'get_argv': function('324')})
   exe: '/home/jiri/Projects/chara.vip/node_modules/.bin/eslint'
   auto_enabled: 0
NOTE: you can define g:neomake_javascript.jsx_enabled_makers to configure it (or b:neomake_javascript.jsx_enabled_makers).

For the project (with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_java_javac_maker = 0
g:neomake_javascript_enabled_makers = ['eslint']
g:neomake_vue_enabled_makers = ['eslint']
g:neomake_place_signs = 1


shell: /usr/local/bin/zsh
shellcmdflag: -c
Windows: 0
```

#### :version
```

NVIM 0.2.0-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-O_tSkR/neovim-0.1.7ubuntu1+git201702251442+3157+23~ubuntu16.04.1/build/config -I/build/neovim-O_tSkR/neovim-0.1.7ubuntu1+git201702251442+3157+23~ubuntu16.04.1/src -I/build/neovim-O_tSkR/neovim-0.1.7ubuntu1+git201702251442+3157+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-O_tSkR/neovim-0.1.7ubuntu1+git201702251442+3157+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-O_tSkR/neovim-0.1.7ubuntu1+git201702251442+3157+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-O_tSkR/neovim-0.1.7ubuntu1+git201702251442+3157+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-O_tSkR/neovim-0.1.7ubuntu1+git201702251442+3157+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-O_tSkR/neovim-0.1.7ubuntu1+git201702251442+3157+23~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/neovim-O_tSkR/neovim-0.1.7ubuntu1+git201702251442+3157+23~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-O_tSkR/neovim-0.1.7ubuntu1+git201702251442+3157+23~ubuntu16.04.1/build/include
Compiled by root@lcy01-19

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

#### :messages
```
"src/utils/client.js" 28L, 683C
```

**Comment by JiriChara** [comment]
@blueyed I have updated the issue. Please let me know if you need more info. Thanks!

**Comment by JiriChara** [comment]
Oh. I see what is wrong. I am using `vim-jsx` and have following setting in my $VIMRC:

```
" Enable jsx for *.js files
let g:jsx_ext_required = 0
```

so neomake actually thinks that I am editing a jsx file.

**Comment by blueyed** [comment]
Likely https://github.com/neomake/neomake/commit/28559ed0e575aca6addbace534c0851143bc70c9.

See also https://github.com/neomake/neomake/issues/572.

**Comment by JiriChara** [comment]
I guess we can close this ticket then?

**Comment by JiriChara** [comment]
@blueyed closing. Thanks!

**Comment by blueyed** [comment]
Fixed in https://github.com/neomake/neomake/pull/1124.
