### ISSUE TITLE
Make some variables maker-dependant rather than global

### ISSUE THREAD

**Issue by teto** [neomake/neomake#1043]
I wonder if it were possible to let the makers override more of the neomake variables (as is done with neomake_remove_invalid_entries); such as:
- g:neomake_info_sign / warn/error
- g:neomake_place_signs
- g:neomake_open_list

### Expected behavior

When I use linters, I don't want to autoopen the location list for instance, while when running Neomake! make, I do want the quickfix to open.

**Comment by blueyed** [comment]
Good idea!
