### ISSUE TITLE
Is it possible to set environment variables to maker?

### ISSUE THREAD

**Issue by NickeZ** [neomake/neomake#1052]
It would be nice if I could override some behavior of the rustc compiler when using the cargo maker. To do this it seems that I need to be able to set the environment variable RUSTFLAGS when cargo is run. Is this possible?

**Comment by blueyed** [comment]
Not easily as of now, but you can might be able to use `env` for `exe`:

```vim
let g:neomake_rust_rustc_exe = 'env'
let g:neomake_rust_rustc_args = ['RUSTFLAGS=foo', ''rustc']
```

We could add better support for it, e.g. through a dict, or through a more generic setting.

**Comment by blueyed** [comment]
You might also be able to use the experimental `maker.fn` callback.

**Comment by blueyed** [comment]
See https://github.com/neomake/neomake/issues/1052 for some ideas in the tests.
