### ISSUE TITLE
Output handlers need to deal with CRLF from Windows

### ISSUE THREAD

**Issue by kylemacfarlane** [neomake/neomake#1078]
Carrying on from #992.

On Windows the messages from the Python makers all end with a CR (showing as a `^M` in vim). This is more than just cosmetic as it breaks regular expression matching in the post processors such as the use of `$` here: https://github.com/neomake/neomake/blob/master/autoload/neomake/makers/ft/python.vim#L209

This is probably only a problem with Python because when you use stdout in Python on Windows it matches the environment which means cp850 encoding and CRLF. For example, take the following Python:

```
import sys
print('CRLF')
print('CRLF')
print('CRLF', end='\n')
print('CRLF', end='\n')
sys.stdout.write('CRLF\n')
sys.stdout.write('CRLF\n')
sys.stdout.flush()
sys.stdout.buffer.write(b'LF\n')
sys.stdout.buffer.write(b'LF\n')
```

And run it from cmd.exe like:

```
python test.py > test.txt
```

With `ff=unix` and `set list` you will see the following:

```
CRLF^M$
CRLF^M$
CRLF^M$
CRLF^M$
CRLF^M$
CRLF^M$
LF$
LF$
```

So unless you specifically write binary to the buffer Python will convert LF to CRLF on Windows. Since all the Python linters just write regular text to stdout we end up with CRLFs everywhere which breaks some of the post processing in neomake.

I think all that needs changing is https://github.com/neomake/neomake/blob/master/autoload/neomake.vim#L1066 to something like:

```
let data = split(substitute(a:output, "\r\n", "\n", "g"), "\n", 1)
```

**Comment by blueyed** [comment]
Another option might be to not use `raw` mode with Vim's `job_start`, but `nl` instead.

This would mean to move output munging out of the generic output handling to Neovim's.

**Comment by blueyed** [comment]
Using "nl" mode however will trigger the output callback for every new line, which is not what we want really.

**Comment by blueyed** [comment]
Thanks for the detailed report.
See https://github.com/neomake/neomake/pull/1080.
