### ISSUE TITLE
Java Linting Not Working Correctly

### ISSUE THREAD

**Issue by IQubic** [neomake/neomake#1089]
I'm trying to lint a multi-file Java project. When I ask Neomake to lint one of my source files it tells me that there is a "symbol not found".
Let's say the file is something like this:

    package textExcel;
    
    public class RealCell implements Cell {
    }

Neomake tells me that the symbol Cell can't be found. That's bogus. Cell is another file in the same directory, also in the same package.

I even added this to my .vimrc:

    let g:neomake_java_javac_args = ['-cp', '~/textExcel']

And that's still not working.

### Expected behavior

I want Neomake to feed my javac args to javac when linting.

### Steps to reproduce

If you want to take a look at the project that isn't linting correctly, it can be found here:
https://github.com/IQubic/Text-Excel

But in general just create a java project with at least two classes, in separate files. Then have one depend on the other. Linting will most likely fail.

### Output from (verbose) NeomakeInfo
Neomake [155.702]: [6] Starting async job: ['javac', '-cp', '~/textExcel/src/textExcel', '/home/avi/textExcel/src/textExcel/RealCell.java']
 
#### Neomake debug information
Async support: 1
Current filetype: java

##### Enabled makers
For the current filetype (with :Neomake):
 -java

**Comment by IQubic** [comment]
Turns out I misunderstood how to use the -cp argument. Closing this thread as Neomake works just fine, I was just being stupid.

**Comment by IQubic** [comment]
Reopening this because I still can't get this to work.
This works from command line:

    javac -cp ~/textExcel/src RealCell.java

But adding this to my vimrc:

   let g:neomake_java_javac_args = ['-cp', '~/textExcel/src/']

Still gives me "Cannot find symbol"

Is there something I'm missing here?

**Comment by blueyed** [comment]
Try an absolute path.. `~` might not get resolved.
We're using `expand()` but it's not triggered here.

Try `let g:neomake_java_javac_args = ['-cp', expand('~').'/textExcel/src/']`.

/cc @tweekmonster

**Comment by tweekmonster** [comment]
I always just assumed that Vim sorted out the tilde.  I guess this should be covered by `ExpandArgs()`

**Comment by blueyed** [comment]
It might depend on how jobs are run, i.e. if the shell resolves it.

@IQubic 
Are you using Vim/Neovim?  Windows/Linux?

**Comment by blueyed** [comment]
Closing this issue itself, but I am still curious about @IQubic's setup - that's also why I've created an issue template in the first place.. ;)

See #1091 for the PR to eventually fix this.

**Comment by IQubic** [comment]
I am running Gentoo Linux with Neovim 0.1.7
So, I got the classpath issue settled. However, now Neomake is working intermittently. Sometimes it will correctly lint the file, and other times it will run for a while any still not find any errors. I assumed the class path was the issue, so I tried to lint a different file, in a different directory, without any javac arguments being given. I'm still getting weird behaviors. Sometimes the file gets linted just fine, but other times I don't get any change at all.

**Comment by blueyed** [comment]
Tilde should now get expanded: https://github.com/neomake/neomake/commit/9a02417581448169c0b8ca23488c7487baf948be.

**Comment by Cypher1** [comment]
Thought that I might leave a function that  I found helpful here.
```
function! SetupJava()
  " let l:path=system("echo -n \"$CLASSPATH:$(git rev-parse --show-toplevel)\"")
  let l:path=system("echo -n \"$CLASSPATH:$(pwd)\"")
  echom l:path
  let g:neomake_java_javac_args = ['-cp', l:path.'/src/']
endfunction
```

This assumes that you are going to open vim in the folder containing src/**/*,java
```
  au Filetype java call SetupJava()
```

Would there be a way to get Neomake to do something like this automatically? I'd love to get it to read my build.xml for finding the classpath (instead of my above hack).

Thanks

**Comment by blueyed** [comment]
@Cypher1 
You could use `neomake#utils#FindGlobFile('build.xml')` to find a `build.xml`.

Please consider creating a PR or a new issue to track/improve this.

**Comment by liamaharon** [comment]
I'm still having issues setting a classpath, irregardless if I expand my ~ or not.

My .jar files are in `~/Github/shadow-blocks/lib`
My .java files in `~/Github/shadow-blocks/src/project1`

I've tried setting
`let g:neomake_java_javac_args = ['-cp', '/home/liam/Github/shadow-blocks/lib/**:/home/liam/Github/shadow-blocks/src/project1/**']`

`let g:neomake_java_javac_args = ['-cp', '/home/liam/Github/shadow-blocks/lib/*:/home/liam/Github/shadow-blocks/src/project1/*']`

`let g:neomake_java_javac_args = ['-cp', '/home/liam/Github/shadow-blocks/lib:/home/liam/Github/shadow-blocks/src/project1']`

however when Neomake lints a file from `~/Github/shadow-blocks/src/project1` it shows `javac: package <package> does not exist` on import lines and `javac: cannot find symbol (E)` when I reference another class.

**Comment by blueyed** [comment]
@liamaharon 
Please create a new issue, and provide the logfile output there (see the issue template).
