### ISSUE TITLE
Get vim script grammar error when Neomake java file 

### ISSUE THREAD

**Issue by icearith** [neomake/neomake#1139]
### Expected behavior

Run `:Neomake` on a java file, get the class file 

### Steps to reproduce

1. `vim test.java`
2. execute `:Neomake`

### Output from (verbose) NeomakeInfo

```
Error detected while processing function neomake#Make[11]..<SNR>192_Make[32]..neomake#GetEnabledMakers[28]..neomake#GetMaker:
line   46:
E712: Argument of extend() must be a List or Dictionary
Error detected while processing function neomake#Make[11]..<SNR>192_Make:
line   32:
E171: Missing :endif
```

**Comment by blueyed** [comment]
Please use the issue template.
What is your config, and which version (Git hash) are you using?  (there have been many changes lately).
