### ISSUE TITLE
Neomake takes over location list with gv.vim

### ISSUE THREAD

**Issue by BonaBeavis** [neomake/neomake#1165]
### Issue

With gv.vim and fugitive installed:
1. Open a file in a git workspace
1. `:GV?` i
1. select item in quickfix-list
1. press `o`
4. ```
    Neomake: [12.-:-] file is not readable (fugitive:///home/~~~~/Studium/Thesis/Veritask/.git//572bb4d80d15290a51bce2fe1d21d3736c561e4c/app/controllers/Tasks.scala)                                                                            
    E926: Current location list was changed 
    ```
### Expected behavior

Step 5 should open the file

With tempfile enabled it works for the first item.

### Output from (verbose) NeomakeInfo

#### Neomake debug information
Async support: 1
Current filetype: scala

##### Enabled makers
For the current filetype (with :Neomake):
 - scalac
   - args: ['-Ystop-after:parser']
   - auto_enabled: 1
   - errorformat: '%E%f:%l: %trror: %m,%Z%p^,%-G%.%#'
   - exe: 'scalac'
 - scalastyle
   - args: []
   - auto_enabled: 1
   - errorformat: '%trror file=%f message=%m line=%l column=%c,%trror file=%f message=%m line=%l,%tarning file=%f message=%m line=%l column=%c,%tarning file=%f message=%m line=%l'
   - exe: 'scalastyle'
   ERRORS:
    - maker's exe (scalastyle) is not executable.
NOTE: you can define g:neomake_scala_enabled_makers to configure it (or b:neomake_scala_enabled_makers).


For the project (with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.


Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1


##### Settings
```
g:neomake_error_sign = {'texthl': 'NeomakeErrorSign', 'text': 'x'}
g:neomake_info_sign = {'texthl': 'NeomakeInfoSign', 'text': 'i'}
g:neomake_javascript_enabled_makers = ['standard']
g:neomake_message_sign = {'texthl': 'NeomakeMessageSign', 'text': '>'}
g:neomake_open_list = 0
g:neomake_place_signs = 1
g:neomake_vimwiki_enabled_makers = ['mdl']
g:neomake_vimwiki_mdl_maker = {'errorformat': '%f:%l: %m'}
g:neomake_warning_sign = {'texthl': 'NeomakeWarningSign', 'text': '⚠'}

Windows: 0
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
```


#### :version
```

NVIM v0.2.0-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fdebug-prefix-map=/build/neovim-jbdVy6/neovim-0.1.7ubuntu1+git201703221849+3251+23~ubuntu16.10.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-jbdVy6/neovim-0.1.7ubuntu1+git201703221849+3251+23~ubuntu16.10.1/build/config -I/build/neovim-jbdVy6/neovim-0.1.7ubuntu1+git201703221849+3251+23~ubuntu16.10.1/src -I/build/neovim-jbdVy6/neovim-0.1.7ubuntu1+git201703221849+3251+23~ubuntu16.10.1/.deps/usr/include -I/build/neovim-jbdVy6/neovim-0.1.7ubuntu1+git201703221849+3251+23~ubuntu16.10.1/.deps/usr/include -I/build/neovim-jbdVy6/neovim-0.1.7ubuntu1+git201703221849+3251+23~ubuntu16.10.1/.deps/usr/include -I/build/neovim-jbdVy6/neovim-0.1.7ubuntu1+git201703221849+3251+23~ubuntu16.10.1/.deps/usr/include -I/build/neovim-jbdVy6/neovim-0.1.7ubuntu1+git201703221849+3251+23~ubuntu16.10.1/.deps/usr/include -I/build/neovim-jbdVy6/neovim-0.1.7ubuntu1+git201703221849+3251+23~ubuntu16.10.1/.deps/usr/include -I/usr/include -I/build/neovim-jbdVy6/neovim-0.1.7ubuntu1+git201703221849+3251+23~ubuntu16.10.1/build/src/nvim/auto -I/build/neovim-jbdVy6/neovim-0.1.7ubuntu1+git201703221849+3251+23~ubuntu16.10.1/build/include
Compiled by root@lgw01-06

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

**Comment by blueyed** [comment]
> With tempfile enabled it works for the first item.

I think that's what the tempfile feature is about then.

I can see though that you should not see an error when autolinting, but currently we do not distinguish between running `Neomake` manually or through an autocommand.

https://github.com/neomake/neomake/pull/1167 is meant to improve this, so that you would not configure an autocommand yourself and/or we would detect if being run from an autocommand (https://github.com/neomake/neomake/issues/1171).

Can this issue be closed then for now, i.e. have it understood correctly?

**Comment by blueyed** [comment]
The "E926: Current location list was changed" should not happen though, if it is caused by Neomake it needs to be fixed: it should not change the location list if the file is skipped.
And even of it is not skipped, it would replace the existing location list then?!

**Comment by BonarBeavis** [comment]
> With tempfile enabled it works for the first item.
> 
>> I think that's what the tempfile feature is about then.

For the next files it gives the same error and with and without tempfiles enabled, it breaks the quickfixlist for selecting a revision of the file.
Maybe the issue is that neomake triggers on every scala buffer, even if it is a revision from the git tree?

**Comment by blueyed** [comment]
How do you run Neomake? (i.e. how have you configured the autocommands)?
If you would run it only on `BufWritePost` this would not happen I suppose.

I could imagine that Neomake would not take over a location list that exists already, e.g. based on `getloclist(0, {'all': 1})` being empty or something similar.
Then however, errors would not be displayed.

As for your current setup, you could use a function to call Neomake, and there check if it should run:

```vim
function! MyNeomakeCheck()
    let locinfo = getloclist(0, {'all': 1})
    if has_key(locinfo, 'winid')
        if getwinvar(locinfo.winid, 'quickfix_title') == 'o: open / o (in visual): diff / O: open (tab) / q: quit'
            return
        endif
    endif
    Neomake
endfunction
augroup my_neomake
    au!
    au BufWritePost,BufWinEnter * call MyNeomakeCheck()
augroup END
```

This will only skip Neomake in case the gv.vim window is open.
You could use just `title` instead, but it requires https://github.com/junegunn/gv.vim/pull/36.

> Maybe the issue is that neomake triggers on every scala buffer, even if it is a revision from the git tree?

More or less, but I consider it to be a feature that temporary/virtual buffers like that can be linted, e.g. when using `:Gdiff` etc.
With #1171 this would be silent in case you do not enable tempfiles, and with a custom function like above you could also skip certain files, e.g. based on the bufname.

**Comment by blueyed** [comment]
There have been made improvements in this regard.
Please re-open with more information if it is still an issue for you.
