### ISSUE TITLE
Processes written file, not buffer

### ISSUE THREAD

**Issue by DerWeh** [neomake/neomake#1187]
Executing `Neomake` processes the content of the saved file. Hence changes to the buffer which are note saved yet won't be considered. I often find my self fixing an error and checking if it worked by running `Neomake` and consequently wondering, while there still is an error.

### Expected behavior

I would have expected `Neomake` to process the content of my buffer, so what I actually see. So I can first check if I really fixed my error before writing the file.
This would also allow a more responsive behavior like e.g. [Pyflakes-Vim](https://github.com/kevinw/pyflakes-vim) has, where `Neomake` via multiple auto-commands in the background, while I am still typing.

Of course a feature for a continuous scan in the background for IDE like error-warnings would be a welcome feature.

**Comment by blueyed** [comment]
`let g:neomake_tempfile_enabled = 1`

It is not enabled by default, since I wanted to see how it behaves with people opting in, but in the long run we might enable it by default.
See https://github.com/neomake/neomake/pull/1167 for a start at automaking.
