### ISSUE TITLE
(Typescript) With the new tslint (v5) error markers don't appear in the gutter 

### ISSUE THREAD

**Issue by ManiacalAce** [neomake/neomake#1199]
The default makers for typescript are `['tsc', 'tslint']`. The `tsc` maker runs fine and shows error signs as expected, but the `tslint` maker doesn't.

The errors do appear in `:lopen`, but no signs are placed in the gutter.
When you hit 'enter' on a `tslint` error in the location list, you're taken to a new file.

I think this is due to the `errorformat` specified in the `tslint` maker no longer matching output from `tslint 5.0`.

You're taken to a new file on hitting enter since the filename in the error message seems to be `"ERROR /path/to/file.ts"` (ie. file name is thought to include "ERROR " as well

I downgraded my `tslint` to `4.x` and things work - with signs being placed properly.

**Comment by blueyed** [comment]
Can you provide some example output, please?

**Comment by ManiacalAce** [comment]
Here is a sample `.ts` file.
I use the default `tslint.config` from `tslint v 5.1`.
In my `tsconfig.json`, I have `noUnusedParameters: true`.

```
function dummy(unusedParam: number) {
  var v = 2;
  return v;
}
```

When the makers run, I see the following errors in `:lopen`.
Only one sign is placed in the gutter - for the error returned by `tsc`.

```
|| 
ERROR: /tmp/ts/omg.ts|2 col 3 error| Forbidden 'var' keyword, use 'let' or 'const' instead
ERROR: /tmp/ts/omg.ts|2 col 7 error| Identifier 'v' is never reassigned; use 'const' instead of 'var'.
omg.ts|1 col 16 error| TS6133: 'unusedParam' is declared but never used.
```

When I hit 'enter' on any of the lint errors, I'm taken to a new file.
The status line at the bottom says: `"ERROR: /tmp/ts/omg.ts" [New DIRECTORY]`

**Comment by ManiacalAce** [comment]
Thanks! The new format you provided makes it work now.

Some clarification about your comment about `tslint -c tsconfig.json t.ts`:

`tslint` reads linting rules from `tslint.json` (not `tsconfig.json`).
The `-c` switch accepts a `tsconfig.json`.

`noUnusedParameters` is an option for `tsc` in `tsconfig.json`. I just included it to demonstrate that `tsc` was working properly, when `tslint` was not.

Thanks again.

**Comment by blueyed** [comment]
Ok, so we would have to fix the errorformat then.
Are there only lines prefixed with `ERROR:`?  Should we use another output format maybe? (it seems to also provide JSON)

**Comment by blueyed** [comment]
See #1204 about the WIP fix for this.

**Comment by euclio** [comment]
I think this can be closed.
