### ISSUE TITLE
Show error number in EchoCurrentError

### ISSUE THREAD

**Issue by languitar** [neomake/neomake#120]
It would be nice if the error number was displayed in the command line in addition to the error message so that e.g. for linters it is easier to set up a suppression.

**Comment by benekastah** [comment]
I like this idea. Piggybacking along with this, it would be nice to show the name of the maker that produced the error as well.

**Comment by languitar** [comment]
That's true.

**Comment by wsdjeg** [comment]
can this issue be closed?

**Comment by languitar** [comment]
Probably.
