### ISSUE TITLE
Rust, cargo: `:cc` does not work for errors.

### ISSUE THREAD

**Issue by dpc** [neomake/neomake#1200]
`:cc` does not work after finding an error on file save with Rust projects

### Expected behavior

`:cc` should jump to the line with an error

### Steps to reproduce

Compile Rust project with error, `:cc`, cursor doesn't jump.

I'm using neomake on every save.

The problem was introduced recently during changes related to using `cargo check`. I reported it here: https://github.com/neomake/neomake/issues/843#issuecomment-292766946 , and after the feature got completed, it seems still there.

@jonhoo reported same problem. Can you please confirm if it's gone for you?

**Comment by jonhoo** [comment]
This is because neomake has now moved to using vim `location-list` instead of `quickfix`. Thus, you need to use the commands `:lnext`, `:lprev`, `:lopen`, and `:lclose`.

**Comment by dpc** [comment]
Oh, that's what it meant.

Seems like adding:

```
cnoreabbrev cn lnext                                                                                                
cnoreabbrev cp lprev                                                                                                
cnoreabbrev cc lopen<CR>   
```

fixed my issue.

**Comment by blueyed** [comment]
Well, quickfix and location lists are different, and you should not mask one by the other.
Check out https://github.com/tpope/vim-unimpaired/, which provides a set of useful mappings, also for navigating qf/location lists.
