### ISSUE TITLE
config: b:neomake_enabled_makers should override g:neomake_vim_enabled_makers

### ISSUE THREAD

**Issue by blueyed** [neomake/neomake#1217]
Something to consider with #1156, too.

**Comment by blueyed** [comment]
I think this is the case by now.

**Comment by davidosomething** [comment]
is there `b:neomake_enabled_makers`? this is the project-level maker for a buffer
not in the docs, though `g:neomake_enabled_makers` is

**Comment by blueyed** [comment]
> is there b:neomake_enabled_makers?

Yes, at least used in tests.

Docs are behind in general, IIRC the new dict-based config is not in there altogether.. (`neomake#config#set`).
I've merged this as experimental a while ago, and have not come to adding it to the docs.
