### ISSUE TITLE
csslint is not executable

### ISSUE THREAD

**Issue by jrock2004** [neomake/neomake#1228]
I am noticing that I am not seeing my css files being linted. This may have to do with not having something installed but thought I would start here.

### Expected behavior

My css file to be linted during save

#### Neomake debug information
Async support: 1
Current filetype: css

##### Enabled makers
For the current filetype (with :Neomake):
 - csslint
   - args: ['--format=compact']
   - auto_enabled: 1
   - errorformat: '%-G,%-G%f: lint free!,%f: line %l\, col %c\, %trror - %m,%f: line %l\, col %c\, %tarning - %m,%f: line %l\, col %c\, %m,%f: %tarning - %m'
   - exe: 'csslint'
   ERRORS:
    - maker's exe (csslint) is not executable.
 - stylelint
   - args: []
   - auto_enabled: 1
   - errorformat: '%+P%f,%*\s%l:%c  %t  %m,%-Q'
   - exe: 'stylelint'
   ERRORS:
    - maker's exe (stylelint) is not executable.
NOTE: you can define g:neomake_css_enabled_makers to configure it (or b:neomake_css_enabled_makers).

For the project (with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_place_signs = 1
g:neomake_scss_csslint_maker = {'errorformat': '%A%f: line %l\, col %v\, %m \(%t%*\d\)', 'args': ['--verbose']}
g:neomake_scss_enabled_markers = ['csslint']


Windows: 0
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
```

#### :version
```

NVIM 0.1.7
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

#### :messages
```
"src/css/app.css" 22L, 442C
```

**Comment by blueyed** [comment]
Yes, you need to install the linter programs, i.e. `csslint` in this case.

What do you think could be improved to make this more clear?

**Comment by jrock2004** [comment]
@blueyed forgot to mention that I installed that via 'npm install -g css-lint'. Outside of vim I can execute that app. 'csslint'.

**Comment by blueyed** [comment]
Then it might be a $PATH problem.
Look at `which csslint` from outside of Neovim, and then `:echo $PATH` inside of Neovim.

**Comment by jrock2004** [comment]
@blueyed interesting. The path is different. In my terminal I have `/home/jcostanzo/.nvm/versions/node/v7.8.0/bin` but in neovim, when I `echo $PATH` it is not listed. Well Now I need to figure out why this is happening. Thanks

**Comment by blueyed** [comment]
Likely you define it in .zshrc, which is not used by Neovim then.

**Comment by jrock2004** [comment]
Ok, I figured out how to get the error, but now neomake is not reporting any errors to me. Thoughts?

**Comment by blueyed** [comment]
> I figured out how to get the error

What do you mean?

Please try `let g:neomake_logfile = '/tmp/neomake.log'` and look at the output and/or post it here.

**Comment by jrock2004** [comment]
Here you go

```
22:33:29 [D      ] Not processing output for mode t
22:33:31 [D +2.35] [1.-:1] Running makers: csslint (auto), stylelint (auto)
22:33:31 [V      ] [1.-:1] Starting async job: ['csslint', '--verbose', '/home/jcostanzo/Development/anime-realm/src/css/app.css']
22:33:31 [V      ] [1.-:1] Starting async job: ['stylelint', '/home/jcostanzo/Development/anime-realm/src/css/app.css']
22:33:32 [D +0.07] [1.6:1] stdout: csslint: ['verbose is not a valid option. Exiting...', '']
22:33:32 [D      ] [1.6:1] stdout: csslint: ['', 'Usage: csslint-rhino.js [options]* [file|dir]*', ' ', 'Global Options', '  --help                                   Displays this information.', '  --format=<format>                        Indicate which format to use for output.', '  --list-rules                             Outputs all of the rules available.', '  --quiet                                  Only output when errors are present.', '  --errors=<rule[,rule]+>                  Indicate which rules to include as errors.', '  --warnings=<rule[,rule]+>                Indicate which rules to include as warnings.', '  --ignore=<rule[,rule]+>                  Indicate which rules to ignore completely.', '  --exclude-list=<file|dir[,file|dir]+>    Indicate which files/directories to exclude from being linted.', '  --config=<file>                          Reads csslint options from specified file.', '  --version                                Outputs the current version number.', '', '']
22:33:32 [D      ] [1.6:1] exit: csslint: 0
22:33:32 [D      ] [1.6:1] csslint: processing 16 lines of output.
22:33:32 [D      ] Skipping User autocmd NeomakeCountsChanged: no hooks.
22:33:32 [D      ] [1.6:1] csslint: completed with exit code 0.
22:33:32 [D      ] [1.6:1] Cleaning jobinfo
22:33:32 [D      ] Skipping User autocmd NeomakeJobFinished: no hooks.
22:33:32 [D +0.40] [1.7:1] stdout: stylelint: ['Error: No configuration provided for /home/jcostanzo/Development/anime-realm/src/css/app.css', '    at module.exports (/home/jcostanzo/.nvm/versions/node/v7.8.0/lib/node_modules/stylelint/lib/utils/configurationError.js:8:27)', '    at stylelint._fullExplorer.load.then.then.config (/home/jcostanzo/.nvm/versions/node/v7.8.0/lib/node_modules/stylelint/lib/getConfigForFile.js:39:13)', '']
22:33:32 [D      ] [1.7:1] exit: stylelint: 78
22:33:32 [D      ] [1.7:1] stylelint: processing 3 lines of output.
22:33:32 [D      ] Skipping User autocmd NeomakeCountsChanged: no hooks.
22:33:32 [D      ] [1.7:1] stylelint: completed with exit code 78.
22:33:32 [D      ] [1.7:1] Cleaning jobinfo
22:33:32 [D      ] Skipping User autocmd NeomakeJobFinished: no hooks.
22:33:32 [D      ] File-level errors cleaned in buffer 1
22:33:32 [D      ] Skipping User autocmd NeomakeFinished: no hooks.
```

**Comment by jrock2004** [comment]
So maybe I need to comment out the first let?

**Comment by blueyed** [comment]
Yes, normally you should not have to configure makers (and especially not redefine them completely).  It is defined in https://github.com/neomake/neomake/blob/d7b808bed3ae312def0e7044a77ac0692d83024d/autoload/neomake/makers/ft/css.vim#L5-L16 (in a different way).
What made you think so?

**Comment by jrock2004** [comment]
I just copied the one I had for scss linting. So all is good now. Thanks
