### ISSUE TITLE
Documentation of the errorformat string

### ISSUE THREAD

**Issue by sriedel** [neomake/neomake#1245]
I wanted to adapt the ruby errorformat to ignore any "possibly useless use of <foo> in void context" messages. Since there was already a statement with ==, I assumed the row was to ignore exactly this type of error, so I replaced == with .* to no avail. Looking at the amount of percent-signs, I'm bound to have to add some myself. Unfortunately the sheer volume of percent signs makes it pretty much ungrokkable for as to what needs to be prefixed and why. 

Could you add a short documentation for the errorformat strings to the README please?

**Comment by blueyed** [comment]
See the end of `:h neomake-faq`.
Can you provide the output of `:echo getloclist(0)`?
Maybe the entries are marked as invalid already, and changing `remove_invalid_entries` would help.

**Comment by sriedel** [comment]
Thanks for the faq pointer, I didn't find that yet. 

The issue with my unsuccessful attempts however was due to a rogue syntastic plugin still being active without me being aware of it, at it was marking the lines as bad.

 Sorry about the noise.
