### ISSUE TITLE
C/C++ makers don't clean up after themselves

### ISSUE THREAD

**Issue by wesbland** [neomake/neomake#1268]
### Expected behavior

When linting C/C++ files/headers, a lot of intermediate junk can get created that we'd ideally want to clean up after the maker finishes running (e.g. `.gch` and `.o` files). 

### Steps to reproduce

Run a C/C++ maker on a file.

Is there some flag that I can't find that will automatically do this or is this something that would need to get developed?

**Comment by blueyed** [comment]
Which maker do you use?
Do the executables for them have options to not create those files, or rather somewhere else?

**Comment by wesbland** [comment]
I'm using the gcc maker. 

I was poking around with some of the other linters and their options and someone suggested `-o /dev/null`, which is a nice little trick I hadn't considered. The reason I couldn't just use `-fsyntax-only` is because my project makes prodigious use of static inlines in headers and I want to be able to lint the headers along with the .c files (I spend almost none of my time in .c files). Using `-fsyntax-only` wouldn't lint the headers.

Using `-o /dev/null` seems to have eliminated both the `.o` and the `.gch` files.

I'll go ahead and close this.

**Comment by blueyed** [comment]
> I'll go ahead and close this.

Shouldn't/can't we fix it in Neomake's shipped makers?
Which one are you  using?
