### ISSUE TITLE
Config for nice priority

### ISSUE THREAD

**Issue by stamm** [neomake/neomake#1271]
Is it possible to add config, that set's priority for nice util and start all command with this nice priority?

**Comment by blueyed** [comment]
Do you want to wrap all maker commands with `nice`?

Maybe we could add a hook that would allow you to change `argv` globally? (after https://github.com/neomake/neomake/blob/55dce5b85fccf4e7be41c18adcedb02b1dc53e82/autoload/neomake.vim#L201)

```vim
call neomake#utils#hook('NeomakeJobStart', {'jobinfo': a:jobinfo, 'argv': argv})
```

But it can be a string or list, depending on the maker, and if Neovim or Vim is used.

**Comment by stamm** [comment]
Yeap, you understand me correctly.

**Comment by blueyed** [comment]
Might be better to add a `NeomakeJobStarted` hook: https://github.com/neomake/neomake/pull/1273.

**Comment by blueyed** [comment]
Asked for this in Neovim in https://github.com/neovim/neovim/issues/6651.

Would something like #1273 work for you?

**Comment by blueyed** [comment]
@stamm 
In case you are using Neovim (or in general), you might want to provide feedback there: https://github.com/neovim/neovim/issues/6651#issuecomment-298743628.

**Comment by blueyed** [comment]
Added an init hook in https://github.com/neomake/neomake/pull/1273 now, too.
