### ISSUE TITLE
Go build checking has an incorrect quickfix path for the files in nvim

### ISSUE THREAD

**Issue by jgeiger** [neomake/neomake#1306]
NVIM Version: NVIM v0.2.1-dev
neomake version: 3517b435ec788651780462d10b917d429268a78a

When running NeoMake against a Go project inside of a package directory, the error list seems to add an additional "./" before the file name with an error. This causes nvim to throw a file is already being edited warning about swapfiles.

### Expected behavior

If I have an error in my code, it should list the files in the quickfix and I should be able to select the file I'm currently working on without seeing an error.

### Steps to reproduce

Add to init:
autocmd! BufWritePost *.go Neomake

Open a Go file inside a package.
Edit the file, including an expected error.
Save the file

The quickfix now shows something like:
packagename/./filename.go:12

Expected:
packagename/filename.go:12

### Possible fix?

Looking at the code, removing 
https://github.com/neomake/neomake/blob/master/autoload/neomake/makers/ft/go.vim#L27
seems to fix the issue.

**Comment by blueyed** [comment]
Thanks for the report - I could reproduce it.
I will have to investigate a bit in how to fix this properly.

**Comment by blueyed** [comment]
https://github.com/neomake/neomake/pull/1326 should fix this.
