### ISSUE TITLE
Settings not taking effect in latest neovim

### ISSUE THREAD

**Issue by Garoth** [neomake/neomake#1323]
After I upgraded to post 0.2 neovim, the location list opens every time Neomake is run. This is not my preferred workflow, and I'm having trouble disabling the behaviour. I'm sorry if I'm doing something dumb here, but if so, it's not very obvious to me. I would like it to show the symbols, and echo to console when you go on the line, but not do the location list stuff.

### Expected behavior

Location list / quick fix list stays hidden when using g:neomake_open_list = 0

Arguably, g:neomake_list_height = 0 should have the same effect, but I think it errors if you have a value less than 1

### Steps to reproduce

I'm using vim-plugged, and I set `g:neomake_open_list` to 0. Then, I open a javascript file, and run :Neomake. Note that I use a plugin to get it to reference a local eslint installation if it is found. Though I had the same experience with some Go code. Here are the verbose debug messages:

Neomake [     ]: [1.-:2] Exe (jshint) of auto-configured maker jshint is not executable,
skipping.
Neomake [     ]: [1.-:2] Exe (jscs) of auto-configured maker jscs is not executable, skip
ping.
Neomake [     ]: [1.-:2] Running makers: eslint (auto).
Neomake [     ]: [1.-:2] Starting async job: ['/Users/athorp/Programs/uno/node_modules/.b
in/eslint', '-f', 'compact', '/Users/athorp/Programs/uno/src/editing.js'].
Neomake [+7.19]: [1.8:2] stdout: eslint: ['/Users/athorp/Programs/uno/src/editing.js: line 35, col 17, Warning - Unexpected console statement. (no-console)', '/Users/athorp/Programs/uno/src/realtime/editing.js: line 101, col 13, Warning - Unexpected console statement. (no-console)', '/Users/athorp/Programs/uno/src/realtime/editing.js: line 113,
col 9, Warning - Unexpected console statement. (no-console)', '', '3 problems', ''].
Neomake [     ]: [1.8:2] exit: eslint: 0.
Neomake [     ]: [1.8:2] eslint: processing 5 lines of output.
Neomake [     ]: [1.8:2] Creating location list.
Neomake [+0.05]: [1.8:2] Queueing action: s:ProcessEntries for WinEnter.
Neomake [     ]: [1.8:2] eslint: completed with exit code 0.
Neomake [     ]: [1.8:2] Cleaning jobinfo.
Neomake [     ]: Skipping User autocmd NeomakeJobFinished: no hooks.
Neomake [     ]: File-level errors cleaned in buffer 2.
Neomake [     ]: Skipping User autocmd NeomakeFinished: no hooks.
Neomake [+9.89]: Processing action queue for WinEnter (1 items).
Neomake [     ]: [1.8:2] Processing 3 entries.
Neomake [     ]: Placing sign: sign place 5000 line=113 name=neomake_warn buffer=2.
Neomake [+0.01]: Placing sign: sign place 5001 line=35 name=neomake_warn buffer=2.
Neomake [     ]: Placing sign: sign place 5002 line=101 name=neomake_warn buffer=2.
Neomake [     ]: Skipping User autocmd NeomakeCountsChanged: no hooks.

#### Neomake debug information
Async support: 1
Current filetype: javascript

##### Enabled makers
For the current filetype (with :Neomake):
 - jshint
   - args: ['--verbose']
   - auto_enabled: 1
   - errorformat: '%A%f: line %l\, col %v\, %m \(%t%*\d\)'
   - exe: 'jshint'
   - postprocess: function('neomake#postprocess#GenericLengthPostprocess')
   - ERRORS:
     - maker's exe (jshint) is not executable.
 - jscs
   - args: ['--no-colors', '--reporter', 'inline']
   - auto_enabled: 1
   - errorformat: '%E%f: line %l\, col %c\, %m'
   - exe: 'jscs'
   - ERRORS:
     - maker's exe (jscs) is not executable.
 - eslint
   - args: ['-f', 'compact']
   - auto_enabled: 1
   - errorformat: '%E%f: line %l\, col %c\, Error - %m,%W%f: line %l\, col %c\, Warning - %m,%-G,%-G%*\d problems%#'
   - exe: '/Users/athorp/Programs/uno/node_modules/.bin/eslint'
NOTE: you can define g:neomake_javascript_enabled_makers to configure it (or b:neomake_javascript_enabled_makers).

For the project (with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure
clipboard: error:  it.

Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_echo_current_error = 1
g:neomake_list_height = 1
g:neomake_open_list = 0
g:neomake_place_signs = 1
g:neomake_verbose = 3


Windows: 0
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]
```

#### :version
```

NVIM v0.2.1-151-gedfe098
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170511-36766-1vo1yo9/build/config -I/tmp/neovim-20170511-36766-1vo1yo9/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I/tmp/neovim-20170511-36766-1vo1yo9/build/src/nvim/auto -I/tmp/neovim-20170511-36766-1vo1yo9/build/include
Compiled by athorp@Lanaya.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-edfe098/share/nvim"

```

#### :messages
```
"src/realtime/editing.js" 116L, 4289C
E121: Undefined variable: g:neomake_logfile
E488: Trailing characters

Neomake [     ]: [1.-:2] Exe (jshint) of auto-configured maker jshint is not executable, skipping.
Neomake [     ]: [1.-:2] Exe (jscs) of auto-configured maker jscs is not executable, skipping.
Neomake [     ]: [1.-:2] Running makers: eslint (auto).
Neomake [     ]: [1.-:2] Starting async job: ['/Users/athorp/Programs/uno/node_modules/.bin/eslint', '-f', 'compact', '/Users/athorp/Programs/uno/src/realtime/editing.js'].
Neomake [+7.19]: [1.8:2] stdout: eslint: ['/Users/athorp/Programs/uno/src/realtime/editing.js: line 35, col 17, Warning - Unexpected console statement. (no-console)', '/Users/athorp/Programs/uno/src/realtime/editing.js: line 101, col 13, Warning - Unexpected console statement. (no-console)', '/Users/athorp/Programs/uno/src/realtime/editing.js: line 113, col 9, Warning - Unexpected console statement. (no-console)', '', '3 problems', ''].
Neomake [     ]: [1.8:2] exit: eslint: 0.
Neomake [     ]: [1.8:2] eslint: processing 5 lines of output.
Neomake [     ]: [1.8:2] Creating location list.
Neomake [+0.05]: [1.8:2] Queueing action: s:ProcessEntries for WinEnter.
Neomake [     ]: [1.8:2] eslint: completed with exit code 0.
Neomake [     ]: [1.8:2] Cleaning jobinfo.
Neomake [     ]: Skipping User autocmd NeomakeJobFinished: no hooks.
Neomake [     ]: File-level errors cleaned in buffer 2.
Neomake [     ]: Skipping User autocmd NeomakeFinished: no hooks.
Neomake [+9.89]: Processing action queue for WinEnter (1 items).
Neomake [     ]: [1.8:2] Processing 3 entries.
Neomake [     ]: Placing sign: sign place 5000 line=113 name=neomake_warn buffer=2.
Neomake [+0.01]: Placing sign: sign place 5001 line=35 name=neomake_warn buffer=2.
Neomake [     ]: Placing sign: sign place 5002 line=101 name=neomake_warn buffer=2.
Neomake [     ]: Skipping User autocmd NeomakeCountsChanged: no hooks.
Neomake [ +107]: WideMessage: echo eslint: Unexpected console statement. (no-console).
```

In the above, it seems to confirm what I'm saying. The open_list setting is set to zero, but yet -- the location list opens. I actually went as far as to drop an echo into the function that seems to be referencing that global & rendering the list -- but it did not execute.

**Comment by Garoth** [comment]
Also, thank you for Neomake. It has been perfectly silently serving me for some months now.

**Comment by hiyali** [comment]
same problem

**Comment by blueyed** [comment]
Thanks for the detailed report!

However `Creating location list` in the output just means that the list is created, but not opened.
I've added tests in https://github.com/neomake/neomake/pull/1324 and it seems to work as expected.

I've merged some list improvements yesterday, so that might have triggered something else?!
Can you git-bisect it to some commit where it breaks maybe?

Apart from that are you using vim-qf by chance? #1097

**Comment by Garoth** [comment]
@blueyed Ugh, yep, you nailed it. I'm running vim-qf. I'll update my reddit post so that hopefully more people find this issue / justinmk knows what happened. That's some crazy interaction -- nvim update caused bug is vim-qf which expressed itself as a bug in neomake (as far as the user can tell).

**Comment by blueyed** [comment]
FYI: there is a workaround for vim-qf now.
