### ISSUE TITLE
Adding cargo clippy

### ISSUE THREAD

**Issue by NickeZ** [neomake/neomake#1330]
I would like to run `cargo clippy` as well as `cargo check`. How would I go about adding that?

**Comment by blueyed** [comment]
There is https://github.com/neomake/neomake/blob/4cf0b39777728652f13eed32b1667a4412e1a286/autoload/neomake/makers/clippy.vim already, so `Neomake! clippy` should work.

**Comment by NickeZ** [comment]
Cool, i missed that..
