### ISSUE TITLE
Add a command to clear/reset Neomake

### ISSUE THREAD

**Issue by blueyed** [neomake/neomake#1342]
This should:
 - clear all signs and errors
 - close the location/quickfix list
 - reset internal caches (like #395)

This should be done for project mode (quickfix list), for the buffer (file mode, location list), or globally.

Ref: https://github.com/SpaceVim/SpaceVim/issues/547

**Comment by wsdjeg** [comment]
here is some idea:
1. neomake should only clear it's own signs

2. if there other info in the quickfix and location list, which is not generate by neomake, it will be very hard to check it.

**Comment by blueyed** [comment]
> neomake should only clear it's own signs

That is the case already.

> if there is other info in the quickfix and location list, which is not generate by neomake, it will be very hard to check it.

Neomake uses its own location/quickfix lists, but user's could have added to it, of course.
This command would not clear any lists, but rather just close the window (and preferably only if it's from Neomake - which would be a new feature; possibly related to #924).

**Comment by bluz71** [comment]
Yes, this would be very handy.

In the meantime, for those interested, this crude example mapping can be used to clear out the signs column:

```
noremap <silent> <leader>cls :sign unplace *<CR>:set signcolumn=auto<CR>
```

This unplaces all signs and then toggles the empty signs column away. Not good if you have other non-Neomake signs, but good enough for those of us who only use signs with Neomake.

**Comment by wsdjeg** [comment]
@bluz71 after clear sign, when move cursor to the error line, the error info will still be printed.

**Comment by bluz71** [comment]
Yeah, I don't know how to clear that.

We have to wait until `NeomakeReset` (or whatever it will be called) is implemented.

My hack mapping just clears the signs column only; which is all I needed.

**Comment by somini** [comment]
Syntastic had this feature, it might be useful to steal some ideas.
https://github.com/vim-syntastic/syntastic/blob/96cc251075f3f9d290c5afd4adf1b64c1542d469/plugin/syntastic.vim#L252-L255

**Comment by blueyed** [comment]
Some WIP I have in my vimrc:
```
function! MyneomakeCleanFile()
  let buf = bufnr('%')
  call neomake#highlights#ResetFile(buf)
  call neomake#signs#ResetFile(buf)
  call neomake#signs#CleanOldSigns(buf, 'file')
  call neomake#statusline#ResetCountsForBuf(buf)
endfunction
com! NeomakeCleanFile call MyneomakeCleanFile()

function! MyneomakeCleanProject()
  call neomake#CleanOldProjectSignsAndErrors()
  call neomake#statusline#ResetCountsForProject()
endfunction
com! NeomakeCleanProject call MyneomakeCleanProject()
```

TODO:
 - [ ] after clear sign, when move cursor to the error line, the error info will still be printed.
 - [ ] close location/quickfix list, possibly only if owned by Neomake (not sure if that should get done though?!)

**Comment by hertogp** [comment]
```vim
let g:neomake_clear_maker = {}
:Neomake clear
```
seems to do the trick for the location list?

**Comment by blueyed** [comment]
@hertogp 
Nice hack.. :)
Does `:Neomake! clear` then work for the quickfix list, too?

But after all it should get real, full-blown commands.

**Comment by hertogp** [comment]
Yeah I know. The idea was to create a filetype independent 'null' maker, returning zero errors/warnings, which would replace the location or qf list and also remove the error info messages.  

I don't have a project level maker setup at the moment, but as a small test (using a doc example):
```vim
let my_maker = {'name': 'prj_maker'}
function! my_maker.get_list_entries(jobinfo) abort
  return [
        \ {'text': 'My error', 'lnum': 1, 'bufnr': bufnr("%"), 'col': 2},
        \ {'text': 'My warning', 'lnum': 2, 'bufnr': bufnr("%"), 'col': 1}
        \]
endfunction
let g:neomake_test_maker = my_maker
```
Running `Neomake! test` fills the quickfix list with 2 entries after which `Neomake! clear` clears it just fine.

**Comment by hertogp** [comment]
Btw, just got started with neomake and I love it.  Well done!

**Comment by blueyed** [comment]
Thanks!

I suggest going with the WIP in my comment above (put it into `plugin/neomake.vim`), and use / improve this then.

I am interested in this myself, so please consider creating a PR then maybe, where we can work on to implement this properly.

It is also relevant with/for `:NeomakeDisable`, where signs etc are left around, and you want to either clear them manually, or they might even get cleared automatically.

**Comment by blueyed** [comment]
Will start working on this in https://github.com/neomake/neomake/pull/2124.

**Comment by blueyed** [comment]
Just for info: there is something to try in https://github.com/neomake/neomake/pull/2124, if you want to provide feedback.

**Comment by bluz71** [comment]
`NeomakeClean` is looking very nice.

Note, I only tested with my rudimentary JavaScript (create-react-app) and Ruby (rails) projects, but it worked as desired.

Looking forward to this being merged into master.

**Comment by blueyed** [comment]
https://github.com/neomake/neomake/pull/2124 has been merged.
