### ISSUE TITLE
Maker for Tsuquyomi, if possible

### ISSUE THREAD

**Issue by ahstro** [neomake/neomake#1356]
I am not sure whether it would be possible to have a maker for [Tsuquyomi](https://github.com/Quramy/tsuquyomi) since it uses a Nvim command to get errors, not a standalone program. I tried to find info on whether this was possible, but couldn't.

**Comment by blueyed** [comment]
You can have a maker with a `get_list_entries` function, which would then call `tsuquyomi#createFixlist()`  (like Syntastic does in https://github.com/Quramy/tsuquyomi/blob/master/syntax_checkers/typescript/tsuquyomi.vim#L22).

See `:h neomake-makers-get_list_entries` (https://github.com/neomake/neomake/blob/f96b161c3354718587a21474022639eef588e6c3/doc/neomake.txt#L85).

**Comment by ahstro** [comment]
Thank you, I'll look into that!

**Comment by blueyed** [comment]
Closing this in favor of https://github.com/neomake/neomake/issues/1361.
