### ISSUE TITLE
MRI maker throws an unexpected output error for its expected behavior

### ISSUE THREAD

**Issue by danarnold** [neomake/neomake#1360]
Neomake should execute the MRI maker without any errors, but instead, it displays the following error:

`Neomake: [19.15:4] mri: unexpected output. See :messages for more information.`

Upon checking the `:messages`, the issue is:

`Neomake: mri: unexpected output on stdout: Syntax OK`

Executing the linter command manually on the file gives the same output, which seems to be handled properly in errorformat:

```
$ ruby -c -T1 -w test-file.rb
Syntax OK
```

The above output is the same on my version of ruby, 2.3.3p222, as well as the system version which I also checked, 2.0.0p648.

### Expected behavior

It shouldn't show an error message.

### Steps to reproduce

Create a simple ruby class with no errors, such as

```ruby
class Abc
  def function
    puts 'ok'
  end
end
```

Run `:Neomake` and you should see the error.

### Output from (verbose) NeomakeInfo

```

#### Neomake debug information
Async support: 1
Current filetype: ruby


##### Enabled makers
For the current filetype (with :Neomake):
 - mri
   - args: ['-c', '-T1', '-w']
   - auto_enabled: 0
   - errorformat: '%-G%\m%.%#warning: %\%%(possibly %\)%\?useless use of == in void context,%-G%\%.%\%.%\%.%.%#,%-GSyntax OK,%E%f:%l: synta
```

**Comment by blueyed** [comment]
Sorry, I have only tested the error case.
You can revert https://github.com/neomake/neomake/pull/1344/files#diff-86e03410da7a3fcbd66e757a29ff000e for now, or change it to "both".
Can it be made quiet in case of success?
(Here it might make sense to also look at the exit code.)

**Comment by danarnold** [comment]
Thanks for the quick fix!

**Comment by blueyed** [comment]
Thanks for reporting it! :)

(it's easy to fix something that you just broke, and it is also appreciated to get feedback on usage through this kind of stream after all)
