### ISSUE TITLE
Improve gradle maker

### ISSUE THREAD

**Issue by blueyed** [neomake/neomake#1376]
See https://github.com/neomake/neomake/issues/749#issuecomment-304444093.

Should also be moved to be a file mode maker probably - included in java.vim.
/cc @wsdjeg

**Comment by whossname** [comment]
The basic Java build chain seems to be: 
```
:compileJava
:processResources
:classes
:jar
:assemble
:compileTestJava
:processTestResources
:testClasses
:test
:check
:build
:buildDependents
```
I think the compileJava task will pick up most errors, but buildDependents will be more thorough. No noticeable difference between them in execution time (about 0.55 seconds on my computer). No idea how this translates to Android projects.

I still need to test it, but this is my proposal that should work for vanila Java.
https://github.com/neomake/neomake/compare/master...whossname:patch-1

**Comment by whossname** [comment]
Tested it now, seems good.

**Comment by DonnieWest** [comment]
@whossname that looks like it works on my end. Awesome!

My only concern is that `buildDependents` will become slower and slower the more tests and dependents that are added. I think an `assemble` task would be more appropriate

**Comment by whossname** [comment]
I'm happy with that, should work fine.

**Comment by whossname** [comment]
Tested it before making the change this time. Baby steps.

**Comment by pltanton** [comment]
@whossname just tested it too, works like a charm! By the way, is there any idiomatic way to apply `Neomake! gradle` on each filesave (or on the fly) instead of `Neomake` **only** for gradle projects?

**Comment by blueyed** [comment]
@pltanton 
https://github.com/neomake/neomake/issues/749#issuecomment-304023562 ?

(But it might be moved to a file-mode maker anyway, so this might break in the future)

**Comment by whossname** [comment]
@DonnieWest what do you think of moving to a file-mode maker? You have some projects that look like they might use this maker, so I think you would be affected by this the most.

**Comment by blueyed** [comment]
The definition of a file mode maker is a bit vague.
I think there should be just settings for:
- use location or quickfix list
- append the current file or not
- filter out other files than the current one

Those would be normal maker settings, that can also be configured/overridden by the user.
Calling `:Neomake!` (with a bang) could than just mean to use e.g. the quickfix list always, and keep all reported files.

**Comment by blueyed** [comment]
@whossname 
I've created https://github.com/neomake/neomake/pull/1396 from your patch.
I think we should go with this for now, ok?
/cc @pltanton

**Comment by whossname** [comment]
It seems to work for everyone, so it seems like a good move to me. Sorry for not making the pull request. In my normal git workflow I usually just merge, so I'm only just getting a handle on that part of git.

**Comment by blueyed** [comment]
@whossname 
No worries.

Unfortunately your authorship got lost (probably since I've created the PR that was squashed (with your commits).
