### ISSUE TITLE
How to change color of column highlight?

### ISSUE THREAD

**Issue by xiumingzhang** [neomake/neomake#1378]
While linting, the problematic column is highlighted in a way that it gets the same color as the background and hence becomes invisible.

Before linting

![before](http://i.imgur.com/SPXOs49.png "Before")

After linting

![after](http://i.imgur.com/DkJNKnE.png "After")

If my terminal highlight line weren't there, the left bracket before `thisFile` would've been totally invisible.

### Expected behavior

The problematic column should be highlighted in a color different from the background.

### Steps to reproduce

Here is the relevant part of `init.vim`.

```
" neomake
autocmd! BufWritePost * Neomake "Run :Neomake on w
let g:neomake_python_enabled_makers = ['pyflakes', 'pep8']
hi MyErrorMsg ctermfg=red ctermbg=none
let g:neomake_error_sign = { 'text': '✖', 'texthl': 'MyErrorMsg' }
hi MyWarningMsg ctermfg=yellow ctermbg=none
let g:neomake_warning_sign = { 'text': '⚠', 'texthl': 'MyWarningMsg' }
let g:neomake_highlight_lines = 0
let g:neomake_highlight_columns = 1
```

Is it that I didn't find a way of changing the column highlight color or that this is actually not configurable?

Many thanks!

**Comment by xiumingzhang** [comment]
@blueyed Thanks for adding the label. May I check if you know the answer? Pointers are very much appreciated!

**Comment by blueyed** [comment]
The highlight group names are defined in https://github.com/neomake/neomake/blob/991a6faed3c388a3f41bb6ce4307915a7f7b902a/autoload/neomake/highlights.vim#L4-L9.
And get set/linked in https://github.com/neomake/neomake/blob/991a6faed3c388a3f41bb6ce4307915a7f7b902a/autoload/neomake/highlights.vim#L114-L130.

So in case of errors `NeomakeError` is used, which default to the `bg` of `Error`.

I see that you are overriding it for signs already, but in general it should work out of the box, and might indicate some more general problem, e.g. with your colorscheme.

See also `:h g:neomake_highlight_lines`.

**Comment by xiumingzhang** [comment]
@blueyed  I guess the easiest solution is indeed to just switch another color scheme for my neovim. The defaults work out of the box under solarized. Thanks a lot!

**Comment by blueyed** [comment]
What colorscheme were you using before?  (please provide name and URL)

**Comment by xiumingzhang** [comment]
@blueyed I was not using any colorscheme in neovim and the "Dark" profile in iTerm2.

**Comment by blueyed** [comment]
Interesting.

What does `:hi NeomakeErrorDefault` give you in this case?
I am getting the following with a minimal vimrc (no colorscheme).

```vim
:hi NeomakeErrorDefault                                                                     
NeomakeErrorDefault xxx cterm=underline ctermfg=9 gui=undercurl guisp=Red
```

Does the "Dark" profile in iTerm2 has something non-red for color 9?
Or do you get something else than `ctermfg=9`?

**Comment by xiumingzhang** [comment]
@blueyed I get the same thing:

```
:hi NeomakeErrorDefault
NeomakeErrorDefault xxx cterm=underline ctermfg=9 gui=undercurl guisp=Red
```
How do I check if "the 'Dark' profile in iTerm2 has something non-red for color 9"? They look like this.

![img](http://i.imgur.com/X68ZwRr.png)

**Comment by blueyed** [comment]
Looks ok.

You could use `colors-table -` (via https://github.com/blueyed/dotfiles/blob/master/usr/bin/colors-table) to print the colors.


Also check if `NeomakeError` gets setup correctly:
```vim
:hi NeomakeError
NeomakeError   xxx links to NeomakeErrorDefault
```
