### ISSUE TITLE
Lint through ssh

### ISSUE THREAD

**Issue by tdehaeze** [neomake/neomake#1439]
Hi,

I would like to know if there is a way to use a linter through SSH.

Indeed, I use matlab on a server over ssh but I use NeoVim on my machine. The problem is that mlint is only available on the server.
In order to lint a file, I can run `ssh username@server "bash -c '/path/to/mlint /path/to/file.m'"`.
Is there a way to configure neoMake to do that ?

Thank you

**Comment by tdehaeze** [comment]
I solved my issue. I simply adapted a script wrote by @dmalt.

``` bash
#!/bin/bash 

msg=$(ssh -f username@server "bash -c 'path/to/mlint $1'" 2>&1)

if [ ! -z "$msg" ]; then
    echo "$msg" | sed -r "s|^|$1:|g"
fi
```

It's working just fine.

**Comment by blueyed** [comment]
I see.

As for the `sed` part, can you try if using `mapexpr` works instead?  (https://github.com/neomake/neomake/issues/1354#issuecomment-303485744)

**Comment by tdehaeze** [comment]
Yes it's working using `mapexpr`!

But I guess there is a typo in your code (`}` instead of `,`), also I had to remove `'args': ['-id']`.

``` vimL
let g:neomake_matlab_mlint_maker = {
    \ 'exe': 'mlint',

    \ 'mapexpr': "neomake_bufname.':'.v:val"}
    \ 'errorformat':
    \   '%f:L %l (C %c): %m,' .
    \   '%f:L %l (C %c-%*[0-9]): %m,',
    \ }
```

I guess I can close the issue :)
