### ISSUE TITLE
is there any user autocmd for lint done?

### ISSUE THREAD

**Issue by wsdjeg** [neomake/neomake#1444]
hi @blueyed 

I use there func to show errors on statusline
```viml
    function! s:syntax_checking()
        if !exists('g:loaded_neomake')
            return ''
        endif
        let counts = neomake#statusline#LoclistCounts()
        let warnings = get(counts, 'W', 0)
        let errors = get(counts, 'E', 0)
        let l =  warnings ? ' %#SpaceVim_statusline_warn#●' . warnings . ' ' : ''
        let l .=  errors ? (warnings ? '' : ' ') . '%#SpaceVim_statusline_error#●' . errors  . ' ' : ''
        return l
    endfunction
```

and my statusline is update on autocmd `BufWinEnter,WinEnter,FileType`, but I need to update statusline when neomake's syntax checking is done. does neomake has user autocmd for this?

**Comment by blueyed** [comment]
NeomakeJobFinished an NeomakeFinished, see the doc.

**Comment by blueyed** [comment]
btw: https://github.com/neomake/neomake/pull/1416

Worked a bit more yesterday on it.  You might want to provide feedback there.
