### ISSUE TITLE
Creating a directory maker for SBT

### ISSUE THREAD

**Issue by McBrainy** [neomake/neomake#1472]
Hello,

I'm trying to create a maker for SBT (with the intention of contributing it), and I'm not sure if I'm doing this right. Here's my maker:

```vim
let g:neomake_sbtcompile_maker = {
    \ 'exe': 'sbt',
    \ 'args': ['compile'],
    \ 'errorformat': '[%trror] %f:%l: error: %m'
\ }
```

Which I run with `Neomake! sbtcompile`. And here's an example SBT error that I would like to match:

```
[info] Loading project definition from /path/to/projroot/project
[info] Set current project to ProjName (in build file:/path/to/projroot)
[info] Compiling 1 Scala source to /path/to/projroot/ProjName/target/scala-2.11/classes...
[error] /path/to/projroot/and/stuff/MyClass.scala:4: not found: object mypackage
[error] import mypackage._
[error]        ^
[error] 1 errors found
```

It doesn't seem to find any errors. Is there something obviously wrong with my maker/errorformat or the way I'm doing this?

(I know I can make this more sophisticated by matching the number of spaces on the next line with `%p` to find the column number, but right now I'm just trying to get the basic thing working.)

**Comment by McBrainy** [comment]
I noticed that the Maven maker escapes spaces in its errorformat, so I tried that, but it didn't change anything. Also, I tried using `Neomake! mvn` in a Maven project where I introduced an error intentionally, and it didn't show any errors in the gutter, so maybe the problem is on my end?

**Comment by blueyed** [comment]
Remove the 2nd ”error" (before %m).
Also see the doc for hints on developing the errorformat.

**Comment by McBrainy** [comment]
Thanks, that was a dumb mistake on my part; it works now. I'm still working on trying to get it to find column numbers before I make a PR.

**Comment by blueyed** [comment]
See `%p` in `:h errorformat`.
