### ISSUE TITLE
Node based makers don't work in nvim on Windows

### ISSUE THREAD

**Issue by kylemacfarlane** [neomake/neomake#1476]
Very similar to #992 but only nvim this time around.

Python makers seem to work fine but node makers can't find the binaries. Here's the log output:

```
00:42:42 [D      ] [1.-:1:1] Nothing to make: no enabled file mode makers (filetype=cfg).
00:42:42 [D      ] [1.-:-:1] Cleaning make info.
00:42:45 [D +2.84] [2.-:3:1] Running makers: eslint.
00:42:45 [D      ] Skipping User autocmd NeomakeJobInit: no hooks.
00:42:45 [V      ] [2.1:3:1] Starting async job: ['eslint', '-f', 'compact', 'C:\Users\kyle\projects\test-neomake\app.js'].
00:42:45 [D      ] [2.1:3:1] cwd: C:\Users\kyle\projects\test-neomake.
00:42:45 [E +0.06] [2.-:-:1] Failed to start Neovim job: ['eslint', '-f', 'compact', 'C:\Users\kyle\projects\test-neomake\app.js']: Vim(let):E903: Process failed to start: no such file or directory: "eslint".
00:42:45 [D      ] [2.-:-:1] Cleaning make info.
```

If you remember from #992 there's a specific issue with node due to the batch files npm generates on Windows. This would explain why it's node only but I'm not sure if it is the same issue this time around.

For example the current code at https://github.com/neomake/neomake/blob/master/autoload/neomake.vim#L628

    if has('nvim')
        if args_is_list
            let argv = [exe] + args
        else
            let argv = exe . (!empty(args) ? ' ' . args : '')
        endif

If I change this to:

    if has('nvim')
        if args_is_list
            let argv = ["eslint.cmd"] + args
        else
            let argv = "eslint.cmd" . (!empty(args) ? ' ' . args : '')
        endif

Then it works. Which implies that nvim doesn't check for `%PATHEXT%` but if that was the case how are the Python linters working?

The only fix I've found is to bypass the nvim specific arguments on Windows:

    if has('nvim') && !neomake#utils#IsRunningWindows()
        if args_is_list
            let argv = [exe] + args
        else
            let argv = exe . (!empty(args) ? ' ' . args : '')
        endif

**Comment by kylemacfarlane** [comment]
Yeah this looks like an nvim bug.

There are two eslint files: `eslint` and `eslint.cmd`. `eslint` is the actual javascript file and `eslint.cmd` is just a script that wraps it to run it with node.

When just these two files are present the error message is: `no such file or directory "eslint"`.

But if I create a dummy `eslint.exe` file the error changes to: `unknown error "eslint"`.

This implies that nvim ignores `%PATHEXT%` and manually appends `.exe`.

**Comment by kylemacfarlane** [comment]
Doing just `:!eslint` works fine so is it something to do with the options passed to `jobstart()`?

**Comment by blueyed** [comment]
Which Neovim version are you using?

Does `:call system(['eslint', '-h'])` work?
What about `:call system('eslint -h')`?

Neovim seems to use `%PATHEXT%` in its `os_can_exe` and `is_executable_in_path` functions only.

We have a comment in Neomake already:
> " Windows needs a subshell to handle PATH/%PATHEXT% etc.

So this might just apply for Neovim also.

**Comment by blueyed** [comment]
It looks a bit like it should update the full path (via %PATHEXT%) e.g. here: https://github.com/neovim/neovim/blob/5acda12419858da202ce7ea962fae75102a75b2b/src/nvim/eval.c#L11601

**Comment by blueyed** [comment]
The following probably works (using a string instead of a list always on Windows):
```diff
diff --git i/autoload/neomake.vim w/autoload/neomake.vim
index 8c2e27d6..6ccba132 100644
--- i/autoload/neomake.vim
+++ w/autoload/neomake.vim
@@ -627,7 +627,12 @@ function! s:command_maker_base._get_argv(jobinfo) abort dict
 
     if has('nvim')
         if args_is_list
-            let argv = [exe] + args
+            " Use a string on Windows, which will use a subshell (to handle %PATHEXT%).
+            if neomake#utils#IsRunningWindows()
+                let argv = join(map(copy([exe] + args), 'neomake#utils#shellescape(v:val)'))
+            else
+                let argv = [exe] + args
+            endif
         else
             let argv = exe . (!empty(args) ? ' ' . args : '')
         endif
```

But I would rather avoid this, if it could be fixed in Neovim instead.

**Comment by blueyed** [comment]
From `#neovim`:
```
   blueyed | Do jobs on Windows need a subshell to pick up eslint.cmd for eslint? https://github.com/neomake/neomake/issues/1476#issuecomment-318822215
JustinMKey+| blueyed: .cmd by definition needs a shell
JustinMKey+| cannot run a .cmd without a shell
JustinMKey+| technically it is just a "shell" not a subshell :>
   blueyed | I see.. :)  Could Neovim handle this automatically?  The plugin cannot tell from `executable('eslint')` if it is a .cmd.
JustinMKey+| jobstart('foo.cmd') without list arg should work. Or jobstart(['cmd.exe', ...])
JustinMKey+| you can tell with `executable('foo.exe')`
JustinMKey+| can't remember if `executable('foo.cmd')` works as expected or if it requires a full path. But the .exe form should be enough to infer.
JustinMKey+| jobstart() works in a very specific, documented, deterministic way. we did a lot of work to make things work well on windows. very hesitant to add
           | any magic
JustinMKey+| for magic, use the non-list form jobstart('...')
```

**Comment by blueyed** [comment]
I will create a PR to address this in a more generic way for windows.

**Comment by blueyed** [comment]
@kylemacfarlane 
Please test https://github.com/neomake/neomake/pull/1477 with both Neovim and Vim.

**Comment by kylemacfarlane** [comment]
#1477 seems to work in both Vim 8 and Neovim 0.2.

**Comment by blueyed** [comment]
@kylemacfarlane 
Thanks for confirming.
I am not very confident, i.e. assume this to break somewhere, but we'll see.. :)
