### ISSUE TITLE
【neomake#Sh】Directory name invalid

### ISSUE THREAD

**Issue by tracyone** [neomake/neomake#1481]
### Expected behavior

Run  command asynchronously  in win32.

### Steps to reproduce

Minimal vimrc

```vim
if &compatible
  set nocompatible
endif

let &rtp=&rtp.','."c:/Users/tracyone/vimfiles/bundle/neomake"


colorscheme desert
filetype plugin indent on
syntax on
```

**Step**

```vim
:call neomake#Sh("dir ..")
:cw
```

#### Neomake debug information
Async support: 1
Current filetype: 
Windows: 1
[shell, shellcmdflag, shellslash]: ['C:\WINDOWS\system32\cmd.exe', '/c', 0]

##### Enabled makers
For the current filetype ("", used with :Neomake): None.
NOTE: the current buffer does not have a filetype.

For the project (used with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_place_signs = 1
```

#### :version
```

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 28 2017 22:02:02)
MS-Windows 64-bit GUI version 带 OLE 支持
包含补丁: 1-799
编译者 appveyor@APPVYR-WIN
巨型版本 带图形界面。  可使用(+)与不可使用(-)的功能:
+acl                +ex_extra           +multi_byte_ime/dyn -tag_any_white
+arabic             +extra_search       +multi_lang         +tcl/dyn
+autocmd            +farsi              +mzscheme/dyn       -termguicolors
+balloon_eval       +file_in_path       +netbeans_intg      -terminal
+browse             +find_in_path       +num64              -tgetent
++builtin_terms     +float              +ole                -termresponse
+byte_offset        +folding            +packages           +textobjects
+channel            -footer             +path_extra         +timers
+cindent            +gettext/dyn        +perl/dyn           +title
+clientserver       -hangul_input       +persistent_undo    +toolbar
+clipboard          +iconv/dyn          -postscript         +user_commands
+cmdline_compl      +insert_expand      +printer            +vertsplit
+cmdline_hist       +job                +profile            +virtualedit
+cmdline_info       +jumplist           +python/dyn         +visual
+comments           +keymap             +python3/dyn        +visualextra
+conceal            +lambda             +quickfix           +viminfo
+cryptv             +langmap            +reltime            +vreplace
+cscope             +libcall            +rightleft          +wildignore
+cursorbind         +linebreak          +ruby/dyn           +wildmenu
+cursorshape        +lispindent         +scrollbind         +windows
+dialog_con_gui     +listcmds           +signs              +writebackup
+diff               +localmap           +smartindent        -xfontset
+digraphs           +lua/dyn            +startuptime        -xim
+directx            +menu               +statusline         +xpm_w32
-dnd                +mksession          -sun_workshop       -xterm_save
-ebcdic             +modify_fname       +syntax             
+emacs_tags         +mouse              +tag_binary         
+eval               +mouseshape         +tag_old_static     
     系统 vimrc 文件: "$VIM\vimrc"
     用户 vimrc 文件: "$HOME\_vimrc"
 第二用户 vimrc 文件: "$HOME\vimfiles\vimrc"
 第三用户 vimrc 文件: "$VIM\_vimrc"
      用户 exrc 文件: "$HOME\_exrc"
  第二用户 exrc 文件: "$VIM\_exrc"
    系统 gvimrc 文件: "$VIM\gvimrc"
    用户 gvimrc 文件: "$HOME\_gvimrc"
第二用户 gvimrc 文件: "$HOME\vimfiles\gvimrc"
第三用户 gvimrc 文件: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
        系统菜单文件: "$VIMRUNTIME\menu.vim"
编译方式: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE  -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL   -DFEAT_XPM_W32   -DWINVER=0x500 -D_WIN32_WINNT=0x500 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /Zl /MT -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_MBYTE -DFEAT_GUI_W32 -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python35.dll\" -DFEAT_MZSCHEME -I "C:\Program Files\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_a0solc.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a0solc.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl524.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=22 -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby220.dll\" -DFEAT_HUGE /Fd.\ObjGXOULYHTRZAMD64/ /Zi
链接方式: link /RELEASE /nologo /subsystem:windows /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:AMD64 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib  /machine:AMD64 /nodefaultlib libcmt.lib oleaut32.lib user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python35.lib   "C:\Tcl\lib\tclstub86.lib" WSock32.lib xpm\x64\lib\libXpm.lib /PDB:gvim.pdb -debug
```

#### :messages
```
简体中文消息维护者: Yuheng Xie <elephant@linux.net.cn>
```

call neomake#Sh whitout command's argument is work well.

**Comment by blueyed** [comment]
Please use `let g:neomake_logfile = '…'`, trigger the issue, and post the contents of the logfile here.
It works for me using `NeomakeSh ls ..` on Linux.
Do other commands work?
What is your `cwd` (see `:pwd` in Vim).

**Comment by tracyone** [comment]
@blueyed It is a issue of neomake in MS windows only.

**Comment by tracyone** [comment]
> 19:21:12 [D      ] [1.-:1:1] Running makers: sh: dir ...
19:21:12 [D +0.01] Skipping User autocmd NeomakeJobInit: no hooks.
19:21:12 [V      ] [1.1:1:1] Starting async job: 'C:\WINDOWS\system32\cmd.exe /c "C:\WINDOWS\system32\cmd.exe" /c "dir .."'.
19:21:12 [D      ] [1.1:1:1] cwd: C:\Users\tracyone.
19:21:12 [D      ] [1.1:1:1] Vim job: {'status': 'run', 'stoponexit': 'term', 'exitval': 0, 'exit_cb': 0, 'channel': channel 0 open, 'process': 9936}.
19:21:12 [D      ] [1.1:1:1] Vim channel: {'status': 'open', 'id': 0, 'in_io': 'pipe', 'err_mode': 'RAW', 'in_status': 'open', 'out_io': 'pipe', 'err_io': 'pipe', 'err_status': 'open', 'out_timeout': 2000, 'out_status': 'open', 'out_mode': 'RAW', 'in_mode': 'RAW', 'in_timeout': 2000, 'err_timeout': 2000}.
19:21:12 [D      ] Skipping User autocmd NeomakeJobStarted: no hooks.
19:21:12 [D +0.08] [1.1:1:1] stderr: sh: dir ..: ['目录名称无效。', ''].
19:21:12 [D +0.10] [1.1:1:1] exit: sh: dir ..: 1.
19:21:12 [D      ] [1.1:1:1] sh: dir ..: processing 1 lines of output.
19:21:12 [D      ] [1.1:1:1] Creating quickfix list.
19:21:12 [D      ] [1.1:1:1] Processing 1 entries.
19:21:12 [D      ] [1.1:1:1] Skipped 1 entries without bufnr.
19:21:12 [D      ] Skipping User autocmd NeomakeCountsChanged: no hooks.
19:21:12 [D      ] [1.1:1:1] sh: dir ..: completed with exit code 1.
19:21:12 [D      ] [1.1:1:1] Cleaning jobinfo.
19:21:12 [D      ] Skipping User autocmd NeomakeJobFinished: no hooks.
19:21:12 [D      ] Removing signs: {file: {}, project: {}}.
19:21:12 [D      ] Skipping User autocmd NeomakeFinished: no hooks.
19:21:12 [D      ] [1.-:-:1] Cleaning make info.

**目录名称无效--->Directory name invalid**

**Comment by blueyed** [comment]
Seems to get wrapped in a shell now twice:

> Starting async job: 'C:\WINDOWS\system32\cmd.exe /c "C:\WINDOWS\system32\cmd.exe" /c "dir .."'.

Did this just happen for you (i.e. after 19fec8a)?

**Comment by blueyed** [comment]
Does it work in a shell from `C:\Users\tracyone` to run `dir ..`?
Isn't it that users are not allowed to view `C:\Users` maybe, and that's where the error is coming from?

**Comment by tracyone** [comment]
@blueyed Yes.

Run any command with any argument or any space in any directory will lead to this issue with same output in quickfix. 

call neomake#Sh("dir")  --------work

call neomake#Sh("dir ")  --------not work

call neomake#Sh("dir  ..")  --------not work

**Comment by blueyed** [comment]
I see.
Has it regressed with https://github.com/neomake/neomake/commit/19fec8ac28d6372f2c3a4613804982e860c66a70?
Did it work before?

**Comment by tracyone** [comment]
NO.

19fec8ac28d6372f2c3a4613804982e860c66a70 Add neomake#compat#get_argv to fix .cmd lookup on Windows (#1477)
407a2c97ac04f69d7635b7d7db50a4b26fc8a0e6 neomake#CancelJob: improve log msg with removed queue emtries (#1475)

git checkout 407a2c97ac04f69d7635b7d7db50a4b26fc8a0e6

**Comment by blueyed** [comment]
Can you try the patch from https://github.com/neomake/neomake/pull/1483/files, please?

**Comment by blueyed** [comment]
Merged now.

**Comment by tracyone** [comment]
@blueyed Sorry for the late reply.

After update neomake,

call neomake#Sh("dir") --------work

call neomake#Sh("dir ..") -------"dir .."  Command not found

**Comment by blueyed** [comment]
Can you post the log for `call neomake#Sh("dir ..")` and `call neonate#Sh("git fetch --all && git status")`, please?

The important/interesting part being "Starting async job: …", but feel free to provide it completely.

**Comment by tracyone** [comment]
>14:26:57 [D      ] [1.-:1:1] Running makers: sh: dir ...
14:26:57 [D +0.03] Skipping User autocmd NeomakeJobInit: no hooks.
14:26:57 [V      ] [1.1:1:1] Starting async job: 'C:\WINDOWS\system32\cmd.exe /c """C:\WINDOWS\system32\cmd.exe"" /c ""dir .."""'.
14:26:57 [D      ] [1.1:1:1] cwd: C:\Users\tracyone.
14:26:57 [D      ] [1.1:1:1] Vim job: {'status': 'run', 'stoponexit': 'term', 'exitval': 0, 'exit_cb': 0, 'channel': channel 0 open, 'process': 5784}.
14:26:57 [D      ] [1.1:1:1] Vim channel: {'status': 'open', 'id': 0, 'in_io': 'pipe', 'err_mode': 'RAW', 'in_status': 'open', 'out_io': 'pipe', 'err_io': 'pipe', 'err_status': 'open', 'out_timeout': 2000, 'out_status': 'open', 'out_mode': 'RAW', 'in_mode': 'RAW', 'in_timeout': 2000, 'err_timeout': 2000}.
14:26:57 [D      ] Skipping User autocmd NeomakeJobStarted: no hooks.
14:26:57 [D +0.16] [1.1:1:1] stderr: sh: dir ..: ['''"dir .."'' 不是内部或外部命令，也不是可运行的程序', '或批处理文件。', ''].
14:26:57 [D +0.12] [1.1:1:1] exit: sh: dir ..: 1.
14:26:57 [D      ] [1.1:1:1] sh: dir ..: processing 2 lines of output.
14:26:57 [D      ] [1.1:1:1] Creating quickfix list.
14:26:57 [D      ] [1.1:1:1] Processing 2 entries.
14:26:57 [D      ] [1.1:1:1] Skipped 2 entries without bufnr.
14:26:57 [D      ] Skipping User autocmd NeomakeCountsChanged: no hooks.
14:26:57 [D      ] [1.1:1:1] sh: dir ..: completed with exit code 1.
14:26:57 [D      ] [1.1:1:1] Cleaning jobinfo.
14:26:57 [V      ] [1.1:1:1] Calling User autocmd NeomakeJobFinished with context: {'jobinfo': '鈥?}.
14:26:57 [D +0.06] Removing signs: {file: {}, project: {}}.
14:26:57 [D      ] Skipping User autocmd NeomakeFinished: no hooks.
14:26:57 [D      ] [1.-:-:2] Cleaning make info.


----

> 14:28:01 [D +63.4] [2.-:1:1] Running makers: sh: git fetch --all && git status.
14:28:01 [D      ] Skipping User autocmd NeomakeJobInit: no hooks.
14:28:01 [V      ] [2.2:1:1] Starting async job: 'C:\WINDOWS\system32\cmd.exe /c """C:\WINDOWS\system32\cmd.exe"" /c ""git fetch --all && git status"""'.
14:28:01 [D      ] [2.2:1:1] cwd: C:\Users\tracyone.
14:28:01 [D      ] [2.2:1:1] Vim job: {'status': 'run', 'stoponexit': 'term', 'exitval': 0, 'exit_cb': 0, 'channel': channel 3 open, 'process': 7492}.
14:28:01 [D      ] [2.2:1:1] Vim channel: {'status': 'open', 'id': 3, 'in_io': 'pipe', 'err_mode': 'RAW', 'in_status': 'open', 'out_io': 'pipe', 'err_io': 'pipe', 'err_status': 'open', 'out_timeout': 2000, 'out_status': 'open', 'out_mode': 'RAW', 'in_mode': 'RAW', 'in_timeout': 2000, 'err_timeout': 2000}.
14:28:01 [D      ] Skipping User autocmd NeomakeJobStarted: no hooks.
14:28:01 [D +0.18] [2.2:1:1] stderr: sh: git fetch --all && git status: ['fatal: Not a git repository (or any of the parent directories): .git', ''].
14:28:01 [D +0.10] [2.2:1:1] exit: sh: git fetch --all && git status: 128.
14:28:01 [D      ] [2.2:1:1] sh: git fetch --all && git status: processing 1 lines of output.
14:28:01 [D      ] [2.2:1:1] Creating quickfix list.
14:28:01 [D      ] [2.2:1:1] Processing 1 entries.
14:28:01 [D      ] [2.2:1:1] Skipped 1 entries without bufnr.
14:28:01 [D      ] Skipping User autocmd NeomakeCountsChanged: no hooks.
14:28:01 [D      ] [2.2:1:1] sh: git fetch --all && git status: completed with exit code 128.
14:28:01 [D      ] [2.2:1:1] Cleaning jobinfo.

**Comment by blueyed** [comment]
I think the best would be if you investigated based on the patch from https://github.com/neomake/neomake/pull/1483/files#diff-e2b548b64d6c9b4921146d55b75ba665R177.

E.g. remove the `neomake#utils#shellescape` for `args` in the `return`.

There should also be no wrapping of the shell twice (https://github.com/neomake/neomake/pull/1483/files#diff-e2b548b64d6c9b4921146d55b75ba665R174).

You could use `echom string(…)` to output values, and `:runtime autoload/neomake/compat.vim` to reload the file on changes.
