### ISSUE TITLE
Thank you for defaulting to makeprg

### ISSUE THREAD

**Issue by mqudsi** [neomake/neomake#1504]
Not a bug, not a complaint, not an issue, not a question. I just want to say thanks for defaulting to makeprg when a compiler isn't defined for the project. It makes playing nice with all the various language plugins nice and easy.

Thanks, Daniel!

**Comment by blueyed** [comment]
Thank you!

It wasn't me though, but @benekastah (who initially created Neomake) :)

Do you know https://github.com/tpope/vim-dispatch?
The approach there is to use Vim's compiler feature(s), which is basically a combination of `&makeprg` and `&errorformat`.

Let's close the issue, but keep discussing, of course.

**Comment by mqudsi** [comment]
Thank you @benekastah as well, then. I wasn't aware he was the initial author!

I'm completely unaware of vim-dispatch; I didn't realize there was work on asynchronous builds (or just background builds, I guess) prior to neovim's insistence on that point. @tpope has awesome stuff (and now @shougo is carrying that torch).
