### ISSUE TITLE
NeomakeInfo reports cannot execute makeprg

### ISSUE THREAD

**Issue by mqudsi** [neomake/neomake#1505]
I have `makeprg` set correctly for my filetype (typescript), but `NeomakeInfo` seems to treat `makeprg` literally and insists that it isn't executable (even though neomake actually works fine).

`:set makeprg`

`makeprg=tsc`

`:echo executable(&makeprg)`

`1`

This is probably more of a feature/improvement request than a bug, but `NeomakeInfo` should detect `exe=makeprg` and read the actual `&makeprg` settings to fill in that info.

#### Neomake debug information
Async support: 1
Current filetype: typescript
Windows: 0
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]

##### Enabled makers
For the current filetype ("typescript", used with :Neomake):
 - tsc
   - append_file: 0
   - args: ['--project', '/mnt/c/Users/Mahmoud/Documents/CPSA/stats/tsconfig.json', '--noEmit', '--watch', 'false']
   - auto_enabled: 1
   - errorformat: '%E%f %#(%l\,%c): error %m,%E%f %#(%l\,%c): %m,%Eerror %m,%C%\s%\+%m'
   - exe: 'tsc'
 - tslint
   - args: ['%:p']
   - auto_enabled: 1
   - errorformat: '%EERROR: %f[%l\, %c]: %m,%E%f[%l\, %c]: %m'
   - exe: 'tslint'
NOTE: you can define g:neomake_typescript_enabled_makers to configure it (or b:neomake_typescript_enabled_makers).

For the project (used with :Neomake!):
 - makeprg
   - args: []
   - auto_enabled: 0
   - errorformat: '%+A %#%f %#(%l\,%c): %m,%C%m'
   - exe: 'makeprg'
   - fn: function('7')
   - ERRORS:
     - maker's exe (makeprg) is not executable.
NOTE: you can define g:neomake_enabled_makers to configure it.

**Comment by blueyed** [comment]
Good corner case.

But it looks like you're also using `let g:neomake_enabled_makers = ['makeprg']` - otherwise it does not seem to show up in the info at all?

So I think there are two issues here:
1. your use case (I think maker.exe should point at &makeprg)
2. display info about `makeprg` if it is not enabled manually

**Comment by mqudsi** [comment]
@blueyed good point. I wasn't sure how to override the default arguments for mkaeprg without explicitly adding it to the list of makers. I wanted to pass `-j4` to the default maker without overriding what the default maker would be.

However, I do have maker.exe pointing at &makeprg:

```vim
	let g:neomake_enabled_makers = ['makeprg']
	let g:neomake_makeprg_maker = {
		\ 'exe': &makeprg,
		\ 'args': [ '-j4' ],
		\ 'errorformat': &errorformat,
		\ }
```

**Comment by blueyed** [comment]
#1954 fixes the initial issue.

As for using `-j4` you could just `:set makeprg=make\ -j4` probably also, and then use `:Neomake!` / `:Neomake! makeprg` (the default/internal one).

See https://github.com/neomake/neomake/issues/589 for some ideas/discussion about passing args in general.
