### ISSUE TITLE
Flake8 ignores setup.cfg

### ISSUE THREAD

**Issue by MichaelAquilina** [neomake/neomake#1512]
### Expected behavior
When Neomake runs flake8 it should use the configuration values set in `setup.cfg` (e.g. max-line-length = 100). 

### Steps to reproduce
Open vim in python project folder (with setup.cfg at root). Open any python file in `src` and notice that flake8 marks e.g. lines >80 as lint errors.

I suspected that maybe the issue was that flake8 was being run from outside the root project directory (where setup.cfg is found), but the logs and the documentation makes thing otherwise.

### Output from (verbose) NeomakeInfo
https://gist.github.com/MichaelAquilina/158c7eea55ce0b8e72f2a7652fb2ebfb

**Comment by blueyed** [comment]
You seem to be using neomake-autolint?!

> Starting async job: ['flake8', '--format=default', '/home/michael/.cache/.neomake_autolint_cache/urls.py'].

That seems to be the reason for it.

As for Neomake there is WIP in https://github.com/neomake/neomake/pull/1167 to have easy setup/support for autolinting.

**Comment by MichaelAquilina** [comment]
Ah, that makes sense. Running `Neomake` on its own doesnt show this issue so I will close this issue :)
