### ISSUE TITLE
No entries in quickfix (Neomake cargo)

### ISSUE THREAD

**Issue by Ploppz** [neomake/neomake#1514]
nvim v0.2.0

When running `:Neomake cargo`, errors show up in the sign column, and when I move the cursor there I can see the error in the status line. However, QuickFix (`:copen`) is empty. 

### Expected behavior

I expected the errors and warnings to appear in the QuickFix window.

### Output
`:verbose NeomakeInfo`
https://bpaste.net/show/80239f91b3d3

**Comment by blueyed** [comment]
They appear in the location list.

From the debug log:

> Creating location list.

This changed a while ago, and there is some WIP in https://github.com/neomake/neomake/pull/1452 to clean up project/file mode.
