### ISSUE TITLE
neomake not running on D (dlang) files

### ISSUE THREAD

**Issue by kraxli** [neomake/neomake#1526]
Hi,
after using neomake successfully with python, I gave it a try on a D (dlang) file. Unfortunately there was no action/response at all (also no log file produced which may be due to the fact that I do not fully grasp neomake). I could also not find any tests for D file types to run.

Is there any specific setting required and/or can anybody help me out on getting neomake work for D-files?

Many thanks!

**Comment by blueyed** [comment]
Is your filetype "d"?
Do you have any of the programs in https://github.com/neomake/neomake/blob/master/autoload/neomake/makers/ft/d.vim installed?
Try running `:Neomake dmd` then directly for example.

`:Neomake <tab>` should complete makers.

**Comment by kraxli** [comment]
Oh it works :-) - Thanks a lot and sorry! 
I tried the wrong things, for example:
``` Neomake! dmd ``` or ``` Neomake DMD ```
