### ISSUE TITLE
mypy configuration improvement suggestion

### ISSUE THREAD

**Issue by niklas88** [neomake/neomake#1528]
Trying out neomake with Python, I've found that "python -m mypy --ignore-missing-imports --follow-imports=skip" breaks even local annotations that reference imported types. Removing the "--follow-imports=skip" shows these while still ignoring errors about missing imports. I therefor propose to drop the "--follow-imports=skip" part which according to the following comment was likely added because the author believed it to only remove the warning about missing imports.

https://github.com/neomake/neomake/blob/d9c1c8b27d1a8bd5a3f2f22882e43028754643ca/autoload/neomake/makers/ft/python.vim#L283

**Comment by blueyed** [comment]
I do not know myself.

/cc @zackhsi @miedzinski 
What do you think?

A PR for this would be nice then.

**Comment by niklas88** [comment]
I'll prepare a PROn Aug 25, 2017 18:20, Daniel Hahler <notifications@github.com> wrote:I do not know myself.
/cc @zackhsi @miedzinski
What do you think?
A PR for this would be nice then.

**Comment by zackhsi** [comment]
Relevant docs: http://mypy.readthedocs.io/en/latest/command_line.html.

In particular:
> `normal` (the default) follow imports normally and type check all top level code (as well as the bodies of all functions and methods with at least one type annotation in the signature).
`silent` follow imports normally and even “type check” them normally, but suppress any error messages. This is typically the best option for a new codebase.

As use cases may vary, the best solution is to provide a sane default (maybe either value here is fine), but provide a way to customize.
