### ISSUE TITLE
Neomake errors in clist does not have the correct path

### ISSUE THREAD

**Issue by Mariappan** [neomake/neomake#154]
Hi,
I have been using neovim for past three months and after using neomake today only 
I realised i have not utilize the full power of neovim. Thanks for this wonderful plugin. 

I have one doubt and one issue though:
Doubt:
Is there a way to send a argument to Neomake command like:
:Neomake!              => to build (cli.sh build)
:Neomake! clean     => to build (cli.sh build clean)
Currently i defined two makers like below. Is there a easy way to acheive this?

``` vim
if has('nvim')
    let g:neomake_cli_maker = {
            \ 'exe': 'cli.sh',
            \ 'args': ['build'],
            \ }

    let g:neomake_clic_maker = {
            \ 'exe': 'cli.sh',
            \ 'args': ['build', 'clean'],
            \ }
endif
```

Issue:
When i use :make the errors in the clist are using the full path from the project root.
But using Neomake. it only show the partial filepath, how do i change it to behavior like :make?
Do i need to change errorformat to achieve this?
I tried buffer_output=1 it did not solve the problem

Output from Neomake:
`1 src/cli_util.c:73 col 5: error: implicit declaration of function ‘cli_arg_init’ [-Werror=implicit-function-declaration]`

Output from make:
`46 cli/src/cli_util.c:73 col 5: error: implicit declaration of function ‘cli_arg_init’ [-Werror=implicit-function-declaration]`

**Comment by benekastah** [comment]
To answer your questions:

1. Currently there isn't a better way to pass arguments to a maker. To do this we would probably need a separate command (since arguments to `Neomake!` are all interpreted as makers). It would certainly be handy to have.
2. If you aren't parsing out the filename with `%f` in your errorformat, I'm not sure why neomake would result in a different filename. Neomake ought to use neovim's current directory to run its commands. Are you running the command from the same working directory each time?

**Comment by Mariappan** [comment]
Thanks benekastah. I changed the current directory everytime to project root (which is not the directory where error file is present) and build. 
My repo dir is like: /reponame is the root dir from which i should give "cli.sh build" to build all modules.
/reponame/cli/src/
/reponame/http/src/

Makefile traverse recursively and build in each subdir(make -C /subdir). I think the issue is due to make happening in recursive directories. So I try to add the default errorformat to my maker which tracks Entering and Leaving directory as follows:

``` vim
    let g:neomake_cli_maker = {
            \ 'exe': 'cli.sh',
            \ 'args': ['build'],
            \ 'errorformat':
            \ '%*[^"]"%f"%*\D%l: %m,' .
            \ '"%f"%*\D%l: %m,%-G%f:%l: (Each undeclared identifier is reported only once,' .
            \ '%-G%f:%l: for each function it appears in.),' .
            \ '%-GIn file included from %f:%l:%c:,' .
            \ '%-GIn file included from %f:%l:%c\,,' .
            \ '%-GIn file included from %f:%l:%c,' .
            \ '%-GIn file included from %f:%l,' .
            \ '%-G%*[ ]from %f:%l:%c,' .
            \ '%-G%*[ ]from %f:%l:,' .
            \ '%-G%*[ ]from %f:%l\,,' .
            \ '%-G%*[ ]from %f:%l,' .
            \ '%f:%l:%c:%m,' .
            \ '%f(%l):%m,%f:%l:%m,' .
            \ '"%f"\, line %l%*\D%c%*[^ ] %m,' .
            \ '%D%*\a[%*\d]: Entering directory %*[`']%f',' .
            \ '%X%*\a[%*\d]: Leaving directory %*[`']%f',' .
            \ '%D%*\a: Entering directory %*[`']%f',' .
            \ '%X%*\a: Leaving directory %*[`']%f',' .
            \ '%DMaking %*\a in %f,' .
            \ '%f|%l| %m' .
            \ }
```

With this I got error like this
``` bash 
λ  ft [  master] » vim ~/.vimrc                                                                                      ~/.vim/plugged/neomake/autoload/neomake/makers/ft
Error detected while processing /home/mariappan/.nvimrc:
line  361:
E722: Missing comma in Dictionary: ]%f',' . '%X%*\a[%*\d]: Leaving directory %*[`']%f',' . '%D%*\a: Entering directory %*[`']%f',' . '%X%*\a: Leaving directory %*[`']%f',' . '%DMaking %*\a in %f,' . '%f|%l| %m' . }
E15: Invalid expression: { 'exe': 'ngos.sh', 'args': ['build'], 'buffer_output': 1, 'errorformat': '%*[^"]"%f"%*\D%l: %m,' . '"%f"%*\D%l: %m,%-G%f:%l: (Each undeclared identifier is reported only once,' . '%-G%f:%l: for each function it appears in.),' . '%-GIn file included from %f:%l:%c:,' . '%-GIn file included from %f:%l:%c\,,' . '%-GIn file included from %f:%l:%c,' . '%-GIn file included from %f:%l,' . '%-G%*[ ]from %f:%l:%c,' . '%-G%*[ ]from %f:%l:,' . '%-G%*[ ]from %f:%l\,,' . '%-G%*[ ]from %f:%l,' . '%f:%l:%c:%m,' . '%f(%l):%m,%f:%l:%m,' . '"%f"\, line %l%*\D%c%*[^ ] %m,' . '%D%*\a[%*\d]: Entering directory %*[`']%f',' . '%X%*\a[%*\d]: Leaving directory %*[`']%f',' . '%D%*\a: Entering directory %*[`']%f',' . '%X%*\a: Leaving directory %*[`']%f',' . '%DMaking %*\a in %f,' . '%f|%l| %m' . }
Press ENTER or type command to continue
```

**Comment by benekastah** [comment]
It looks like your error format string ends with a `.`. Remove that dangling dot (or replace it with a comma if you like) and that error should go away.

**Comment by Mariappan** [comment]
Thanks for the tip. I changed then after I got the error. Then i tried removing one by one to debug.
```vim 
    let g:neomake_cli_maker = {                                                                                                                                                    \ 'exe': 'cli.sh',                                                                                                                                                     \ 'args': ['build'],
            \ 'errorformat':
            \ '"%f"%*\D%l: %m,%-G%f:%l: (Each undeclared identifier is reported only once,' .
            \ '%-G%f:%l: for each function it appears in.),' .
            \ '%-GIn file included from %f:%l:%c:,' .
            \ '%-GIn file included from %f:%l:%c\,,' .
            \ '%-GIn file included from %f:%l:%c,' .
            \ '%-GIn file included from %f:%l,' .                                                                                                                                   \ '%-G%*[ ]from %f:%l:%c,' .
            \ '%-G%*[ ]from %f:%l:,' .                                                                                                                                              \ '%-G%*[ ]from %f:%l\,,' .                                                                                                                                             \ '%-G%*[ ]from %f:%l,' .                                                                                                                                               \ '%f:%l:%c:%m,' .                                                                                                                                                      \ '%f(%l):%m,%f:%l:%m,' .
            \ '"%f"\, line %l%*\D%c%*[^ ] %m,' .
            \ '%f|%l| %m' ,
            \ }
            "\ '%D%*\a[%*\d]: Entering directory %*[`']%f',' .
            "\ '%X%*\a[%*\d]: Leaving directory %*[`']%f',' .
            "\ '%D%*\a: Entering directory %*[`']%f',' .
            "\ '%X%*\a: Leaving directory %*[`']%f',' .
            "\ '%DMaking %*\a in %f,' .
            "\ '%*[^"]"%f"%*\D%l: %m,' .
```
With this snippet above it worked. Seems there is a problem with [] inside the format

"\ '%D%*\a[%*\d]: Entering directory %*[`']%f',' .
In this line single quotes ' appear in between the format. Tried \' to escape '. 
But not worked. Can u pl tell how to escape ' ? 
Any idea how to fix the rest of the lines?

**Comment by Mariappan** [comment]
hi benekastah

At last I fixed the error format issue. If we want to escape ', need to use two single quotes.
Changed that. Then also with :make it worked and :Neomake! it didnt.
Then i enabled debug log in neomake and got the following trace.
``` mk
Neomake: makeprg stdout: make[2]: Leaving directory `/home/mariappan/repo1/http'
Neomake: makeprg stdout:
Neomake: makeprg stdout done.
Neomake: makeprg processing 4 lines of output
Neomake: makeprg stdout: make[2]: Entering directory `/home/mariappan/repo1/cli'
Neomake: makeprg stdout:
Neomake: makeprg stdout done.
Neomake: makeprg processing 2 lines of output
Neomake: makeprg stdout: x86_64-linux-gnu-gcc-4.8  -c src/cli_utils.c -o /home/mariappan/repo1/cli/src/cli_utils.o -MD -MF /home/mariappan/repo1/cli/src/cli_utils.o.dep -MT  /home/mariappan/repo1/cli/src/cli_utils.o  -fPIC  -I../inc -g3 -Wall -Werror
Neomake: makeprg stdout:
Neomake: makeprg stdout done.
Neomake: makeprg processing 2 lines of output
Neomake: makeprg stderr: src/cli_utils.c: In function ‘cli_add_ns’:
Neomake: makeprg stderr:
Neomake: makeprg stderr done.
Neomake: makeprg processing 2 lines of output
Neomake: makeprg stderr: src/cli_utils.c:57:48: error: ‘NUL’ undeclared (first use in this function)
Neomake: makeprg stderr:                  xmlSetNs((xmlNodePtr)att_node, NUL);
Neomake: makeprg stderr:                                                 ^
Neomake: makeprg stderr: src/cli_utils.c:57:48: note: each undeclared identifier is reported only once for each function it appears in
```

I am suspecting since caddexpr is happening separately for stdout which has Entering Directory and stderr which has the error output, it is not able to add the full path of the error file.

Trying to debug further.

**Comment by benekastah** [comment]
See if it works when you buffer the output: https://github.com/benekastah/neomake/blob/master/doc/neomake.txt#L131 or `:help neomake-makers-buffer_output`

**Comment by ohle** [comment]
I have the same problem. Either with setting `makeprg` and `errorformat` directly or via a maker, using the `errorformat` from the default `gcc` compiler plugin which handles "Entering directory",  I get correct paths with `:make` but incorrect paths with `Neomake!`. Adding `'buffer_output': 1` to the maker definition does not help.

**Comment by benekastah** [comment]
Ah, this sounds like an unimplemented feature then. I forgot about `make`'s ability to keep track of which directory it is in (I don't really use it myself). I'm not sure how tricky this would be to implement; I suspect it will require some custom parsing of maker output on neomake's end (which we have avoided doing up until now).

**Comment by blueyed** [comment]
There have been fixes in this regard, i.e. changing to the jobs' `cwd` when processing output, and buffering output is disabled by default.

I am closing this for now, but please feel free to re-open in case it's still an issue.
It could certainly benefit from having a test for this, of course.

**Comment by akorchemniy** [comment]
This still doesn't work for me. Any intention to support quickfix-directory-stack, %D, %X error formats?

**Comment by blueyed** [comment]
@akorchemniy 
The problem more likely is that those typically come on stderr, and the rest on stdout (or the other way around).
Are you using Neovim?  (related issue there https://github.com/neovim/neovim/issues/8823)
What maker is it about?

**Comment by akorchemniy** [comment]
Indeed. It works after wrapping the make command in a script to redirect stderr 2>&1. Thanks!

**Comment by blueyed** [comment]
Ok.  For reference: https://github.com/neomake/neomake/issues/1884
