### ISSUE TITLE
Is there a callback method awaiting the neomake get error info

### ISSUE THREAD

**Issue by zhujinxuan** [neomake/neomake#1540]
I am trying to update source file after `eslint --fix`.  However, simple checktime could not work 
because, during the async callback, source file is not updated by `eslint --fix`.  Therefore I have to
get around by

``` vim
" Only use eslint
let g:neomake_javascript_enabled_makers = ['eslint']
" Use the fix option of eslint
let g:neomake_javascript_eslint_args = ['-f', 'compact', '--fix']

if has('nvim')
  " Callback for reloading file in buffer when eslint has finished and maybe has
  " autofixed some stuff
  function! s:Neomake_javascript_callback(options)
    if (a:options.name ==? 'eslint') && (a:options.has_next == 0)
      let timer = timer_start(100, 
            \ {->execute('checktime ' . bufname('%')) }, 
            \ {'repeat': 20})
    endif
  endfunction

  "
  " Call neomake#Make directly instead of the Neomake provided command
  autocmd Filetype javascript call neomake#Make(1, [], function('s:Neomake_javascript_callback'))
endif
```

I have to use timer here because the when this callback is called, the `eslint --fix` has not yet finished.

Is there a way to config the `neomake#Make` callback to make it called when neomake already receive responses from `eslint`?

**Comment by blueyed** [comment]
You could use `NeomakeFinished` - see https://github.com/neomake/neomake/blob/4a3c4acfb37f75da9e547675a16e84d031d88f08/doc/neomake.txt#L620.

**Comment by zhujinxuan** [comment]
@blueyed  It works.  Thank you.
