### ISSUE TITLE
option to disable automake on certain cases

### ISSUE THREAD

**Issue by davidosomething** [neomake/neomake#1590]
i ran into some issues in the past on plugin-generated buffers (i think it was with gita)
disabled mine on `&buftype ==# 'nofile'`
and on `empty(glob(expand('%')))` (this could probably be better written, like `empty(bufname('%'))`, not sure if that's more performant)

**Comment by blueyed** [comment]
1. A non-empty buftype should get ignored already: https://github.com/neomake/neomake/blob/f2bb4aeeb2a76b76c39d2a99372f64c0278274a8/autoload/neomake/configure.vim#L366-L372

2. I do not think that an empty bufname should get ignored by default - that is what tempfiles are meant to handle.

There is an (undocumented) setting to ignore filetypes already (https://github.com/neomake/neomake/blob/f2bb4aeeb2a76b76c39d2a99372f64c0278274a8/autoload/neomake/configure.vim#L6), for which I have to add documentation still.
