### ISSUE TITLE
Indicator for success?

### ISSUE THREAD

**Issue by eterps** [neomake/neomake#1592]
I configure neomake to run my unit tests.
I can see that neomake has indicators for info, warnings & errors.
Is it possible to configure an indicator for succes? I.e. something like:

https://cms-assets.tutsplus.com/uploads/users/469/posts/22394/image/Screen%20Shot%202014-10-12%20at%209.11.46%20PM.png

**Comment by blueyed** [comment]
The new statusline supports this: you will see a green checkmark.

See doc/neomake.txt - let me know if you have problems understanding it.
Via: #1416

**Comment by eterps** [comment]
@blueyed do I understand correctly that it only supports a positive indicator for the complete file? (i.e. not line based like in the screenshot?)

**Comment by blueyed** [comment]
@eterps 
Yes, it is per file (if all linters are successful).
I misunderstood your initial question.

You could use the same signs / highlights that Neomake already defines, but you have to place and manage them yourself.
I think support for that is out of scope for this Neomake.

Maybe something for https://github.com/janko-m/vim-test?!
