### ISSUE TITLE
support nixos based workflow

### ISSUE THREAD

**Issue by teto** [neomake/neomake#1594]
Nixos follows a very specific workflow, where development should happen inside a nix-shell (to see the dependancies) and your typical binaries are in unexpected locations.

As I am still looking for what  the perfect workflow is, I have little advice to provide here. It might also be hard to automate, I am not sure: detect for a shell.nix/default.nix or let user manually load a maker

if we are in a nix-shell (check with $IN_NIX_SHELL), one can do:
from neovim one could create a shell that "source $stdenv/setup" (according to https://nixos.org/nixpkgs/manual/) and then run the buildPhase (assuming patchPhase/configurePhase were already done)

### Expected behavior
I don't expect anyone to work on this, but the issue can be useful to gather some solutions. Some makers could also be patched on the nixos side I suppose.

Meanwhile minor fixes can be done I believe. For instance, I tried to run
`Maker not found (for filetype c): make`
I am Neomake!
```
     1 || mkdir build                                                                     
     2 || make: /bin/bash: Command not found                                              
     3 || make: /bin/bash: Command not found  
```
/usr/bin/env bash might be more portable ? (not sure about that either)

So mostly looking for input (for now).

**Comment by teto** [comment]
Here is a first attempt https://github.com/teto/neomake/tree/nixos but I wonder if just sourcing the setup file is enough. I've been trying to get it to work with wireshark but it seems like I miss something, just  running buildPhase generates:
```
15:31:49 [D      ] [4.-:5:1] Nothing to make: no valid makers.
15:31:49 [D      ] [4.-:5:1] Cleaning make info.
15:32:05 [D      ] [1.-:5:1] Running makers: nix.
15:32:05 [D      ] Skipping User autocmd NeomakeJobInit: no hooks.
15:32:05 [V      ] [1.1:5:1] Starting async job: ['bash', '-c', 'source $stdenv/setup; echo $NIX_CFLAGS_COMPILE; buildPhase'].
15:32:05 [D      ] [1.1:5:1] cwd: /home/teto/wireshark/build.
15:32:05 [V      ] [1.1:5:1] Calling User autocmd NeomakeJobStarted with context: {'jobinfo': '…'}.
15:32:05 [D +0.03] [1.1:5:1] stderr: nix: ['mkdir: impossible de créer le répertoire « /home/teto/wireshark/build/__nix_qt5__/bin »'].
15:32:05 [D      ] [1.1:5:1] stderr: nix: [': File exists', ''].
15:32:05 [D      ] [1.1:5:1] exit: nix: 1.

```

**Comment by blueyed** [comment]
Why is this closed?

For reference, I've created https://github.com/neomake/neomake/pull/1686 to fix the `/bin/bash` issue.

**Comment by teto** [comment]
I would like to push a PR for a maker that runs the buildPhase. As it's not filetype specific where should I put it ?

**Comment by blueyed** [comment]
Just for the record: this was answered on IRC, it should go into `autoload/neomake/makers` directly.

**Comment by teto** [comment]
indeed. relevant PR https://github.com/neomake/neomake/pull/2070

**Comment by teto** [comment]
I dont use neomake for this usecase so closing.
