### ISSUE TITLE
Neomake breaks [motion]c inputs

### ISSUE THREAD

**Issue by mnakama** [neomake/neomake#1598]
Editor: neovim
OS: MacOSX
UI: iterm or vimR (issue exists on both)

Using latest master (2713ea9a475841e7a28d7a636fb9e590542f8691)

After loading Neomake with "execute pathogen#infect()", [motion]c inputs are strangely broken. I isolated it to just Neomake, and I disabled all my mappings.

In normal mode on a line of text of multiple words, press "ec" quickly. "e" moves to the end of the current word, then "c" deletes the character and goes into insert mode. But, if you type "ec" slowly, it works correctly by going to the end of the word and awaiting a motion for the "c" command.

This happens with all [motion]c commands. Using "hc" or "lc", we end up in insert mode (without deleting a character). "jc" and "kc" erase an entire line then go into insert mode.

It doesn't happen with any other command that I've tested. "ed", etc. will properly await a motion no matter how fast I type it.

### Expected behavior

Typing any [motion]c command should await a motion before erasing text and going into insert mode, no matter how fast I type it. This works perfectly if I don't load Neomake.

### Steps to reproduce

1. Load Neomake into neovim with pathogen@infect
2. open a file
3. in normal mode, type "ec" quickly.
4. observe that a character was erased and you're in insert mode

### Output from (verbose) NeomakeInfo

I tried ":let g:neomake_verbose = 3", but there are no logged ":messages" at all. I'm not running :Neomake, but it's breaking normal neovim input handling.

**Comment by blueyed** [comment]
Interesting.
So you have no custom Neomake config either then?!
Does it happen with a minimal vimrc where just Neomake is installed/loaded?

**Comment by mnakama** [comment]
Right. I removed everything from my .config/nvim/init.vim except "execute pathogen#infect", and I removed everything from nvim/bundle except neomake, and the issue still exists. So, no Neomake config settings (I normally set it to run on save and buffer load) Removing Neomake solves the issue, no matter what other plugins and config settings I have.

I'm honestly wondering if this is a bug in neovim itself, regarding concurrency. Neomake /shouldn't/ break anything if I'm not running any :Neomake commands, right?

**Comment by mnakama** [comment]
I just tested with regular vim with the same setup (empty vimrc, only neomake loaded), and the issue doesn't exist at all.

Here's my version info for neovim and regular vim:

**$ nvim -v**
NVIM v0.2.0
Build type: Release
Compilation: /Users/me/homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170914-97250-wtl7bh/neovim-0.2.0/build/config -I/tmp/neovim-20170914-97250-wtl7bh/neovim-0.2.0/src -I/Users/me/homebrew/include -I/Users/me/homebrew/include -I/Users/me/homebrew/include -I/Users/me/homebrew/include -I/Users/me/homebrew/include -I/Users/me/homebrew/include -I/Users/me/homebrew/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I/tmp/neovim-20170914-97250-wtl7bh/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170914-97250-wtl7bh/neovim-0.2.0/build/include
Compiled by [me]

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/Users/me/homebrew/Cellar/neovim/0.2.0_1/share/nvim"


**$ /usr/bin/vim --version**
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr  4 2017 18:14:54)
Included patches: 1-898, 8056
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl             -farsi           -mouse_netterm   +syntax
-arabic          +file_in_path    -mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           -mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
+builtin_terms   -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    -keymap          +postscript      +virtualedit
+comments        -langmap         +printer         +visual
-conceal         +libcall         -profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             -rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
-emacs_tags      -mouseshape      -sniff           -xsmp
+eval            -mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv

**Comment by blueyed** [comment]
> Neomake /shouldn't/ break anything if I'm not running any :Neomake commands, right?

The plugin is still loaded, but this narrows it down a lot.

Does it also happen with Vim?

**Comment by blueyed** [comment]
Can you try Neovim master / nightly, please?

**Comment by mnakama** [comment]
Oh, nightly fixes the issue perfectly. My apologies, I should have tried this first before opening an issue. Thanks =)

nvim-osx64/bin$ ./nvim -v
**NVIM v0.2.1-885-g460aab3**
Build type: Release
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@Traviss-Mac-1167.local

Features: +acl +iconv -jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"
