### ISSUE TITLE
Error when on save: E713: Cannot use empty key for Dictionary

### ISSUE THREAD

**Issue by williamtstanley** [neomake/neomake#1599]
Saving my file causes Error message:
Neomake [+11.4]: [6.-:1:1] Calling Make with options {'ft': 'javascript', 'file_mode': 1}.
Error detected while processing function neomake#Make[18]..<SNR>90_Make[71]..<SNR>90_map_makers:
line   34:
E713: Cannot use empty key for Dictionary

My settings in vimrc for neomake:
autocmd! BufWritePost * Neomake

let g:neomake_javascript_enabled_makers = ['eslint']
let g:neomake_warning_sign = {
  \ 'text': 'W',
  \ 'texthl': 'WarningMsg',
  \ }
let g:neomake_error_sign = {
  \ 'text': 'E',
  \ 'texthl': 'ErrorMsg',
  \ }

let g:jsx_ext_required = 0 " Allow JSX in normal JS files

let g:multi_cursor_quit_key='<Esc>'

let g:localvimrc_persistent = 1

-->

### Output from (verbose) NeomakeInfo

"matchService/routing/router.js" 37L, 780C written
Error detected while processing function neomake#Make[18]..<SNR>90_Make[71]..<SNR>90_map_makers:
line   34:
E713: Cannot use empty key for Dictionary
"matchService/routing/router.js" 37L, 780C written
Error detected while processing function neomake#Make[18]..<SNR>90_Make[71]..<SNR>90_map_makers:
line   34:
E713: Cannot use empty key for Dictionary
"matchService/routing/router.js" 37L, 780C written
Error detected while processing function neomake#Make[18]..<SNR>90_Make[71]..<SNR>90_map_makers:
line   34:
E713: Cannot use empty key for Dictionary
"matchService/routing/router.js" 37L, 780C written
Neomake [     ]: [4.-:1:1] Calling Make with options {'ft': 'javascript', 'file_mode': 1}.
Error detected while processing function neomake#Make[18]..<SNR>90_Make[71]..<SNR>90_map_makers:
line   34:
E713: Cannot use empty key for Dictionary

**Comment by blueyed** [comment]
Is this still an issue?
Can you provide steps to reproduce it then, i.e. the file or a minimal example you are using?

**Comment by williamtstanley** [comment]
It was still an issue but I have since switched to ale. to note: doing eslint --init in a repo seemed to resolve the issue.

**Comment by blueyed** [comment]
Ok, closing it then for now.
Thanks for reporting back.
