### ISSUE TITLE
Set title of quickfix/locationlist window

### ISSUE THREAD

**Issue by blueyed** [neomake/neomake#160]
It would be useful to see there which checkers have been run.

See https://github.com/ervandew/ag/pull/14/files (using try/catch for a more enhanced `setqflist`/`setloclist`) and https://github.com/scrooloose/syntastic/blob/c4c610c26cec14e823aebdbb1c36ce15e8f3ec56/plugin/syntastic/loclist.vim#L312-329 for ways to do so.

**Comment by nerdrew** [comment]
Added an issue to neovim: https://github.com/neovim/neovim/issues/4279

FWIW, I hacked around this with: https://github.com/nerdrew/neomake/commit/60836329f36c6ad3810f04f9650e0661109031bb

**Comment by blueyed** [comment]
Neovim added support for it in https://github.com/neovim/neovim/pull/4337.

I am seeing the following (via airline) currently:

>  Location  :        lgetexpr '' 

**Comment by blueyed** [comment]
Closing this in favor of #316.
