### ISSUE TITLE
Overrides ignored with automake

### ISSUE THREAD

**Issue by lheckemann** [neomake/neomake#1616]
### Expected behavior

Overrides like `g:neomake_cpp_gcc_args` are taken into account equally regardless of automake settings.

### Steps to reproduce

1. Open a C++ source file without automake enabled
2. Set `g:neomake_cpp_gcc_args` to some value that will change how compilation goes (e.g. remove a necessary header include path, or add necessary ones)
3. `:Neomake`
4. `:call neomake#configure#automake('rnw', 1000)`
5. Make some change to the file, observe that the compiler is not passed the overridden args.

[neomake.log](https://github.com/neomake/neomake/files/1329127/neomake.log)

# NeomakeInfo

#### Neomake debug information
Async support: 1
Current filetype: cpp
Windows: 0
[shell, shellcmdflag, shellslash]: ['/nix/store/qp5fw57d38bd1n07ss4zxh88zg67c3vg-bash-4.4-p12/bin/bash', '-c', 0]

##### Enabled makers
For the current filetype ("cpp", used with :Neomake):
 - gcc
   - append_file: 1
   - args: ['-I/nix/store/p8pr8h05ih3dfzya4kh8yh20dals67jp-SDL2-2.0.5-dev/include/SDL2', '-I/nix/store/vqydw2r33n07q6bav9wyy7cbx6rrdnh8-SDL2_image-2.0.1/include/SDL2', '-I/nix/store/d5lsyjnbmbcw66diry48a4w3vi6rq9kv-SDL2_net-2.0.1/include/SDL2', '-I/nix/store/71p15clwdcwyk2z5gr5pvmvsfj6h9ns7-SDL2_ttf-2.0.14/include/SDL2', '-I/nix/store/4g9c7yixc4y071zb0qsvaixmqsjswdf3-openal-soft-1.17.2/include/AL', '-I/nix/store/yxw0m0d5p30ma5v8yrbx3c0k3wnlj2cq-libogg-1.3.2-dev/include', '-I/nix/store/xypw21nbr91q6kncf5y2xspbcs50lhvr-libvorbis-1.3.5-dev/include', '-I/nix/store/an1f51im28jf90h4d1bv7p9pyzj6zvyc-libpng-apng-1.6.31-dev/include', '-I/nix/store/0wc0m18vr2qivfx29kzs225hpay43mhy-zlib-1.2.11-dev/include', '-c', '-Wall']
   - auto_enabled: 0
   - errorformat: '%-G%f:%s:,%-G%f:%l: %#error: %#(Each undeclared identifier is reported only%.%#,%-G%f:%l: %#error: %#for each function it appears%.%#,%-GIn file included%.%#,%-G %#from %f:%l\,,%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%I%f:%l:%c: note: %m,%f:%l:%c: %m,%f:%l: %trror: %m,%f:%l: %tarning: %m,%I%f:%l: note: %m,%f:%l: %m'
   - exe: 'g++'
NOTE: you can define g:neomake_cpp_enabled_makers to configure it (or b:neomake_cpp_enabled_makers).

For the project (used with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_cpp_enabled_makers = ['gcc']
g:neomake_cpp_gcc_args = ['-I/nix/store/p8pr8h05ih3dfzya4kh8yh20dals67jp-SDL2-2.0.5-dev/include/SDL2', '-I/nix/store/vqydw2r33n07q6bav9wyy7cbx6rrdnh8-SDL2_image-2.0.1/include/SDL2', '-I/nix/store/d5lsyjnbmbcw66diry48a4w3vi6rq9kv-SDL2_net-2.0.1/include/SDL2', '-I/nix/store/71p15clwdcwyk2z5gr5pvmvsfj6h9ns7-SDL2_ttf-2.0.14/include/SDL2', '-I/nix/store/4g9c7yixc4y071zb0qsvaixmqsjswdf3-openal-soft-1.17.2/include/AL', '-I/nix/store/yxw0m0d5p30ma5v8yrbx3c0k3wnlj2cq-libogg-1.3.2-dev/include', '-I/nix/store/xypw21nbr91q6kncf5y2xspbcs50lhvr-libvorbis-1.3.5-dev/include', '-I/nix/store/an1f51im28jf90h4d1bv7p9pyzj6zvyc-libpng-apng-1.6.31-dev/include', '-I/nix/store/0wc0m18vr2qivfx29kzs225hpay43mhy-zlib-1.2.11-dev/include', '-c', '-Wall']
g:neomake_logfile = '/tmp/neomake.log'
g:neomake_place_signs = 1
g:neomake_verbose = 3


  makeprg=make
```

#### :version
```

NVIM v0.2.0
Build type: Release
Compilation: /nix/store/m3hr6jjlg637240q67as3js21dg6h218-gcc-wrapper-6.4.0/bin/gcc -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-v0.2.0-src/build/config -I/build/neovim-v0.2.0-src/src -I/nix/store/3xxi0jj8ia4qx6nm9x06k5np3n871xny-libuv-1.13.1/include -I/nix/store/z5ma2zs8klaihvz5ybwz0g4w27rjgxv8-libmsgpack-2.0.0/include -I/nix/store/3yj32waw64f0hq3731nlbdb4cc7pxzc6-unibilium-1.2.0/include -I/nix/store/22nhx625br245w8mkc7kxs8vqdmb31rp-libtermkey-0.19/include -I/nix/store/apcb9alqnp7zssf3blkaqkrxdyqrnx9i-neovim-libvterm-2016-10-07/include -I/nix/store/5sxk93h247vp5b9qycdpzfnj1m42n3gm-jemalloc-4.5.0/include -I/nix/store/50jw5m7lda3rylirxyly9diy55lh149z-glibc-2.25-49-dev/include -I/build/neovim-v0.2.0-src/build/src/nvim/auto -I/build/neovim-v0.2.0-src/build/include
Compiled by nixbld

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/nix/store/aq1rrp7jm4p7cvy4vl14pynvlbwzysx5-neovim-0.2.0/share/nvim"

```

#### :messages
```
"src/main.cpp" 347L, 8296C
```

#### Neomake debug information
Async support: 1
Current filetype: cpp
Windows: 0
[shell, shellcmdflag, shellslash]: ['/nix/store/qp5fw57d38bd1n07ss4zxh88zg67c3vg-bash-4.4-p12/bin/bash', '-c', 0]

##### Enabled makers
For the current filetype ("cpp", used with :Neomake):
Neomake [+2.90]: [-.-:1:1] Using setting errorformat='%-G%f:%s:,%-G%f:%l: %#error: %#(Each undeclared identifier is reported only%.%#,%-G%f:%l: %#error: %#for each function it appears%.%#,%-GIn file included%.%#,%-G %#from %f:%l\,,%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%I%f:%l:%c: note: %m,%f:%l:%c: %m,%f:%l: %trror: %m,%f:%l: %tarning: %m,%I%f:%l: note: %m,%f:%l: %m' from 'maker'.
Neomake [     ]: [-.-:1:1] Using setting args=['-fsyntax-only', '-Wall', '-Wextra', '-I./', '-std=c++1z'] from 'maker'.
Neomake [     ]: [-.-:1:1] Using setting exe='g++' from 'maker'.
Neomake [     ]: [-.-:1:1] Using setting errorformat='%-G%f:%s:,%-G%f:%l: %#error: %#(Each undeclared identifier is reported only%.%#,%-G%f:%l: %#error: %#for each function it appears%.%#,%-GIn file included%.%#,%-G %#from %f:%l\,,%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%I%f:%l:%c: note: %m,%f:%l:%c: %m,%f:%l: %trror: %m,%f:%l: %tarning: %m,%I%f:%l: note: %m,%f:%l: %m' from 'maker'.
Neomake [     ]: [-.-:1:1] Using setting args=['-fsyntax-only', '-Wall', '-Wextra', '-I./', '-std=c++1z'] from 'maker'.
Neomake [     ]: [-.-:1:1] Using setting exe='g++' from 'maker'.
Neomake [     ]: [-.-:1:1] Using setting remove_invalid_entries=0 from 'maker'.
Neomake [     ]: [-.-:1:1] Using setting buffer_output=1 from 'maker'.
 - gcc
   - append_file: 1
   - args: ['-fsyntax-only', '-Wall', '-Wextra', '-I./', '-std=c++1z']
   - auto_enabled: 0
   - errorformat: '%-G%f:%s:,%-G%f:%l: %#error: %#(Each undeclared identifier is reported only%.%#,%-G%f:%l: %#error: %#for each function it appears%.%#,%-GIn file included%.%#,%-G %#from %f:%l\,,%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%I%f:%l:%c: note: %m,%f:%l:%c: %m,%f:%l: %trror: %m,%f:%l: %tarning: %m,%I%f:%l: note: %m,%f:%l: %m'
   - exe: 'g++'
NOTE: you can define g:neomake_cpp_enabled_makers to configure it (or b:neomake_cpp_enabled_makers).

For the project (used with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_cpp_enabled_makers = ['gcc']
g:neomake_cpp_gcc_args = ['-I/nix/store/p8pr8h05ih3dfzya4kh8yh20dals67jp-SDL2-2.0.5-dev/include/SDL2', '-I/nix/store/vqydw2r33n07q6bav9wyy7cbx6rrdnh8-SDL2_image-2.0.1/include/SDL2', '-I/nix/store/d5lsyjnbmbcw66diry48a4w3vi6rq9kv-SDL2_net-2.0.1/include/SDL2', '-I/nix/store/71p15clwdcwyk2z5gr5pvmvsfj6h9ns7-SDL2_ttf-2.0.14/include/SDL2', '-I/nix/store/4g9c7yixc4y071zb0qsvaixmqsjswdf3-openal-soft-1.17.2/include/AL', '-I/nix/store/yxw0m0d5p30ma5v8yrbx3c0k3wnlj2cq-libogg-1.3.2-dev/include', '-I/nix/store/xypw21nbr91q6kncf5y2xspbcs50lhvr-libvorbis-1.3.5-dev/include', '-I/nix/store/an1f51im28jf90h4d1bv7p9pyzj6zvyc-libpng-apng-1.6.31-dev/include', '-I/nix/store/0wc0m18vr2qivfx29kzs225hpay43mhy-zlib-1.2.11-dev/include', '-c', '-Wall']
g:neomake_logfile = '/tmp/neomake.log'
g:neomake_place_signs = 1
g:neomake_verbose = 3


  makeprg=make
```

#### :version
```

NVIM v0.2.0
Build type: Release
Compilation: /nix/store/m3hr6jjlg637240q67as3js21dg6h218-gcc-wrapper-6.4.0/bin/gcc -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-v0.2.0-src/build/config -I/build/neovim-v0.2.0-src/src -I/nix/store/3xxi0jj8ia4qx6nm9x06k5np3n871xny-libuv-1.13.1/include -I/nix/store/z5ma2zs8klaihvz5ybwz0g4w27rjgxv8-libmsgpack-2.0.0/include -I/nix/store/3yj32waw64f0hq3731nlbdb4cc7pxzc6-unibilium-1.2.0/include -I/nix/store/22nhx625br245w8mkc7kxs8vqdmb31rp-libtermkey-0.19/include -I/nix/store/apcb9alqnp7zssf3blkaqkrxdyqrnx9i-neovim-libvterm-2016-10-07/include -I/nix/store/5sxk93h247vp5b9qycdpzfnj1m42n3gm-jemalloc-4.5.0/include -I/nix/store/50jw5m7lda3rylirxyly9diy55lh149z-glibc-2.25-49-dev/include -I/build/neovim-v0.2.0-src/build/src/nvim/auto -I/build/neovim-v0.2.0-src/build/include
Compiled by nixbld

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/nix/store/aq1rrp7jm4p7cvy4vl14pynvlbwzysx5-neovim-0.2.0/share/nvim"

```

#### :messages
```
"src/main.cpp" 347L, 8296C
Copied Neomake info to clipboard ("+).
Neomake [     ]: [-.-:1:1] automake: registered events: FileType, FileChangedShellPost, InsertLeave, BufWinEnter, BufWritePost, TextChanged.
```

**Comment by blueyed** [comment]
Related maybe: https://github.com/neomake/neomake/issues/1633

But both are missing detailed info.

**Comment by lheckemann** [comment]
Which detailed info?

**Comment by blueyed** [comment]
The output from the logfile, see https://github.com/neomake/neomake/issues/1633#issuecomment-334876789.

**Comment by lheckemann** [comment]
[neomake.log](https://github.com/neomake/neomake/files/1367726/neomake.log)

This includes both the successful run before calling `neomake#configure#automake` and the broken one afterwards.

**Comment by lheckemann** [comment]
Is there any info still missing?

**Comment by blueyed** [comment]
@lheckemann 
Might be enough, but I had no time to look into it yet.
Do you have new-style config? `g:neomake` / `b:neomake`?

The problem is that `g:neomake_cpp_gcc_args` gets used with `:Neomake`, but not automaking?

**Comment by blueyed** [comment]
@mxmul
Maybe you can provide more info?

**Comment by blueyed** [comment]
I think https://github.com/neomake/neomake/pull/1773 should fix it.

**Comment by lheckemann** [comment]
Yes, that seems to have fixed it. Thanks!
