### ISSUE TITLE
Statusline is changed globally by neomake

### ISSUE THREAD

**Issue by tracyone** [neomake/neomake#1621]
https://github.com/neomake/neomake/blob/master/autoload/neomake/statusline.vim#L314

Some how this line will change statusline globally.

I do use neomake's autocmd:

see following code:

https://github.com/tracyone/neomake-multiprocess/blob/master/autoload/neomakemp.vim#L238

see following video:

https://asciinema.org/a/iFxL5Gtj3ASVsrVU902xw2Xy1

**Comment by blueyed** [comment]
Thanks for the report, should be fixed now.
