### ISSUE TITLE
[colorscheme] warnings hide the first char at the respective lines

### ISSUE THREAD

**Issue by Paludan** [neomake/neomake#1662]
When I save my file (:w) neomake displays warnings and errors as it should, but the lines where warnings are shown, the first character is hidden.
### Expected behavior

Expected behavior is, that warnings will be shown but not hide the first character in the respective line

### Output from (verbose) NeomakeInfo

Neomake [     ]: [-.-:1:2] automake: handling event BufWritePost.
Neomake [     ]: [-.-:1:2] Using setting automake.ignore_filetypes=['startify'] from 'global'.
Neomake [     ]: [-.-:1:2] automake: automake for event BufWritePost.
Neomake [     ]: [-.-:1:2] Using setting automake.events={'BufWritePost': {'delay': 0}} from 'global'.
Neomake [     ]: [-.-:1:2] automake: neomake_do_automake: BufWritePost.
Neomake [     ]: [-.-:1:2] automake: buffer was not changed.

#### Neomake debug information
Async support: 1
Current filetype: haskell
Windows: 0
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]

##### Enabled makers
For the current filetype ("haskell", used with :Neomake):
Neomake [+39.4]: [-.-:1:2] Using setting errorformat='%E%f:%l:%v: Error: %m,%W%f:%l:%v: Warning: %m,%I%f:%l:%v: Suggestion: %m,%C%m' from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting args=['--verbosity', 'silent', 'exec', '--', 'hlint'] from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting exe='stack' from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting errorformat='%-G%\s%#,%f:%l:%c:%trror: %m,%f:%l:%c:%tarning: %m,%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%E%f:%l:%c:%m,%E%f:%l:%c:,%Z%m' from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting args=['--verbosity', 'silent', 'exec', '--', 'ghc-mod', 'check'] from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting exe='stack' from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting errorformat='%E%f:%l:%v: Error: %m,%W%f:%l:%v: Warning: %m,%I%f:%l:%v: Suggestion: %m,%C%m' from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting args=['--verbosity', 'silent', 'exec', '--', 'hlint'] from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting exe='stack' from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting remove_invalid_entries=0 from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting buffer_output=1 from 'maker'.
 - hlint
   - append_file: 1
   - args: ['--verbosity', 'silent', 'exec', '--', 'hlint']
   - auto_enabled: 1
   - errorformat: '%E%f:%l:%v: Error: %m,%W%f:%l:%v: Warning: %m,%I%f:%l:%v: Suggestion: %m,%C%m'
   - exe: 'stack'
   - postprocess: function('neomake#makers#ft#haskell#HlintEntryProcess')
   - stackexecargs: []
Neomake [     ]: [-.-:1:2] Using setting errorformat='%-G%\s%#,%f:%l:%c:%trror: %m,%f:%l:%c:%tarning: %m,%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%E%f:%l:%c:%m,%E%f:%l:%c:,%Z%m' from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting args=['--verbosity', 'silent', 'exec', '--', 'ghc-mod', 'check'] from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting exe='stack' from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting remove_invalid_entries=0 from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting buffer_output=1 from 'maker'.
 - ghcmod
   - append_file: 1
   - args: ['--verbosity', 'silent', 'exec', '--', 'ghc-mod', 'check']
   - auto_enabled: 1
   - errorformat: '%-G%\s%#,%f:%l:%c:%trror: %m,%f:%l:%c:%tarning: %m,%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%E%f:%l:%c:%m,%E%f:%l:%c:,%Z%m'
   - exe: 'stack'
   - mapexpr: 'substitute(v:val, "\n", "", "g")'
   - stackexecargs: []
NOTE: you can define g:neomake_haskell_enabled_makers to configure it (or b:neomake_haskell_enabled_makers).

For the project (used with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_place_signs = 1
g:neomake_verbose = 3


  makeprg=make
```

#### :version
```

NVIM 0.1.7
Build type: None
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-UFyCc4/neovim-0.1.7=. -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-UFyCc4/neovim-0.1.7/build/config -I/build/neovim-UFyCc4/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-UFyCc4/neovim-0.1.7/build/src/nvim/auto -I/build/neovim-UFyCc4/neovim-0.1.7/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

#### :messages
```
"/media/lee/9A4EFE0C4EFDE0C5/Users/user/Documents/AtSite Parser/parser/src/Main.hs" 30L, 753C
NERDTree: Please wait, caching a large dir ...
NERDTree: Please wait, caching a large dir ... DONE (103 nodes cached).

"/media/lee/9A4EFE0C4EFDE0C5/Users/user/Documents/AtSite Parser/parser/src/Main.hs" 30L, 754C written

1 change; before #2  6 seconds ago
1 change; before #1  10 seconds ago
Already at oldest change
Already at oldest change
Already at oldest change
Already at oldest change
Already at oldest change

1 change; before #3  1 seconds ago
Already at oldest change
Already at oldest change
Already at oldest change

"/media/lee/9A4EFE0C4EFDE0C5/Users/user/Documents/AtSite Parser/parser/src/Main.hs" 30L, 753C written
E15: Invalid expression: 3`
"/media/lee/9A4EFE0C4EFDE0C5/Users/user/Documents/AtSite Parser/parser/src/Main.hs" 30L, 753C written
Neomake [     ]: [-.-:1:2] automake: handling event BufWritePost.
Neomake [     ]: [-.-:1:2] Using setting automake.ignore_filetypes=['startify'] from 'global'.
Neomake [     ]: [-.-:1:2] automake: automake for event BufWritePost.
Neomake [     ]: [-.-:1:2] Using setting automake.events={'BufWritePost': {'delay': 0}} from 'global'.
Neomake [     ]: [-.-:1:2] automake: neomake_do_automake: BufWritePost.
Neomake [     ]: [-.-:1:2] automake: buffer was not changed.
Neomake [+66.8]: [-.-:1:2] Using setting errorformat='%E%f:%l:%v: Error: %m,%W%f:%l:%v: Warning: %m,%I%f:%l:%v: Suggestion: %m,%C%m' from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting args=['--verbosity', 'silent', 'exec', '--', 'hlint'] from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting exe='stack' from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting errorformat='%-G%\s%#,%f:%l:%c:%trror: %m,%f:%l:%c:%tarning: %m,%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%E%f:%l:%c:%m,%E%f:%l:%c:,%Z%m' from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting args=['--verbosity', 'silent', 'exec', '--', 'ghc-mod', 'check'] from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting exe='stack' from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting errorformat='%E%f:%l:%v: Error: %m,%W%f:%l:%v: Warning: %m,%I%f:%l:%v: Suggestion: %m,%C%m' from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting args=['--verbosity', 'silent', 'exec', '--', 'hlint'] from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting exe='stack' from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting remove_invalid_entries=0 from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting buffer_output=1 from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting errorformat='%-G%\s%#,%f:%l:%c:%trror: %m,%f:%l:%c:%tarning: %m,%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%E%f:%l:%c:%m,%E%f:%l:%c:,%Z%m' from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting args=['--verbosity', 'silent', 'exec', '--', 'ghc-mod', 'check'] from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting exe='stack' from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting remove_invalid_entries=0 from 'maker'.
Neomake [     ]: [-.-:1:2] Using setting buffer_output=1 from 'maker'.
NVIM 0.1.7
Build type: None
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-UFyCc4/neovim-0.1.7=. -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-UFyCc4/neovim-0.1.7/build/config -I/build/neovim-UFyCc4/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-UFyCc4/neovim-0.1.7/build/src/nvim/auto -I/build/neovim-UFyCc4/neovim-0.1.7/build/include
```

![screenshot from 2017-10-16 16-18-37](https://user-images.githubusercontent.com/9047148/31659332-1a8dbe1e-b334-11e7-8b51-d87e8cde83af.png)
![screenshot from 2017-10-16 16-18-23](https://user-images.githubusercontent.com/9047148/31659336-1de06d28-b334-11e7-9be2-c14dc42cf511.png)

Hey so you can see how the first image shows the editor before saving, and the second when I save. The second one after I save hides the first character.

**Comment by blueyed** [comment]
Looks like the highlighting hides it.

It should normally be underlined or something like that.

**Comment by blueyed** [comment]
What colorscheme are you using?

**Comment by Paludan** [comment]
I use Solarized Dark, but this is just the built in Terminator color schemes. I've also tried with gnome-terminal without any color schemes, no change :S

**Comment by willxy** [comment]
(Note: Figured out by the end -- tldr:
- set `highlight NeomakeWarning`, not just `highlight NeomakeWarningSign`, to something that will show up on a dark background
- or set `let g:neomake_highlight_columns = 0` to not have the first-char highlight at all

)

Seeing the same thing; it seems to be highlighting the first char, with the color of the sign, although in the case of my `highlight NeomakeWarningSign ctermfg=darkblue`, it seems to be showing up in black rather than darkblue:

![screen shot 2018-01-06 at 5 25 40 pm](https://user-images.githubusercontent.com/18635433/34644935-acd1b6f6-f306-11e7-918e-3e1b7f2ea041.png)

With the cursor over it, indeed I can see the char is underlined:

![screen shot 2018-01-06 at 5 20 55 pm](https://user-images.githubusercontent.com/18635433/34644921-3aa05e3e-f306-11e7-9e4d-4d30a811aa97.png)

With `let g:neomake_highlight_lines = 1`:

![screen shot 2018-01-06 at 5 22 15 pm](https://user-images.githubusercontent.com/18635433/34644923-3e226e6c-f306-11e7-8f33-95cd229df84f.png)

Ah --  I see I can make the highlight of that first char go away, with:

        let g:neomake_highlight_columns = 0

It looks like the lingering question is why it's rendering in black instead of the highlight color.  Actually it looks like it's not using the highlight color at all for those columns.  Eg with:

    highlight NeomakeErrorSign ctermfg=darkblue
    highlight NeomakeWarningSign ctermfg=white

it gives me:

![screen shot 2018-01-06 at 5 39 46 pm](https://user-images.githubusercontent.com/18635433/34645009-a0d35934-f308-11e7-956a-4e7d3c58a3e3.png)

Ahh -- I see -- there's another set of highlight groups -- I hadn't caught on to those.

Now I set eg:

    highlight NeomakeError ctermbg=red ctermfg=white
    highlight NeomakeWarning ctermbg=red ctermfg=white

and get:

![screen shot 2018-01-06 at 5 49 54 pm](https://user-images.githubusercontent.com/18635433/34645065-0d0f0ec6-f30a-11e7-8137-bcbca41b5ae8.png)

And that works great.

**Comment by blueyed** [comment]
@willxy 
What colorscheme are you using?

**Comment by willxy** [comment]
@blueyed - I don't think I ever configured colorschemes per se.  Looks like `:colo`says `default` for me.

**Comment by blueyed** [comment]
Could reproduce it using the default colorscheme - very unfortunate indeed!

https://github.com/neomake/neomake/pull/1827 should fix it.
