### ISSUE TITLE
Temporary files should be expanded correctly with `%:p` in args

### ISSUE THREAD

**Issue by CptnKirk** [neomake/neomake#1665]
See https://github.com/neomake/neomake/pull/1666#issuecomment-338444276

Original issue:

Neomake can asynchronously run makers against dirty buffers.  This is exposed via enhanced append_file support.  The credo and dogma makers however still use the '%p' expansion, which returns the current filename.  Neomake will still trigger makers on buffer change, but the makers will scan the wrong file. 

### Expected behavior
Type as you go linting happens without having to save changes.

### Steps to reproduce
1. Open file.  
2. Make changes that should be warned.  
3. Wonder why nothing happens.

**Comment by CptnKirk** [comment]
I have a fix.  Just needed an issue to link against.

**Comment by blueyed** [comment]
Thanks.

It might actually indicate a bug also, so that it should get expanded to the tempfile really.

**Comment by blueyed** [comment]
This should be fixed.
There are tests for this being added in 8ac0d09.
