### ISSUE TITLE
Rubocop default args could use some love

### ISSUE THREAD

**Issue by ledhed2222** [neomake/neomake#1695]
For rails uses, rubocop has a command line option `-R` that includes additional rails-specific linters. The included neomake rubocop maker does not include this flag.

The maker also does not include the `-D` option to output the failed linter rule.

Now, it's trivial to just add them with
```vimscript
let g:neomake_ruby_rubocop_args=['--format', 'emacs', '--force-exclusion', '-D', '-R']
```

But for new users seems like we should just add the flags.

### Expected behavior
I'd expect both flags to be included by default

Include the `-R` and `-D` flags for the rubocop maker

### Steps to reproduce
Lint this file:
```ruby
#!/usr/bin/env ruby
x = Time.now
puts x
```
Neomake will not report an error. However if you then
```bash
rubocop -R $FILE_NAME
```
you will see an error with the invocation of `Time.now`.

#### Neomake debug information
Async support: 1
Current filetype: ruby
Windows: 0
[shell, shellcmdflag, shellslash]: ['/bin/zsh', '-c', 0]

##### Enabled makers
For the current filetype ("ruby", used with :Neomake):
 - mri
   - append_file: 1
   - args: ['-c', '-T1', '-w']
   - auto_enabled: 0
   - errorformat: '%-G%\m%.%#warning: %\%%(possibly %\)%\?useless use of == in void context,%-G%\%.%\%.%\%.%.%#,%-GSyntax OK,%E%f:%l: syntax error\, %m,%Z%p^,%W%f:%l: warning: %m,%Z%p^,%W%f:%l: %m,%-C%.%#'
   - exe: 'ruby'
   - output_stream: 'both'
 - rubocop
   - append_file: 1
   - args: ['--format', 'emacs', '--force-exclusion']
   - auto_enabled: 0
   - errorformat: '%f:%l:%c: %t: %m,%E%f:%l: %m'
   - exe: 'rubocop'
   - postprocess: function('neomake#makers#ft#ruby#RubocopEntryProcess')
NOTE: you can define g:neomake_ruby_enabled_makers to configure it (or b:neomake_ruby_enabled_makers).

For the project (used with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_echo_current_error = 1
g:neomake_highlight_columns = 1
g:neomake_javascript_enabled_makers = ['eslint']
g:neomake_place_signs = 1
g:neomake_ruby_enabled_makers = ['mri', 'rubocop']


  makeprg=make
```

#### :version
```

NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/config -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/include
Compiled by brew@Sierra-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0_1/share/nvim"

```

#### :messages
```
"~/Documents/Dev/grailed/app/models/listing/create.rb" 121L, 3991C
"~/Documents/Dev/grailed/app/models/listing/create.rb" 121L, 3991C written


"~/Documents/Dev/grailed/app/models/listing/create.rb" 126L, 4051C written


"~/Documents/Dev/grailed/app/models/listing/create.rb" 127L, 4068C written

"~/Documents/Dev/grailed/app/models/listing/create.rb" 128L, 4079C written
E121: Undefined variable: g:neomake_enabled_makers
"script/rails" 6L, 295C
```

**Comment by blueyed** [comment]
Thanks for the report.
Please create a PR.

**Comment by ledhed2222** [comment]
You got it: https://github.com/neomake/neomake/pull/1706

**Comment by YorickPeterse** [comment]
This change seems to have resulted in Rubocop always enabling Rails checks, even for non Rails projects. This leads to annoying warnings such as Rubocop not telling you to use `puts` instead of `Rails.logger`.

Because of the `--rails` flag there's no way to disable this either as Rubocop seems to ignore adding the following to `.rubocop.yml`:

```
Rails:
  Enabled: false
```

I realise I can disable these options, but it feels like enabling this by default when you can already do htis in the rubocop config might annoy more users than necessary.

**Comment by blueyed** [comment]
@YorickPeterse 
Thanks for the feedback.  Please create a new issue and/or even a PR to fix this.

@ledhed2222 
Please help out.

**Comment by ledhed2222** [comment]
Shoot. I thought rubocop's rails-specific linters only targeted issues that are very specific to rails. I wonder if maybe the right solution is to have two makers: `ruby` and `ruby-rails`? If that solution isn't tenable then I'd agree with @YorickPeterse and would just disable rails by default, but add some documentation to the helptext describing how to enable rails for a given directory (with an external vimscript config)

**Comment by ledhed2222** [comment]
what do you guys think?

**Comment by blueyed** [comment]
> two makers: ruby and ruby-rails?

Sounds good to me.

**Comment by ledhed2222** [comment]
opened https://github.com/neomake/neomake/pull/1742

**Comment by blueyed** [comment]
https://github.com/neomake/neomake/pull/1742 was merged, thanks!
