### ISSUE TITLE
Provide ability to reload file after make run

### ISSUE THREAD

**Issue by ViViDboarder** [neomake/neomake#173]
Taking inspiration from [fatih/vim-go](https://github.com/fatih/vim-go) and it's [fmt](https://github.com/fatih/vim-go/blob/master/autoload/go/fmt.vim) features, it would be really cool if a maker could specify that it would possibly update a file. Then it could trigger logic similar to the fmt.vim file linked above. Though, I don't see this working too well asynchronously.

Any thoughts on if this is something work implementing? Or would be better to put this maker into it's own plugin rather than neomake?

**Comment by benekastah** [comment]
I guess all we need is for #161 to be implemented. Then it would be easy to say "When a maker is complete, run :e on the file". I don't mind making this possible, but I don't specifically want to encourage it (for example, by making a `g:neomake_reload_file` option or something). I don't want neomake to be blamed for messing up people's buffers :)

**Comment by jamischarles** [comment]
Would love this. Trying to run `eslint --fix` in neomake, but the changes don't show up w/o reloading.

**Comment by derekdowling** [comment]
As an example, I have this running with:
```
autocmd BufWritePost * call neomake#Make(1, [], function('s:Neomake_callback'))

" Callback for reloading file in buffer when eslint has finished and maybe has
" autofixed some stuff
function! s:Neomake_callback(options)
    if (a:options.name ==? 'goimports') && (a:options.status == 0)
        edit
    endif
endfunction
```

**Comment by blueyed** [comment]
Interesting.
Are people still using / interested in this kind of thing?

Instead of `:edit` it could use `:checktime` instead?!

**Comment by snoblenet** [comment]
yes please

**Comment by blueyed** [comment]
@snoblenet 
What is your use case?

Quick'n'dirty:
```vim
augroup my_neomake
  au!
  autocmd NeomakeFinished * checktime
augroup END
```

**Comment by snoblenet** [comment]
Thanks @blueyed I'll do that.

My use case is having the `--fix` argument set on eslint and then making a change and Vim asking if I'm sure I want to save the buffer as the file has also been changed externally.

**Comment by blueyed** [comment]
`checktime` would also ask you, which might be annoying (depending on the `autoread` setting, which defaults to `on`).
You could check `g:neomake_hook_context.jobinfo.maker.name` in the autocmd, so that it only gets done for eslint.

A callback on the maker like suggested in https://github.com/neomake/neomake/issues/173#issuecomment-217597959 might make sense, too.

**Comment by snoblenet** [comment]
In the end, I decided that automatic asynchronous linting _without_ autofixing was the ideal use case for Neomake, while linting _with_ autofixing was better of being triggered manually and handled synchronously -- blocking me for a few seconds to avoid the risk of read-write conflicts. So my `init.vim` now looks like this:

```
set updatetime=5000
augroup auto_writing
  autocmd!
  autocmd BufRead * :Neomake! ctags
  autocmd BufWritePre * :Neomake! ctags
  autocmd BufLeave * silent! wall | Neomake
  autocmd FocusLost * silent! wall | Neomake
  autocmd CursorHold * silent! wall | Neomake
  autocmd InsertLeave * silent! wall | Neomake
augroup END
" brew tap universal-ctags/universal-ctags
" brew install --HEAD universal-ctags
let g:neomake_ctags_maker = { 'exe': 'ctags', 'args': ['-R'] }
function! FixThis()
  retab
  execute 'normal! mm gg=G `m'
    if (&ft ==# 'javascript')
      :!eslint --fix %
    elseif (&ft ==# 'json')
      :!eslint --fix --plugin json %
    elseif (&ft ==# 'html')
      :! tidy --indent yes --vertical-space no --literal-attributes yes --show-body-only no --indent-spaces 2 --tidy-mark no --wrap 100 %
  endif
  checktime
  Neomake
endfunction
nnoremap <leader>fix :call FixThis()<CR>
set autoread
set autowrite
set autowriteall
let g:neomake_open_list=0
" pip install vim-vint
let g:neomake_vim_vint_maker = { 'args': ['--enable-neovim'] }
let g:neomake_vim_enabled_makers = ['vint']
" npm install eslint --global
" npm install eslint_d --global
" npm install eslint-config-airbnb-base --global
" npm install eslint-plugin-chai-friendly --global
" npm install eslint-plugin-import --global
let g:neomake_javascript_enabled_makers = ['eslint']
" npm install jsonlint --global
let g:neomake_json_enabled_makers = ['jsonlint']
" html-tidy
let g:neomake_html_enabled_makers = ['tidy']
" npm install csslint --global
let g:neomake_css_enabled_makers = ['csslint']
" brew install shellcheck
let g:neomake_sh_enabled_makers = ['shellcheck']
" pip install yamllint
let g:neomake_yaml_enabled_makers = ['yamllint']
```

Thanks for your advice along the way.

**Comment by blueyed** [comment]
> let g:neomake_vim_vint_maker = { 'args': ['--enable-neovim'] }

that is not necessery, is it?

**Comment by snoblenet** [comment]
I can't remember the details, but without it, Vint complains if your `init.vim` doesn't contain certain things that have been deprecated in Neovim.

**Comment by flybayer** [comment]
This is working good for me:
```vim
augroup my_neomake_hooks
  au!
  autocmd User NeomakeJobFinished :checktime
augroup END
```

**Comment by blueyed** [comment]
Closing, since this can be done via hooks.
