### ISSUE TITLE
Neomake should not create files in current repo.

### ISSUE THREAD

**Issue by wsdjeg** [neomake/neomake#1736]
here is what `git status` show:

```
On branch version-control
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   autoload/SpaceVim/default.vim

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	autoload/SpaceVim/.default.vim@neomake_6232_10.vim
	autoload/SpaceVim/.default.vim@neomake_6232_8.vim
	autoload/SpaceVim/layers/.VersionControl.vim@neomake_6232_3.vim
	autoload/SpaceVim/layers/VersionControl.vim

no changes added to commit (use "git add" and/or "git commit -a")
````

I think neomake should not create files like:

```
autoload/SpaceVim/.default.vim@neomake_6232_10.vim	
autoload/SpaceVim/.default.vim@neomake_6232_8.vim	
autoload/SpaceVim/layers/.VersionControl.vim@neomake_6232_3.vim
````

**Comment by blueyed** [comment]
There are some issues / discussion regarding this already.

Normally it should not really be a problem, but mostly only if you run Neomake and then <kbd>Ctrl</kbd><kbd>z</kbd> Vim while it is running still etc - or in case it was not removed properly (which is a bug).

As a workaround you can add `.*@neomake*` to your global (git) ignore file.

**Comment by blueyed** [comment]
Related issues: https://github.com/neomake/neomake/issues/1212 https://github.com/neomake/neomake/issues/1595 https://github.com/neomake/neomake/issues/1617

**Comment by wsdjeg** [comment]
@blueyed This happens when I use `:wq` in neovim. ok, I will update gitignore of my projects.

**Comment by blueyed** [comment]
It should not happen though: it should get cleaned up on VimLeave - but maybe this is related to #1617 then.
Does it happen always? Do you have steps to reproduce it?

**Comment by wsdjeg** [comment]
no, I do not have reproduce step, but it only sometimes happens when I use `:wq`.

**Comment by chancez** [comment]
Can we get a config flag to tell neomake where to store tmpfiles? I already put files like this in `~/.vim/tmp/{backup,swap,undo}` and would prefer to be able to configure neomake to use something like `~/.vim/tmp/neomake`.

**Comment by blueyed** [comment]
Yes, would make sense.
For reference, the code is this https://github.com/neomake/neomake/blob/ffa7ee5b534d86f6db5d51ff788f82a6ddc9161c/autoload/neomake.vim#L515-L552 (and could need some revisit in general I suppose).

**Comment by lheckemann** [comment]
>ok, I will update gitignore of my projects

@wsdjeg you can also make a global gitignore file that you do not have to keep in the git repo but applies to all repos — see the core.excludesFile git config option.

**Comment by hiqua** [comment]
I just had the same problem because vim crashed, apparently while neomake was doing something.

@blueyed From your snippet, but it looks like neomake uses tempname(). According to `:h tempfile`, if $TMPDIR is set, then it will be used preferably instead of /tmp or the current directory. Would it then be enough to just define this variable to avoid this problem in the future?

**Comment by chancez** [comment]
So I started looking into this and I made a small change that enables customizing the location the tempfiles are saved in.

This is the branch:
https://github.com/chancez/neomake/tree/custom_tempfile_dir

If you're using vim-plug you can test it out with:

```
Plug 'git@github.com:chancez/neomake.git', { 'branch': 'custom_tempfile_dir' }
let g:neomake_tempfile_base_directory = '/Users/chance/.vim/tmp/neomake/'
```

I'm not really sure how to add tests or where in the `doc/neovim.txt` this should go, but if this turns out to work for others, perhaps it could be upstreamed.

**Comment by chancez** [comment]
@blueyed I'm pretty new to vimscript and plugins overall, what would I need to do to get this added as a new option in neomake? I'm sure tests/docs, but I may need some help/guidance on where to put this in the docs/what the existing `neomake-makers-tempfile_enabled` section should be modified to look like. And tests...that is definitely something I'm less familiar with.

**Comment by blueyed** [comment]
It should use `neomake#utils#GetSetting`, so that it can be configured per buffer/maker etc.

I'm looking into it later.

**Comment by blueyed** [comment]
See https://github.com/neomake/neomake/pull/1788.
Feedback would be appreciated, of course.
