### ISSUE TITLE
Use Vim 8 features for updating the quickfix list without replacing quickfix lists from other plugins

### ISSUE THREAD

**Issue by yegappan** [neomake/neomake#1737]
When the neomake plugin is updating a quickifx list asynchronously, some other
Vim plugin or user can create/modify the quickfix list resulting in the neomake
plugin updating the incorrect quickfix list. This can be avoided by using
the new features in Vim8.

Refer to the following thread for the steps to do this:
https://groups.google.com/forum/#!topic/vim_use/LTWNG0nRQCc

Patch 1023 for Vim 8 added the support for the quickfix list identifier.

**Comment by blueyed** [comment]
Thank you!

I will consider doing it once the patch is in Neovim - but any PR / help is welcome before already of course.

**Comment by blueyed** [comment]
Fixed in https://github.com/neomake/neomake/pull/2188, thanks!
