### ISSUE TITLE
Disable typescript temp files 

### ISSUE THREAD

**Issue by mhartington** [neomake/neomake#1785]
### Expected behavior
The making of temp files triggers rebuilds when developing and having a build system watching my app. I read over the docs on how to disable the temp-file feature using this: 

```
  let g:neomake_typescript_tsc_tempfile_enabled = 0
  let g:neomake_typescript_tlint_tempfile_enabled = 0
```
 
But the temp file will still being created. Is this the correct way to do this?

The temp file would not be created.

### Steps to reproduce
Clone this repo
https://github.com/mhartington/chroma-test

cd into it, run `npm install` and then `npm run ionic:serve` and observe the build output when linting. The app will get rebuild multiple times when the temp file is made and then deleted. 

### Output from (verbose) NeomakeInfo

<details>

#### Neomake debug information
Async support: 1
Current filetype: typescript
Windows: 0
[shell, shellcmdflag, shellslash]: ['/usr/local/bin/zsh', '-c', 0]

##### Enabled makers
For the current filetype ("typescript", used with :Neomake):
 - tsc
   - append_file: 0
   - args: ['--noEmit', '--watch', 'false', '--pretty', 'false', '--project', '/Users/mhartington/GitHub/tmp2/tsconfig.json']
   - auto_enabled: 1
   - errorformat: '%E%f %#(%l\,%c): error %m,%E%f %#(%l\,%c): %m,%Eerror %m,%C%\s%\+%m'
   - exe: 'tsc'
 - tslint
   - append_file: 1
   - args: ['--project', '/Users/mhartington/GitHub/tmp2/tsconfig.json']
   - auto_enabled: 1
   - cwd: '/Users/mhartington/GitHub/tmp2'
   - errorformat: '%EERROR: %f[%l\, %c]: %m,%E%f[%l\, %c]: %m'
   - exe: 'tslint'
NOTE: you can define g:neomake_typescript_enabled_makers to configure it (or b:neomake_typescript_enabled_makers).

For the project (used with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_error_sign = {'text': '•'}
g:neomake_html_enabled_makers = []
g:neomake_javascript_enabled_makers = ['eslint']
g:neomake_markdown_enabled_makers = ['alex', 'proselint']
g:neomake_markdown_proselint_maker = {'postprocess': function('neomake#postprocess#GenericLengthPostprocess'), 'errorformat': '%W%f:%l:%c: %m'}
g:neomake_place_signs = 1
g:neomake_scss_enabled_makers = ['scsslint']
g:neomake_typescript_tlint_tempfile_enabled = 0
g:neomake_typescript_tsc_tempfile_enabled = 0
g:neomake_warning_sign = {'text': '•'}


  makeprg=tsc  $* %
	Last set from ~/.config/nvim/.cache/init.vim/.dein/compiler/typescript.vim
```

#### :version
```

NVIM v0.2.3-220-g3cc7ebf81
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20171209-98512-5z6q7r/build/config -I/tmp/neovim-20171209-98512-5z6q7r/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -I/tmp/neovim-20171209-98512-5z6q7r/build/src/nvim/auto -I/tmp/neovim-20171209-98512-5z6q7r/build/include
Compiled by mhartington@Mikes-MBP-2.fios-router.home

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-3cc7ebf/share/nvim"

Run :checkhealth for more info
```

#### :messages
```
"src/app/app.module.ts" 93L, 3068C
nvim-ts: Server Started
Neoformat: prettier formatted buffer
NVIM v0.2.3-220-g3cc7ebf81
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20171209-98512-5z6q7r/build/config -I/tmp/neovim-20171209-98512-5z6q7r/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -I/tmp/neovim-20171209-98512-5z6q7r/build/src/nvim/auto -I/tmp/neovim-20171209-98512-5z6q7r/build/include
```

</details>

**Comment by blueyed** [comment]
That should work.

Are you sure the tempfiles are from Neomake, and not from Neovim itself?
(it should be visible in the debug log)

**Comment by mhartington** [comment]
Pretty sure it's from neomake, as it has neomake in the file name.

Though, it appears to only be when using the auto-make settings 

```
  call neomake#configure#automake({
  \ 'BufWritePost': {'delay': 0},
  \ 'BufWinEnter': {},
  \ 'TextChanged': {},
  \ 'InsertLeave': { },
  \ }, 1000)
```

Here's a gif of the issue happening.

![neomake-temp-file](https://user-images.githubusercontent.com/2835826/33949133-bc714126-dff6-11e7-9460-ae447bc1ad89.gif)

**Comment by blueyed** [comment]
Thanks for the .gif, but a logfile is more useful.

However, you have a typo: missing `s` with `let g:neomake_typescript_tlint_tempfile_enabled = 0`.

`let g:neomake_typescript_tsc_tempfile_enabled = 0` is not required since it does not append a file.

tslint complains for me anyway:

> Invalid source file: t/.t.ts@neomake_14085_20.ts. Ensure that the files supplied to lint have a .ts, .tsx, .d.ts, .js or .jsx extension.

It probably does not really look at the last part/extension of the file?!
(should get fixed there, or a custom pattern should be used)
See also #1212.

**Comment by mhartington** [comment]
Ahh, right you are. Thanks. Regarding #1212, does that mean a different location, (something like `$HOME/neovim_temp`) could be used for the temp files? Or am I mistaken?

**Comment by blueyed** [comment]
Yes.
The current default is based on the idea that the file's location should mimic the real file (regarding subdirs etc).
