### ISSUE TITLE
Constant spamming of Error detected while processing function <SNR>144_TabEnterHandler[16]..SNR>144_RestoreNERDTreeViewIfPossible: E16: Invalid range: 2wincmd w

### ISSUE THREAD

**Issue by juicetin** [neomake/neomake#1796]
### Expected behavior

Be able to change tabs with NERDTree open, with the keep NERDTree position across tabs option on, without this error.

Seems to be a re-surfacing of https://github.com/neomake/neomake/issues/350.

### Steps to reproduce

1. set `let g:nerdtree_tabs_synchronize_view=1` in neovim config.
2. Try and tab between tabs in different directories. Doesn't seem to always happen, but once it starts, it happens without fail switching between tabs of files in different directories in the same project.

### Output from (verbose) NeomakeInfo
This command doesn't exist in my neovim? Will investigate and provide if needed.

**Comment by blueyed** [comment]
The command `:verbose NeomakeInfo` does not work?

It would be helpful to have the logfile from when this starts to happen, and any custom settings you have.

**Comment by blueyed** [comment]
@juicetin 
Is this still an issue for you?
Can you provide additional information, please?

**Comment by blueyed** [comment]
I assume that 582ff9c3 fixed this.
