### ISSUE TITLE
pylint: unexpected output on stderr

### ISSUE THREAD

**Issue by airhuman** [neomake/neomake#1806]
Some errors happened when I was using neomake and pylint(1.8.0) 

Neomake [     ]: [1.-:1:1] Calling Make with options {'ft': 'python', 'file_mode': 1}.
Neomake [     ]: [1.-:1:1] Running makers: pylint.
Neomake [     ]: Defining sign: sign define neomake_file_err texthl=NeomakeErrorSign text=✖.
Neomake [     ]: Defining sign: sign define neomake_project_err texthl=NeomakeErrorSign text=✖.
Neomake [     ]: Defining sign: sign define neomake_file_warn texthl=NeomakeWarningSign text=⚠.
Neomake [     ]: Defining sign: sign define neomake_project_warn texthl=NeomakeWarningSign text=⚠.
Neomake [     ]: Defining sign: sign define neomake_file_info texthl=NeomakeInfoSign text=ℹ.
Neomake [     ]: Defining sign: sign define neomake_project_info texthl=NeomakeInfoSign text=ℹ.
Neomake [     ]: Defining sign: sign define neomake_file_msg texthl=NeomakeMessageSign text=➤.
Neomake [     ]: Defining sign: sign define neomake_project_msg texthl=NeomakeMessageSign text=➤.
Neomake [     ]: [1.1:1:1] Setting neomake_automake_tick.
Neomake [     ]: [1.1:1:1] Starting async job: ['pylint', '--output-format=text', '--msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg} [{msg_id}]"', '--reports=no', '/Users/liyong/tmp/a.py'].
Neomake [     ]: [1.1:1:1] cwd: /Users/liyong/tmp.
Neoformat: no change necessary with autopep8
Neomake [+0.68]: [1.1:1:1] stderr: pylint: ['Using config file /Users/liyong/.pylintrc', ''].
Neomake [     ]: [1.1:1:1] stdout: pylint: ['', '--------------------------------------------------------------------', 'Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)', '', ''].
Neomake [+0.16]: [1.1:1:1] exit: pylint: 0.
Neomake [     ]: [1.1:1:1] pylint: processing 4 lines of output.
Neomake [     ]: [1.1:1:1] Creating location list.
Neomake [     ]: [1.1:1:1] Processing 0 entries.
Neomake [     ]: [1.-:1:1] File-level errors cleaned.
Neomake [     ]: [1.1:1:1] pylint: completed with exit code 0.
Neomake [     ]: [1.1:1:1] pylint: unexpected output on stderr: Using config file /Users/liyong/.pylintrc.
Neomake: pylint: unexpected output on stderr: Using config file /Users/liyong/.pylintrc
Neomake [     ]: [1.1:1:1] pylint: unexpected output. See :messages for more information.
Neomake [     ]: [1.1:1:1] Cleaning jobinfo.
Neomake [     ]: [1.-:1:1] Cleaning make info.
"a.py" 21L, 266C written
Neomake [+4.65]: [2.-:1:1] Calling Make with options {'ft': 'python', 'file_mode': 1}.
Neomake [     ]: [2.-:1:1] Running makers: pylint.
Neomake [     ]: [2.2:1:1] Setting neomake_automake_tick.
Neomake [     ]: [2.2:1:1] Starting async job: ['pylint', '--output-format=text', '--msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg} [{msg_id}]"', '--reports=no', '/Users/liyong/tmp/a.py'].
Neomake [     ]: [2.2:1:1] cwd: /Users/liyong/tmp.
Neomake [+0.64]: [2.2:1:1] stderr: pylint: ['Using config file /Users/liyong/.pylintrc', ''].
Neomake [     ]: [2.2:1:1] stdout: pylint: ['', '--------------------------------------------------------------------', 'Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)', '', ''].
Neomake [+0.16]: [2.2:1:1] exit: pylint: 0.
Neomake [     ]: [2.2:1:1] pylint: processing 4 lines of output.
Neomake [     ]: [2.2:1:1] Creating location list.
Neomake [     ]: [2.2:1:1] Processing 0 entries.
Neomake [     ]: [2.-:1:1] File-level errors cleaned.
Neomake [     ]: [2.2:1:1] pylint: completed with exit code 0.
Neomake [     ]: [2.2:1:1] pylint: unexpected output on stderr: Using config file /Users/liyong/.pylintrc.
Neomake: pylint: unexpected output on stderr: Using config file /Users/liyong/.pylintrc
Neomake [     ]: [2.2:1:1] pylint: unexpected output. See :messages for more information.
Neomake [     ]: [2.2:1:1] Cleaning jobinfo.
Neomake [     ]: [2.-:1:1] Cleaning make info.

**Comment by airhuman** [comment]
When I use pylint==1.7.5 or pylint==1.7.4, it's okay. No error ouput.
Maybe it's a bug of pylint.

**Comment by vvollaro** [comment]
Hi, I have the same issue with pylint 1.8.1 but also with pytlint 1.7.5
