### ISSUE TITLE
No signs drawn when using latest Rust nightly build

### ISSUE THREAD

**Issue by YorickPeterse** [neomake/neomake#1809]
Using the latest nightly version of Rust results in Neomake not displaying any error/info/etc signs in the line number bar. Using Rust stable does work.

I managed to generate a diff of the output of stable vs nightly, and it's as following (with the additions being what was changed in rust nightly):

```diff
diff --git a/stable.txt b/nightly.txt
index 21cb326..b9131f8 100644
--- a/stable.txt
+++ b/nightly.txt
@@ -20,7 +20,7 @@
     },
     "level": "error",
     "message": "the trait bound `{integer}: std::ops::Shr<&str>` is not satisfied",
-    "rendered": null,
+    "rendered": "error[E0277]: the trait bound `{integer}: std::ops::Shr<&str>` is not satisfied\n --> src/main.rs:2:23\n  |\n2 |     println!(\"{}\", 10 >> \"foo\");\n  |                       ^^ no implementation for `{integer} >> &str`\n  |\n  = help: the trait `std::ops::Shr<&str>` is not implemented for `{integer}`\n\n",
     "spans": [
       {
         "byte_end": 36,
@@ -65,7 +65,7 @@
     "code": null,
     "level": "error",
     "message": "aborting due to previous error",
-    "rendered": null,
+    "rendered": "error: aborting due to previous error\n\n",
     "spans": [
 
     ]
```

A gist containing the neomake logs can be found at https://gist.github.com/YorickPeterse/49d8355b8381d52a35d30d4a4c4156f3.

### Steps to reproduce

Create the following Rust file:

```rust
fn main() {
    println!("{}", 10 >> "foo");
}
```

Run `rustup default nightly` to make nightly the default. Then open the Rust file in Vim and run `Neomake cargo`. Note how no signs are drawn. Running `:lopen` will display the location list with the error, but jumping to an error will result in a new buffer being opened instead of the existing one being reused. Trying to write said buffer will result in the error "E203: Autocommands deleted or unloaded buffer to be written". Said buffer _will_ show the signs.

A recording of this behaviour can be found at https://asciinema.org/a/av0SbrSTtm4M0sKLlPlEOmLpJ.

**Comment by YorickPeterse** [comment]
Version info:

```
$ rustc --version
rustc 1.24.0-nightly (b98fd524e 2018-01-05)
$ cargo --version
cargo 0.25.0-nightly (a88fbace4 2017-12-29)
$ nvim --version
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by blueyed** [comment]
For me the diff looks different: the `file_name` is the problem.
Using cargo 0.23.0 (via Arch Linux `rust`) it is relative to cwd (`main.rs`), whereas it is relative to the project root with cargo 0.25.0-nightly (a88fbace4 2017-12-29).
The maker changes to the file's directory (via `cwd`), and then `src/main.rs` creates a new buffer in Vim.

**Comment by blueyed** [comment]
Does it make sense to change to the dir where `Cargo.toml` is?
That seems to be a required file for cargo to work anyway, isn't it?

**Comment by YorickPeterse** [comment]
@blueyed Changing the cwd to the directory containing `Cargo.toml` sounds like a better approach.

**Comment by blueyed** [comment]
better than what? :)

I can imagine this to be a bug in cargo maybe even.. i.e. it should output either the correct relative path (to `cwd`), or an absolute file name.
Tried to find a changelog in this regard, but could not.

**Comment by blueyed** [comment]
https://github.com/neomake/neomake/pull/1814 should fix it, but it would be good to clarify this.
The downside here is of course that it will do this globbing now always additionally when invoking the maker..

**Comment by YorickPeterse** [comment]
@blueyed 

> better than what? :)

Better than the current approach of setting `cwd`.

> #1814 should fix it, but it would be good to clarify this.

I applied this patch locally and it indeed solves the problem. Thanks :smile:
