### ISSUE TITLE
error message after install

### ISSUE THREAD

**Issue by burningTyger** [neomake/neomake#1845]
I installed neomake as described in the readme.
when I start nvim I get this:
```
Error detected while processing /home/me/.config/nvim/init.vim:
line   81:
E117: Unknown function: neomake#configure#automake
Press ENTER or type command to continue
```

### Expected behavior
Neovim (latest on Arch) starts just fine.

### Steps to reproduce
add

```vim
Plug 'neomake/neomake'
call neomake#configure#automake('rw', 1000)
let g:neomake_open_list = 2
```
to my `~/.config/nvim/init.vim`

### Output from (verbose) NeomakeInfo

1. Paste the output from `:verbose NeomakeInfo` here.
   You can use `:verbose NeomakeInfo!` (with a bang at the end) to copy it to
   your clipboard.
#### Neomake debug information

Async support: 1
Current filetype: vim
Windows: 0
[shell, shellcmdflag, shellslash]:['/bin/bash', '-c', 0]

##### Enabled makers

For the current filetype ("vim", used with :Neomake):
 - vint
   - args: ['--style-problem', '--no-color', '-f', '{file_path}:{line_number}:{column_number}:{severity}:{description} ({policy_name})', '--enable-neovim']
   - auto_enabled: 1
   - errorformat: '%I%f:%l:%c:style_problem:%m,%f:%l:%c:%t%*[^:]:E%n: %m,%f:%l:%c:%t%*[^:]:%m'
   - exe: 'vint'
   - output_stream: 'stdout'
   - postprocess: {'pattern': '\v(Undefined variable: |:)\zs([^ ]+)', 'fn': function('neomake#postprocess#generic_length')}
   - WARNINGS:
     - maker's exe (vint) is not executable.
NOTE: you can define g:neomake_vim_enabled_makers to configure it (or b:neomake_vim_enabled_makers).

Default maker settings:
 - output_stream: 'both'
 - remove_invalid_entries: 0
 - buffer_output: 1

For the project (used with :Neomake!):
None.
NOTE: you can define g:neomake_enabled_makers to configure it.

###### New-style (dict, overrides old-style)

```
g:neomake: unset
b:neomake: unset
```

###### Old-style

```
g:neomake_logfile = '/tmp/neomake.log'
g:neomake_open_list = 2
g:neomake_place_signs = 1

```
  makeprg=make

#### :version

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

#### :messages

```
Error detected while processing /home/me/.config/nvim/init.vim:
line   81:
E117: Unknown function: neomake#configure#automake
"~/.config/nvim/init.vim" 296L, 8242C
```

2. If relevant paste the contents of the logfile (via `g:neomake_logfile`).

**Comment by blueyed** [comment]
@burningTyger 
I've clarified the README.

**Comment by burningTyger** [comment]
ok, thank you!

**Comment by blueyed** [comment]
You're welcome.
Thanks for the report and please let me know of any other problems you might find.
