### ISSUE TITLE
ESLint should use "--stdin" for temporary files

### ISSUE THREAD

**Issue by t0str** [neomake/neomake#1850]
I recently started using ESLint on a project I work on. To manage the first influx of errors ESLint throws, I wanted to have an integration in neovim (running HEAD) that makes it easy for me to comb through all files and fix the error.

### Expected

Being able to use neomake with ESLint in this fashion:
```
call neomake#configure#automake('nw', 750)
```
or like this:
```
call neomake#configure#automake({
  \ 'TextChanged': {},
  \ 'InsertLeave': {},
  \ 'BufWritePost': {'delay': 0},
  \ 'BufWinEnter': {},
  \ }, 500)
```

### Actual

Opening a .js file works fine. As soon as any other event except `BufEnter` or `BufWritePost` ist triggered I get this in the location window:

```
some_file_name_that_exists.js|| File ignored by default.  Use a negated ignore pattern (like "--ignore-pattern '!<relative/path/to/filename>'") to override.
```

After this, location window and the red crosses in the main editor window are gone. `:w` the file fixes the problem until the next time I trigger an event that is not save or open.

It works flawlessly if I configure it like this:

```
autocmd BufWritePost,BufEnter * Neomake
```

#### Neomake debug information

Async support: 1
Current filetype: javascript.jsx
Windows: 0
[shell, shellcmdflag, shellslash]:['/bin/bash', '-c', 0]

##### Enabled makers

For the current filetype ("javascript.jsx", used with :Neomake):
 - eslint
   - args: ['-f', 'compact']
   - auto_enabled: 0
   - cwd: '%:p:h'
   - errorformat: '%E%f: line %l\, col %c\, Error - %m,%W%f: line %l\, col %c\, Warning - %m,%-G,%-G%*\d problems%#'
   - exe: '/private/path/node_modules/.bin/eslint'
NOTE: you can define g:neomake_javascript_jsx_enabled_makers to configure it (or b:neomake_javascript_jsx_enabled_makers).

Default maker settings:
 - output_stream: 'both'
 - remove_invalid_entries: 0
 - buffer_output: 1

For the project (used with :Neomake!):
None.
NOTE: you can define g:neomake_enabled_makers to configure it.

###### New-style (dict, overrides old-style)

```
g:neomake: {
  'automake': {
    'ignore_filetypes': ['startify'],
    'events': {
      'BufWritePost': {
        'delay': 0,
      },
      'InsertLeave': {},
      'BufWinEnter': {},
      'TextChanged': {},
    },
  },
  'automake_delay': 500,
}
b:neomake: unset
```

###### Old-style

```
g:neomake_javascript_enabled_makers = ['eslint']
g:neomake_javascript_eslint_exe = '/private/path/node_modules/.bin/eslint'
g:neomake_javascript_jsx_enabled_makers = ['eslint']
g:neomake_javascript_jsx_eslint_exe = '/private/path/node_modules/.bin/eslint'
g:neomake_place_signs = 1
g:neomake_ruby_enabled_makers = ['mri', 'rubocop']

```
  makeprg=make

#### :version

```
NVIM v0.2.3-688-g9e9e4431c
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180212-5190-14wjv43/build/config -I/tmp/neovim-20180212-5190-14wjv43/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180212-5190-14wjv43/build/src/nvim/auto -I/tmp/neovim-20180212-5190-14wjv43/build/include
Compiled by ost@orianna.tostr.io

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-9e9e443_1/share/nvim"

Run :checkhealth for more info
```

#### :messages

```
Copied Neomake info to clipboard ("+).
```

**Comment by blueyed** [comment]
Looks like an issue with temporary files - sadly logs are missing.
I think we could use `"--ignore-pattern '!$tempfilename"` to fix this.

**Comment by blueyed** [comment]
better: `--stdin` and `--stdin-filename` (hopefully skipping the ignoring then).

**Comment by t0str** [comment]
Adding the requested log file @blueyed 

[neomake.log](https://github.com/neomake/neomake/files/1725009/neomake.log)

**Comment by polodrawsshowing** [comment]
Is there way to fix it right now?

**Comment by blueyed** [comment]
@polodrawsshowing 
As said above the maker should use the said options, i.e. its args need to get adjusted.
See other makers using `--stdin` or similar already.
