### ISSUE TITLE
Feasible to use xolox/vim-misc for legacy Vim async calls?

### ISSUE THREAD

**Issue by dragon788** [neomake/neomake#186]
http://peterodding.com/code/vim/misc

He has coded a workaround for the non-async nature of most Vim calls to prevent the interface becoming unavailable.

**Comment by benekastah** [comment]
It may be possible, but I think the client-server feature would be required. I don't think I'll put effort into this personally, but your (or anyone) is welcome to try it out and see if you can make it work. If so, I would consider merging it (provided it doesn't add too much complexity).

**Comment by blueyed** [comment]
Yeah, likely not worth it, since Vim supports jobs by now, and older Vims are just meant to be synchronous.
