### ISSUE TITLE
Statusline functions don't show running checks when Neomake is disabled

### ISSUE THREAD

**Issue by somini** [neomake/neomake#1861]
It is possible to `NeomakeDisable*` and then run Neomake manually. This is mentioned in the docs.

When Neomake is disabled, the statusline changes to an unconditional `$SCOPE-`, with scope being the disable scope.
This is triggered by this code:
https://github.com/neomake/neomake/blob/dbd873a988af116017fba2bfffcb27ac92097d9a/autoload/neomake/statusline.vim#L271-L275

This means when Automake is disabled and you run a check manually, there's no feedback.

### Expected behavior

The same feedback for running a check when automake is enabled should be available when automake is disabled.

### Steps to reproduce

1. Disable automake for a buffer: `NeomakeDisableBuffer`
2. Verify the statusline string is now "b-"
1. Run Neomake manually
1. Verify the statusline shows no feedback, as opposed to the behaviour with automake enabled

**Comment by blueyed** [comment]
https://github.com/neomake/neomake/pull/1865 would fix this also, without adding new formats etc - which might be good base for #1862 then.
Please let me know what you think.
