### ISSUE TITLE
automake 1 buffer wiped out message with report=0 or 1

### ISSUE THREAD

**Issue by matthsims** [neomake/neomake#1876]
### Expected behavior

Using neomake (automake) with `set report=0` or `1`, if there is any signs in the column (any errors or warnings) I will frequently get reports of `'1 buffer wiped out'`. I don't expect this behavior, and it doesn't go away if I `silent` the only occurrence of `bwipeout` in the neomake repository.

### Steps to reproduce
Using vim-plug to install neomake, here is a minimal config to reproduce:
```vim
set report=0

call plug#begin('~/.config/vim/plugged')
Plug 'neomake/neomake' 
call plug#end()

" I have tested each of these three individually, the error occurs any
" time there is something for neomake to warn the user about.
let g:neomake_python_enabled_makers = ['pycodestyle', 'pydocstyle', 'pyflakes']

call neomake#configure#automake({
			\ 'TextChanged': {},
			\ 'InsertLeave': {},
			\ 'BufWritePost': {'delay': 0},
			\ 'BufWinEnter': {},
			\ }, 100)
```

For reproducing, I open neovim on a python file with these contents:
```python
if __name__ == "__main__":
    maintest()
```
I just open a newline anywhere, exit insert mode, and the `1 buffer wiped out` message is reported.

#### Neomake debug information

Async support: 1
Current filetype: python
Windows: 0
[shell, shellcmdflag, shellslash]:['/usr/bin/zsh', '-c', 0]

##### Enabled makers

For the current filetype ("python", used with :Neomake):
 - pycodestyle
   - args: []
   - auto_enabled: 0
   - errorformat: '%f:%l:%c: %m'
   - exe: 'pycodestyle'
   - postprocess: function('neomake#makers#ft#python#Pep8EntryProcess')
 - pydocstyle
   - args: []
   - auto_enabled: 0
   - errorformat: '%W%f:%l %.%#:,%+C        %m'
   - exe: 'pydocstyle'
   - postprocess: function('neomake#postprocess#compress_whitespace')
 - pyflakes
   - args: []
   - auto_enabled: 0
   - errorformat: '%E%f:%l: could not compile,%-Z%p^,%E%f:%l:%c: %m,%E%f:%l: %m,%-G%.%#'
   - exe: 'pyflakes'
NOTE: you can define g:neomake_python_enabled_makers to configure it (or b:neomake_python_enabled_makers).

Default maker settings:
 - output_stream: 'both'
 - remove_invalid_entries: 0
 - buffer_output: 1

For the project (used with :Neomake!):
None.
NOTE: you can define g:neomake_enabled_makers to configure it.

###### New-style (dict, overrides old-style)

```
g:neomake: {
  'automake': {
    'ignore_filetypes': ['startify'],
    'events': {
      'BufWritePost': {
        'delay': 0,
      },
      'InsertLeave': {},
      'BufWinEnter': {},
      'TextChanged': {},
    },
  },
  'automake_delay': 100,
}
b:neomake: unset
```

###### Old-style

```
g:neomake_place_signs = 1
g:neomake_python_enabled_makers = ['pycodestyle', 'pydocstyle', 'pyflakes']
g:neomake_verbose = 1

```
  makeprg=make

#### :version

```
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.4
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-HJnLxJ/neovim-0.2.2/build/config -I/build/neovim-HJnLxJ/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-HJnLxJ/neovim-0.2.2/build/src/nvim/auto -I/build/neovim-HJnLxJ/neovim-0.2.2/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

#### :messages

```
"simple.py" 2L, 42C

1 buffer wiped out
```

**Comment by blueyed** [comment]
>  it doesn't go away if I silent the only occurrence of bwipeout in the neomake repository.

Have you reloaded the file / restarted Neovim?

For me it work when using `silent exe` here:
https://github.com/neomake/neomake/blob/ffb2f9a1bb5778563fcc73c4343ab9fe0d2f7528/autoload/neomake.vim#L1391

I am not sure if the `bwipeout` is really necessary after all, or how Vim/Neomake handles unlisted buffers from setloclist etc over time.
You can remove it locally, and then look at `:ls!` over time to see if things pile up / get clean automatically.

**Comment by matthsims** [comment]
Super cool! I will test complete removal of that line over time, but I can't investigate it thoroughly for a few weeks.
Thanks!

**Comment by blueyed** [comment]
Any updates?

NOTE: this will move/conflict with https://github.com/neomake/neomake/pull/1883.
