### ISSUE TITLE
Is there a way to add a maker to the existing enabled makers?

### ISSUE THREAD

**Issue by euclio** [neomake/neomake#1898]
I'm writing an internal plugin for my company, and I'd like to enable some custom makers for specific filetypes. However, I don't want to clobber any existing makers that people might have configured.

I tried overriding `b:neomake_<ft>_enabled_makers` in hopes that both the global and buffer-local makers would run, but this doesn't seem to be the case.

Is there a better solution than the following (for each filetype, in an ftplugin)?

```
if executable('custom_maker') && exists(':Neomake')
  let g:neomake_<ft>_custom_maker_maker = ...
  if exists('g:neomake_<ft>_enabled_makers')
    call add(g:neomake_<ft>_enabled_makers, 'custom_maker')
  else
    let g:neomake_<ft>_enabled_makers = add(neomake#makers#<ft>#EnabledMakers(), 'custom_maker')
  endif
endif
```

**Comment by blueyed** [comment]
Interesting use case.
Maybe `let b:neomake_<ft>_enabled_makers = neomake#GetEnabledMakers(1, '<ft>') + ['custom_maker']` works?
Haven't tested it, but I agree that there should be an easy way to achieve this.

**Comment by euclio** [comment]
Hm, `neomake#GetEnabledMakers(1, '<ft>')` seems to always return empty list for me.

**Comment by blueyed** [comment]
Sorry, args were wrong.

To get names you can use e.g. `map(neomake#GetEnabledMakers('python'), 'v:val.name')`.

**Comment by euclio** [comment]
For me that function is always returning the default makers, regardless of having `g:neomake_<ft>_enabled_makers` set. Maybe it's just easiest to provide the maker args and have the users enable it if they want it?

**Comment by euclio** [comment]
I ended up setting up per-filetype autocmds that set `b:neomake_<ft>_enabled_makers`, and it worked! Since this is a pretty unique use-case, I'm going to go ahead and close this. Thanks for the help.
