### ISSUE TITLE
Allow linting on-the-fly (by piping buffer content to maker)

### ISSUE THREAD

**Issue by dan-santana** [neomake/neomake#190]
It would be nice to have an option to pipe the buffer content to the maker instead of relying only on the file saved to disk.

With this feature, it would be possible to make on-the-fly linting with some tools (e.g. `eslint` with `--stdin` and `--stdin-filename` options) by `:Neomake`ing on `CursorHold`.

For example, the following would suffice to make the magic happen:

```
let g:neomake_javascript_eslint_maker = {
        \ 'pipe': 1,
        \ 'args': ['-f', 'compact', '--stdin', '--stdin-filename', '%:p'],
        \ 'errorformat': '%E%f: line %l\, col %c\, Error - %m,' .
        \ '%W%f: line %l\, col %c\, Warning - %m'
        \ }

autocmd! CursorHold *.js,*.jsx Neomake
```

Bonus: It would allow testing the code on-the-fly too, if the test setup is fast enough.

**Comment by benekastah** [comment]
This is a nice idea. I would be happy to review a pull request for something like this, but it's unlikely I'll implement features I don't need myself anytime soon.

**Comment by dan-silva** [comment]
Good! I'll try to work on this as soon as possible (I'm still in a transition from Vim to Neovim, and this would be a killer feature to help me change completely).

**Comment by gunar** [comment]
I use [vim-auto-save](https://github.com/vim-scripts/vim-auto-save) and I'm quite happy with it. Bonus: it solves your problem.

**Comment by johannestroeger** [comment]
no, it just introduce side-effects.

**Comment by dan-santana** [comment]
Actually using [vim-auto-save](https://github.com/vim-scripts/vim-auto-save) would create another problem in my setup: rebuild will be triggered when using [gulp](http://gulpjs.com/) or [webpack](https://webpack.github.io/) watchers.

Linting a single file is already costly in some projects, and if I also rebuild the entire project every time... probably my computer will explode (although it may work well for small projects).

**Comment by gunar** [comment]
So I shouldn't be doing this? I've just transitioned from vim so I'll use it like this for a while and give feedback later on.

@dan-santana what kind of whatches are you talking about?

**Comment by dan-santana** [comment]
Not that you shouldn't use it – if it fits to your workflow, there's no problem at all.

The watchers I'm talking about are [this](https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulpwatchglob--opts-tasks-or-gulpwatchglob--opts-cb) and [this](https://webpack.github.io/docs/tutorials/getting-started/#watch-mode).

**Comment by gunar** [comment]
@dan-santana I believe you could benefit from this workflow of mine. The buffer is saved (written) only when I exit Insert mode -- entering Normal mode -- so there aren't so many writes/updates/compilations after all. It should work without burning you CPU :)

**Comment by ivalkeen** [comment]
It is a really good idea! On-the-fly linting option would be an amazing improvement.

**Comment by wsdjeg** [comment]
@blueyed what do you think of [ale](https://github.com/w0rp/ale)? it support lint on the fly. I was very confused, why do people like to repeat the wheel。

**Comment by blueyed** [comment]
Just for reference: https://github.com/dojoteef/neomake-autolint supports linting on the fly, based on using temporary files.

**Comment by blueyed** [comment]
As for linting on the fly there is some WIP in https://github.com/neomake/neomake/pull/1055.

**Comment by blueyed** [comment]
There is support for temporay files by now, and a flag for linters to indicate if they can process stdin.
This is not enabled by default.

#1167 is still WIP though, which would probably then also toggle tempfiles to be enabled by default shortly after being merged.
