### ISSUE TITLE
gvim/win: sign icon only shown partly

### ISSUE THREAD

**Issue by NewUserHa** [neomake/neomake#1905]
btw, the icons are awesome.

I tried set nu!, but still only half.

win10
gvim8
using flask8 for python3

thanks!

**Comment by blueyed** [comment]
Can you show a screenshot, please?
What colorscheme and font are you using?
I could imagine that it's related to the font.
Have you tried Vim in a command window and/or Neovim?

**Comment by NewUserHa** [comment]
guifont: Consolas_NF:h11.5
colorscheme: crusoexia/vim-monokai
![image](https://user-images.githubusercontent.com/32261870/37927609-2b0cd2fe-316d-11e8-9d1f-c865752c9a7a.png)

**Comment by blueyed** [comment]
Looks more like an issue with gvim to me - have you tried another font?

**Comment by NewUserHa** [comment]
tried `Droid_Sans_Mono_Dotted_for_powe:h11`, same.

**Comment by NewUserHa** [comment]
![image](https://user-images.githubusercontent.com/32261870/37957140-ca2b8b7e-31df-11e8-966a-830b1ffb40a2.png)  ![image](https://user-images.githubusercontent.com/32261870/37957120-bf055d60-31df-11e8-9beb-c03e47c74fe6.png)
I put the pics here to help solve this issue.(I know my settings for the two terminal are buggy)

**Comment by NewUserHa** [comment]
I tested `let g:ale_sign_error = '✖'` with `ale`, same, only display left half

**Comment by NewUserHa** [comment]
changing  the 
```
let g:ale_sign_info = ''
let g:ale_sign_error = ''
let g:ale_sign_warning = ''
```
to other unicode icon can solve this issue

**Comment by blueyed** [comment]
Yes, it looks more like an issue with Vim/gvim - closing the issue for Neomake.
Might make sense to use other default icons (maybe based on some detection), and/or document the issue / workaround, so please feel free to follow up here anyway.
