### ISSUE TITLE
[feature] is neomake able to auto check a buffer content every x time(real time) like other plugs?

### ISSUE THREAD

**Issue by NewUserHa** [neomake/neomake#1906]
like sublime anaconda and vim ale.
both they will check automatically and make you know immediately once something wrong.
I think neomake is a nice plugin and it should have the nice feature too but I'm not so familiar with vim, therefore I wanna know is there an option or easy way to achieve that? and can it be documented to help others future?
thanks!

**Comment by blueyed** [comment]
Have you read https://github.com/neomake/neomake#setup?

**Comment by NewUserHa** [comment]
yea. all of the three commands need write buffer to do `make`

**Comment by blueyed** [comment]
Using `call neomake#configure#automake('nw', 1000)` will trigger it when writing and for normal mode changes (with a 1s timer), and when leaving insert mode.
If it does not work, please provide the logfile (see the issue template).

**Comment by blueyed** [comment]
`'i'` can be used for insert mode changes.

**Comment by NewUserHa** [comment]
thanks.
I mean checking syntax without writing buffer is useful

**Comment by blueyed** [comment]
Closing this issue then, since this is possible.
But I am not sure you got it?!
If you do not want to check it when writing the buffer you could leave out `w`, but it is a good idea to have it in general.
You can also lower the timeout, of course.

**Comment by NewUserHa** [comment]
I last tried `call neomake#configure#automake('n', 500)` failed.
sorry, it works now.

btw, hope this can be documented to help others.
thanks.

**Comment by blueyed** [comment]
Revisited the README in f7c4ff6.
However, you should still read `:help neomake-automake` for more details.

**Comment by NewUserHa** [comment]
yeah. but a good readme also can make ppl star this project.
umm.. 
the pathed readme.md is still not clear for 'every 500 ms without needing writing buffer' to non-english speakers, like me, I think..
