### ISSUE TITLE
NeomakeCancelJobs not always working

### ISSUE THREAD

**Issue by antoyo** [neomake/neomake#1911]
### Expected behavior

`:NeomakeCancelJobs` should cancel all jobs, even when using the `cargo` maker.

### Steps to reproduce

1. Build the project with neomake.
2. Type `:NeomakeCancelJobs`.
3. In a terminal, type `cargo build`: `cargo` thinks the file is locked because neomake didn't kill the job.
4. Exiting neovim will unlock the file.

#### Neomake debug information

Async support: 1
Current filetype: rust
Windows: 0
[shell, shellcmdflag, shellslash]:['/usr/bin/fish', '-c', 0]

##### Enabled makers

For the current filetype ("rust", used with :Neomake):
 - cargo
   - append_file: 0
   - args: ['check', '--message-format=json', '--quiet']
   - auto_enabled: 1
   - cwd: '%:p:h'
   - exe: 'cargo'
   - process_output: function('neomake#makers#ft#rust#CargoProcessOutput')
NOTE: you can define g:neomake_rust_enabled_makers to configure it (or b:neomake_rust_enabled_makers).

Default maker settings:
 - output_stream: 'both'
 - remove_invalid_entries: 0
 - buffer_output: 1

For the project (used with :Neomake!):
None.
NOTE: you can define g:neomake_enabled_makers to configure it.

###### New-style (dict, overrides old-style)

```
g:neomake: {
  'automake': {
    'ignore_filetypes': ['startify'],
    'events': {
      'BufWritePost': {
        'delay': 0,
      },
    },
  },
}
b:neomake: unset
```

###### Old-style

```
g:neomake_asciidoc_enabled_makers = []
g:neomake_open_list = 2
g:neomake_place_signs = 1

```
  makeprg=make

#### :version

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compilé par builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

         fichier vimrc système : "$VIM/sysinit.vim"
               $VIM par défaut : "/usr/share/nvim"

Run :checkhealth for more info
```

#### :messages

```
```

**Comment by blueyed** [comment]
Please provide the logs from canceling jobs.

Neovim should kill it after 4s.
At least that happens with `:NeomakeSh tests/helpers/trap.sh`, and then `:NeomakeCancelJobs`:
```
11:27:15 [D +34.0] [3.-:4:1] Running makers: sh: tests/helpers/trap.sh.
11:27:15 [V +0.01] [3.3:4:1] Starting async job: /bin/sh -c tests/helpers/trap.sh.
11:27:15 [D      ] [3.3:4:1] cwd: /home/daniel/src/neomake.
11:27:18 [D +22.5] Calling VimLeave.
11:27:31 [D +15.6] Cancelling 1 jobs.
11:27:31 [D      ] [3.3:4:1] Cancelling job.
11:27:31 [D      ] [3.3:4:1] Stopping job.
11:27:35 [D +4.00] [3.3:4:1] stderr: sh: tests/helpers/trap.sh: ['Terminated', ''].
11:27:35 [D      ] [3.3:4:1] Ignoring output (job was canceled).
11:27:35 [D      ] [3.3:4:1] stdout: sh: tests/helpers/trap.sh: ['Started: 31431', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '>
11:27:35 [D      ] [3.3:4:1] Ignoring output (job was canceled).
11:27:35 [D      ] [3.3:4:1] exit: job was canceled.
11:27:35 [D      ] [3.3:4:1] Cleaning jobinfo.
11:27:35 [D      ] [3.-:4:1] Cleaning make info.
```

**Comment by blueyed** [comment]
Are you waiting 4s?
Do you suspend Neovim (Ctrl-Z)?

**Comment by antoyo** [comment]
I was able to reproduce while waiting 4 seconds.
Let me some time to reproduce with the logs, now.

**Comment by blueyed** [comment]
> exit: job was canceled.

This means that the exit handler was called, i.e. the job should have exited and Neovim got notified.

1. Can you investigate using `ps aux|grep cargo` and `pstree -apL` to see what process is still there.
2. What is the error from running `cargo build` then exactly?

**Comment by blueyed** [comment]
Assuming this was fixed, otherwise please re-open with more information.
