### ISSUE TITLE
Prevent neomake from running at startup

### ISSUE THREAD

**Issue by antoyo** [neomake/neomake#1918]
### Expected behavior

Neomake should not run a task at startup if not instructed to.

### Steps to reproduce

Here's my config:
```vim
let g:neomake_open_list = 2
call neomake#configure#automake('w')
```

1. Open a Rust project.
2. cargo is running, but it should not.

Here's the log when I open the project:
```
09:38:51 [D      ] [-.-:1:1] automake: registered events: BufWritePost.
```

(I don't know what triggers this BufWrite since I only open files.)

#### Neomake debug information

Async support: 1
Current filetype: rust
Windows: 0
[shell, shellcmdflag, shellslash]:['/usr/bin/fish', '-c', 0]

##### Enabled makers

For the current filetype ("rust", used with :Neomake):
 - cargo
   - append_file: 0
   - args: ['check', '--message-format=json', '--quiet']
   - auto_enabled: 1
   - cwd: '/projects/relm'
   - exe: 'cargo'
   - process_output: function('neomake#makers#ft#rust#CargoProcessOutput')
NOTE: you can define g:neomake_rust_enabled_makers to configure it (or b:neomake_rust_enabled_makers).

Default maker settings:
 - output_stream: 'both'
 - remove_invalid_entries: 0
 - buffer_output: 1

For the project (used with :Neomake!):
None.
NOTE: you can define g:neomake_enabled_makers to configure it.

###### New-style (dict, overrides old-style)

```
g:neomake: {
  'automake': {
    'ignore_filetypes': ['startify'],
    'events': {
      'BufWritePost': {
        'delay': 0,
      },
    },
  },
}
b:neomake: unset
```

###### Old-style

```
g:neomake_logfile = '/tmp/neomake.log'
g:neomake_open_list = 2
g:neomake_place_signs = 1

```
  makeprg=make

#### :version

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compilé par builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

         fichier vimrc système : "$VIM/sysinit.vim"
               $VIM par défaut : "/usr/share/nvim"

Run :checkhealth for more info
```

#### :messages

```
"examples/buttons-attribute.rs" 142L, 4073C
LanguageClient project root: /projects/relm
```

**Comment by blueyed** [comment]
> 09:38:51 [D      ] [-.-:1:1] automake: registered events: BufWritePost.

This does not run the maker, but only informs about what autocommands are registered/handled.

Is there more in the logs, i.e. something about really running the maker?

**Comment by blueyed** [comment]
I do not think it runs.
Something else might run `cargo`.

You could check using `pstree -apL` to see where it is coming from maybe.

I am going to close this issue here, but feel free to provide more info still, of course.
