### ISSUE TITLE
Support Haml (I need some help!)

### ISSUE THREAD

**Issue by jalada** [neomake/neomake#193]
I'm using this config as a starter for syntax checking my Haml, which I've copied from syntastic.

```
let g:neomake_haml_haml_maker = {
    \ 'args': ['-c'],
    \ 'errorformat': 'Haml error on line %l: %m,' .
        \ 'Syntax error on line %l: %m,' .
        \ '%-G%.%#'
    \ }
let g:neomake_haml_enabled_makers = ['haml']
```

It mostly works, but I don't get any markers in the file gutter. I think it's because Haml doesn't output the file name, so my location window after running `:Neomake` looks like:

```
|5| Illegal nesting: nesting within plain text is illegal.
```

Am I on the right lines as to why I'm not getting markers? Any suggestions? I couldn't find a similar syntax checker in the currently supported checkers (e.g. one that doesn't mention the file name in the output).

**Comment by benekastah** [comment]
Yeah, neomake doesn't currently handle the case where the filename isn't output by the maker. This should be treated as a bug.

**Comment by blueyed** [comment]
@jalada 
There are ways to support this by now.
Do you still want to work on this?

Then please re-open the issue, and I'd be glad to help.
