### ISSUE TITLE
Docker maker

### ISSUE THREAD

**Issue by nomasprime** [neomake/neomake#1956]
If I want to develop apps in Docker containers and run NeoMake makers through the container, rather than on the local machine, how would I do that?

**Comment by blueyed** [comment]
Depends a bit.
You could use the `NeomakeJobInit` hook to wrap the makers command (see https://github.com/neomake/neomake/blob/8fdf6786e0576b30e6146f54e43e34bad8e76ed8/tests/hooks.vader#L77-L93 for an example with `nice`).
You could also set the maker's exe and args directly, e.g. via global or buffer config, e.g.
```vim
let b:neomake_python_flake8_exe = 'docker'
let b:neomake_python_flake8_args = ['exec', '-ti', '…'] + neomake#makers#ft#python#flake8().args
```

**Comment by blueyed** [comment]
See also https://github.com/neomake/neomake/issues/1979.

Closing as answered.

**Comment by nomasprime** [comment]
Hi @blueyed, I went another direction but I've come back to Neomake and keen to get this working. Is the above still the best way to transform the maker command?

I tried the following without success:

```
  function! s:TransformNeomakeJobInit(context) abort
    let jobinfo = a:context.jobinfo

    if type(jobinfo.argv) == type([])
      let jobinfo.argv = ['dip'] + jobinfo.argv
    else
      let jobinfo.argv = 'dip'.jobinfo.argv
    endif
  endfunction

  augroup neomake_config
    au User NeomakeJobInit call s:TransformNeomakeJobInit(g:neomake_hook_context)
  augroup END
```

I don't know VimScript but I'm guessing it has something to do with the call in the augroup?

**Comment by blueyed** [comment]
@nomasprime 
Welcome back! :)
I think InitForJob is better, see `:h neomake-makers-InitForJob`.
(just for reference, there's a using NeomakeJobInit (https://github.com/neomake/neomake/blob/e319509a93498dd66cb468686ca227f12c57866d/tests/hooks.vader#L66-L104), and several using InitForJob (https://github.com/neomake/neomake/blob/e319509a93498dd66cb468686ca227f12c57866d/tests/makers.vader#L377-L433) - just try it based on the doc though first :))

**Comment by blueyed** [comment]
Also a good approach in general is just creating a wrapper in e.g. `~/bin` that would do e.g. `docker run -it --rm … "$@"` then.

**Comment by nomasprime** [comment]
Ooops! Way I phrased it sounded like I left Neomake. I didn't. Neomake is too awesome. Meant I gave up on the Docker workflow but decided to have another go.

I'm actually using another great tool called Dip that does actually that, wraps Docker commands. For some reason though the commands are wrapped in the shell but not in NeoVim. Would be a big win if I could get them working in NeoVim because currently I'm wrapping for multiple plug-ins. Do you have any ideas?

**Comment by nomasprime** [comment]
Dip is loaded in my `.zshrc` but NeoVim doesn't seem to have access to this. Apparently loading aliases, wrappers, etc., in `.zshenv` is a bad idea.

**Comment by blueyed** [comment]
@nomasprime 
Cool.. :)
Is it this dip?  https://github.com/bibendi/dip
What does `dip console` output?  (which is meant to be used via eval)
Is it creating aliases for installed "apps"?

**Comment by blueyed** [comment]
btw: Neomake checks for executables, which does not include aliases/functions then anyway.
If you can use it via e.g. `dip run …` then I recommend still adding wrapper shell scripts to e.g. `~/bin` (which should be added to your `$PATH` then also, of course ;)).
(I assume you do not want to use/try `dip` anyway for all makers, but only for those where it installs something into your shell).

**Comment by nomasprime** [comment]
@blueyed yes, that's it.

I have `eval "$(dip console)"` in my `.zshrc` and the wrapper are available, e.g., rubocop, in my shell but not in NeoVim.

If I could get these wrapper working in NeoVim, wouldn't that be the same as adding wrappers to `~/bin` or would the Neomake checks be broken in both instances?

Ideally I'd like to get all my dev/test environments running in Docker so I guess I'd actually use Dip for all makers.

**Comment by nomasprime** [comment]
If I move the relevant config to `.zshenv`, everything seems to work. But, as above, apparently this is a bad idea? Is there a better way?

**Comment by blueyed** [comment]
What's the output from `dip console` (some examples).
You cannot have shell functions/alias "in Neovim" really.

> `.zshenv`
Interesting.  I still don't know what "dip console" does.

**Comment by nomasprime** [comment]
This is output from `dip console`:

```
export DIP_SHELL=1
export DIP_EARLY_ENVS=TERM_SESSION_ID,SSH_AUTH_SOCK,LC_TERMINAL_VERSION,COLORFGBG,ITERM_PROFILE,XPC_FLAGS,LANG,PWD,SHELL,TERM_PROGRAM_VERSION,TERM_PROGRAM,PATH,LC_TERMINAL,COLORTERM,COMMAND_MODE,TERM,HOME,TMPDIR,USER,XPC_SERVICE_NAME,LOGNAME,ITERM_SESSION_ID,__CF_USER_TEXT_ENCODING,SHLVL,OLDPWD,BROWSER,EDITOR,VISUAL,PAGER,LESS,DIP_SHELL,DIP_EARLY_ENVS,DIP_PROMPT_TEXT,LESS_TERMCAP_mb,LESS_TERMCAP_md,LESS_TERMCAP_me,LESS_TERMCAP_se,LESS_TERMCAP_so,LESS_TERMCAP_ue,LESS_TERMCAP_us,LS_COLORS,GREP_COLOR,GREP_COLORS,HOMEBREW_PREFIX,HOMEBREW_CELLAR,HOMEBREW_REPOSITORY,PROMPT_EOL_MARK,BASE16_THEME,HUB_CONFIG,FZF_DEFAULT_OPTS,_
export DIP_PROMPT_TEXT="ⅆ"

function dip_clear() {
  # just stub, will be redefined after injecting aliases
  true
}

function dip_inject() {
  eval "$(dip console inject)"
}

function dip_reload() {
  dip_clear
  dip_inject
}

# Inspired by RVM
function __zsh_like_cd() {
  \typeset __zsh_like_cd_hook
  if
    builtin "$@"
  then
    for __zsh_like_cd_hook in chpwd "${chpwd_functions[@]}"
    do
      if \typeset -f "$__zsh_like_cd_hook" >/dev/null 2>&1
      then "$__zsh_like_cd_hook" || break # finish on first failed hook
      fi
    done
    true
  else
    return $?
  fi
}

[[ -n "${ZSH_VERSION:-}" ]] ||
{
  function cd()    { __zsh_like_cd cd    "$@" ; }
  function popd()  { __zsh_like_cd popd  "$@" ; }
  function pushd() { __zsh_like_cd pushd "$@" ; }
}

export -a chpwd_functions
[[ " ${chpwd_functions[*]} " == *" dip_reload "* ]] || chpwd_functions+=(dip_reload)

if [[ "$ZSH_THEME" = "agnoster" ]]; then
  eval "`declare -f prompt_end | sed '1s/.*/_&/'`"

  function prompt_end() {
    if [[ -n $DIP_PROMPT_TEXT ]]; then
      prompt_segment magenta white "$DIP_PROMPT_TEXT"
    fi

    _prompt_end
  }
fi

dip_reload
```

**Comment by blueyed** [comment]
I see.
This does now make it work from Neovim's `:!…` command though when used via `.zshenv`, does it?
Do you mean that it works in `:term` then?

**Comment by blueyed** [comment]
Well, what's needed is the output from `dip console inject` also.. :)

**Comment by nomasprime** [comment]
@blueyed moving the Dip eval to `.zshenv` everything works.

Without in `.zshenv` and in `.zshrc` I can run commands from `:term` but not `:!…`.

Output of `dip console inject`:

```
function bundle() { dip bundle $@; }

function rspec() { dip rspec $@; }

function rubocop() { dip rubocop $@; }

function compose() { dip compose $@; }

function up() { dip up $@; }

function stop() { dip stop $@; }

function down() { dip down $@; }

function provision() { dip provision $@; }

function dip_clear() {
  unset -f bundle
  unset -f rspec
  unset -f rubocop
  unset -f compose
  unset -f up
  unset -f stop
  unset -f down
  unset -f provision
}
```

**Comment by nomasprime** [comment]
Tried `set shell=/usr/local/bin/zsh\ --rcs\ ~/.zprofile` but then I get no output at all with `!…` for some reason.

**Comment by blueyed** [comment]
> Without in `.zshenv` and in `.zshrc` I can run commands from `:term` but not `:!…`.

Yeah, that's what I've expected.

> Tried `set shell=/usr/local/bin/zsh\ --rcs\ ~/.zprofile` but then I get no output at all with `!…` for some reason.

I recommend not to mess with that.. I actually use `set shell=/bin/sh` for performance reasons, and have a wrapper for `:term` then, but that is just btw: (not using a terminal in neovim much anyway, but rather tmux)
```
:fun MyTerm
   function MyTerm(...)                                                            
1      " echom string(a:000)
2      if a:0
3        let l:shell = &shell
4        let &shell = $SHELL
5        try
6          call termopen(a:000)
7        catch
8        finally
9          let &shell = l:shell
10       endtry
11     else
12       call termopen($SHELL)
13     endif
14     startinsert
   endfunction
:com Term                                                                          
    Name        Args       Address   Complete  Definition
    Term        *                    shellcmd      call MyTerm(<f-args>)
:set shell?
  shell=/bin/sh                                                                    
```

I still recomment to just create the wrapper(s), which can actually be symlinks to the same script then.  If you need more you could think about scripting it based on the output of `dip console inject` (to create missing wrappers), but honestly it is easy to just create a new symlink then.

`~/bin/dip-wrapper`
```sh
#!/bin/sh
set -x

# Get last part (symlink name).
prog=${0##*/}

# Run dip
exec dip "$prog" "$@"
```
Then in `~/bin`: `ln -s dip-wrapper rubocop`, `ln -s dip-wrapper rspec` etc.

For testing I've used `~/bin/dip`:
```sh
#!/bin/sh
set -x
printf '%s\n' "$@"
```

The `set -x` is for debugging, you can remove it if it works.

**Comment by nomasprime** [comment]
Thanks @blueyed, really appreciate it.

How come create the wrappers manually though when Dip does it already?

**Comment by nomasprime** [comment]
@blueyed seems to be working OK now: got NeoVim sourcing `.zprofile` so Dip's eval is called.

Just not sure if the preference for actual files has something to do with your earlier statement?

> btw: Neomake checks for executables, which does not include aliases/functions then anyway.

**Comment by nomasprime** [comment]
Now think I just need to sort out the `^@` and multiple consecutive whitespace characters and I'll be living the dream.

**Comment by blueyed** [comment]
> How come create the wrappers manually though when Dip does it already?

Dip creates shell functions.  They only work when sourced/used in a shell, which has quite some overhead.
Try `time ( for i in {1..100}; do sh -f -c exit; done )` vs `time ( for i in {1..100}; do zsh -i -c exit; done )`. (that starts "sh -f" and "zsh -i" 100 times; you can also try just "zsh -f" and "zsh" also)

I also do not like `$(eval foo init -)` things in my interactive shell startup for performance reasons.
I am creating a lot of new terminal sessions over the day.
And with e.g. `shell` in Neovim that gets used quite a lot (for `system` etc, depending on how you quote it etc).
But you might want to add some `echo "zprofile called: $(date)" >> /tmp/zprofile.log" and check that after some time.

Anyway I'm glad you got it working for now - but still recommend using the wrapper script, especially since I took the time to write it for you.. ;)

**Comment by nomasprime** [comment]
Thanks @blueyed. Really appreciate the extra help getting started.

Guess I'm just trying to get my setup into a workable state and learning a bit before I start working on performance but I'll definitely come back to it.

Talking of which the idea behind running everything in Docker was to have one mechanism for handling different dependencies as opposed to installing RBenv, NodeEnv, etc.

The main downside though, apart from it's not a well trodden path, is the significant performance hit on Mac. Any suggestions?

**Comment by blueyed** [comment]
No, but thought about Docker overhead while reading your comment before the last sentence already.. ;)

**Comment by nomasprime** [comment]
After I got working switched back to local environment to test performance.

Now Dispatch doesn't pick anything up with Minitest and adds `#` to RSpec paths so that doesn't work with Neomake either.

Didn't realise this would be so hard 😄

**Comment by nomasprime** [comment]
@blueyed Btw I ran the tests you suggested and there was indeed a massive difference 😅 Hardly any between Sh and Zsh though.

I'm looking for an alternative to Dispatch now and I'm curious how you run tests?
