### ISSUE TITLE
E117: Unknown function: neomake#configure#automake

### ISSUE THREAD

**Issue by SleeplessNights** [neomake/neomake#1958]
#### Neomake debug information

Async support: 1
Current filetype: vim
Windows: 0
[shell, shellcmdflag, shellslash]:['/usr/bin/zsh', '-c', 0]

##### Enabled makers

For the current filetype ("vim", used with :Neomake):
 - vint
   - args: ['--style-problem', '--no-color', '-f', '{file_path}:{line_number}:{column_number}:{severity}:{description}
({policy_name})']
   - auto_enabled: 1
   - errorformat: '%I%f:%l:%c:style_problem:%m,%f:%l:%c:%t%*[^:]:E%n: %m,%f:%l:%c:%t%*[^:]:%m'
   - exe: 'vint'
   - output_stream: 'stdout'
   - postprocess: {'pattern': '\v%(^:|%([^:]+: ))\zs(\S+)', 'fn': function('neomake#postprocess#generic_length')}
   - WARNINGS:
     - maker's exe (vint) is not executable.
NOTE: you can define g:neomake_vim_enabled_makers to configure it (or b:neomake_vim_enabled_makers).

Default maker settings:
 - output_stream: 'both'
 - remove_invalid_entries: 0
 - buffer_output: 1

For the project (used with :Neomake!):
None.
NOTE: you can define g:neomake_enabled_makers to configure it.

###### New-style (dict, overrides old-style)

```
g:neomake: unset
b:neomake: unset
```

###### Old-style

```
g:neomake_logfile = '/tmp/neomake.log'
g:neomake_open_list = 2
g:neomake_place_signs = 1

```
  makeprg=make

**Comment by blueyed** [comment]
@SleeplessNights 
Glad you solved it.
What was the problem?
