### ISSUE TITLE
Allow file to be excluded from file maker

### ISSUE THREAD

**Issue by jason0x43** [neomake/neomake#196]
It seems like project level builders such as `go build` and `tsc` would generally work fine as filetype builders if the builder definition had a way of excluding the filename. Consider the `go` plugin. It currently includes filetype builders for `go` and `golint`. It's nice to use the filetype mode with go files since you can see both syntax errors (from `go build`) and style errors (from `golint`). However, it doesn't make sense to run `go build` with a filename argument since you'll get spurious errors if the current file uses things defined in other files, so using `Neomake` (not `Neomake!`) with go files as it stands can be kind of annoying.

If the filename could be excluded, either by providing something like a 'nofile' option or by making the ':p' placeholder non-optional for filename inclusion, then filetype-specific project builders like `go build` could run with other filetype builders. I mean, `go build` *is* a filetype builder,it just makes more sense to run it without a file argument.

**Comment by benekastah** [comment]
This is a good idea. As always, not sure when I can get around to fixing this myself, but always willing to review a pull request :)

**Comment by jason0x43** [comment]
I'll submit a PR this weekend. I implemented a `nofile` option locally, which worked fine with Go. Making the ':p' flag a requirement would be cleaner, but it also breaks existing makers.

**Comment by blueyed** [comment]
Fixed/closed by https://github.com/neomake/neomake/pull/198.
