### ISSUE TITLE
Vim(autocmd):E216: No such group or event: neomake

### ISSUE THREAD

**Issue by antoyo** [neomake/neomake#1969]
### Expected behavior

No error.

### Steps to reproduce

Open a C file.
Open another C file.

You get the following error:
```
Error detected while processing function 113[30]..<SNR>44_callback:
line   33:
Vim(autocmd):E216: No such group or event: neomake
```

Logs:

```
15:12:41 [D      ] [-.-:1:1] automake: registered events: BufWritePost.
15:48:37 [D      ] [-.-:1:1] automake: registered events: BufWritePost.
15:48:50 [D +12.2] [-.-:1:1] automake: handling event BufWritePost.
15:48:50 [D      ] [-.-:1:1] Using setting automake.ignore_filetypes=['startify'] from 'global'.
15:48:50 [D      ] [-.-:1:1] automake: configured buffer for ft=remind (no enabled makers).
15:48:50 [D      ] [-.-:1:1] automake: setting tick for new buffer.
15:48:50 [D      ] [-.-:1:1] automake: no enabled makers.
15:48:51 [D +0.98] Calling VimLeave.
15:59:40 [D      ] [-.-:1:1] automake: registered events: BufWritePost.
16:00:04 [D      ] [-.-:1:1] automake: registered events: BufWritePost.
16:00:22 [D +18.4] Calling VimLeave.
16:00:23 [D +43.3] Calling VimLeave.
16:00:26 [D      ] [-.-:1:1] automake: registered events: BufWritePost.
16:00:33 [D      ] [-.-:1:1] automake: registered events: BufWritePost.
16:00:37 [D +4.68] [-.-:1:1] automake: handling event BufWritePost.
16:00:37 [D      ] [-.-:1:1] Using setting automake.ignore_filetypes=['startify'] from 'global'.
16:00:37 [D +0.02] [-.-:1:1] Exe (vint) of auto-configured maker vint is not executable, skipping.
16:00:37 [D      ] [-.-:1:1] automake: configured buffer for ft=vim (no enabled makers).
16:00:37 [D      ] [-.-:1:1] automake: setting tick for new buffer.
16:00:37 [D      ] [-.-:1:1] automake: no enabled makers.
16:00:54 [D +16.9] [-.-:1:1] automake: handling event BufWritePost.
16:00:54 [D      ] [-.-:1:1] Using setting automake.ignore_filetypes=['startify'] from 'global'.
16:00:54 [D      ] [-.-:1:1] automake: no enabled makers.
16:01:07 [D +12.9] [-.-:1:1] automake: handling event BufWritePost.
16:01:07 [D      ] [-.-:1:1] Using setting automake.ignore_filetypes=['startify'] from 'global'.
16:01:07 [D      ] [-.-:1:1] automake: no enabled makers.
16:01:13 [D      ] [-.-:1:1] automake: registered events: BufWritePost.
16:02:57 [D      ] [-.-:1:1] automake: registered events: BufWritePost.
16:04:16 [D      ] [-.-:1:1] automake: registered events: BufWritePost.
```

I don't run neomake at all (and I removed all config), so I'm not sure why this happens.

#### Neomake debug information

Async support: 1
Current filetype: c
Windows: 0
[shell, shellcmdflag, shellslash]:['/usr/bin/fish', '-c', 0]

##### Enabled makers

For the current filetype ("c", used with :Neomake):
 - clang
   - args: ['-fsyntax-only', '-Wall', '-Wextra', '-I./']
   - auto_enabled: 1
   - errorformat: '%-G%f:%s:,%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%I%f:%l:%c: note: %m,%f:%l:%c: %m,%f:%l: %trror: %m,%f:%l: %tarning: %m,%I%f:%l: note: %m,%f:%l: %m'
   - exe: 'clang'
 - clangtidy
   - args: ['%:p']
   - auto_enabled: 1
   - errorformat: '%E%f:%l:%c: fatal error: %m,%E%f:%l:%c: error: %m,%W%f:%l:%c: warning: %m,%-G%\m%\%%(LLVM ERROR:%\|No compilation database found%\)%\@!%.%#,%E%m'
   - exe: 'clang-tidy'
   - short_name: 'ctdy'
 - clangcheck
   - args: ['%:p']
   - auto_enabled: 1
   - errorformat: '%-G%f:%s:,%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%I%f:%l:%c: note: %m,%f:%l:%c: %m,%f:%l: %trror: %m,%f:%l: %tarning: %m,%I%f:%l: note: %m,%f:%l: %m'
   - exe: 'clang-check'
 - checkpatch
   - args: ['--no-summary', '--no-tree', '--terse', '--file']
   - auto_enabled: 1
   - errorformat: '%f:%l: %tARNING: %m,%f:%l: %tRROR: %m'
   - exe: 'checkpatch.pl'
   - WARNINGS:
     - maker's exe (checkpatch.pl) is not executable.
 - cppcheck
   - args: '--quiet --language=c --enable=warning'
   - auto_enabled: 1
   - errorformat: '[%f:%l]: (%trror) %m,[%f:%l]: (%tarning) %m'
   - exe: 'cppcheck'
   - WARNINGS:
     - maker's exe (cppcheck) is not executable.
NOTE: you can define g:neomake_c_enabled_makers to configure it (or b:neomake_c_enabled_makers).

Default maker settings:
 - output_stream: 'both'
 - remove_invalid_entries: 0
 - buffer_output: 1

For the project (used with :Neomake!):
None.
NOTE: you can define g:neomake_enabled_makers to configure it.

###### New-style (dict, overrides old-style)

```
g:neomake: {
  'disabled': 1,
  'automake': {
    'ignore_filetypes': ['startify'],
    'events': {
      'BufWritePost': {
        'delay': 0,
      },
    },
  },
}
b:neomake: unset
```

###### Old-style

```
g:neomake_asciidoc_enabled_makers = []
g:neomake_logfile = '/tmp/neomake.log'
g:neomake_open_list = 2
g:neomake_place_signs = 1

```
  makeprg=make

#### :version

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

#### :messages

```
Error detected while processing function <SNR>26_Open:
line    2:
E484: Can't open file /home/antoni/.config/nvim/sessions/pacnigd.vim
"test/sims/throttling_sims.c" 208L, 5353C
"src/prog_sched_utils.c" 266L, 7134C
Error detected while processing function 113[30]..<SNR>44_callback:
line   33:
Vim(autocmd):E216: No such group or event: neomake
```

**Comment by blueyed** [comment]
Given the "113" in the error msg, what does `:fun {113}` display?
(the number is likely different if you try it again)
It looks like it is coming from outside of Neomake, trying to figure out where it is from.

**Comment by blueyed** [comment]
I've noticed that it might happen in Neomake itself with `:NeomakeDisable` (#1972).
Likely not your issue, but you might want to grep your plugins for "NeomakeDisable" and "^\s+au.*neomake$", too - but also see my previous comment.

**Comment by antoyo** [comment]
Ok, I'm still trying to display the function, but I can't: there's something weird going on.

**Comment by blueyed** [comment]
What's the current error?
Have you tried disabling your plugins and/or bisecting them to find which one is causing it?

**Comment by antoyo** [comment]
Hum, I updated the plugin and it now seems to be fixed.
I'll close this issue if I don't get it anymore for a few days.

**Comment by blueyed** [comment]
The I assume #1972 fixed it for you - closing.

To make sure you could try it without the patch from there.

This would mean however that you somewhere somehow try to disable it globally when it is disabled already (or maybe not yet enabled?!).
