### ISSUE TITLE
Use relative file paths

### ISSUE THREAD

**Issue by AuditeMarlow** [neomake/neomake#1979]
### Expected behavior

Use relative file paths instead of absolute file paths with PHP makers.

### Steps to reproduce

Lint a PHP file using one of Neomake's makers.

**Comment by blueyed** [comment]
Do you mean the output in the location list?

That might just depend on `:cd`, `:tcd`, `:lcd` etc.

Example output would be good.

**Comment by AuditeMarlow** [comment]
I'm using PHP inside a Docker container. The location list displays `|| Could not open input file: /home/niek/test/index.php` for a sample PHP file with syntax errors.

**Comment by blueyed** [comment]
It appears to come from the maker already, i.e. it cannot open the file for some reason.
Please provide the output from `:verbose NeomakeInfo` (see the issue template).
How do you mount the local file?
What is the path in Vim itself?

**Comment by blueyed** [comment]
I would assume it's an issue with shell files then, too.
Can you try `:Neomake sh` on some `t.sh` file with the following contents: `s="`?

**Comment by AuditeMarlow** [comment]
I'm mounting the file as followed:
```sh
docker run \
    --init \
    --interactive \
    --rm \
    --volume "$(pwd)":/app \
    --workdir /app \
    auditemarlow/php:latest "$@"
```

The path of Vim itself is `/home/niek/test` in the case of my test example.

Output of `:verbose NeomakeInfo`:


  makeprg=make

NVIM v0.3.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.0/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
"index.php" 3L, 28C#### Neomake debug information

Async support: 1
Current filetype: php
Windows: 0
[shell, shellcmdflag, shellslash]:['/bin/zsh -l', '-c', 0]

##### Enabled makers

For the current filetype ("php", used with :Neomake):
 - php
   - args: ['-l', '-d', 'display_errors=1', '-d', 'log_errors=0', '-d', 'xdebug.cli_color=0']
   - auto_enabled: 1
   - errorformat: '%-GNo syntax errors detected in%.%#,%EParse error: %#syntax error\, %m in %f on line %l,%EParse error: %m in %f on line %l,%EFatal error: %m in %f on line %l,%-G\s%#,%-GErrors parsing %.%#'
   - exe: 'php'
 - phpmd
   - args: ['%:p', 'text', './phpmd-ruleset.xml']
   - auto_enabled: 1
   - errorformat: '%W%f:%l%\s%\s%#%m'
   - exe: 'phpmd'
   - WARNINGS:
     - maker's exe (phpmd) is not executable.
 - phpcs
   - args: ['--report=csv']
   - auto_enabled: 1
   - errorformat: '%-GFile\,Line\,Column\,Type\,Message\,Source\,Severity%.%#,"%f"\,%l\,%c\,%t%*[a-zA-Z]\,"%m"\,%*[a-zA-Z0-9_.-]\,%*[0-9]%.%#'
   - exe: 'phpcs'
   - WARNINGS:
     - maker's exe (phpcs) is not executable.
 - phpstan
   - args: ['analyse', '--errorFormat', 'raw', '--no-progress', '--level', 0]
   - auto_enabled: 1
   - errorformat: '%E%f:%l:%m'
   - exe: 'phpstan'
   - WARNINGS:
     - maker's exe (phpstan) is not executable.
NOTE: you can define g:neomake_php_enabled_makers to configure it (or b:neomake_php_enabled_makers).

Default maker settings:
 - output_stream: 'both'
 - remove_invalid_entries: 0
 - buffer_output: 1

For the project (used with :Neomake!):
None.
NOTE: you can define g:neomake_enabled_makers to configure it.

##### Settings

###### New-style (dict, overrides old-style)

```
g:neomake: {
  'automake': {
    'ignore_filetypes': ['startify'],
    'events': {
      'FileType': {},
      'FileChangedShellPost': {},
      'BufWritePost': {
        'delay': 0,
      },
      'BufWinEnter': {},
    },
  },
}
b:neomake: unset
```

###### Old-style

```
g:neomake_error_sign = {'text': ''}
g:neomake_info_sign = {'text': ''}
g:neomake_message_sign = {'text': ''}
g:neomake_open_list = 2
g:neomake_php_phpmd_args = ['%:p', 'text', './phpmd-ruleset.xml']
g:neomake_place_signs = 1
g:neomake_warning_sign = {'text': ''}

```
  makeprg=make


#### :version

```
NVIM v0.3.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.0/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

#### :messages

```
"index.php" 3L, 28C
```

**Comment by AuditeMarlow** [comment]
My `sh` maker is working fine, as I am not using Docker to containerize it: `sh: unexpected EOF while looking for matching `"' (E)`

**Comment by blueyed** [comment]
> My sh maker is working fine

I've meant to try it in the Docker container.

The debug output does not contain a failed run - the really interesting part.

I suggest using `let g:neomake_logfile = '/tmp/neomake.log'` and then triggering it.

> I'm mounting the file as followed:

How do you use this container then for running the maker(s)?
Wouldn't you have to override `_exe`?  (the logs should show it)

**Comment by blueyed** [comment]
Have you seen https://github.com/neomake/neomake/issues/1956?

**Comment by blueyed** [comment]
Using this for `g:neomake_php_php_exe` works:
```
#!/bin/sh
docker run \
    --init \
    --interactive \
    --rm \
    --volume "$(pwd)":/app \
    --workdir /app \
    auditemarlow/php:latest "$@"
```

You could try the following patch, but it breaks other makers that use e.g. `cwd` (that might be fixable though, by changing before already):

```diff
diff --git i/autoload/neomake.vim w/autoload/neomake.vim
index ee698735..8f033940 100644
--- i/autoload/neomake.vim
+++ w/autoload/neomake.vim
@@ -592,7 +592,7 @@ function! s:command_maker_base._get_tempfilename(jobinfo) abort dict
         if empty(bufname)
             let temp_file = tempname() . slash . 'neomaketmp.'.a:jobinfo.ft
         else
-            let orig_file = neomake#utils#fnamemodify(a:jobinfo.bufnr, ':p')
+            let orig_file = neomake#utils#fnamemodify(a:jobinfo.bufnr, ':.')
             if empty(orig_file)
                 let dir = tempname()
                 let filename = fnamemodify(bufname, ':t')
@@ -648,7 +648,7 @@ function! s:command_maker_base._get_fname_for_buffer(jobinfo) abort
         endif
         let used_for = 'unreadable'
     else
-        let bufname = fnamemodify(bufname, ':p')
+        let bufname = fnamemodify(bufname, ':.')
         let used_for = ''
     endif
 ```

**Comment by blueyed** [comment]
https://github.com/neomake/neomake/pull/1980 should fix it.

**Comment by AuditeMarlow** [comment]
I can verify your changes to be working. Thanks a lot!

**Comment by blueyed** [comment]
Great!
Thanks for bringing it up in the first place, and reporting back.
