### ISSUE TITLE
Support for Kotlin (ktlint)

### ISSUE THREAD

**Issue by jlobos** [neomake/neomake#1984]
It is possible to add ktlint (Kotlin linter) https://github.com/shyiko/ktlint

**Comment by blueyed** [comment]
Sure.
A PR would be welcome.

I guess that you only need to figure out its errorformat.  See `:h neomake-faq-errorformat`.

ALE has it, but it does not use errorformat: https://github.com/w0rp/ale/blob/d9e139ae2384b04af05ce9343aa0d0a5bae5449b/ale_linters/kotlin/ktlint.vim#L26-L46

Given the nature of ktlint (no config, no thrills), you might also just want to use its formatter automatically when writing a buffer, if that's your style.. :)
