### ISSUE TITLE
How to show error line number in status line

### ISSUE THREAD

**Issue by clozed2u** [neomake/neomake#199]
I looking for neomake feature that equivalent `SyntasticStatuslineFlag`, that show the error line in status line.

I dig to the document but found no solution.

I also try `set statusline+=\ %#ErrorMsg#%{neomake#statusline#QflistStatus('qf:\ ')}` but got nothing show in statusline.

Here my statusline config

```
set statusline=%{getcwd()}/%f\ %{fugitive#head()}\ %m\ %=\ [%l,%c]\ [%L,%p%%]
set statusline+=\ %#ErrorMsg#%{neomake#statusline#QflistStatus('qf:\ ')}
```

And here my neomake config

```
let g:neomake_place_signs=0
let g:neomake_verbose=2
let g:neomake_echo_current_error=1
let g:neomake_open_list=0
let g:neomake_javascript_enabled_makers=['standard']
let g:neomake_python_enabled_makers=['flake8']
let g:neomake_ruby_enabled_makers=['rubocop']
nnoremap <c-c> :Neomake<cr>
```

![screen shot 2015-10-13 at 04 27 21](https://cloud.githubusercontent.com/assets/935924/10439239/c3c18832-7162-11e5-9484-e56623a01b2e.png)

**Comment by benekastah** [comment]
Since you are seeing the error message in the statusline, then your current line is the one with the error. I'm not 100% sure what `SyntasticStatuslineFlag` does, so I'm shooting in the dark a bit here, but if you want to see errors on other lines you have two reasonable options:

1. Open the loclist (`:lopen`). This will show you all the errors neomake found, along with line and column information.
2. Set `g:neomake_place_signs` to 1 (or remove that line since 1 is the default). This places error and warning signs by each line with an error or warning.

**Comment by FuzzOli87** [comment]
I have a similar situation using JSCS maker. It does not properly show me the count in the airline warning bar. I'm not familiar with Vim's language, how do you count up the errors/warnings? It looks like it looks for "type" in the loclist but my loclist correctly populates with JSCS and JSHINT errors/warnings.

**Comment by blueyed** [comment]
I am closing this issue since it might be fixed already in the meantime.
Please create a new issue with detailed information (using the issue template) in case it is not fixed, referring to this original issue - in case it is relevant and helps.

**Comment by artnez** [comment]
Hello! I had a similar problem the creator of this issue. I simply wanted to display the line number of errors in `statusline` (not the count of errors, but actual line numbers).

I ended up having to write my own solution and figured I'd share it here. My solution probably isn't very portable so you'll need to adapt it to your needs. It's very small and simple though.

First I have a VIM script file called `statusline.vim`:

```vim
if !has('python')
    finish
endif

function! GetStatusline()
    pyfile $HOME/.vim/statusline.py
    return g:new_statusline
endfunction

set statusline+=%#warningmsg#
set statusline+=%{GetStatusline()}
```

That imports a Python file called `statusline.py`:

```python
import vim

statusline = ''

bufnr = vim.eval('bufnr("%")')
loclist = vim.eval('getloclist(0)')
errors = [l for l in loclist if l["lnum"] != "0" and l["bufnr"] == bufnr]

if len(errors) > 0:
    locations = ', '.join(['%s:%s' % (e['lnum'], e['col']) for e in errors])
    label = 'Error' if len(errors) == 1 else 'Errors'
    statusline = ' %d %s (%s)' % (len(errors), label, locations)

vim.command('let g:new_statusline = "%s"' % statusline)
```

The Python file simply reads the current location list and sends it back to the VIM script so it can be appended to `statusline`. You can modify the Python file to include more information. The `errors` array has all the info you need.

Cheers!
