### ISSUE TITLE
flake8 unexpected output with Python 3.7

### ISSUE THREAD

**Issue by petobens** [neomake/neomake#1990]
Hi,

I've recently updated to python3.7. Now when I use flake8 neomake spits the following error message:
```
Neomake: flake8: unexpected output on stderr: /usr/local/lib/python3.7/site-packages/pycodestyle.py:113: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
Neomake: flake8: unexpected output. See :messages for more information.
```
Is there a way to avoid it? Thanks!

**Comment by blueyed** [comment]
Thanks for the report, #1994 should fix it.

**Comment by blueyed** [comment]
btw: pycodestyle 2.4.0 should fix it: https://github.com/PyCQA/pycodestyle/commit/368e62cb6c57ff386b5a08659a5a9d2866b80a2f

**Comment by petobens** [comment]
Thank you!
