### ISSUE TITLE
Lint Errors appearing as Warnings?

### ISSUE THREAD

**Issue by perks** [neomake/neomake#201]
In particular with PEP8, Is there a way to properly differentiate Errors from Warnings? Currently they are being misinterpreted as all warnings for markers. Using something like the following:

```
let g:neomake_error_sign = {
            \ 'text': '❯❯',
            \ 'texthl': 'ErrorMsg',
            \ }
hi MyWarningMsg ctermbg=3 ctermfg=0
let g:neomake_warning_sign = {
            \ 'text': '❯❯',
            \ 'texthl': 'MyWarningMsg',
            \ }
let g:neomake_python_enabled_makers = ['pep8']
```

**Comment by strokirk** [comment]
As well, certain linters will return entry types not recognized by Neomake, such as `C` or `F` from `pylint` and `frosted`. These should not be marked with `neomake_err`, but rather using `neomake_info`.

**Comment by blueyed** [comment]
@perks 
This was improved in general.
Is it still an issue?
Is it about mapping it in a user's config?

@strokirk 
That should have been fixed for the Python linters.

**Comment by blueyed** [comment]
Closing due to missing feedback.
Please re-open in case I've missed something.
