### ISSUE TITLE
g:neomake_remove_invalid_entries option is ignored

### ISSUE THREAD

**Issue by mogelbrod** [neomake/neomake#2039]
## Expected behavior

Adding
```vim
let g:neomake_remove_invalid_entries = 1
```
to my `.vimrc` should tell neomake to omit invalid entries from the quickfix/location list.

## Actual behavior

Invalid entries are included in the list.

Setting `g:neomake_{filetype}_remove_invalid_entries` does however work:
```vim
let g:neomake_javascript_jsx_remove_invalid_entries = 1
```

## Neomake debug information

Async support: 1
Current filetype: javascript.jsx
Windows: 0
[shell, shellcmdflag, shellslash]:['/usr/local/bin/zsh', '-c', 0]

##### Enabled makers

For the current filetype ("javascript.jsx", used with :Neomake):
 - eslint
   - args: ['--format=compact']
   - auto_enabled: 0
   - cwd: '%:p:h'
   - errorformat: '%E%f: line %l\, col %c\, Error - %m,%W%f: line %l\, col %c\, Warning - %m,%-G,%-G%*\d problems%#'
   - exe: 'eslint'
   - output_stream: 'stdout'
   - supports_stdin: function('287')
NOTE: you can define g:neomake_javascript_jsx_enabled_makers to configure it (or b:neomake_javascript_jsx_enabled_makers).

Default maker settings:
 - output_stream: 'both'
 - remove_invalid_entries: 0
 - buffer_output: 1

For the project (used with :Neomake!):
None.
NOTE: you can define g:neomake_enabled_makers to configure it.

###### New-style (dict, overrides old-style)

```
g:neomake: {
  'automake': {
    'ignore_filetypes': ['startify'],
    'events': {
      'BufWritePost': {
        'delay': 0,
      },
    },
  },
}
b:neomake: unset
```

###### Old-style

```
g:neomake_highlight_columns = 0
g:neomake_javascript_enabled_makers = ['eslint']
g:neomake_list_height = 6
g:neomake_open_list = 2
g:neomake_place_signs = 1
g:neomake_remove_invalid_entries = 1
g:neomake_verbose = 2

```
  makeprg=eslint %
	Last set from ~/.vimrc

#### :version

```
VIM - Vi IMproved 8.1 (2018 May 17, compiled Jul  9 2018 11:06:31)
macOS version
Included patches: 1-72
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +cmdline_compl     -ebcdic            -gettext           +localmap          +mouse_urxvt       +printer           -sun_workshop      +toolbar           -X11
+arabic            +cmdline_hist      +emacs_tags        -hangul_input      -lua               +mouse_xterm       +profile           +syntax            +transparency      -xfontset
+autocmd           +cmdline_info      +eval              +iconv             +menu              +multi_byte        +python            +tag_binary        +user_commands     +xim
-autoservername    +comments          +ex_extra          +insert_expand     +mksession         +multi_lang        -python3           +tag_old_static    +vertsplit         -xpm
+balloon_eval      +conceal           +extra_search      +job               +modify_fname      -mzscheme          +quickfix          -tag_any_white     +virtualedit       -xsmp
+balloon_eval_term +cryptv            +farsi             +jumplist          +mouse             +netbeans_intg     +reltime           +tcl               +visual            -xterm_clipboard
+browse            +cscope            +file_in_path      +keymap            +mouseshape        +num64             +rightleft         +termguicolors     +visualextra       -xterm_save
++builtin_terms    +cursorbind        +find_in_path      +lambda            +mouse_dec         +odbeditor         +ruby              +terminal          +viminfo           
+byte_offset       +cursorshape       +float             +langmap           -mouse_gpm         +packages          +scrollbind        +terminfo          +vreplace          
+channel           +dialog_con_gui    +folding           +libcall           -mouse_jsbterm     +path_extra        +signs             +termresponse      +wildignore        
+cindent           +diff              -footer            +linebreak         +mouse_netterm     +perl              +smartindent       +textobjects       +wildmenu          
+clientserver      +digraphs          +fork()            +lispindent        +mouse_sgr         +persistent_undo   +startuptime       +timers            +windows           
+clipboard         +dnd               +fullscreen        +listcmds          -mouse_sysmouse    +postscript        +statusline        +title             +writebackup       
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -F/usr/local/opt/python@2/Frameworks -I/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L.             -L /BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib -L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib -L.             -L /BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib -L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib -F/usr/local/opt/python@2/Frameworks -L/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -framework CoreFoundation -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/usr/local/opt/python@2/Frameworks -framework Python  -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby    
```

#### :messages

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"index.js" 44L, 1209C
```

**Comment by blueyed** [comment]
It is meant to be a maker specific setting, but I've found that it is documented to work like that - so at least that should be fixed.

You can/should use `call neomake#config#set('maker_defaults.remove_invalid_entries', 1)`.

**Comment by mogelbrod** [comment]
Thanks for the quick reply and fix!

`eslint` appends a context _codeframe_ for every warning/error (in my environment at least) which I can't seem to disable (there's [no option for it](https://eslint.org/docs/user-guide/command-line-interface#options)):
```
$ eslint -f compact test.js
.../test.js: line 1, col 9, Error - Parsing error: Unexpected token

> 1 | function()
    |         ^
  2 |

1 problem
```

The codeframe is redundant since I'm already editing the file. It would be reasonable to set `remove_invalid_entries` for eslint by default if non-verbose output is desired by default.

**Comment by blueyed** [comment]
I would rather look into improving the errorformat, so that this gets filtered out there.

I think I have something stashed in this regard already.

**Comment by mogelbrod** [comment]
I'm getting the following errors when triggering neomake by saving a javascript file now:
```
"test.js" 1L, 11C written
Error detected while processing function <SNR>24_neomake_automake[66]..<SNR>24_neomake_do_automake[44]..neomake#Make[2]..<SNR>137_Make[128]..<SNR>137_handle_next_job[43]..<SNR>137_MakeJob:
line   31:
E716: Key not present in Dictionary: buffer_output, }, 'keep')
E116: Invalid arguments for function extend
Error detected while processing function <SNR>24_neomake_automake[66]..<SNR>24_neomake_do_automake[44]..neomake#Make[2]..<SNR>137_Make:
line  128:
E170: Missing :endwhile
Error detected while processing function <SNR>24_neomake_automake[66]..<SNR>24_neomake_do_automake[44]..neomake#Make:
line    2:
E171: Missing :endif
```

These errors are only thrown when the following line is present in .vimrc:
```vim
call neomake#config#set('maker_defaults.remove_invalid_entries', 1)
```

**Comment by mogelbrod** [comment]
`eslint -f unix` instead of the current `compact` should work with the default vim errorformat AFAIK

**Comment by blueyed** [comment]
> eslint -f unix instead of the current compact should work with the default vim errorformat AFAIK

What is your eslint version?
I do not get the code frame with v5.2.0, and `test.js` containing `function()` only.
But I have seen this before myself, and thought it was something special with parse errors.

Does using `-f unix` instead of `-f compact` removes the code frame for you?

**Comment by mogelbrod** [comment]
`neomake#config#set('maker_defaults', {...})` works for now 👍

I just discovered that the forced inclusion of the codeframe was added by a eslint plugin which the project uses - my bad! Removing the `.eslintrc` also removed the codeframe, and thus the need to remove invalid entries.

I still recommend switching to the eslint unix formatter to avoid having to define a custom `efm` string 👍 

```
$ eslint test.js -f unix
.../test.js:1:9: Parsing error: Unexpected token ( [Error]

1 problem

$ eslint test.js -f compact
.../test.js: line 1, col 9, Error - Parsing error: Unexpected token (

1 problem
```

**Comment by blueyed** [comment]
> I still recommend switching to the eslint unix formatter to avoid having to define a custom efm string

What do you mean?  We have to define the `efm` anyway.
Or do you mean that `-f unix` does not include the code frame, when babel-eslint is used?

**Comment by mogelbrod** [comment]
Ah, I mistakenly assumed that `neomake` could use the vim default errorformats as fallback, nevermind then!

babel-eslint includes the codeframe no matter which formatter is used, I had to add `parserOptions.codeFrame = false` to `.eslintrc` for it to stop.

I consider this issue solved now, thanks for the quick responses!

**Comment by blueyed** [comment]
I see.

> babel-eslint includes the codeframe no matter which formatter is used, I had to add parserOptions.codeFrame = false to .eslintrc for it to stop.

Could this be passed in as default arguments to eslint?
OTOH it is good enough if you can configure it yourself (potentially also by changing the `args` for the maker yourself) - someone might actually find it useful?!

**Comment by blueyed** [comment]
`maker_defaults` should be handled better now (https://github.com/neomake/neomake/pull/2042).

**Comment by blueyed** [comment]
..but I would argue that using `g:neomake_eslint_remove_invalid_entries` makes more sense in general (if you had babel still enabled), since it is specific to this maker then.
