### ISSUE TITLE
What happened to commit d925fc4?

### ISSUE THREAD

**Issue by lilydjwg** [neomake/neomake#2055]
I'm updating my Vim config, and this fails to merge. There are many files resulting in "both modified" state and other conflicting states when git tries to merge.

I notice that the last commit upstream, i.e. d925fc4, has disappeared. Instead, a commit f26a31a with the same message exists. The latest commit I have in common is 5e4a02e1dbe59eff23dd9e7459fbfa21bb6cd2bd, which dates back to one year ago. Have you rebased master? If so, could you avoid that in the future? It confuses git when merging.

This has happened several times before, significantly complicating my progress to update this plugin.

My local changes to this is simple: to un-ignore doc/tags and add my generated one in repo. I want doc/tags in repo so that I won't need to generate them every time I update where I have my instance of Vim configuration.

**Comment by blueyed** [comment]
As you can see Github does not link to d925fc4 - which appears to indicate that this commit never was in this repo.

What does `git show d925fc4` give you?  And `git show d925fc4~1`?

I am not force-pushing to master, so I guess it's rather related to how you handle it locally yourself.

Not sure if your handling of `doc/tags` is worth the extra effort - do you do this will all plugins?
Normally plugin managers provide an easy way to regenerate them altogether.

I am closing this issue for now, but I am willing to help you figure out what happens there.

**Comment by lilydjwg** [comment]
> which appears to indicate that this commit never was in this repo.

GitHub will forget about unreachable objects eventually.

They are in my local repo. I'm managing my plugins with [git-subrepo](https://github.com/ingydotnet/git-subrepo). I'd like to keep my repo small (to reduce cloning time, especially in mainland China) and not depend on external sources (because they may move or become unreachable, e.g. without normal Internet access).

```
>>> git cat-file -p d925fc4
tree 676aabf00ad316dbc02e6b66549200c71904ee80
parent 6f85caabe7e91eff286b6c764805e9eaa0d6c7ef
author Daniel Hahler <github@thequod.de> 1531724075 +0200
committer GitHub <noreply@github.com> 1531724075 +0200

Minor internal improvements (#2008)

>>> git cat-file -p f26a31a
tree 676aabf00ad316dbc02e6b66549200c71904ee80
parent c93e0ded219fb0959f9cdeba783259a275a96a69
author Daniel Hahler <github@thequod.de> 1531724075 +0200
committer GitHub <noreply@github.com> 1531724075 +0200
gpgsig -----BEGIN PGP SIGNATURE-----
 
 wsBcBAABCAAQBQJbTEErCRBK7hj4Ov3rIwAAdHIIAHPPJaiMiRTDH6UHR4WfBCL2
 eUU8hZXNpPAhCdrzEkhPh5qRQfDEMWdr1Ec5pOpJG4dfjL8IMhpa8w9L6v9Qg8Th
 qLeGZo/yvdyj+kw0G5diCLtZVUAc+w+qI7AbVBdZIC+Hm+VtFRZPdkb1Q4zh/VKh
 fA4M+wVD1u8ovsc3q5jnV2dXYb2Csi7zGnSDp3Z0V0qxCjwwC4ikyb/Li/+iC8C7
 4sbqp67DEvCrxaUPTGiHMkUMieDU6v6+HplZ6wjyZIYkKpmGBdmL1ywB66ut6DT0
 7CiklMwAymxacLwq/sY5yaLGaKuSyWVYj521xltgC1AYVskMVNRNHKPks6MmMSo=
 =+Ag9
 -----END PGP SIGNATURE-----
 

Minor internal improvements (#2008)
```

It's commited by github but without a signature. This seems to be a bug (or a limitation) with git-subrepo. I'll test and bother it later.

> do you do this will all plugins?

Yes.
