### ISSUE TITLE
Add python maker: pylava

### ISSUE THREAD

**Issue by decentral1se** [neomake/neomake#2068]
Is anyone against me adding a https://github.com/pyfocus/pylava maker?

It's a fork of pylama which has support for python 3.7.

Not sure what will happen with that project but I'm starting to use pylava now ...

**Comment by blueyed** [comment]
Thanks for considering it, but what about just using `call neomake#config#set('ft.python.pylama.exe', 'pylava')` for now? (or just "pylama.exe" as the key)

**Comment by blueyed** [comment]
With https://github.com/neomake/neomake/commit/b834e3681c3c443134d39b8ba919d6ca2e151df2 you should get notified about errors with pylama due to py37 incompatibility now, too.

**Comment by lwm** [comment]
Oh lovely, that will do! :fire: :fire: :fire: 

You can close this if you want!

**Comment by blueyed** [comment]
Let's keep it open for now.
I see that pylama might be unmaintained, and should get replaced by pylava eventually.
Related: https://github.com/neomake/neomake/issues/1702

**Comment by tjcim** [comment]
@blueyed - Can you clear something up, you mention this:

> but what about just using `call neomake#config#set('ft.python.pylama.exe', 'pylava')`

But I am unsure where that would go...?

I am using nvim and run neomake on write with the default makers (for python). Would that line go in the init.vim?

**Comment by blueyed** [comment]
@tjcim 
You can first try it as a command, and then add it to init.vim, yes.

**Comment by tjcim** [comment]
@blueyed - thank you. That worked out great.
