### ISSUE TITLE
Wrong error locations are sometimes displayed for Rust

### ISSUE THREAD

**Issue by dpc** [neomake/neomake#2075]
### Expected behavior

Rust compiler has this weird behavior of displaying both caller and called function locations. Unfortunately most error checkers  (neomake) included, get confused and display only one, and what worse "the wrong location" . More information can be found here:

https://github.com/rust-lang/rust.vim/issues/174

### Steps to reproduce

Please see.

https://github.com/rust-lang/rust.vim/issues/174

**Comment by blueyed** [comment]
Assuming this is fixed/addressed by #2076.

There is more improvement in https://github.com/neomake/neomake/pull/2143 - maybe you can help there?
