### ISSUE TITLE
Hadolint is broken (/dev/stdin not available in Neovim)

### ISSUE THREAD

**Issue by danihodovic** [neomake/neomake#2108]
### Expected behavior
Hadolint should run, but fails and does not display lint info.
```
$ hadolint --version
Haskell Dockerfile Linter v1.13.0-0-gf355fc0
```

### Steps to reproduce
Call `:Neomake`.

#### Neomake debug information

Async support: 1
Current filetype: dockerfile
Windows: 0
[shell, shellcmdflag, shellslash]:['/bin/sh', '-c', 0]

##### Enabled makers

For the current filetype ("dockerfile", used with :Neomake):
 - hadolint
   - args: ['--format', 'tty']
   - auto_enabled: 1
   - errorformat: '%f:%l %m'
   - exe: 'hadolint'
   - output_stream: 'stdout'
   - uses_stdin: 1
   - version information (/home/dani/.local/bin/hadolint --version): Haskell Dockerfile Linter v1.13.0-0-gf355fc0
NOTE: you can define g:neomake_dockerfile_enabled_makers to configure it (or b:neomake_dockerfile_enabled_makers).

For the project (used with :Neomake!):
 - makeprg
   - append_file: 0
   - args: []
   - auto_enabled: 1
   - errorformat: '%*[^"]"%f"%*\D%l: %m,"%f"%*\D%l: %m,%-G%f:%l: (Each undeclared identifier is reported only once,%-G%f:%l: for each function it appears in.),%-GIn file included from %f:%l:%c:,%-GIn file included from %f:%l:%c\,,%-GIn file included from %f:%l:%c,%-GIn file included from %f:%l,%-G%*[ ]from %f:%l:%c,%-G%*[ ]from %f:%l:,%-G%*[ ]from %f:%l\,,%-G%*[ ]from %f:%l,%f:%l:%c:%m,%f(%l):%m,%f:%l:%m,"%f"\, line %l%*\D%c%*[^ ] %m,%D%*\a[%*\d]: Entering directory %*[`'']%f'',%X%*\a[%*\d]: Leaving directory %*[`'']%f'',%D%*\a: Entering directory %*[`'']%f'',%X%*\a: Leaving directory %*[`'']%f'',%DMaking %*\a in %f,%f|%l| %m'
   - exe: 'make'
   - version information (/usr/bin/make --version): GNU Make 4.1
     Built for x86_64-pc-linux-gnu
     Copyright (C) 1988-2014 Free Software Foundation, Inc.
     License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
     This is free software: you are free to change and redistribute it.
     There is NO WARRANTY, to the extent permitted by law.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - output_stream: 'both'
 - remove_invalid_entries: 0
 - buffer_output: 1

###### New-style (dict, overrides old-style)

```
g:neomake: unset
b:neomake: unset
```

###### Old-style

```
g:neomake_javascript_enabled_makers = ['eslint']
g:neomake_javascript_eslint_exe = '/home/dani/repos/dockerfiles/samson-docker-ansible/node_modules/.bin/eslint'
g:neomake_list_height = 8
g:neomake_logfile = '/tmp/neomake.log'
g:neomake_open_list = 2
g:neomake_place_signs = 1
g:neomake_python_python_exe = 'python3'
g:neomake_terraform_enabled_makers = ['terraform_validate', 'tflint']
g:neomake_typescript_enabled_makers = ['tslint', 'tsc']
g:neomake_typescript_tslint_maker = {'errorformat': '%EERROR: %f[%l\, %c]: %m,%E%f[%l\, %c]: %m', 'args': ['--project', 'tsconfig.json'], 'append_file': 0}

```
  makeprg=make

#### :version

```
NVIM v0.3.2-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-1vOYWK/neovim-0.3.0~ubuntu1+git201809272035-64a8a8f-479a1d0=. -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-1vOYWK/neovim-0.3.0~ubuntu1+git201809272035-64a8a8f-479a1d0/build/config -I/build/neovim-1vOYWK/neovim-0.3.0~ubuntu1+git201809272035-64a8a8f-479a1d0/src -I/build/neovim-1vOYWK/neovim-0.3.0~ubuntu1+git201809272035-64a8a8f-479a1d0/.deps/usr/include -I/usr/include -I/build/neovim-1vOYWK/neovim-0.3.0~ubuntu1+git201809272035-64a8a8f-479a1d0/build/src/nvim/auto -I/build/neovim-1vOYWK/neovim-0.3.0~ubuntu1+git201809272035-64a8a8f-479a1d0/build/include
Compiled by buildd@lgw01-amd64-018

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

#### :messages

```
Neomake: hadolint: unexpected output on stderr: hadolint: /dev/stdin: openBinaryFile: does not exist (No such device or address)
Neomake: hadolint: unexpected output. See :messages for more information.
```

### Logfile contents:
```
06:25:21 [D      ] [1.-:1:1] Running makers: hadolint (auto).
06:25:21 [D      ] Defining sign: sign define neomake_file_err texthl=NeomakeErrorSign text=✖.
06:25:21 [D      ] Defining sign: sign define neomake_project_err texthl=NeomakeErrorSign text=✖.
06:25:21 [D      ] Defining sign: sign define neomake_file_warn texthl=NeomakeWarningSign text=⚠.
06:25:21 [D      ] Defining sign: sign define neomake_project_warn texthl=NeomakeWarningSign text=⚠.
06:25:21 [D      ] Defining sign: sign define neomake_file_info texthl=NeomakeInfoSign text=ℹ.
06:25:21 [D      ] Defining sign: sign define neomake_project_info texthl=NeomakeInfoSign text=ℹ.
06:25:21 [D      ] Defining sign: sign define neomake_file_msg texthl=NeomakeMessageSign text=➤.
06:25:21 [D      ] Defining sign: sign define neomake_project_msg texthl=NeomakeMessageSign text=➤.
06:25:21 [D      ] [1.1:1:1] Using uses_stdin (1) from setting.
06:25:21 [D      ] [1.1:1:1] Setting neomake_automake_tick.
06:25:21 [V      ] [1.1:1:1] Starting async job: hadolint --format tty -.
06:25:21 [D      ] [1.1:1:1] cwd: /home/dani/repos/dockerfiles.
06:25:22 [D +0.32] [1.1:1:1] stdout: hadolint: [''].
06:25:22 [D      ] [1.1:1:1] stderr: hadolint: ['hadolint: /dev/stdin: openBinaryFile: does not exist (No such device or address)', ''].
06:25:22 [D      ] [1.1:1:1] exit: hadolint: 1.
06:25:22 [D      ] [1.1:1:1] hadolint: completed with exit code 1.
06:25:22 [D      ] [1.1:1:1] hadolint: unexpected output on stderr: hadolint: /dev/stdin: openBinaryFile: does not exist (No such device or address).
06:25:22 [E      ] [1.1:1:1] hadolint: unexpected output. See :messages for more information.
06:25:22 [D      ] [1.1:1:1] Cleaning jobinfo.
06:25:22 [D      ] [1.-:1:1] File-level errors cleaned.
06:25:22 [D      ] [-.-:-:1] Handling location list: executing lclose.
06:25:22 [D      ] [1.-:-:1] Cleaning location list.
06:25:22 [D      ] [1.-:1:1] Cleaning make info.
```

**Comment by blueyed** [comment]
How did you install hadolint?

I am using this wrapper script:

```sh
exec /usr/bin/docker run --rm -i hadolint/hadolint hadolint "${@:--}"
```

```
06:25:21 [V      ] [1.1:1:1] Starting async job: hadolint --format tty -.
06:25:21 [D      ] [1.1:1:1] cwd: /home/dani/repos/dockerfiles.
06:25:22 [D +0.32] [1.1:1:1] stdout: hadolint: [''].
06:25:22 [D      ] [1.1:1:1] stderr: hadolint: ['hadolint: /dev/stdin: openBinaryFile: does not exist (No such device or address)', ''].
06:25:22 [D      ] [1.1:1:1] exit: hadolint: 1.
06:25:22 [D      ] [1.1:1:1] hadolint: completed with exit code 1.
06:25:22 [D      ] [1.1:1:1] hadolint: unexpected output on stderr: hadolint: /dev/stdin: openBinaryFile: does not exist (No such device or address).
06:25:22 [E      ] [1.1:1:1] hadolint: unexpected output. See :messages for more information.
```

**Comment by danihodovic** [comment]
I'm downloading the binary from their releases page.

**Comment by blueyed** [comment]
Appears to work for me:

```sh
% cat Dockerfile | ~d/hadolint-Linux-x86_64 --format tty -
/dev/stdin:2 DL4000 MAINTAINER is deprecated
…
```

You get:

> /dev/stdin: openBinaryFile: does not exist (No such device or address)

Do you have `/dev/stdin`?

**Comment by danihodovic** [comment]
Yes.
```
$ file /dev/stdin
/dev/stdin: symbolic link to /proc/self/fd/0
```

It works in the terminal, but not in neovim. 

```
$ cat Dockerfile | hadolint --format tty -
/dev/stdin:3 DL3018 Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>`
/dev/stdin:3 DL3019 Use the `--no-cache` switch to avoid the need to use `--update` and remove `/var/cache/apk/*` when done installing packages
/dev/stdin:13 DL3013 Pin versions in pip. Instead of `pip install <package>` use `pip install <package>==<version>`
```

```
Neomake: hadolint: unexpected output on stderr: hadolint: /dev/stdin: openBinaryFile: does not exist (No such device or address)
Neomake: hadolint: unexpected output. See :messages for more information.
```

**Comment by blueyed** [comment]
`/dev/stdin` is only available with `pty=1` in Neovim, but that has several drawbacks (https://github.com/neovim/neovim/issues/9107)

As a workaround for you: `:let g:neomake_dockerfile_hadolint_uses_stdin = 0` (might require to pull latest fixes when you're using the newer config system already)).

I could imagine shipping the wrapper script I am using in `contrib`, and use it when no `hadolint` binary exists.
If `hadolint` is found it would not use `uses_stdin` then in Neovim (Vim is fine in this regard).

I have also created https://github.com/hadolint/hadolint/issues/273 to ask for a fix in hadolint itself - it could probably use the stdin fd instead of the pseudo file.

What do you think?

**Comment by danihodovic** [comment]
> What do you think?

I think you are one of the best open source maintainers.

```
:let g:neomake_dockerfile_hadolint_uses_stdin = 0
```
Works.

> I could imagine shipping the wrapper script I am using in contrib, and use it when no hadolint binary exists.
If hadolint is found it would not use uses_stdin then in Neovim (Vim is fine in this regard).


> I have also created hadolint/hadolint#273 to ask for a fix in hadolint itself - it could probably use the stdin fd instead of the pseudo file.

:+1: Does it conflict with the changes mention above regarding a contrib script?

:+1:

**Comment by blueyed** [comment]
> I think you are one of the best open source maintainers.

Thank you! :heart: 

> Does it conflict with the changes mention above regarding a contrib script?

With the fix in hadolint we would not really need any special handling then.
I am going to wait a bit on feedback from them, and hopefully this solves it then.

I'll keep this issue open to track the progress on this.  Thanks for reporting and your help!

**Comment by blueyed** [comment]
hadolint 1.14.0 should fix this (currently being released).
