### ISSUE TITLE
NeomakeSh!, errorformat and autoscroll

### ISSUE THREAD

**Issue by sirex** [neomake/neomake#2114]
### Expected behavior

When I run:

    :execute 'NeomakeSh! ' . &makeprg

When command is done I expect, that my `errorformat` will work as it does with `:Neomake!`, but it does. Also, while command is running it would be nice if it would automatically scroll when more output is produced.

### Steps to reproduce

1. Set `errorformat`:

        set errorformat=\ %#File\ \"%f\"\\,\ line\ %l%m
        set errorformat+=\@File\:\ %f
2. Set `makeprg`:

        set makeprg=env/bin/py.test\ -vvx\ --tb=native\ tests.py

3. Create `tests.py` file:

        def test_me():
            assert False

4. Set up environment:

        :term python -m venv env && env/bin/pip install pytest
5. Run `:Neomake!` and quickfix window should interpret output correctly according to `errorformat`.

6. Run `:execute 'NeomakeSh! ' . &makeprg`, and the output in quickfix window does not highligh lines.

**Comment by sirex** [comment]
Not sure, but this might be related: https://github.com/neomake/neomake/issues/1138

**Comment by blueyed** [comment]
The main problem is that the errorformat gets set to `%m` unconditionally with `NeomakeSh`: https://github.com/neomake/neomake/blob/97163ec310240bcfd39af6907eed17ae024e095c/autoload/neomake.vim#L2625
It is meant to run a shell command, and therefore everything should be displayed.
So in your case, for running &makeprg, `Neomake!` appears to be what you want, no?

> Also, while command is running it would be nice if it would automatically scroll when more output is produced.

Nice idea.. I've looked a bit into this (using `:NeomakeSh! i=0; while true; do i=$((++i)); echo $i; sleep 1; done`) and a minimal vimrc:
```vim
set runtimepath+=$PWD
let g:neomake_logfile = '/tmp/neomake.log'
let g:neomake_open_list = 2
```

It opens the quickfix list, and grows it until 10 lines.  For this feature it would basically have to do `:normal! G` after the `:cwindow` always.

btw: consider using https://github.com/janko-m/vim-test to run pytest.
And see also https://github.com/5long/pytest-vim-compiler (which I have local changes in case you're interested in this).

**Comment by sirex** [comment]
>  So in your case, for running &makeprg, Neomake! appears to be what you want, no?

`Neomake!` runs command in background and displays the output only, when command is done. While command is running there is no indication what is going on, and no output. In that regard I like `NeomakeSh` more, because it displays output instantly.

> btw: consider using https://github.com/janko-m/vim-test to run pytest.

Thanks, I will look into it.

**Comment by blueyed** [comment]
> I like NeomakeSh more, because it displays output instantly.

I assume that's because of `buffer_output`.
Try `:let g:neomake_makeprg_buffer_output = 0`.

**Comment by sirex** [comment]
> I assume that's because of `buffer_output`.
> Try `:let g:neomake_makeprg_buffer_output = 0`.
> Tested with `:let &makeprg = 'i=0; while true; do i=$((++i)); echo $i; sleep 1; done'` and then `:Neomake!`.

Thanks, that works! And solves my issue, because there is no need to use `NeomakeSh`. Not sure why output buffering is on by default.

**Comment by blueyed** [comment]
> Not sure why output buffering is on by default.

It is meant to provide better performance, and with Neovim gets turned into a job option even (so handlers are not invoked all the time).

I think it would be good if it would automatically get unbuffered if it takes longer than 0.5s for example, but that does not work if it is a job option already then.

docs: https://github.com/neomake/neomake/blob/617e1524c6e1b2e5029d948e330a6f8c9a2a4ae7/doc/neomake.txt#L364-L381

That being said, it might be better to change the default indeed, and maybe only for project/quickfix mode (where it is expected to take longer anyway)?!
