### ISSUE TITLE
feature request: highlight error line/column, not just gutter

### ISSUE THREAD

**Issue by jaredly** [neomake/neomake#212]
maybe there's a setting for this already? It would be super helpful.

Thanks for an awesome plugin!

**Comment by SimpleX91** [comment]
I'm interested too.

**Comment by erf** [comment]
+1 i find the gutter indentation annoying. would rather highlight line with a color like [wookiehangover/jshint.vim](https://github.com/wookiehangover/jshint.vim)

**Comment by camagu** [comment]
+1

**Comment by ahmedelgabri** [comment]
Yeah this will be great, this is the only thing I miss from [Syntastic](https://github.com/scrooloose/syntastic/blob/b10c59b21492776cb4bd5e9802cae3a766c6b1ab/doc/syntastic.txt#L182-L186)

**Comment by sebenik** [comment]
Yep, this would be really great.

**Comment by yarray** [comment]
+1

**Comment by mikeys** [comment]
Any news about the attached PR? this is really useful.

**Comment by blueyed** [comment]
@mikeys 
Have you tested the PR?

Or anybody else?
Please provide feedback there, and then we can get it merged.

**Comment by mhartington** [comment]
Hmm, curious, is the purpose of the PR and this issue to add a feature like this? 

![](https://raw.githubusercontent.com/jordwalke/VimBox/master/dotVim/images/VimJSXHint.png)

Where errors could be unlined or at least be part of highlight group for themes to target?

**Comment by jaredly** [comment]
that would be great!

**Comment by mikekreeki** [comment]
That would actually be the best thing ever to improve my development workflow 👍

**Comment by blueyed** [comment]
Please see https://github.com/neomake/neomake/pull/361: you could test it already and help out there, although it seems to be waiting for an update by @paretje currently.
And please refrain from +1 comments.

**Comment by blueyed** [comment]
#361 is merged since a while.. 🎆
