### ISSUE TITLE
Run shell command on save

### ISSUE THREAD

**Issue by thezealousfool** [neomake/neomake#2147]
I want to specify a shell command for only the current file such that every time neomake runs in context of the current file, that shell command is executed. I know I can run shell commands with NeomakeSh but can I do something that it is run everytime Neomake is run on the current file? (in my case automatically run every time I save the file)

Scenario:
I am making a presentation in markdown and using pandoc to convert it to a beamer presentation (current filename: slides.md)
Every time I save the file, I want to run the command ```pandoc -t beamer slides.md -o slides.pdf```

PS: I love Neomake. Great job!

Thank You

**Comment by blueyed** [comment]
You could just do this manually:

```vim
augroup my_pandoc_on_save
    autocmd BufWritePost **/slides.md exe '!pandoc -t beamer '.fnameescape(fnamemodify(expand('<amatch>'), ':.')).' -o '.fnameescape(fnamemodify(expand('<amatch>'), ':.:r').'.pdf')
augroup END
```

With Neomake there is a user autocommand triggered when jobs have finished, so you could use that to do it only when all checks were successful:
```vim
    function! MyPandocOnSave()
      " echom string(g:neomake_hook_context)
      let context = g:neomake_hook_context

      if !context.options.file_mode
        return
      endif

      let bufname = bufname(context.options.bufnr)
      if fnamemodify(bufname, ':t') !=# 'slides.md'
        return
      endif

      let finished_jobs = context.finished_jobs
      for job in finished_jobs
        if job.exit_code != 0
          return
        endif
      endfor
      exe '!pandoc -t beamer '.fnameescape(fnamemodify(bufname, ':.')).' -o '.fnameescape(fnamemodify(bufname, ':.:r').'.pdf')
    endfunction
    autocmd User NeomakeFinished call MyPandocOnSave()
```

(use `echo`/`echom` instead of `exe` for debugging)

**Comment by blueyed** [comment]
Closing, since I believe it is answered/solved - but feel free to comment, of course.
