### ISSUE TITLE
Still getting "No matching autocommands" messages

### ISSUE THREAD

**Issue by bluz71** [neomake/neomake#2148]
Hello Neomake,

Just updated to the latest version (#4cf9ee0) and I immediately notice that invoking `Neomake` will produce a warning about *No matching autocommands*.

This appears to have started with this [17a5f1b commit](https://github.com/neomake/neomake/commit/17a5f1b6c358a5022b2371512675186003ae78d5).

The commit [f5ea872](https://github.com/neomake/neomake/pull/2129) does not work for me, even though from the description it should.

Do I need to do something else to make this warning not appear? A Vim/Neovim setting?

This happens with both eslint (JavaScript) and mdlint (Markdown). So I don't think the makers are the issue.

Thanks for a great plugin.

**Comment by blueyed** [comment]
Thanks for the report.
How do you configure Neomake, and when do the warnings appear?

(You might want to try https://github.com/neomake/neomake/pull/2139 also)

**Comment by bluz71** [comment]
@blueyed,

More details. This appears to be a plugin interaction issue; may not be the fault of Neomake, but it only starting manifesting after updating to Neomake commit #17a5f1b and beyond.

The minimal list of plugins that generate the issue is:

```viml
Plug 'pbogut/fzf-mru.vim'
Plug 'tpope/vim-projectionist'
Plug 'neomake/neomake'
  let g:neomake_open_list = 1
```

The issue manifests upon `:Neomake` with the warning message _No matching autocommands_ below the status line. Neomake works correctly, it is just that the warning message is distracting.

I tested #2139 as requested, no difference.

The maker makes no difference, so you should be able to choose whichever you like (I was using mdlint and eslint). But, the source being tested **must** have at least one lint warning/error. If Neomake finds no warning/errors then the _No matching autocommands_ is not emitted.

Many thanks.

**Comment by blueyed** [comment]
Thanks for the additional info.
Have you ensured that commenting the code in Neomake fixes it?  https://github.com/neomake/neomake/pull/2129/files#diff-1ceaba5126b0cf477e72f87cb2767af0R1236

**Comment by blueyed** [comment]
https://github.com/neomake/neomake/pull/2149 might help.

If it still happens there, please put `echo neomake#utils#redir('au QuickfixCmdPost')` before the check/`doautocmd` - but also make sure that it comes from Neomake really.

**Comment by blueyed** [comment]
Also please post your Vim/Neovim version information.

**Comment by blueyed** [comment]
Ok, could reproduce it with fzf-mru.
Related to https://github.com/pbogut/fzf-mru.vim/blob/2b934fef2ef997c8ce80e7cd9351e542610564dd/autoload/fzf_mru/mrufiles.vim#L149.

**Comment by bluz71** [comment]
@blueyed,

Just tested the update and all is well, issue is indeed fixed.

Many thanks, much appreciate your help in fixing this.
