### ISSUE TITLE
Installing neomake globally without a plugin manager

### ISSUE THREAD

**Issue by cancercufasole** [neomake/neomake#2150]
How would I go about installing neomake manually globally ?
I am making a custom neovim package for myself and I want to include this by default.

**Comment by blueyed** [comment]
Like any other Vim plugin I suppose?!

See e.g. https://www.archlinux.org/packages/community/any/vim-jedi/ (check the Package Contents section).

**Comment by cancercufasole** [comment]
What I'm really looking for is what files Neomake actually needs and where in the neovim install do I put them ? At some point I tried git clone --depth 1 in /usr/share/nvim and neovim didn't recognise Neomake.

Here's the PKGBUILD
http://ix.io/1uHN

**Comment by blueyed** [comment]
I would base it on what https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/vim-jedi does (but that's just one random vim-plugin package I found).
I would guess `autoload`, `contrib`, `doc`, `plugin`, and `syntax` should be installed to the appropriate dir (`/usr/share/nvim/runtime/` in your case, but jedi-vim uses `/usr/share/vim/vimfiles`).
