### ISSUE TITLE
Feature Request: VirtualText

### ISSUE THREAD

**Issue by weilbith** [neomake/neomake#2151]
_NeoVim_ has added `nvim_buf_set_virtual_text()` as recent feature ([#8180](https://github.com/neovim/neovim/pull/8180)). It could be used to show the linter's warning/error messages within the buffer when moving the cursor to their location without touching the content of the buffer itself. This feels really handy, cause have to look to the commandline at the bottom can suck a bit. Nevertheless this feature looks nice and support a good workflow.
[Ale](https://github.com/w0rp/ale) has also already integrated this feature. But since I would prefer to stick with _NeoMake_, I to ask for this feature here.

**Comment by blueyed** [comment]
ALE appears to do this for the current item at the cursor only (from skimming the code).

I think it could be useful for all errors in general for example?

Here is a prototype (based on https://github.com/neomake/neomake/pull/2139 - `list` branch):

`autoload/neomake/annotation.vim`:
```vim
scriptencoding utf8

let s:highlight_types = {
    \ 'E': 'NeomakeAnnotationError',
    \ 'W': 'NeomakeAnnotationWarning',
    \ 'I': 'NeomakeAnnotationInfo',
    \ 'M': 'NeomakeAnnotationMessage'
    \ }

function! neomake#annotation#show(...) abort
    let list = neomake#list#get()
    if empty(list)
        echom 'Neomake: no annotations to show (no list)'
        return
    endif

    let filter = a:0 ? a:1 : ''
    if empty(filter)
        let entries = list.entries
    else
        let entries = map(copy(list.entries), filter)
    endif

    if empty(entries)
        echom 'Neomake: no annotations to show (no errors)'
        return
    endif

    for entry in entries
        let buf_info = getbufvar(entry.bufnr, '_neomake_info', {})
        let src_id = get(buf_info, 'virtual_text_src_id', 0)

        let hi = get(s:highlight_types, toupper(entry.type), 'NeomakeAnnotationMessage')

        let prefix = get(g:, 'neomake_annotation_prefix', '❯ ')
        let text = prefix . entry.text
        let used_src_id = nvim_buf_set_virtual_text(entry.bufnr, src_id, entry.lnum-1, [[text, hi]], {})

        if src_id ==# 0
            let buf_info.virtual_text_src_id = used_src_id
            call setbufvar(entry.bufnr, '_neomake_info', buf_info)
        endif
    endfor
endfunction

function! neomake#annotation#show_errors() abort
    call neomake#annotation#show('v:val ==? "e"')
endfunction

function! neomake#annotation#hide() abort
    let bufnr = bufnr('%')
    let buf_info = getbufvar(bufnr, '_neomake_info', {})
    let src_id = get(buf_info, 'virtual_text_src_id', 0)
    if src_id !=# 0
        call nvim_buf_clear_highlight(bufnr, src_id, 0, -1)
    endif
endfunction

function! neomake#annotation#DefineHighlights() abort
    for [group, link] in items({
                \ 'NeomakeAnnotationError': 'NeomakeError',
                \ 'NeomakeAnnotationWarning': 'NeomakeWarning',
                \ 'NeomakeAnnotationInfo': 'NeomakeWarning',
                \ 'NeomakeAnnotationMessage': 'NeomakeWarning'
                \ })
        if !neomake#utils#highlight_is_defined(group)
            exe 'highlight link '.group.' '.link
        endif
    endfor
endfunction

call neomake#annotation#DefineHighlights()

" vim: ts=4 sw=4 et
```

**Comment by blueyed** [comment]
TODO:

- [ ] should be named virtualtext though really
- [ ] functionality to do this only for the current error, and the do this on cursor events?

**Comment by weilbith** [comment]
@blueyed I would prefer to have this configurable. For myself I would like to jump to the errors by the location/quickfix list and then see the message. But I can image that some other people like to see all at ones.

Moreover I'm thinking about wrapping. I quick test shows that if the message does not fit behind the text withing the windows width, just the beginning is shown. And there seem to exist no options to scroll left, since the virtual text is not part of the buffer and the cursor move to the next line.
For short lines the messages could fit. But for longer lines and longer messages I doesn't help and make it even worse. Not sure how to solve this issue. Any suggestions?

**Comment by weilbith** [comment]
Maybe we can make the used highlight group configurable as well, since the signs etc can be adjusted by the user in _NeoMake_ as well.

**Comment by blueyed** [comment]
@weilbith 
Yeah, the whole point is that it won't wrap..
I've added this to the "list" branch now, and it is enabled by default together with the showing of the current error at the bottom - works really well already, i.e. when vint complains a missing endif etc, and you see it right next to the current line already.
Give it a try.. :)

**Comment by weilbith** [comment]
I'm running into the following error:
```vim
Error detected while processing function <SNR>206_nvim_exit_handler_buffered[14]..<SNR>206_exit_handler[28]..<SNR>206_RegisterJobOutput[26]..<SNR>206_process_pending_output[3]..<SNR>206_ProcessPendingOutp
ut:
line   23:
E745: Using a List as a Number
```

**Comment by weilbith** [comment]
@blueyed I asked for the wrapped problem at the _NeoVim_ project [here](https://github.com/neovim/neovim/pull/8180#issuecomment-442411683). So feel free to follow for getting updates, although I will mention important results here.

**Comment by blueyed** [comment]
@weilbith 
The error should not really be related.  Please comment on the "list" branch/PR then.
For reference, the code is https://github.com/neomake/neomake/blob/07eee9ba7e6fad1e79bd6044d076d72f97dfae28/autoload/neomake.vim#L1827.
