### ISSUE TITLE
`%<` in `makeprg` can not be expand

### ISSUE THREAD

**Issue by zgpio** [neomake/neomake#2156]
### Expected behavior
`%<` in `makeprg` should be expand.

### Steps to reproduce
1. foo.c
```c
#include <stdio.h>
int main(int argc, char *argv[])
{
    printf("hello world");
    return 0;
}
```
2. add follow to vimrc:
 ```vim
function! MyOnNeomakeJobFinished() abort
  let context = g:neomake_hook_context
  echom string(context.jobinfo)
endfunction
autocmd User NeomakeJobFinished call MyOnNeomakeJobFinished()
```
3. edit foo.c, exe `set makeprg=clang\ %\ -o\ %<.exe`, then `:Neomake!`
check the info in `:mess`

**Comment by blueyed** [comment]
Thanks for the report.

For now you should be able to use `%:r` instead.

From the help:

    *extension-removal* *:_%<*
    If a "<" is appended to "%", "#", "#n" or "CTRL-V p" the extension of the file
    name is removed (everything after and including the last '.' in the file
    name).  This is included for backwards compatibility with version 3.0, the
    ":r" form is preferred.  Examples: >
