### ISSUE TITLE
Maker for Haxe?

### ISSUE THREAD

**Issue by danbruegge** [neomake/neomake#216]
Hi, i use neovim with vaxe and neomake. Before neomake, i did the syntax checks with syntastic.

Is there a way to check haxe syntax with neomake?

Regards, Dan

**Comment by jaredly** [comment]
Here are some helpful resources for adding a new maker to neomake:

- [syntastic's Haxe config file](https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/haxe/haxe.vim) 
- [this](https://github.com/benekastah/neomake/tree/master/autoload/neomake/makers/ft) is where you would create a new `haxe.vim`

Syntastic's haxe checker also looks for an hxml file, which you may or may not need -- if not, it should be pretty simple to define a maker.

**Comment by danbruegge** [comment]
If i have installed the vaxe plugin, it should be fine too only use the `make` command.
```
function! neomake#makers#ft#haxe#EnabledMakers()
    return ['haxe']
endfunction

function! neomake#makers#ft#haxe#make()
    return {
        \ 'errorformat': '%E%f:%l: characters %c-%n : %m'
    \ }
endfunction
```
![neomake-vaxe-linter](https://cloud.githubusercontent.com/assets/1296438/11056707/c5be3d3c-8784-11e5-84f2-f68dcb5a334c.png)

Otherwise, i have no clue how to build a new maker.
