### ISSUE TITLE
'PosixPath' Error on Windows

### ISSUE THREAD

**Issue by Neur1n** [neomake/neomake#2172]
### Expected behavior

Works properly.

### Steps to reproduce
1. Using latest Neovim.
2. Using vim-vint with `.vim` file.
3. Once enter a vim file, an exception thrown: `NotImplementedError: cannot instantiate 'PosixPath' on your system`

#### Neomake debug information

Async support: 1
Current filetype: vim
Windows: 1
[shell, shellcmdflag, shellslash]:['cmd.exe', '/s /c', 0]

##### Enabled makers

For the current filetype ("vim", used with :Neomake):
 - vint
   - args: ['--style-problem', '--no-color', '-f', '{file_path}:{line_number}:{column_number}:{severity}:{description} ({policy_name})', '--enable-neovim']
   - auto_enabled: 1
   - errorformat: '%I%f:%l:%c:style_problem:%m,%f:%l:%c:%t%*[^:]:E%n: %m,%f:%l:%c:%t%*[^:]:%m'
   - exe: 'vint'
   - output_stream: 'stdout'
   - postprocess: {'pattern': '\v%(^:|%([^:]+: ))\zs(\S+)', 'fn': function('neomake#postprocess#generic_length')}
   - supports_stdin: function('34')
   - version information (E:\ProgramFiles\Python3\Scripts\vint --version): 0.3.19
NOTE: you can define g:neomake_vim_enabled_makers to configure it (or b:neomake_vim_enabled_makers).

For the project (used with :Neomake!):
 - makeprg
   - append_file: 0
   - args: []
   - auto_enabled: 1
   - errorformat: '%*[^"]"%f"%*\D%l: %m,"%f"%*\D%l: %m,%-G%f:%l: (Each undeclared identifier is reported only once,%-G%f:%l: for each function it appears in.),%-GIn file included from %f:%l:%c:,%-GIn file included from %f:%l:%c\,,%-GIn file included from %f:%l:%c,%-GIn file included from %f:%l,%-G%*[ ]from %f:%l:%c,%-G%*[ ]from %f:%l:,%-G%*[ ]from %f:%l\,,%-G%*[ ]from %f:%l,%f:%l:%c:%m,%f(%l):%m,%f:%l:%m,"%f"\, line %l%*\D%c%*[^ ] %m,%D%*\a[%*\d]: Entering directory %*[`'']%f'',%X%*\a[%*\d]: Leaving directory %*[`'']%f'',%D%*\a: Entering directory %*[`'']%f'',%X%*\a: Leaving directory %*[`'']%f'',%DMaking %*\a in %f,%f|%l| %m'
   - exe: 'make'
   - WARNINGS:
     - maker's exe (make) is not executable.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - output_stream: 'both'
 - remove_invalid_entries: 0
 - buffer_output: 1

###### New-style (dict, overrides old-style)

```
g:neomake: {
  'automake': {
    'ignore_filetypes': [
      'startify',
    ],
    'events': {
      'BufWritePost': {
        'delay': 0,
      },
      'InsertLeave': {},
      'BufWinEnter': {},
      'TextChanged': {},
    },
  },
  'automake_delay': 500,
}
b:neomake: unset
```

###### Old-style

```
g:neomake_c_clang_exe = 'clang-7'
g:neomake_c_enabled_makers = ['clang']
g:neomake_cpp_clang_exe = 'clang-7'
g:neomake_cpp_cpplint_exe = 'cpplint'
g:neomake_cpp_enabled_makers = ['clang', 'cpplint']
g:neomake_error_sign = {'text': '✘'}
g:neomake_info_sign = {'text': ''}
g:neomake_message_sign = {'text': ''}
g:neomake_place_signs = 1
g:neomake_python_enabled_makers = ['pyflakes', 'pycodestyle', 'pydocstyle']
g:neomake_python_pycodestyle_exe = 'pycodestyle'
g:neomake_python_pydocstyle_exe = 'pydocstyle'
g:neomake_python_pyflakes_exe = 'pyflakes'
g:neomake_warning_sign = {'text': ''}

```
  makeprg=make

#### :version

```
NVIM v0.3.2-881-gd81b9d5ec
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/msys64/mingw64/bin/cc.exe -Wconversion -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -Wvla -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

#### :messages

```
Neomake: vint: unexpected output on stderr: Traceback (most recent call last):
  File "e:\programfiles\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\programfiles\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\ProgramFiles\Python3\Scripts\vint.exe\__main__.py", line 9, in <module>
  File "e:\programfiles\python3\lib\site-packages\vint\__init__.py", line 11, in main
    init_cli()
  File "e:\programfiles\python3\lib\site-packages\vint\bootstrap.py", line 22, in init_cli
    cli.start()
  File "e:\programfiles\python3\lib\site-packages\vint\linting\cli.py", line 22, in start
    self._validate(env)
  File "e:\programfiles\python3\lib\site-packages\vint\linting\cli.py", line 47, in _validate
    if not self._should_read_from_stdin(env):
  File "e:\programfiles\python3\lib\site-packages\vint\linting\cli.py", line 129, in _should_read_from_stdin
    return len(env['file_paths']) == 1 and PosixPath('-') in env['file_paths']
  File "e:\programfiles\python3\lib\pathlib.py", line 997, in __new__
    % (cls.__name__,))
NotImplementedError: cannot instantiate 'PosixPath' on your system
Neomake: vint: unexpected output. See :messages for more information.
"tagbar.vim" [unix] 13L, 345C written
Neomake: vint: unexpected output on stderr: Traceback (most recent call last):
  File "e:\programfiles\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\programfiles\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\ProgramFiles\Python3\Scripts\vint.exe\__main__.py", line 9, in <module>
  File "e:\programfiles\python3\lib\site-packages\vint\__init__.py", line 11, in main
    init_cli()
  File "e:\programfiles\python3\lib\site-packages\vint\bootstrap.py", line 22, in init_cli
    cli.start()
  File "e:\programfiles\python3\lib\site-packages\vint\linting\cli.py", line 22, in start
    self._validate(env)
  File "e:\programfiles\python3\lib\site-packages\vint\linting\cli.py", line 47, in _validate
    if not self._should_read_from_stdin(env):
  File "e:\programfiles\python3\lib\site-packages\vint\linting\cli.py", line 129, in _should_read_from_stdin
    return len(env['file_paths']) == 1 and PosixPath('-') in env['file_paths']
  File "e:\programfiles\python3\lib\pathlib.py", line 997, in __new__
    % (cls.__name__,))
NotImplementedError: cannot instantiate 'PosixPath' on your system
Neomake: vint: unexpected output. See :messages for more information.
```

2. If relevant (it is always useful with bug reports) paste the contents of the
   logfile (via `g:neomake_logfile`).

-->

**Comment by blueyed** [comment]
Did this start to happen only recently?  (e.g. due to https://github.com/neomake/neomake/commit/e464202cfb0ea4d09ef359b12f3a489f51cfd471)

Does it only happen with changed files, i.e. when temporary files/stdin would be used?

What command is Neomake running?  (see the log)

Apart from that it appears to be a bug with vint.

**Comment by blueyed** [comment]
You can / should also try vint 4.0a1 (`pip install --pre vint`).

**Comment by Neur1n** [comment]
I haven't use Neomake on windows for a very long time, like over half a year. Then I reused it on Windows last week. 
It happens once a `.vim` is opened, either opened from command line or using `:e foo.vim` in (neo)vim.
And, is "[vint](https://pypi.org/project/vint/)" should be used? Or actually "[vim-vint](https://pypi.org/project/vim-vint/)"? I think "vint" is another unrelated thing. Wish I didn't make it wrong.
Thanks.

**Comment by blueyed** [comment]
Oh, yes, it is vim-vint - sorry.

**Comment by Neur1n** [comment]
Using the pre version works now. Thanks a lot.

**Comment by blueyed** [comment]
Cool, closing here then.
