### ISSUE TITLE
Missing signs in neovim

### ISSUE THREAD

**Issue by cancercufasole** [neomake/neomake#2176]
Both the stable neovim and the nightly appimage show this behaviour.
https://my.mixtape.moe/birxjt.png
What does neomake depend on for the signs ? Can I change these to something ascii or unicode by default ?

**Comment by blueyed** [comment]
Should work by default.
Have you tried it with a minimal vimrc?
What is `:set signcolumn?` for you.

Also check the (debug) log, where placing signs gets logged.

**Comment by cancercufasole** [comment]
It's auto. 
Here's the config: http://ix.io/1vWK
I'm currently looking on how to access the log which you mentioned.

**Comment by blueyed** [comment]
See the issue template.. `let g:neomake_logfile = '/tmp/neomake.log'`

**Comment by blueyed** [comment]
Works for me, using a minimal config and your example, with `:Neomake gcc`.

(But I've noticed that the virtualtext identifier (❯) does not appear to be in your font. That should have a more universal default maybe then.)

**Comment by cancercufasole** [comment]
Here it is:
http://ix.io/1vWL

**Comment by blueyed** [comment]
> Placing sign: sign place 5000 line=3 name=neomake_file_err buffer=1.

So it should be there.
Check `:sign place`.

**Comment by blueyed** [comment]
Might be related to the following though:

> WARN: seen entries with bufnr different from jobinfo.bufnr (1): {'3': 1}, current bufnr: 1.

**Comment by cancercufasole** [comment]
:sign place
--- Signs ---

Press ENTER or type command to continue

**Comment by blueyed** [comment]
Check the buffer number reported in the log checks your actual buffer number.

> Placing sign: sign place 5000 line=3 name=neomake_file_err buffer=1.

Also try running `:sign place 5000 line=3 name=neomake_file_err buffer=1` manually (replace the buffer number with your current one).

(I've added information about using a minimal vimrc to the issue template, please also try that to ensure no other plugin(s) are interfering)

**Comment by cancercufasole** [comment]
log: http://ix.io/1vWX
screen: https://a.uchi.moe/ilkvzw.png

**Comment by cancercufasole** [comment]
I've also tried running :sign place 5000 line=3 name=neomake_file_err buffer=1 with both configs.

**Comment by cancercufasole** [comment]
also line=4 actually for the file in the second screenshot

**Comment by cancercufasole** [comment]
The previous :sign place is wrong. I'm an idiot. I ran that with an empty file.

:sign place
--- Signs ---
Signs for lel.cpp:
    line=4  id=5000  name=neomake_file_err

Press ENTER or type command to continue

**Comment by blueyed** [comment]
Ok, in the last screen shot it looks like at least the sign column now shows up.
The sign not showing up there might also be related to it not being in your font.
Try `sign define neomake_file_err texthl=NeomakeErrorSign text=E`.

Still not sure why it is not showing up in the first place though.

**Comment by blueyed** [comment]
> The previous :sign place is wrong.

Ah, so it shows up there at least.
But why is there no sign column in your first screenshot?

**Comment by cancercufasole** [comment]
There is a sign column in the first screenshot. The problem is that it uses the same color as the background.
sign define neomake_file_err texthl=NeomakeErrorSign text=E works, I see an E in the sign column.
I'm using Terminus.

**Comment by blueyed** [comment]
Which terminal program do you use?
I assume the sign characters, and the virtualtext identifier (❯) also do not work outside of Vim/Neovim therein?

**Comment by cancercufasole** [comment]
I'm using st. I don't know how to test them outisde neovim but I tried pasting and it does not show up.

**Comment by cancercufasole** [comment]
This is also the same with rxvt-unicode with it's default font which is probably fixed.
I think changing the defaults will solves this for me.

     let g:neomake_error_sign = {'text': '✖', 'texthl': 'NeomakeErrorSign'}
     let g:neomake_warning_sign = {
         \   'text': '⚠',
         \   'texthl': 'NeomakeWarningSign',
         \ }
     let g:neomake_message_sign = {
          \   'text': '➤',
          \   'texthl': 'NeomakeMessageSign',
          \ }
     let g:neomake_info_sign = {'text': 'ℹ', 'texthl': 'NeomakeInfoSign'}

Is there any way to change that square character that appears right of the line ?

**Comment by blueyed** [comment]
`g:neomake_virtualtext_prefix`

Please let me know what you pick, like I said e.g. for `g:neomake_virtualtext_prefix` we could also have ">> " as default or something more compatible.

**Comment by cancercufasole** [comment]
I went with this:

let g:neomake_virtualtext_prefix='>>'
let g:neomake_error_sign =      {'text': 'e-','texthl': 'ErrorMsg'}
let g:neomake_warning_sign =    {'text': 'w-','texthl': 'WarningMsg'}
let g:neomake_info_sign =       {'text': 'i-','texthl': 'InfoMsg'}
let g:neomake_message_sign =    {'text': 'm-','texthl': 'InfoMsg'}

I have no idea what to choose to be honest.

**Comment by blueyed** [comment]
Thanks, closing for now.
