### ISSUE TITLE
Represent non-number error categories?

### ISSUE THREAD

**Issue by euclio** [neomake/neomake#2184]
My company has an internal linter that emits style violations with specific categories like ("style", "spelling", etc.). I'd like to extract these from the message, but I don't see a specific field or errorformat token to extract it. The closest thing I've seen is `entry.nr`. Does neomake support this?

**Comment by blueyed** [comment]
It is not really supported by Vim/Neovim.

`nr` can be a number, `type` a single char.

This works for flake8 etc, where you have `E501` etc.

I suggest using the `text` field for this - you can append/prepend it there.

See https://github.com/neomake/neomake/blob/bfb7179df2c883a304adfb7d98476001c19db9da/autoload/neomake/makers/ft/python.vim#L136-L250 for an advanced example.

**Comment by blueyed** [comment]
Closing, but feel to follow up, of course.
