### ISSUE TITLE
NeomakeInfo shows nix maker but neomake can't run it

### ISSUE THREAD

**Issue by teto** [neomake/neomake#2289]
### Expected behavior

When editing nix files, I don't have the neomake warnings anymore.
`:Neomake nix` returns `Neomake: Maker not found (for filetype nix): nix.`
and the log 
```
13:06:34 14708 [E      ] [1.-:6:1] Maker not found (for filetype nix): nix.
13:06:34 14708 [D      ] [1.-:6:1] Nothing to make: no valid makers.
13:06:34 14708 [D +0.01] [1.-:6:1] Cleaning make info.
13:06:41 14708 [E +7.42] [2.-:6:1] Maker not found (for filetype nix): nix.
13:06:41 14708 [D      ] [2.-:6:1] Nothing to make: no valid makers.
13:06:41 14708 [D      ] [2.-:6:1] Cleaning make info.

```

but NeomakeInfo shows it:
```

Async support: 1
Current filetype: nix
Windows: 0
[shell, shellcmdflag, shellslash]: ['/run/current-system/sw/bin/zsh', '-c', 0]
makeprg=make

##### Enabled makers

For the current filetype ("nix", used with :Neomake):
 - nix_instantiate
   - args: ['--parse-only']
   - auto_enabled: 1
   - errorformat: 'error: %m at %f:%l:%c'
   - exe: 'nix-instantiate'
   - version information (/run/current-system/sw/bin/nix-instantiate --version): nix-instantiate (Nix) 2.2
NOTE: you can define g:neomake_nix_enabled_makers to configure it (or b:neomake_nix_enabled_makers).
```

I've tried with a minimal.vim and I had the same behavior (btw minimal.vim could be part of the repo). I am using nix 2.2 and neomake master 7f834152836166f533ab4944792c6d0087d60f5a .

**Comment by blueyed** [comment]
The names are different:

> Maker not found (for filetype nix): nix.
> …
> - nix_instantiate

**Comment by blueyed** [comment]
Closing.
As for the minimal vimrc I've created https://github.com/neomake/neomake/issues/2290.

**Comment by blueyed** [comment]
> The maker was not run because I had commented out "call neomake#configure#automake('w') "

Is it a custom maker that gets only loaded when calling the above?

>  Any advice on how to check that neomake is loaded/installed ?

Do you load it lazily?

`g:loaded_neomake` should work in general.

btw: how do you like the virtualtext support so far?
