### ISSUE TITLE
Pick up changes in g:python3_host_prog

### ISSUE THREAD

**Issue by teto** [neomake/neomake#2302]
### Expected behavior

Take into account changes in g:python3_host_prog after starting nvim.

I run neovim on nixos, which generates a specific config with a specific python interpreter g:python3_host_prog=/nix/store/3vwrd209k57ii4mn7rbc45ybkh9rsg8d-neovim-float/bin/nvim-python3.
When I start nvim, it gets this value loads neomake which picks up the previous value of g:python3_host_prog.
Now when I enter a nix-shell with a specific python project, I write a .nvimrc which contains let `g:python3_host_prog="python3"` so that neovim uses the python environment of this specific project (because it has the correct python libraries loaded). This is picked up by neovim (the new value of g:python3_host_prog appears in :checkhealth) but it doesn't seem to be picked up by neomake as
NeomakeInfo still returns information fetch  with the initial value of g:python3_host_prog (/nix/store/3vwrd209k57ii4mn7rbc45ybkh9rsg8d-neovim-float/bin/nvim-python3) : 
```
##### Enabled makers

For the current filetype ("python", used with :Neomake):
 - mypy
   - args: ['-m', 'mypy']
   - auto_enabled: 0
   - errorformat: '%E%f:%l: error: %m,%W%f:%l: warning: %m,%I%f:%l: note: %m'
   - exe: '/nix/store/3vwrd209k57ii4mn7rbc45ybkh9rsg8d-neovim-float/bin/nvim-python3'
   - version information (/nix/store/3vwrd209k57ii4mn7rbc45ybkh9rsg8d-neovim-float/bin/nvim-python3 --version): Python 3.7.2
NOTE: you can define g:neomake_python_enabled_makers to configure it (or b:neomake_python_enabled_makers).
```
I've tried running NeomakeClean to reset the makers to no avail.

### Steps to reproduce

I've tried to reproduce with this command:

`/nix/store/273i3m6i9w9am0wpbn4sycv3nld72flv-neovim/bin/nvim --cmd "let g:loaded_python_provider=1" --cmd "let g:python3_host_prog='/nix/store/3vwrd209k57ii4mn7rbc45ybkh9rsg8d-neovim-float/bin/nvim-python3'" -u minimal.vim --cmd "let g:python3_host_prog='python3'"`

but for some reasons NeomakeInfo didn't display the mypy maker which was showing the problem so I can't show you.

**Comment by teto** [comment]
it might be linked to the fact that neovim seemingly expects a full path for python3 as per the gitter discussion.

**Comment by blueyed** [comment]
Neomake does not look at / use `g:python3_host_prog`.

Are you configuring the mypy maker itself?  (its exe should be just `mypy`, but you have `nvim-python3` there)

**Comment by teto** [comment]
aaah I am so ashamed. You are perfectly right, it's a custom maker I added to work around this I suppose https://github.com/neomake/neomake/issues/2071 . I will try to make this my last stupid issue, sorry.

**Comment by blueyed** [comment]
No problem.. :)

What does your custom maker look like?

**Comment by teto** [comment]
I just overrode the args like this. I only work with python3:
```
let g:neomake_python_mypy_exe = g:python3_host_prog
let g:neomake_python_mypy_args = ['-m', 'mypy'] 
```
I am trying to have nixos build a per-project init.vim/.nvimrc with custom (haskell/python) interpreters (to keep both nix and neomake advantages).
