### ISSUE TITLE
errorformat does not work with Neomake

### ISSUE THREAD

**Issue by sirex** [neomake/neomake#231]
Here is what I get after running `:source /tmp/settings.vim` and `:make`:
![shot-008](https://cloud.githubusercontent.com/assets/297583/11299527/275e5c8a-8f90-11e5-87c6-43d34ab0d694.png)

And here is what I get after running `:Neomake!`:
![shot-009](https://cloud.githubusercontent.com/assets/297583/11299528/2c43ad40-8f90-11e5-8b9f-d1856f187a52.png)

I expect output to be exactly the same as with `:make`. Is this an error or Neomake no longer uses `errorformat`?

Below is the code, that you see in screenshots.

`/tmp/settings.vim`:

``` vim
set makeprg=python3\ /tmp/foobar.py
set errorformat=\ %#File\ \"%f\"\\,\ line\ %l\\,\ %m
set errorformat+=\@File\:\ %f
```

`/tmp/foobar.py`:

``` python
def foo():
    assert False


def bar():
    foo()


def main():
    bar()


if __name__ == '__main__':
    main()
```

**Comment by sbdchd** [comment]
This doesn't solve your issue with `:Neomake!`, `makeprg`, and `errorformat`, but it might be helpful anyway.

I put the following in my .vimrc

```viml
let g:neomake_python_python3_maker = {
            \ 'errorformat': '\ %#File\ \"%f\"\\,\ line\ %l\\,\ %m,' .
            \ '\@File\:\ %f'
            \ }
let g:neomake_python_enabled_makers = ['python3']
```

and it output
<img width="752" alt="screenshot 2016-05-15 13 13 56" src="https://cloud.githubusercontent.com/assets/7340772/15275635/0519d574-1a9f-11e6-9012-f8071682342a.png">

when called with the command `:Neomake`

**Comment by nivoliev** [comment]
On a similar case, I found that modifying the file `autoload/neomake/utils.vim`  as:

```
function! neomake#utils#MakerFromCommand(command) abort
    " XXX: use neomake#utils#ExpandArgs and/or remove it.
    "      Expansion should happen later already!
    let command = substitute(a:command, '%\(:[a-z]\)*',
                           \ '\=expand(submatch(0))', 'g')

"    ========= original version
"    return {
"        \ 'exe': &shell,
"        \ 'args': [&shellcmdflag, command],
"        \ 'remove_invalid_entries': 0,
"        \ 'errorformat': '%+G',
"        \ }
"    ========= modified version
    return {
        \ 'exe': &shell,
        \ 'args': [&shellcmdflag, command],
        \ }
endfunction
```
worked for me.

**Comment by blueyed** [comment]
@nivoliev 
That's a recent change!  Please create a new issue with what you are using - are you using `NeomakeSh`?!

**Comment by blueyed** [comment]
I can see that adding `'errorformat': '%+G'` could be problematic in some context, but please clarify (in the new issue).

**Comment by nivoliev** [comment]
That issue was mostly corresponding to my problem and didn't have any solution proposed, but I can understand that digging old issues is not a good practice. I'll post a new one.

**Comment by blueyed** [comment]
For reference: https://github.com/neomake/neomake/issues/715.

**Comment by blueyed** [comment]
This issue seems to be fixed by now.  I've tested it using the test case posted by @sirex.
