### ISSUE TITLE
Question: disabling for any language except for select few

### ISSUE THREAD

**Issue by funbringer** [neomake/neomake#2312]
Hi!
Many thanks for making Neomake!

I'm sorry if this question has been answered before, but how do I enable Neomake only for a restricted set of languages (for instance, `['rust', 'python']`)?

I don't want to see lints for C/C++ (and possibly any new language I'd like to use Neovim for), but I dislike the idea of writing down a complete list of "banished languages", like:

```vim
let g:neomake_c_enabled_makers   = []
let g:neomake_cpp_enabled_makers = []
" etc...
```

Is there an elegant way to solve this problem?

**Comment by blueyed** [comment]
Good question.

It depends on how you setup/configure Neomake.
You could for example do something along:
```
augroup my_neomake
  au!
  autocmd FileType rust,python call neomake#configure#automake_for_buffer('nw', 1000)
augroup END
```

But also of course more manual using `autocmd BufWritePost rust,python Neomake` etc.

**Comment by blueyed** [comment]
Let me know how this works for you, and we could add it to the docs.

**Comment by funbringer** [comment]
@blueyed yep, it works, thanks!
