### ISSUE TITLE
what is virtualtext highlightgroup？

### ISSUE THREAD

**Issue by taigacute** [neomake/neomake#2318]
### Expected behavior

i got `virtualtext` bg，its red in my own colorscheme， i want to set its ctermbg。can tell me whats it highlight

![1231](https://user-images.githubusercontent.com/41671631/53676293-25ba9500-3cdb-11e9-80dc-1144f8f50745.png)

**Comment by mhinz** [comment]
Here you can see the definitions:

https://github.com/neomake/neomake/blob/master/autoload/neomake/virtualtext.vim#L109-L112

The keys are new highlight groups defined by this plugin and the values are the highlight groups they're linked to by default.

**Comment by taigacute** [comment]
@mhinz   thanks  a lot , i got it
