### ISSUE TITLE
Is it possible to integrate golangci-lint?

### ISSUE THREAD

**Issue by cenkalti** [neomake/neomake#2319]
[Gometalinter](https://github.com/alecthomas/gometalinter) is already integrated.
Gometalinter is deprecated.
The author [recommends](https://github.com/alecthomas/gometalinter/issues/590#issue-407606165) switching to [golangci-lint](https://github.com/golangci/golangci-lint).

**Comment by blueyed** [comment]
Sure, just needs a PR I guess.

**Comment by cenkalti** [comment]
I'll send a PR this weekend.
