### ISSUE TITLE
What is this, and how do I disable it?

### ISSUE THREAD

**Issue by threewordphrase** [neomake/neomake#2320]
I just updated Neovim (as far as I can tell, Neomake was not updated). I am now seeing a new inline display of lint errors which is quite obnoxious and superfluous as these errors are already marked with `neomake_error_sign` (left X) and the specific lint message is displayed in the status bar.

![screen shot 2019-03-03 at 6 33 37 pm](https://user-images.githubusercontent.com/1591971/53707247-0ad34800-3de3-11e9-8237-470dc2559010.png)

I am specifically talking about the wide red banner displayed inline after the commented code. It did not appear until I updated Neovim today. 

What _is_ this, and how can I disable it?

Seen in Neovim v0.3.4, on current neomake `master`.

**Comment by threewordphrase** [comment]
Solved. This is caused by `g:neomake_virtualtext_current_error`. Fixed with this line in my vimrc:

`let g:neomake_virtualtext_current_error=0`

**Comment by blueyed** [comment]
Yeah, sorry for the trouble - maybe it should not be enabled by default.

> which is quite obnoxious

One argument is that it is usually easier to read it there than in the command line.

**Comment by threewordphrase** [comment]
For what it's worth, it's visually jarring, and lint errors are quite common when actively editing a file. When it's time to clean up and move on, the status bar output is quite sufficient.

It's a cool feature, but I'm not sure this is the right implementation.
