### ISSUE TITLE
Swiftpm fails if cwd is not projectroot

### ISSUE THREAD

**Issue by F4IL3D** [neomake/neomake#2342]
If the cwd is not the project root, swiftpm fails because it can not find the Package.swift file.

Therefore, I would suggest the following changes to the swiftpm and swiftpmtest functions, such as the typescript maker::

```
 let maker = {
                \ 'exe': 'swift',
                ......
              \ }
let config = neomake#utils#FindGlobFile('Package.swift')
if !empty(config)
    let maker.cwd = fnamemodify(config, ':h')
endif
return maker
```
Thanks for this great plugin.

**Comment by blueyed** [comment]
I wonder if it is possible to pass in the config (to avoid cwd overhead), but I think your suggestion makes sense otherwise.

**Comment by blueyed** [comment]
See https://github.com/neomake/neomake/pull/2343.

**Comment by F4IL3D** [comment]
Hello Daniel,

many thanks.
Of course, your version is the cleanest solution.  :-D
Only for understanding. What do you mean "to avoid cwd overhead"?

**Comment by blueyed** [comment]
> cwd overhead

This involves changing back and forth for jobs etc.  Not a big overhead, but still..

Have you tested #2343?  (with both makers)

**Comment by F4IL3D** [comment]
Ah okay, now I understand what you mean.

I have tested your changes with both makers. Has worked perfectly in both cases.

![image](https://user-images.githubusercontent.com/48415231/55112077-09442980-50dc-11e9-8092-36a86e735f5a.png)

**Comment by blueyed** [comment]
Great, thanks for the report and suggested fix!
