### ISSUE TITLE
set a maximum number of signs per line / collapse marks

### ISSUE THREAD

**Issue by teto** [neomake/neomake#2349]
### Expected behavior

Let's say I have 3 warnings on the same line, neomake will add 3 marks. The behavior makes sense but with `signcolumn=auto:3`, neomake may end up using every column, leaving none for other plugins. I would prefer to have a maximum of one mark for neomake.

Consider this very low priority, just nice to have :)

**Comment by blueyed** [comment]
Makes sense.
Also a good idea for performance in general, but should be coupled to a setting maybe.
I could also imagine to append a number of the total number of signs to the most dominating sign (only makes sense if it has a width of 1, but would be truncated otherwise I assume anyway).

**Comment by blueyed** [comment]
See also https://github.com/neovim/neovim/pull/9788.

**Comment by blueyed** [comment]
Started working on this.
But isn't it the case currently that there is only a single sign per line?!  (only looked at tests though)

**Comment by blueyed** [comment]
> Let's say I have 3 warnings on the same line, neomake will add 3 marks.

Really?

I've just checked this, and with e.g. "flake8" and "mypy", only one sign is displayed.
I'm experimenting with having a new setting for this, and then it would display more signs.
(I am using `:set signcolumn=auto:3` here)

Are the warnings from the same maker?
Or from different modes (file / project)?

**Comment by teto** [comment]
There was a repetition of the same sign symbol while I had tried to assign different symbols to each plugin. It is possible I made a mistake though so don't spend time on this xD
I've mostly switched to coc.nvim + lsp python client so it's not easy to reproduce but the pyls-mypy plugin crashes the server so I might use Neomake again for python as well.
