### ISSUE TITLE
Consider suppressing exit value messages

### ISSUE THREAD

**Issue by Earnestly** [neomake/neomake#238]
I run neomake everytime I write a buffer, usually write returns some useful information about how many characters/lines have been written but with neomake this is immediately overwritten by a message from neomake informing me that it has exited with a status of 0.

Perhaps you've provided these to let users know that neomake has done something given the async nature of it but could you consider suppressing these messages as they're ultimately not that necessary when neomake reporting becomes part of the basic workflow?

**Comment by blueyed** [comment]
`let neomake_verbose = 0` could be a workaround for now.
But it might also be possible to fix this in a better way.

**Comment by Earnestly** [comment]
It is a nice workaround, thank you very much \o/

**Comment by blueyed** [comment]
The level of the message should be adjusted I guess.
