### ISSUE TITLE
Providing path to executable

### ISSUE THREAD

**Issue by alexlafroscia** [neomake/neomake#246]
I recently switched to Neomake from Syntastic and am working on getting Python checking set up correctly.  I would like to use `flake8` to lint my files, but because of my `virtualenv` setup, the actual `flake8` executable is not in my `$PATH` if the directory I'm working in is using a different `virtualenv`.  Is there some way to hard-code the path to the executable for a particular maker?

**Comment by alexlafroscia** [comment]
Well, I was able to point the maker at the right executable by doing this:

```vim
let g:neomake_python_enabled_makers = ['flake8']
let g:neomake_python_flake8_maker = {
  \ 'exe': $PYENV_ROOT . '/versions/3.5.0/bin/flake8'
  \ }
```

but this seems to have messed with some other settings; I no longer see the output of how many errors and warnings there were in Airline like I did before.  Is this because the new config and existing config don't get merges properly?  How does one add to the existing config instead of overwriting it?

**Comment by halberom** [comment]
I got it to work by doing this

```
" call pylint using the current python (venv or global)
let g:neomake_python_venvpylint_maker = {
    \ 'exe': 'python',
    \ 'args': [
        \ '`which pylint`',
        \ '-f', 'text',
        \ '--msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg}"',
        \ '-r', 'n'
    \ ],
    \ 'errorformat':
        \ '%A%f:%l:%c:%t: %m,' .
        \ '%A%f:%l: %m,' .
        \ '%A%f:(%l): %m,' .
        \ '%-Z%p^%.%#,' .
        \ '%-G%.%#',
    \ }

let g:neomake_python_enabled_makers = ['venvpylint']
```

Curious to know whether there's a better way.

**Comment by mmarchini** [comment]
Using `virtualenv` and `flake8`, I was able to make it work by doing as follow:

```vim
let g:neomake_python_enabled_makers = ['flake8']
let g:neomake_python_flake8_maker = {
  \ 'exe': '/home/matheus/.config/nvim/env2/bin/flake8',
  \ 'args': ['--format=default'],
  \ 'errorformat':
      \ '%E%f:%l: could not compile,%-Z%p^,' .
      \ '%A%f:%l:%c: %t%n %m,' .
      \ '%A%f:%l: %t%n %m,' .
      \ '%-G%.%#',
  \ 'postprocess': function('neomake#makers#ft#python#Flake8EntryProcess')
  \ }
```

AFAIK, there's no better way at the moment.

**Comment by razor-x** [comment]
One option I'm trying for getting python checkers per-environment to work is adding the `~/.pyenv/shims` to my path. Then I can rely on [vim-pyenv](https://github.com/lambdalisue/vim-pyenv) to handle activating the correct environment. This seems to require the least configuration and I don't have to override or add new checkers.

_The main side effect with this approach:_

Say I have pep8 in environment A and pylint in environment B. Then there will be a shim for each, but if I run `pep8` while B is active, the command will exit with code 127 (command not found). 

Neomake "sees" both pep8 and pylint and will try to run both, but one will always "fail" with 127.
**Thus, it would be nice if Neomake caught the 127 exit code and ignored / suppressed it.**

**Comment by blueyed** [comment]
>Thus, it would be nice if Neomake caught the 127 exit code and ignored / suppressed it.

:+1: 

Do you like to create a PR? Or a separate issue to discuss it?

**Comment by razor-x** [comment]
@blueyed New issue here: #537. 

This issue may be a little broader (I'm still looking at how to handle Node binaries installed via NVM), or @alexlafroscia may be looking for a difference solution (maybe a way to override the path to a maker without having to redefine it?).

Not sure when I can get to a PR for the 127 thing, so if someone else wants to implement this go for it.

For future reference, here is an updated version of the script I'm using to add rbenv and pyenv to my path. (This is mainly for nvim-qt which wouldn't get this from my shell.)

For the below to work, I'm using [vim-pyenv](https://github.com/lambdalisue/vim-pyenv) and [vim-rbenv](https://github.com/tpope/vim-rbenv). Also recommend [rbenv-bundler](https://github.com/carsomyr/rbenv-bundler). 

```vim
" Set rbenv root.
if empty($RBENV_ROOT)
  let s:rbenv_root = $HOME . '/.rbenv'
else
  let s:rbenv_root = $RBENV_ROOT
endif

if isdirectory(s:rbenv_root)
  " Add rbenv bin to path.
  let s:rbenv_bin = s:rbenv_root . '/bin'
  let $PATH = substitute($PATH, ':' . s:rbenv_bin, '', '')
  let $PATH .= ':' . s:rbenv_bin

  " Add rbenv shims to path.
  let s:rbenv_shims = s:rbenv_root . '/shims'
  let $PATH = substitute($PATH, ':' . s:rbenv_shims, '', '')
  let $PATH .= ':' . s:rbenv_shims
endif

" Set pyenv root.
if empty($PYENV_ROOT)
  let s:pyenv_root = $HOME . '/.pyenv'
else
  let s:pyenv_root = $PYENV_ROOT
endif

if isdirectory(s:pyenv_root)
  " Add pyenv shims to path.
  let s:pyenv_shims = s:pyenv_root . '/shims'
  let $PATH = substitute($PATH, ':' . s:pyenv_shims, '', '')
  let $PATH .= ':' . s:pyenv_shims
endif

" Bonus example to set deoplete-jedi path from vim-pyenv.
augroup pyenv-deoplete-jedi-path
  autocmd!
  autocmd User vim-pyenv-activate-post
    \ let g:deoplete#sources#jedi#python_path = g:pyenv#python_exec
  autocmd User vim-pyenv-deactivate-post
    \ unlet g:deoplete#sources#jedi#python_path
augroup END
```

**Comment by blueyed** [comment]
I am closing this issue, since it's being solved and several examples have been provided.

**Comment by ManiacalAce** [comment]
Which approach is better?
- Explicitly setting path to the venv's flake8
- Or adding your venv's `bin/`to your $PATH from inside your init.vim?

Would appending to $PATH cause potential conflicts with packages in project venvs?
