### ISSUE TITLE
markdownlinter jumping to wrong file/position

### ISSUE THREAD

**Issue by petobens** [neomake/neomake#2480]
Consider the following minimal `init.vim` file:
```viml
let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/neomake/neomake
filetype plugin indent on

let g:neomake_open_list = 2
let g:neomake_markdown_enabled_makers = ['markdownlint']
```
Now, as in the GIF do:
1. Open nvim and edit a `foo.md` file containing:
```md
# Foo

0. Bar
```
2. Run `:Neomake`
3. When the location list opens switch to it and press `<CR>` on the candidate.

After 3. a new file `foo.md:3` opens. I instead expect the cursor to jump to the existing `foo.md` file on line `3`

![Peek 2020-03-28 12-27](https://user-images.githubusercontent.com/2583971/77826675-9951f000-70ef-11ea-85a2-f2738881b02c.gif)

**Comment by jandamm** [comment]
Hi @petobens, I've opened a pull request which will fix this issue.

If you don't want to wait for the fix to be released, you could add this to your vimrc:

```vim
function! s:MarkdownlintFix() abort
    return {
                \ 'errorformat':
                \ '%f:%l:%c %m,%f: %l: %m,' .
                \ '%f:%l %m,%f: %l: %m'
                \ }
endfunction

let g:neomake_markdown_markdownlint_maker = s:MarkdownlintFix()
```

This will overwrite the markdownlint maker with the fixed one.
This will not change the logic how the maker is enabled.

**Comment by petobens** [comment]
Thanks!
