### ISSUE TITLE
Ansible-lint changed error format

### ISSUE THREAD

**Issue by deponian** [neomake/neomake#2488]
Error format of `ansible-lint -p` changed from
```
'errorformat': '%f:%l: [%tANSIBLE%n] %m'
```
to
```
'errorformat': '%f:%l: [%t%n] %m'
```
so you should update `errorformat` in `autoload/neomake/makers/ft/ansible.vim`

**Comment by blueyed** [comment]
Thanks for the report.
Please check https://github.com/neomake/neomake/pull/2512.
Would be good to have some test with example output there maybe also, if you want to provide some.
