### ISSUE TITLE
Show both NeoMake and GitGutter signs

### ISSUE THREAD

**Issue by nomasprime** [neomake/neomake#2489]
How do I get both NeoMake and GitGutter to play nicely in the sign column? At the moment NeoMake's overwriting GitGutter signs.

**Comment by nomasprime** [comment]
Oh, just set `signcolumn=auto:<n>`, that's all there is to it?

**Comment by blueyed** [comment]
Yes, that should help / do it.
Closing as answered (by yourself :)).
