### ISSUE TITLE
Trying to run JSXHint instead of JSHint

### ISSUE THREAD

**Issue by alexlafroscia** [neomake/neomake#249]
For some reason, with `jshint` enabled for JS files, I can't seem to get JSHint to actually run.  Running `:Neomake` just doesn't seem to output anything at all, and running `:Neomake jshint` gives me an error about `jsxhint` not being installed.  I don't understand why but it seems to be trying to run JSXHint instead, even when I'm specifically telling it not to.

**Comment by sbdchd** [comment]
Is your filetype `jsx`?

It appears that in the [definition for `jsx` ](https://github.com/neomake/neomake/blob/5f048a895d4c3420a7df2740e6ce72948aa9f3e6/autoload/neomake/makers/ft/jsx.vim), there is a maker called `jshint`, which actually calls `jsxhint`.

**Comment by alexlafroscia** [comment]
This should probably be closed, I've handled it.   I had a plugin that set the filetype of `js` files to `javascript.jsx`
