### ISSUE TITLE
What's the reason there's no NeomakeJobCanceled event?

### ISSUE THREAD

**Issue by Furkanzmc** [neomake/neomake#2492]
I use the `NeomakeJobFinished` event to do some clean up after a make, but sometimes I have to cancel it because the process is stuck, or it's a server that I need to cancel. Even when I cancel, I still would like to be able to do the clean up.

I added a small change on my local copy to include this, but I'm curious if there's a reason we don't have this. If there's no particular reason, maybe I can submit a patch for it.

**Comment by blueyed** [comment]
There is no particular reason, so a patch would be welcome.
Maybe `NeomakeJobFinished` could/should be used for this though also, i.e. removing the first `if` here: https://github.com/neomake/neomake/blob/90821a3afbd5206a93e4506b47678e12fc1fc98c/autoload/neomake.vim#L1370-L1374
User's can inspect `jobinfo.canceled` then themselves etc.
However, the `jobinfo` might (or should) be missing some attributes then, e.g. the `exit_code`?

Code/doc refs:
https://github.com/neomake/neomake/blob/90821a3afbd5206a93e4506b47678e12fc1fc98c/autoload/neomake.vim#L2189
https://github.com/neomake/neomake/blob/90821a3afbd5206a93e4506b47678e12fc1fc98c/doc/neomake.txt#L1007-L1019
