### ISSUE TITLE
Neomake shows error info in the status bar of Neovim

### ISSUE THREAD

**Issue by Nova-Striker** [neomake/neomake#2508]
####  Steps to reproduce : 
It happened with me when I made a syntax error and and didn't correct it. For a split second the error was shown in the vim status bar every time I clicked the space bar or backspace.

Terminal : Alacritty
Shell : zsh
vim : Neovim v0.4.4

![Peek 2020-10-29 00-27](https://user-images.githubusercontent.com/64089730/97483535-8b15cc00-197d-11eb-97a0-e4d2499aa0a8.gif)

I dont know if its a bug or a deliberate thing, but I dont want it there on the status bar every time I click space. So if its a deliberate thing , how to disable it?
**Edit : It only happens when the window is minimised**

#### Neomake debug information

Async support: 1
Current filetype: python
Windows: 0
[shell, shellcmdflag, shellslash]: ['/usr/bin/zsh', '-c', 0]
makeprg=make

##### Enabled makers

For the current filetype ("python", used with :Neomake):
 - python
   - args: ['/home/linux/.config/nvim/autoload/plugged/neomake/autoload/neomake/makers/ft/python/compile.py']
   - auto_enabled: 1
   - errorformat: '%E%f:%l:%c: E: %m,%W%f:%l: W: %m'
   - exe: 'python'
   - output_stream: 'stdout'
   - serialize: 1
   - serialize_abort_on_error: 1
   - short_name: 'py'
   - version information (/home/linux/Desktop/Files/hotelsys/hotel/bin/python --version): Python 3.9.0
 - frosted
   - args: ['-vb']
   - auto_enabled: 1
   - errorformat: '%f:%l:%c:%m,%E%f:%l: %m,%-Z%p^,%-G%.%#'
   - exe: 'frosted'
   - WARNINGS:
     - maker's exe (frosted) is not executable.
 - pyflakes
   - args: []
   - auto_enabled: 1
   - errorformat: '%E%f:%l:%c: %m,%E%f:%l:%c %m,%E%f:%l: %m,%-G%.%#'
   - exe: 'pyflakes'
   - WARNINGS:
     - maker's exe (pyflakes) is not executable.
 - pycodestyle
   - args: []
   - auto_enabled: 1
   - errorformat: '%f:%l:%c: %m'
   - exe: 'pycodestyle'
   - postprocess: function('neomake#makers#ft#python#Pep8EntryProcess')
   - version information (/home/linux/.local/bin/pycodestyle --version): 2.6.0
 - pydocstyle
   - args: []
   - auto_enabled: 1
   - errorformat: '%W%f:%l %.%#:,%+C        %m'
   - exe: 'pep257'
   - postprocess: function('neomake#postprocess#compress_whitespace')
   - WARNINGS:
     - maker's exe (pep257) is not executable.
 - pylint
   - args: ['--output-format=text', '--msg-template="{path}:{line}:{column}:{C}: [{symbol}] {msg} [{msg_id}]"', '--reports=no']
   - auto_enabled: 1
   - errorformat: '%A%f:%l:%c:%t: %m,%A%f:%l: %m,%A%f:(%l): %m,%-Z%p^%.%#,%-G%.%#'
   - exe: 'pylint'
   - filter_output: function('304')
   - output_stream: 'stdout'
   - postprocess: [function('neomake#postprocess#generic_length'), function('neomake#makers#ft#python#PylintEntryProcess')]
   - version information (/home/linux/.local/bin/pylint --version): pylint 2.6.0
     astroid 2.4.2
     Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
     [GCC 9.3.0]
NOTE: you can define g:neomake_python_enabled_makers to configure it (or b:neomake_python_enabled_makers).

For the project (used with :Neomake!):
 - makeprg
   - append_file: 0
   - args: []
   - auto_enabled: 1
   - errorformat: '%*[^"]"%f"%*\D%l: %m,"%f"%*\D%l: %m,%-G%f:%l: (Each undeclared identifier is reported only once,%-G%f:%l: for each function it appears in.),%-GIn file included from %f:%l:%c:,%-GIn file included from %f:%l:%c\,,%-GIn file included from %f:%l:%c,%-GIn file included from %f:%l,%-G%*[ ]from %f:%l:%c,%-G%*[ ]from %f:%l:,%-G%*[ ]from %f:%l\,,%-G%*[ ]from %f:%l,%f:%l:%c:%m,%f(%l):%m,%f:%l:%m,"%f"\, line %l%*\D%c%*[^ ] %m,%D%*\a[%*\d]: Entering directory %*[`'']%f'',%X%*\a[%*\d]: Leaving directory %*[`'']%f'',%D%*\a: Entering directory %*[`'']%f'',%X%*\a: Leaving directory %*[`'']%f'',%DMaking %*\a in %f,%f|%l| %m'
   - exe: 'make'
   - version information (/usr/bin/make --version): GNU Make 4.2.1
     Built for x86_64-pc-linux-gnu
     Copyright (C) 1988-2016 Free Software Foundation, Inc.
     License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
     This is free software: you are free to change and redistribute it.
     There is NO WARRANTY, to the extent permitted by law.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - output_stream: 'both'
 - remove_invalid_entries: 0
 - buffer_output: 1

###### New-style (dict, overrides old-style)

```
g:neomake: {
  'automake': {
    'ignore_filetypes': [
      'startify',
    ],
    'events': {
      'TextChangedI': {},
      'FileType': {},
      'FileChangedShellPost': {},
      'InsertLeave': {},
      'BufWritePost': {
        'delay': 0,
      },
      'BufWinEnter': {},
      'TextChanged': {},
    },
  },
  'automake_delay': 500,
}
b:neomake: unset
```

###### Old-style

```
g:neomake_place_signs = 1

```

#### :version

```
NVIM v0.4.4
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/local/clang-7.0.0/bin/clang -O2 -g -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-d8a0d531-236d-4d4c-9703-9d6e27bee65f

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

#### :messages

```
```

**Comment by blueyed** [comment]
This comes via `g:neomake_echo_current_error` (set it to 0 to disable it).
However, it should only display it (again) if it was changed / is new - which likely happens because of you linting on `TextChangedI` (which I would not really recommend for performance reasons).
Code ref: https://github.com/neomake/neomake/blob/18438037a1cd183509f27dd54723ef24cc7dfc80/autoload/neomake.vim#L2490-L2511

Closing as answered.
