### ISSUE TITLE
Airline status not showing?

### ISSUE THREAD

**Issue by mhartington** [neomake/neomake#251]
Took a look through the docs trying to figure this one out, but for some reason I'm not getting any error segment in my airline status bar.

```viml
" Linting ---{{{
  let g:neomake_javascript_enabled_makers = ['eslint']
  autocmd! BufWritePost * Neomake
"}}}
```

Not sure what could be causing this, but let me know what other information you need.

**Comment by davidsteinberger** [comment]
I'm having the same issue. It's strange, as the default markers config for eslint looks good to me.

**Comment by davidsteinberger** [comment]
Found the issue for me: I was working in a react project with an `.eslintrc`. So I had to install several modules globally to make eslint work. I think it was:

-  babel-eslint@4.1.6
-  eslint-config-standard@4.4.0
-  eslint-config-standard-react@1.2.1
-  eslint-plugin-react@3.11.3
-  eslint-plugin-standard@1.3.1

**Comment by blueyed** [comment]
@mhartington 
Make sure you do not have `g:airline#extensions#disable_rtp_load = 1`, which skips loading the neomake airline extension.
Also, `'g:airline_extensions'` should not be set.
See also https://github.com/vim-airline/vim-airline/pull/1074.

**Comment by blueyed** [comment]
@mhartington 
Any feedback on how you solved it?

**Comment by mhartington** [comment]
I'm going to blame user error (my fault probably)


Looking good now! 

<img width="1680" alt="screen shot 2016-08-06 at 1 41 49 pm" src="https://cloud.githubusercontent.com/assets/2835826/17458335/8f7bcaec-5bdb-11e6-89f2-f74edbd3d7c1.png">

**Comment by yevhen-m** [comment]
I don't have neomake status segment in my airline. Could somebody help?
```
" Neomake settings {{{
let g:neomake_python_enabled_makers = ['flake8']
" E501 -- line too long
" E402 -- import not at top of file
" E128 -- continuation line underindented
" E225 -- missing whitespace around operator
" E231 -- missing whitespace after ','
" F403 -- import * used, unable to detect undefined names
" F405 -- name may be undefined, or defined from * imports
" E126 -- indentation error
let g:neomake_python_flake8_maker = { 'args': ['--ignore=E501,E402,E128,E225,E231,F403,F405,E126'], }
let g:neomake_verbose = 0
autocmd! BufWritePost,BufEnter * Neomake
" }}}

" Airline settings {{{
let g:airline#extensions#whitespace#checks = []
let g:airline#extensions#hunks#enabled = 1
let g:airline#extensions#hunks#non_zero_only = 1
let g:airline#extensions#branch#displayed_head_limit = 13
let g:airline_section_warning = ''
let g:airline_section_error = ''
let g:airline#extensions#branch#format = 2
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#tabline#show_close_button = 0
let g:airline#extensions#tabline#buffer_nr_show = 0
let g:airline_skip_empty_sections = 1
let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline#extensions#disable_rtp_load = 0
" let g:airline#extensions#syntastic#enabled = 0
let g:airline_detect_iminsert=1
let g:airline#extensions#tmuxline#enabled = 0
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_tabs = 1
let g:airline#extensions#tabline#show_buffers = 0
let g:airline#extensions#tabline#show_tab_nr = 0
let g:airline#extensions#tabline#show_splits = 1
let g:airline#extensions#wordcount#enabled = 0
let g:airline_powerline_fonts = 1
let g:airline_theme='bubblegum'
" }}}

nvim 0.1.4
```

**Comment by blueyed** [comment]
@yevhen-m 
Check https://github.com/neomake/neomake/issues/617.

I am not using airline myself and would consider this part therefore being not maintained currently.
