### ISSUE TITLE
[QUESTION] How the change clangcheck to use -std=c++2a?

### ISSUE THREAD

**Issue by Godnyx** [neomake/neomake#2521]
I don't have any problem, I just wanted to ask how I can change clangcheck to use another C++ standard like C++2a? Also can I change the include directories? In general, I couldn't find any info on how to change the settings of clangcheck. Feel free to close this if you want. Thanks a lot in advance!

**Comment by Godnyx** [comment]
Found it!

**Comment by blueyed** [comment]
@Godnyx please consider providing your findings/solution for reference.
