### ISSUE TITLE
option for using quickfix list only

### ISSUE THREAD

**Issue by wsdjeg** [neomake/neomake#2539]
Hi @blueyed, thanks for working on this project, and we use neomake as default linter in spacevim, and someone request a new feature: using only one neomake list windows. https://github.com/SpaceVim/SpaceVim/issues/4276

we need an option to use quickfix list only.

**Comment by FelipeLema** [comment]
the original issue is no longer visible, btw

**Comment by wsdjeg** [comment]
Hi,

no, I think this issue has not been solved.

**Comment by wsdjeg** [comment]
@blueyed this issue already exists.
