### ISSUE TITLE
Neomake: Exe (ruby-lint) of maker rubylint is not executable. 

### ISSUE THREAD

**Issue by ghost** [neomake/neomake#2559]
### Expected behavior
The plugin run perfectly.

### What Happened
![image](https://user-images.githubusercontent.com/96674887/232160050-51fd8a78-29c8-4b85-ad94-331c137af63c.png)

### Steps to reproduce
Install SpaceVim, add the Ruby Language Layer, try to save any .rb file.

#### Neomake debug information

Async support: 1
Current filetype: ruby
Windows: 0
[shell, shellcmdflag, shellslash]: ['/bin/bash', '-c', 0]
makeprg=make

##### Enabled makers

For the current filetype ("ruby", used with :Neomake):
 - rubylint
   - args: ['--presenter', 'syntastic']
   - auto_enabled: 0
   - errorformat: '%f:%t:%l:%c: %m'
   - exe: 'ruby-lint'
   - remove_invalid_entries: 1
   - ERRORS:
     - maker's exe (ruby-lint) is not executable.
NOTE: you can define g:neomake_ruby_enabled_makers to configure it (or b:neomake_ruby_enabled_makers).

For the project (used with :Neomake!):
 - makeprg
   - append_file: 0
   - args: []
   - auto_enabled: 1
   - errorformat: '%*[^"]"%f"%*\D%l: %m,"%f"%*\D%l: %m,%-G%f:%l: (Each undeclared identifier is reported only once,%-G%f:%l: for each function it appears in.),%-GIn file included from %f:%l:%c:,%-GIn file included from %f:%l:%c\,,%-GIn file included from %f:%l:%c,%-GIn file included from %f:%l,%-G%*[ ]from %f:%l:%c,%-G%*[ ]from %f:%l:,%-G%*[ ]from %f:%l\,,%-G%*[ ]from %f:%l,%f:%l:%c:%m,%f(%l):%m,%f:%l:%m,"%f"\, line %l%*\D%c%*[^ ] %m,%D%*\a[%*\d]: Entering directory %*[`'']%f'',%X%*\a[%*\d]: Leaving directory %*[`'']%f'',%D%*\a: Entering directory %*[`'']%f'',%X%*\a: Leaving directory %*[`'']%f'',%DMaking %*\a in %f,%f|%l| %m'
   - exe: 'make'
   - version information (/usr/sbin/make --version): GNU Make 4.4.1
     Built for x86_64-pc-linux-gnu
     Copyright (C) 1988-2023 Free Software Foundation, Inc.
     License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
     This is free software: you are free to change and redistribute it.
     There is NO WARRANTY, to the extent permitted by law.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - output_stream: 'both'
 - remove_invalid_entries: 0
 - buffer_output: 1

###### New-style (dict, overrides old-style)

```
g:neomake: {
  'automake': {
    'ignore_filetypes': [
      'startify',
    ],
    'events': {
      'BufWritePost': {
        'delay': 0,
      },
    },
  },
}
b:neomake: unset
```

###### Old-style

```
g:neomake_cursormoved_delay = 300
g:neomake_echo_current_error = 0
g:neomake_error_sign = {'texthl': 'GruvboxRedSign', 'text': '✖'}
g:neomake_info_sign = {'texthl': 'GruvboxYellowSign', 'text': 'ⓘ'}
g:neomake_java_javac_delete_output = 0
g:neomake_open_list = 0
g:neomake_place_signs = 1
g:neomake_ruby_enabled_makers = ['rubylint']
g:neomake_ruby_rubylint_remove_invalid_entries = 1
g:neomake_verbose = 0
g:neomake_virtualtext_current_error = 0
g:neomake_warning_sign = {'texthl': 'GruvboxYellowSign', 'text': '⚠'}

```

#### :version

```
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

#### :messages

```
NERDTree: CWD is now: /home/isac
```

**Comment by ghost** [comment]
I put g:neomake_ruby_enabled_makers in my config file.

**Comment by blueyed** [comment]
You had `g:neomake_ruby_enabled_makers = ['rubylint']` there before explicitly, no? But no rubylint installed, or with another exe?
