### ISSUE TITLE
Project-only maker support

### ISSUE THREAD

**Issue by msoucy** [neomake/neomake#256]
There should probably be a way to specify project-only makers. This is useful for makers that are obviously meant to be used project-wide (`cabal` and `dub`, for instance) vs file-specific (`ghc` and `dmd`)

**Comment by blueyed** [comment]
You could use https://github.com/embear/vim-localvimrc and (maybe) https://github.com/tpope/vim-projectionist/ to configure this dynamically.

**Comment by msoucy** [comment]
I'm not looking for a maker that's configured only for one specific project, I'm looking for makers than can only be run project-wide (with `:Neomake!`, like a "build entire project") vs on the current file (with `:Neomake`, like a single-file linter)

**Comment by msoucy** [comment]
This was implemented in d0727dcb66aad722737ca37ff6dbc4b7c1958a18
