### ISSUE TITLE
jshint not finding all errors

### ISSUE THREAD

**Issue by jrock2004** [neomake/neomake#258]
I am trying to figure out a problem I am seeing with jshint. If I try to use a variable that is not defined, should jshint throw that error?

```
""""" NeoMake
let g:neomake_javascript_jshint_maker = {
    \ 'args': ['--verbose'],
    \ 'errorformat': '%A%f: line %l\, col %v\, %m \(%t%*\d\)',
\ }
let g:neomake_javascript_enabled_markers = ['jshint', 'jscs']
```

Does jshint not find those type of errors?

**Comment by indiesquidge** [comment]
@jrock2004 if you run `jshint` from the command line does it produce errors in the output?

**Comment by blueyed** [comment]
Closing due to missing feedback.
Please feel free to re-open, of course.
