### ISSUE TITLE
status line funcref has already been applied

### ISSUE THREAD

**Issue by s0undt3ch** [neomake/neomake#270]
![screenshot_20160105_135106](https://cloud.githubusercontent.com/assets/300048/12116760/07b44d5c-b3b4-11e5-99b4-b06f2f0e6d79.png)

**Comment by s0undt3ch** [comment]
![screenshot_20160105_135106](https://cloud.githubusercontent.com/assets/300048/12116760/07b44d5c-b3b4-11e5-99b4-b06f2f0e6d79.png)

**Comment by blueyed** [comment]
It was moved over to airline, closing.
