### ISSUE TITLE
Not running checkers for all filetypes

### ISSUE THREAD

**Issue by alexlafroscia** [neomake/neomake#272]
I use a [`jsx` addon](http://github.com/mxw/vim-jsx) that sets all JS files to the filetype `javascript.jsx`, so that I get syntax highlighting for JSX in all JS files.  However, for some reason it seems like _only_ the JSX file checkers are getting run, despite the following being in my Vim configuration:

``` viml
let g:neomake_javascript_enabled_makers = ['jshint', 'jscs']
```

So, with the given configuration, `jscs` doesn't get by default.  However, if I do the following instead

``` viml
let g:neomake_javascript_enabled_makers = ['jshint', 'jscs']
let g:neomake_jsx_enabled_makers = ['jshint', 'jscs']
```

it works fine.  In this `.js` file, the `set filetype` returns `filetype=javascript.jsx`.

**Comment by hpurmann** [comment]
Do you know how to set up standard with `babel-eslint` parser to have neomake lint es6 code as well?

**Comment by KevinSjoberg** [comment]
Any update on this? /cc @blueyed

**Comment by davidosomething** [comment]
Agreed this should be fixed for multi-FT files
As a stopgap you can get it to work by copying the maker config from the main ft (`jsx`) to the sub f (`javascript`)

so define `g:neomake_jsx_jshint_maker = { same as in autoload/neomake/makers/javascript }`

OR switch the ft to `jsx.javascript` (if the other plugins you're using support multi-ft correctly this will be fine).

**Comment by wejrowski** [comment]
I have this problem with html files - it's not running on html files with JS in script tags.

**Comment by blueyed** [comment]
@wejrowski 
What &ft are you using?
If it is only "html" then it's a different issue: it will only run checkers for "html".

As for using `javascript.jsx` etc: only makers from all the filetypes are being considered: https://github.com/neomake/neomake/blob/914609831b904f84f296826c2ad8f99d4bc7ce23/autoload/neomake.vim#L303-L304.

I am not sure if that makes sense though.

See also https://github.com/neomake/neomake/issues/572.

**Comment by wejrowski** [comment]
I ended up figuring it out and needing to define the maker args as is done by default behind the scenes.. not very clear.. I just had to copy the js one to html:

```vim
let g:neomake_html_eslint_maker = {
        \ 'args': ['-f', 'compact'],
        \ 'errorformat': '%E%f: line %l\, col %c\, Error - %m,' .
        \ '%W%f: line %l\, col %c\, Warning - %m'
        \ }
```

**Comment by blueyed** [comment]
@wejrowski that is covered by / being discussed in #572 then.
