### ISSUE TITLE
Is there a way to specify the working (build) directory?

### ISSUE THREAD

**Issue by sztomi** [neomake/neomake#273]
I have a C++ project with a out-of-source build. I would like to build the project with neomake. Ideally it would do `cd build && make -j6`. Note that the build directory is relative to the project root, not the current file.  Is there a way to do this?

**Comment by c-brenn** [comment]
you can specify the directory you want the maker to run in using the `cwd` option.
Here's the example from `:help neomake-makers-cwd`

```
        let g:neomake_my_example_maker = {
        \ 'exe': 'pwd',
        \ 'cwd': '%:p:h'
        \ }
```

`%:p:h` gets the directory the file you're editing is in if I recall correctly.

**Comment by blueyed** [comment]
"getcwd()" would be the default.
IIRC "cwd" can (or at least could) be a function/callback.

**Comment by blueyed** [comment]
There should be `neomake#utils#FindGlobFile` by now to help you with finding the root.
https://github.com/neomake/neomake/blob/649e78f4d3924f44969cbbcd554ec5160d8819d8/autoload/neomake/utils.vim
