### ISSUE TITLE
Go test files are not checked

### ISSUE THREAD

**Issue by jonhoo** [neomake/neomake#282]
If you run `:Neomake` with a Go test file open (i.e., a file ending in `_test.go`), no errors will be reported. This is because `go build` will not build test files. Syntastic works around this by [testing the filename](https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/go/go.vim#L54), and calling [`go test -c`](https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/go/go.vim#L61) instead.

**Comment by jonhoo** [comment]
Note also that after calling `go test`, some [cleanup](https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/go/go.vim#L89) is required.

**Comment by wsantos** [comment]
were you able to make it work ?

**Comment by jonhoo** [comment]
I haven't built this -- just filed the request.

**Comment by blueyed** [comment]
go-test is used by now.
