### ISSUE TITLE
'Checker' complete with exit code 1

### ISSUE THREAD

**Issue by darnir** [neomake/neomake#286]
For any filetype, when I run "Neomake, I get the following message in the statusbar:

    <<checker>> compete with exit code 1

Replace `<<checker>>` with name of relevant checker. However, I don't get any quickfix window to see the actual errors.

**Comment by antoyo** [comment]
I have the same issue with the `hlint` checker but sometimes, I see the quickfix window.

**Comment by blueyed** [comment]
This might happen if the linter fails by itself, and does not report any errors.  Try to run it manually and/or use `:let neomake_verbose = 1`.

**Comment by antoyo** [comment]
If it run it manually, I get the errors but I would like to see them in neovim.

**Comment by blueyed** [comment]
What does `:let neomake_verbose = 3` give you?
Maybe it's not invoked in the same way, and/or not available inside of vim etc.

**Comment by antoyo** [comment]
@blueyed I'll try this command the next time it happens (I only have this issue from time to time).

**Comment by antoyo** [comment]
With this command, all I see is the following:

```
"src/Escape.hs" 460L, 21114C written
Neomake: Starting: hlint […]/src/Escape.hs
Press ENTER or type command to continue
```

And typing `:messages` shows me the following:

```
"src/Escape.hs" 460L, 21114C written
Neomake: Starting: hlint […]/src/Escape.hs
Neomake: hlint stdout: […]/src/Escape.hs:336:13: Suggestion: Redundant bracket
Neomake: hlint stdout: Found:
Neomake: hlint stdout:   (traceShow lastTrueStatement) $
Neomake: hlint stdout:     statementEscapes lastTrueStatement || lastFalseStatementEscapes
Neomake: hlint stdout: Why not:
Neomake: hlint stdout:   traceShow lastTrueStatement $
Neomake: hlint stdout:     statementEscapes lastTrueStatement || lastFalseStatementEscapes
Neomake: hlint stdout:
Neomake: hlint stdout: 1 hint
Neomake: hlint stdout:
Neomake: hlint stdout done.
Neomake: hlint processing 10 lines of output
Neomake: hlint complete with exit code 1
Neomake: File-level errors cleaned in buffer 16
```

This looks ok.

**Comment by blueyed** [comment]
Then it's probably related to the errorformat setting for this maker not handling this correctly.

@antoyo 
I suggest creating a new issue with the information from above, and state that it's about the `hlint` maker.

**Comment by blueyed** [comment]
Closing this in favor of #339.

@darnir 
Please create a new issue if you're still getting this (and it's not with hlint).
