### ISSUE TITLE
No output from `:Neomake!` (with makeprg)

### ISSUE THREAD

**Issue by JustAPerson** [neomake/neomake#294]
Hi,

leaving `makeprg` and `errorformat` unchanged from the neovim defaults should cause `:Neomake!` to run any makefile in the working directory. However, no output is emitted.

Consider this makefile

``` make
run:
    echo test
```

When running `:make` the following is emitted to the quickfix window:

```
echo test
test
```

But nothing is emitted to the quickfix window after running `:Neomake!`

**Comment by blueyed** [comment]
Confirmed.
When adding `false` though to the target, the following appears:

> Makefile|5| recipe for target 'run' failed

Did this work for you before?

**Comment by blueyed** [comment]
Seems to be fixed by now.

I get the expected output after `:Neomake!` and `:copen`.
