### ISSUE TITLE
csslint on sass files

### ISSUE THREAD

**Issue by jrock2004** [neomake/neomake#295]
Trying to get neomake to run css lint on my scss files. But nothing happens. If I run outside of vim, csslint against the scss file it finds errors. Any thoughts?

```
""""" NeoMake
let g:neomake_javascript_jshint_maker = {
    \ 'args': ['--verbose'],
    \ 'errorformat': '%A%f: line %l\, col %v\, %m \(%t%*\d\)',
\ }
let g:neomake_scss_csslint_maker = {
    \ 'args': ['--verbose'],
    \ 'errorformat': '%A%f: line %l\, col %v\, %m \(%t%*\d\)',
\ }
let g:neomake_javascript_enabled_markers = ['jshint', 'jscs']
let g:neomake_scss_enabled_markers = ['csslint']
```

**Comment by sbdchd** [comment]
Are you sure --verbose is a valid argument for csslint?

https://github.com/CSSLint/csslint/wiki/Command-line-interface#options

**Comment by jrock2004** [comment]
So I removed verbose line and it still does not work

**Comment by sbdchd** [comment]
`errorformat` must correspond to the output of the csslint.

I think it would make sense to copy the `errorformat` for csslint in the css.vim maker file.

[See here](https://github.com/benekastah/neomake/blob/51c3e592453b0ca26a3d23482d9b8c9b7a61a41f/autoload/neomake/makers/ft/css.vim#L5)

**Comment by blueyed** [comment]
scsslint gets used by now in `autoload/neomake/makers/ft/scss.vim`, which is probably better than `csslint` anyway in this regard?!

Not sure if it has been like that when this issue has been created, but it is missing feedback anyway, therefore closing it for now.
