### ISSUE TITLE
Improve NeomakeInfo

### ISSUE THREAD

**Issue by siddharthist** [neomake/neomake#302]
Similar to `SyntasticInfo`, it would be great to add a function to Neomake to check which makers are active for the current buffer (and other information as well, maybe which preconfigured makers could be found on the user's `PATH`, etc.).

**Comment by blueyed** [comment]
We have NeomakeInfo by now.

Does it work for you?
Feel free to suggest enhancements to it.

> which preconfigured makers could be found on the user's PATH 

Can you elaborate? Does Syntastic have that?

**Comment by siddharthist** [comment]
@blueyed I'm no longer using neomake, I've switched to [Spacemacs](http://spacemacs.org/). Best of luck!

**Comment by blueyed** [comment]
Thanks for reporting back.
Spacemacs is tempting.. ;)
