### ISSUE TITLE
Add continuous integration build

### ISSUE THREAD

**Issue by siddharthist** [neomake/neomake#303]
It would be nice to have just a basic syntax-checking continuous integration build for this repo, maybe one that just executes vint on all `*.vim` files. I'm happy to write this, would you accept a PR to this effect @benekastah?

My preferred option is Drone CI since you can test locally as well as after pushing your commit, but I'm also happy to write one using Travis CI.

**Comment by theamazingfedex** [comment]
Go ahead and make the pull request, and I'll do my best to get the author to merge it in. Link me to it once you do, because I think it's a great idea. Breaking changes suck.

**Comment by benekastah** [comment]
Sorry for the late reply. I'd happily merge such a PR in :)

**Comment by siddharthist** [comment]
Sorry for the duplicated references, I amended my commit a bunch as to not screw up the git history. PR is in!

**Comment by blueyed** [comment]
@benekastah 
This has never been activated, has it?

Should we use both vimlint/vimlparser and vint?
(with vint we can configure policies, so that it could also check for warnings and style issues - and not just errors; https://github.com/Kuniwak/vint/wiki/Vint-linting-policy-summary)

**Comment by benekastah** [comment]
@blueyed I don't have a lot of experience with vimscript linters. I tried to set one up several times and it didn't work for me for whatever reason. So I'm happy to go with whatever you suggest.

**Comment by blueyed** [comment]
@benekastah 
I'd go for Vint currently.

I am also in the process of setting up tests using https://github.com/junegunn/vader.vim.

As a first step I've activated the Travis integration now.

**Comment by blueyed** [comment]
I am working on improved Travis integration in https://github.com/neomake/neomake/pull/434.

Closing this issue for now.
