### ISSUE TITLE
Puppet maker behaving oddly

### ISSUE THREAD

**Issue by daenney** [neomake/neomake#312]
I have a Puppet file in which I deliberately introduce a Puppet syntax error and a linter error.

The linter works fine and gives me the lint error, the syntax error however does not show up. If I then run a `Neomake! puppet` I see `Neomake: puppet complete with exit code 0`. Writing that same file again (without further modifying it) then causes `Neomake: puppet complete with exit code 1` to show up but still nothing in the gutter, quick fix or location list.

Unfortunately I have no idea how to debug this. Any tips?

**Comment by daenney** [comment]
Appears to be related to #286

**Comment by tylerjl** [comment]
It looks like I _may_ have come across the same issue that I submitted #626 for, I'd be curious whether this also fixes your problem.

**Comment by blueyed** [comment]
#626 is in.
Assuming this is fixed.

**Comment by blueyed** [comment]
Otherwise, please see https://github.com/neomake/neomake/blob/28395f788fbd99dbe96180b2f4daeef8c3d10990/README.md#logging for logging.
