### ISSUE TITLE
Need option to disable CursorMoved autocmd

### ISSUE THREAD

**Issue by chemzqm** [neomake/neomake#313]
For the sake of performance.

**Comment by bstaletic** [comment]
@blueyed 
I have a branch on my fork of Neomake that implements one way doing this. It is done by using `if get(g:,'neomake_enable_cursormoved_autocmd',1)` to dictate if the CursorMoved autocmd should be defined. Is this thte way to do it, or would wrapping the body of `neomake#CursorMoved()` function in the same if statement be a better alternative?

**Comment by blueyed** [comment]
@bstaletic 
Check out https://github.com/neomake/neomake/projects/1.
I would not like to have multiple vars to configure this etc.

I think we could have some approach where there is a default config (with the CursorMoved handling improved), which could be disabled - e.g. `neomake_setup_default_autocmds` then.
After all, currently you could just delete and override the `neomake` augroup - but I do not really recommend that, since you will not get future improvements then that easily.

**Comment by bstaletic** [comment]
> Check out https://github.com/neomake/neomake/projects/1.

That is actually the link that brought me to this specific issue. 

> I think we could have some approach where there is a default config (with the CursorMoved handling improved), which could be disabled - e.g. `neomake_setup_default_autocmds` then.

Are you saying that you'd prefer a solution that would take care of most, if not all, of the issues in the TODO list and should be fairly simple for users to configure? That would be great, but to be honest, I'm not sure how feasible that is. I personally prefer doing that sort of things one small step at a time and when the occasion arises refactor what is needed.

> delete and override the `neomake` augroup

I agree that doing that is generally a bad idea.

**Comment by mhinz** [comment]
Maybe it would be simpler to have optional callbacks that are executed before and after `:Neomake`?

Something like:

```vim
function! s:neomake_start() abort
  set eventignore+=CursorMoved
endfunction

function! s:neomake_end() abort
  set eventignore-=CursorMoved
endfunction

let g:neomake_callback_start = function('s:neomake_start')
let g:neomake_callback_end  = function('s:neomake_end')
```

**Comment by blueyed** [comment]
I like the idea of callbacks, and we could do so through User autocommands (we have a good wrapper for that already).

We have `NeomakeFinished` already, and could add `NeomakeStarted`:

```vim
augroup my_neomake_config
  au!
  au NeomakeStarted * set eventignore+=CursorMoved
  au NeomakeFinished * set eventignore-=CursorMoved
augroup END
```

However, that changes global settings, which is not cool!

@bstaletic 
> Are you saying that you'd prefer a solution that would take care of most, if not all, of the issues in the TODO list and should be fairly simple for users to configure?

No, but we should keep the whole project in mind.

> That would be great, but to be honest, I'm not sure how feasible that is. I personally prefer doing that sort of things one small step at a time and when the occasion arises refactor what is needed.

Sure, but let's not add global vars to disable some specific (internal) autocommand.

**Comment by bstaletic** [comment]
@blueyed 
Sorry for the late reply.

Would something like this be a viable option:
```VimL
function NeomakeStartStop()
    let s:save_eventignore=&eventignore
    if neomake#ListJobs() != 0
        set eventignore-=CursorMoved
    else
        let &eventignore=s:save_eventignore
   endif
endfunction
augroup Neomake
    autocmd NeomakeStarted,NeomakeFinished * call NeomakeStartStop()
augroup END
```
If I have not made a mistake here, this would ignore CursorMoved event as long as there are any Neomake jobs running. I know this is not ideal. I thought of making two functions, one for NeomakeFinished and the other for NeomakeStarted, but I couldn't figure out how to make it work without touching the global scope.

**Comment by blueyed** [comment]
@bstaletic 
btw: you should use `len(neomake#GetJobs())` - `ListJobs` returns `''` always.

I think we should not touch `eventignore` at all.

But instead fix performance issues, and fix processing logic.

We have this currently (or rather soonish):

```vim
let s:last_cursormoved = [0, 0]
function! neomake#CursorMoved() abort
    let l:line = line('.')
    if s:last_cursormoved[0] != l:line || s:last_cursormoved[1] != bufnr('%')
        let s:last_cursormoved = [l:line, bufnr('%')]
        if g:neomake_place_signs
            call neomake#signs#PlaceVisibleSigns()
        endif
        call neomake#EchoCurrentError()
    endif
endfunction
```

The placement of signs could be avoided with #471 for example.

And then I could imagine that "display error under cursor" could become a setting.

**Comment by blueyed** [comment]
btw: there is a `neomake_echo_current_error` setting already, which basically short-circuits the CursorHold event.
But I can see that it makes sense to only dynamically add autocommands, when they make sense: i.e. when there are no errors, we should not hook into `CursorMoved` etc.

**Comment by blueyed** [comment]
Considering this as being fixed with https://github.com/neomake/neomake/pull/909 being merged.
