### ISSUE TITLE
Neomake creating .gch files in my working directory

### ISSUE THREAD

**Issue by RenatoUtsch** [neomake/neomake#314]
Hi,

I am using neomake with neovim on a MacBook Pro with OS X El Capitain. However, sometimes when I open .hpp files neomake creates .gch files alongside them (for example, if I open a Kernel.hpp file, it sometimes creates a Kernel.hpp.gch file). This curiously doesn't happen every time.

How can I disable this? The only configurations I currently have related to neomake are:

```
let g:neomake_c_clang_maker = {
    \   'args': ['-std=c11', '-Wall', '-Wextra', '-Werror', '-Wno-unused-parameter'
    \   ] }

let g:neomake_cpp_clang_maker = {
    \   'args': ['-std=c++14', '-Wall', '-Wextra', '-Werror', '-Wno-unused-parameter'
    \   ] }
```

**Comment by iguessthislldo** [comment]
This has been bothering me for a while too. I looked into neomake to see if there was a difference between what me and it were setting for the clang arguments. The difference was `'-fsyntax-only'` in c.vim. I added that and it stopped making the gch files in my directories.

**Comment by RenatoUtsch** [comment]
Nice. Will try it.

But this is more a hack than a fix. Neomake creates temporary files from other languages too. For example, it also creates .class files alongside my .java ones. Maybe there is a way to change where these temp files are created?

**Comment by wsdjeg** [comment]
@RenatoUtsch I will change the path of `.class`

**Comment by blueyed** [comment]
`-fsyntax-only` is used by now.
Not sure about the Java maker(s), but there should be a separate issue for it then.
