### ISSUE TITLE
wrong maker invoked on default window when multiple tabs open

### ISSUE THREAD

**Issue by leemhenson** [neomake/neomake#315]
I've got three tabs open in my session:

1. some sql files in various splits
2. some ruby files in various splits
3. `nvimrc`

If I:

1. switch to `nvimrc`
2. save the session and quit
3. restart neovim

...I see my `nvimrc` file has lots of warnings and errors from `mri` and `rubocop` (the ruby linters). If I then:

1. switch to the ruby tab
2. save session and quit
3. restart neovim
4. switch to the nvimrc tab

I see no errors or warnings. 

It feels like a race condition of some kind, because if I switch from:

```
autocmd! BufWinEnter * Neomake
autocmd! BufWritePost * Neomake
```

to

```
autocmd! VimEnter * Neomake
autocmd! BufWritePost * Neomake
```

then I don't see that behaviour (but obviously I have to write a file to see new lint, which is not ideal).

**Comment by blueyed** [comment]
This behavior should have improved by now (although there are still issues in that regard).
Closing this one for now, please re-open in case I'm wrong.
