### ISSUE TITLE
Asynchronous make in (ordinary) Vim?

### ISSUE THREAD

**Issue by lifepillar** [neomake/neomake#319]
Recently, Vim has added support for spawning jobs asynchronously (`:h job_start()`). How about extending Neomake to support asynchronous make in Vim, too?

**Comment by prabirshrestha** [comment]
+1 I would also love to see neomake work asynchronously in ordinary vim using jobs.

I have created async.vim so we don't have to worry about the internals and just use a single api for both vim and neovim. https://github.com/prabirshrestha/async.vim

**Comment by jpleau** [comment]
@prabirshrestha do you have a fork of neomake that makes use of your plugin?

**Comment by saaguero** [comment]
I give it a quick try and seems to be working:

https://github.com/saaguero/neomake

It needs a good refactoring though.

**Comment by blueyed** [comment]
@saaguero 
Looks quite decent already! :)

**Comment by blueyed** [comment]
We have this by now, although there are still issues etc - and apparently the PR was shot, needed to be fixed and now the problems are left to the maintainers (which is just me).
Sorry for ranting, but this can be closed at least.

See https://github.com/neomake/neomake/issues/694 and https://github.com/neomake/neomake/pull/697 for follow-ups.

FWIW, I am a bit upset: I do not use Vim nor Windows myself, but still appear to be the one to triage, fix and forward it to Vim eventually.  It would be nice if people that are using it would step up to helping out!
