### ISSUE TITLE
Should stop running when closing Neovim

### ISSUE THREAD

**Issue by blueyed** [neomake/neomake#329]
I've noticed that neomake will keep running after Neovim has been closed.

This is not necessarily from `:wq`, but processes that had been called earlier (manually and/or through `BufWritePost`).

This is somehow related to https://github.com/benekastah/neomake/issues/309, which is about not running any checks on exit.

With some `echom` statements in the plugin, this is what you might get after closing:

```
neomake_open_list
file_mode
lwindow
neomake#ProcessCurrentBuffer() 9
Error detected while processing function UltiSnips#FileTypeChanged[1]..provider#python3#Call:
line   18:
Invalid channel "1"
Error detected while processing function UltiSnips#FileTypeChanged[2]..provider#python3#Call:
line   18:
Invalid channel "1"
neomake#ProcessCurrentBuffer() 9
neomake_open_list
file_mode
lwindow
```

Maybe a command like `NeomakeCancelJobs` would be helpful and could be used in a `QuitPre` autocommand?  It would stop all running jobs, similar to `:NeomakeCancelJob`, which only cancels a single job (that you need to specify).

See also https://github.com/neovim/neovim/issues/4666 for a request to know if (Neo)Vim is exiting.

**Comment by lucc** [comment]
I am using this in my init.vim and it seems to solve the issue (nvim not returning after `:wq` even  though the screen is back to the way it was before nvim started):
```vim
augroup LucNeoMake
  autocmd!
  autocmd BufWritePost * Neomake
  autocmd VimLeave * NeomakeCancelJobs
augroup END
```

Should something like this (at least the second autocmd) be added to core neomake? Or should it be mentioned in the docs?

**Comment by blueyed** [comment]
@lucc 
Should not be necessary anymore: https://github.com/neomake/neomake/blob/0c5bb41a16f46e414dd0d5815b5f88273703b165/plugin/neomake.vim#L76, which cancels all makes: https://github.com/neomake/neomake/blob/0c5bb41a16f46e414dd0d5815b5f88273703b165/autoload/neomake.vim#L1240-L1245.

Were you using master, but still had the need for that?

**Comment by blueyed** [comment]
Since I am the OP, I think we can close this.. ;)

@lucc 
Still interested in your response, of course.

**Comment by lucc** [comment]
looks like I didn't update my plugins for a while. It is fixed without my custom autocmd.
