### ISSUE TITLE
statusline functions return nothing

### ISSUE THREAD

**Issue by nhooyr** [neomake/neomake#336]
The functions for the status line return nothing for me, no matter what. No clue what's wrong. The counts functions all return empty as well even though there are errors in the loclist and quick fix list.

```vim
call plug#begin('.')
Plug 'benekastah/neomake'
call plug#end()
set statusline+=%{neomake#statusline#QflistStatus('qf:\ ')}%{neomake#statusline#QflistStatus('qf:\ ')}
```

I just tested by opening the neovim source, deleting a few lines for some errors and nothing changed on the status line after I ran `:Neomake!`

**Comment by motdef** [comment]
I have the same problem. ```neomake#statusline#LoclistStatus``` returns an empty string even if I deliberately introduce errors to populate the location list.

**Comment by SageEx** [comment]
Same here.

**Comment by SageEx** [comment]
Any updates on this ?

**Comment by thalesmello** [comment]
I suspect it has to do with the maker syntax.

I get error counts for errors in Python files, but not error counts for JavaScript files (using 'standard' maker).

Analyzing the maker syntax for standard:
```
function! neomake#makers#ft#javascript#standard()
    return {
        \ 'errorformat': '  %f:%l:%c: %m'
        \ }
endfunction
```

Analyzing the syntax for pep8:
```
function! neomake#makers#ft#python#python()
    return {
        \ 'args': [ '-c',
            \ "from __future__ import print_function\r" .
            \ "from sys import argv, exit\r" .
            \ "if len(argv) != 2:\r" .
            \ "    exit(1)\r" .
            \ "try:\r" .
            \ "    compile(open(argv[1]).read(), argv[1], 'exec', 0, 1)\r" .
            \ "except SyntaxError as err:\r" .
            \ "    print('%s:%s:%s: %s' % (err.filename, err.lineno, err.offset, err.msg))"
        \ ],
        \ 'errorformat': '%E%f:%l:%c: %m',
        \ }
endfunction
```
The error message stards with a `%E`.
In fact, if I place

```
let g:neomake_javascript_standard_maker = { 'errorformat': '%E %f:%l:%c: %m' }
```

In my Vimfile, the statusline functions start working.

Therefore, I think there is a problem with Neomake regarding the case when there is no Warning nor Error indication in the `errorformat`. Maybe it should default to error or something like that.

**Comment by SageEx** [comment]
The development seems to have stated again. Please fix this issue.
Thanks.

**Comment by blueyed** [comment]
@SageEx 
What maker(s) are you using?

Defaulting to handle entries without any type as errors seems sensible.

**Comment by SageEx** [comment]
I am using the standard clang maker.

On Mon, May 30, 2016 at 7:30 AM, Daniel Hahler Ⓥ <notifications@github.com>
wrote:

> @SageEx <https://github.com/SageEx>
> What maker(s) are you using?
>
> Defaulting to handle entries without any type as errors seems sensible.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/neomake/neomake/issues/336#issuecomment-222397898>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGz56yw2pL3KAGZjk_1hVsIo8qQfRf8vks5qGkTCgaJpZM4HqGGb>
> .
>



-- 
Arindam Banerjee

**Comment by ebkalderon** [comment]
Neither the clang maker nor the rustc maker output anything when `neomake#statusline#LoclistStatus` is called. Somewhat annoying.

**Comment by shvenkat** [comment]
@thalesmello @blueyed I have a PR (#531) to fix this issue, using your suggestion of treating entries of unknown type as errors. The signcolumn already does this, so this fix extends that treatment to the statusline.

**Comment by blueyed** [comment]
@ebkalderon 
As for `rustc` it should have a type for errors: https://github.com/neomake/neomake/blob/08375e0c5fe8a90d0346128379d7286e042afd82/autoload/neomake/makers/ft/rust.vim#L12-L14.  Please file a separate issue with the output of `echom getloclist(0)`.

As for the PR #531, there is #515 where we should discuss it.
I am inclined to fix the `errorformat` definitions instead.  PRs for that are welcome.  See https://github.com/neomake/neomake/pull/532.

**Comment by blueyed** [comment]
In general, please check `echom getloclist(0)` to see if there is a `type` for the entries - and if the entries are there at all.

**Comment by shvenkat** [comment]
@blueyed I've close #531 and opened #533 to fix the errorformat.

**Comment by blueyed** [comment]
I did not expect it to get closed based on the PR's description (https://github.com/neomake/neomake/pull/533)..

But after all, I would say that we should track this for the different makers separately.

In case you are affected by this issue, please create a new issue mentioning which maker it is and additional information, like the output of `echo getloclist(0)`.  A PR to fix it would be more welcome of course, see #533 and #532 for ways how to fix it.

I am closing this issue therefore for now.

**Comment by ebkalderon** [comment]
@blueyed Will do. Thanks for the guidance!
