### ISSUE TITLE
Neomake! does not update airline warnings

### ISSUE THREAD

**Issue by mmlb** [neomake/neomake#344]
#46 is marked closed but `Neomake!` still does not show signs if there are errors. Also seems to not update vim-airline either

**Comment by timfeirg** [comment]
what version of neovim/neomake/airline are you using? @mmlb 

I'm using NVIM v0.1.3-350-gc94575f and the signs are showing, airline status line is also updated, could you update everything and see if the problem still exists?

BTW setting `let g:neomake_place_signs=0` would disable the signs

**Comment by mmlb** [comment]
@timfeirg hmm after updating signs come up, but isn't updated. Any thoughts?

**Comment by blueyed** [comment]
@mmlb 
Does it only affect `Neomake!`, or `Neomake` also?
What is your airline config?
You could add some `echom` statement(s) in autoload/airline/extensions/neomake.vim to see what's going on (and if it gets loaded after all).

**Comment by mmlb** [comment]
Hey @blueyed sorry for taking so long getting back to you. `Neomake` correctly shows the error in the airline bar, `Neomake!` never does.

all my airline related stuff follows:

```vimL
Plug 'bling/vim-airline'
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tagbar#enabled = 1
let g:airline#extensions#whitespace#mixed_indent_algo = 2
let g:airline_theme = 'dark'
if !exists('g:airline_symbols')
	let g:airline_symbols = {}
endif
let g:airline_powerline_fonts = 1
```

I'll add some `echom`s and see if anything pops up, anything you think would be helpful?

**Comment by mmlb** [comment]
@blueyed airline neomake extension does seem to be getting called:
```                                                                                                                                                                              
in airline#extensions#neomake#init                                                                                                                                                                          
leaving airline#extensions#neomake#init                                                                                                                                                                     
in airline#extensions#neomake#apply                                                                                                                                                                         
w:airline_section_warning :: %{airline#util#wrap(airline#extensions#whitespace#check(),0)} %{neomake#statusline#LoclistStatus()}                                                                            
leaving airline#extensions#neomake#apply                                                                          
```

**Comment by kwinczek** [comment]
Apologies to hijack this issue with possibly not related issue, but I have noticed that no Airline status is updated when `g:neomake_open_list` is not set to `0`.

But even with that set to `0` I am still getting some odd behaviour for python files with following linters enabled: `python frosted pep8 pylint`.
If there is single warning - I can see W:1 in statusline.
If there also is a syntax error  - I can only see E:2, but now warning being displayed neither in statusline nor sign column.

I can confirm that both `airline#extensions#neomake#init` and `airline#extensions#neomake#apply` get called in last case.

I trigger Neomake by having that autcmd set `autocmd! BufWritePost,BufReadPost * Neomake`.

**Comment by michael-younkin** [comment]
I'm also using `Neomake!` and airline and neomake doesn't seem to be updating it.

**Comment by michael-younkin** [comment]
Workaround: as long as you don't care about whether Neomake uses the location list or quick fix list, you can just redefine the maker in your `init.vim`, add the option `append_file: 0`, and call it using the regular `:Neomake` command. This seems to behave in almost the same way as `:Neomake!`

**Comment by blueyed** [comment]
The problem appears to be that Neomake's airline extension only uses the location list (from `Neomake`) via `neomake#statusline#LoclistStatus()` and not `neomake#statusline#QflistCounts`.

A PR would be welcome.

**Comment by blueyed** [comment]
For me it looks like the API usage for Airline could be improved (currently it defines a part, but then does not use it?!).
And the part (`neomake`) should then also include `neomake#statusline#QflistStatus('Q:')`, where the `Q:` would be used as a prefix (to distinguish it from loclist counts).

**Comment by blueyed** [comment]
Check out https://github.com/neomake/neomake/pull/524 (untested and unfinished).

**Comment by blueyed** [comment]
This has been moved to airline now: https://github.com/vim-airline/vim-airline/pull/1275#issuecomment-251012822.

**Comment by euclio** [comment]
@blueyed I'm still only seeing the errors from `:Neomake` in airline if I call `:AirlineRefresh` manually. I do not have `g:neomake_open_list` set.

**Comment by blueyed** [comment]
@euclio 
Please file a new issue then, probably first here.
The important part will be if there are types defined for your errors (check `getloclist(0)`) etc - but please file a new issue, using the template.

**Comment by blueyed** [comment]
Oh. I missed that :AirlineRefresh works when called manually. No idea then.
Use Vim's :debug and :echom to see what is going on.
