### ISSUE TITLE
Constant spamming of E16: Invalid range: 2wincmd w

### ISSUE THREAD

**Issue by ironhouzi** [neomake/neomake#350]
This commit 319ffc79e58d64b147ce258d526cef6fbfbb887d broke neomake for me.

I get spammed with these messages contantly:

```
Error detected while processing function neomake#MakeHandler..<SNR>78_RegisterJobOutput..neomake#ProcessCurrentBuffer..<SNR>78_P
rocessJobOutput:
line   12:
E16: Invalid range: 2wincmd w
Error detected while processing function neomake#MakeHandler..<SNR>78_RegisterJobOutput..neomake#ProcessCurrentBuffer..<SNR>78_P
rocessJobOutput:
line   12:
E16: Invalid range: 2wincmd w
```
As you see they always come in pairs.

I've narrowed it down to this commit because when I comment out the code that was added between lines 406 - 408, the messages stop.

The code in question is this block:

```
if winnr() != a:maker.winnr
    let cur_window = winnr()
    let prev_window = winnr('#')
    exec a:maker.winnr.'wincmd w'
endif
```

I see that `a:maker.winnr` has the value of `2`, while `prev/cur_window` are both `1`.

I'm getting the error on python3 code and I always reproduce it by exiting the `:Gstatus` buffer from the fugitive plugin. I tried with both asm and c code, and wasn't able to reproduce the error.

The code block in question seems to fire too late as if it thinks that my `:Gstatus` buffer is still open, since that buffer will return `1` from calling `winnr()` and the main buffer `2`. But it fires when there's only one buffer and tries to move to a second non existing buffer.

Sorry for not making a more detailed report, but I really am under a time crunch. Hope this helps and let me know if there's anything I can do to help you debug.

Thanks for a really nice plugin.

**Comment by blueyed** [comment]
I am seeing this occasionally myself (and added the broken code, sorry!).

I've not really investigated, but it appears to be related to a job being processed for some buffer, but with a changed window layout.

**Comment by blueyed** [comment]
Also reported in #348 already.

**Comment by blueyed** [comment]
@ironhouzi 
Please try https://github.com/benekastah/neomake/pull/354 and report back how it works for you.

**Comment by ironhouzi** [comment]
No more errors. :+1: Thanks!

Even learned how to fetch/checkout a pull request from github.

**Comment by blueyed** [comment]
@ironhouzi 
Cool!  I've pushed some more commits to it, please update and keep evaluating.

**Comment by ironhouzi** [comment]
Still works fine when trying to reproduce the old bug. :+1:

**Comment by simonsmith** [comment]
Would be great to see that merged as I also see similar errors

**Comment by scribu** [comment]
Can also confirm that errors went away when I switched to #354.

**Comment by sodapopcan** [comment]
Just commenting since #354 has been open for over a month.  Any chance of weighing in here @benekastah?  I was getting spammed by these messages constantly until switching to @blueyed 's branch (I switch between zero and 1 splits often).  Huge respect and thanks for the work you put into this plugin but unfortunately, it's unusable in this state.  #354 totally fixes it.

**Comment by simonsmith** [comment]
Looks like neomake [needs a maintainer](https://github.com/benekastah/neomake/commit/320859c1224db0480ddb241dfaf0fb8e2b8a0446), so we might not see this fixed for a while :(

**Comment by sodapopcan** [comment]
Does this mean you are taking over this project, @blueyed?  Or at least temporarily?

**Comment by blueyed** [comment]
@sodapopcan 

> Does this mean you are taking over this project, @blueyed?

I am just helping out, and have now more freedom to do so.. :)

@simonsmith 
Thanks for referring to that commit, that helped get things going.

I'm glad that this issue could be fixed!

**Comment by simonsmith** [comment]
Great wor @blueyed, thanks
