### ISSUE TITLE
Go files outside outside CWD are built/vet'ted incorrectly

### ISSUE THREAD

**Issue by anupcshan** [neomake/neomake#358]
Example:

```
$ cat test/file.go 
package main

const T = 5

$ cat test/main.go 
package main

func main() {
	return T   // Should be a compile-time error
}
```

Fails when opening file outside CWD:
```
$ nvim test/main.go
```
`:NeoMake` **doesn't detect an error.**

Works when opening file in CWD:
```
$ nvim main.go
```
`:NeoMake` **detects `too many arguments to return`**

**Comment by hansrodtang** [comment]
#351 is relevant here. Adding a correct `cwd` property to all Go makers would probably do the trick.

**Comment by pengux** [comment]
@hansrodtang I tried to add that change in #351 manually but it doesn't fix the issue. But adding it also for `function! neomake#makers#ft#go#go()` seems to do the trick.

**Comment by hansrodtang** [comment]
Yes, that is what I said in the comment above.
Adding the changes in #351 to "all Go makers" like I said includes adding it to `neomake#makers#ft#go#go()` as well. Thanks for confirming it though.

**Comment by pengux** [comment]
There's an additional issue and that is navigating to the errors in the quickfix window doesn't work. It doesn't jump to the correct line in the buffer.

**Comment by mediocregopher** [comment]
Having the same issue as @pengux. If for example I have: `./foo/foo.go` in my project, and it has some kind of error in it, with the `cwd` fix the path which shows up in the location list is `./foo.go`, which isn't correct and causes a non-existent file to be opened. I think the fix in this case is relate the file paths to `cwd` if it was set, but I don't know what implications that would have for other kinds of cases.

**Comment by mediocregopher** [comment]
Just to follow up, I ended up using `mapexpr` to fix that issue. It's not super pretty, but it works. Here's an example of a maker I made to build tests (and therefore do static analysis on library packages):

```go
let g:neomake_go_gotest_maker = {
    \ 'exe': 'go',
    \ 'args': ['test', '-c', '-o', '/dev/null'],
    \ 'append_file': 0,
    \ 'cwd': '%:h',
    \ 'mapexpr': 'expand("%:h") . "/" . v:val',
    \ 'errorformat': '%f:%l: %m',
    \ }
```

**Comment by blueyed** [comment]
@mediocregopher 
Can you please create a PR for this?

It could also include the `cwd` fix, of course - probably based on the commit/work from https://github.com/neomake/neomake/pull/351.

**Comment by mediocregopher** [comment]
Made PR #410 with my fix as well as @gnanderson's
