### ISSUE TITLE
doc: link to `:h errorformat`

### ISSUE THREAD

**Issue by siddharthist** [neomake/neomake#369]
The README has an example that contains the following line:
```
'errorformat': '%A%f: line %l\, col %v\, %m \(%t%*\d\)',
```
but these different strings like `%A,%f,%m,%t,%*` are never explained! 

Could there be exhaustive documentation on the options?

**Comment by notantonia** [comment]
These are already part of (neo)vim's documentation. See `:h errorformat`.

**Comment by siddharthist** [comment]
@notantonia Thanks! Maybe we should point to that in the README, then?

**Comment by blueyed** [comment]
@siddharthist 
Good point.  Do you like to create a PR for that?
