### ISSUE TITLE
Error message gets cut off

### ISSUE THREAD

**Issue by notantonia** [neomake/neomake#370]
I'm using a custom maker for oberon in init.vim

```
let g:neomake_oberon_obc_maker = {
    \ 'exe' : 'obc',
    \ 'args': ['-x'],
    \ 'errorformat': '%W\"%f\"\, line %l: warning -- %m,' .
    \                '%E\"%f\"\, line %l: %m,' .
    \                '%Z>%p^%.%#,' .
    \                '%-G%.%#,',
    \ 'buffer_output' : 1
    \ }
let g:neomake_oberon_enabled_makers = ['obc']
```

The messages shown in `:lopen` are all cut off, e.g.:

```
1  file.m|130 col 4 error| 'notaprocedure' has not
2  file.m|33 col 12 warning| proc1
```

It works fine outside using `:make`:

```
let &errorformat="%W\"%f\"\\,\ line\ %l:\ warning\ --\ %m,"
    \."%E\"%f\"\\,\ line\ %l:\ %m,"
    \."%Z>%p^%.%#,"
    \."%-G%.%#"
set makeprg=obc\ -x\ %
```

doing `:copen` gives the full message (which I want)

```
1  file.m|130 col 4 error| 'notaprocedure' has not been declared
2  file.m|33 col 12 warning| proc1 is declared but not used or exported
```

`:Neomake!` also gives the full message.

How do I make it use the full message with just `:Neomake`?

**Comment by sbdchd** [comment]
Does the following still have the error?
I copied `&errorformat` to make sure it was equivalent.
```viml
let g:neomake_oberon_obc_maker = {
    \ 'exe' : 'obc',
    \ 'args': ['-x'],
    \ 'errorformat': "%W\"%f\"\\,\ line\ %l:\ warning\ --\ %m,"
        \."%E\"%f\"\\,\ line\ %l:\ %m,"
        \."%Z>%p^%.%#,"
        \."%-G%.%#",
    \ 'buffer_output' : 1
    \ }
let g:neomake_oberon_enabled_makers = ['obc']
```

**Comment by blueyed** [comment]
Is it related to using `buffer_output`?  Try removing that setting.

**Comment by blueyed** [comment]
Try also `remove_invalid_entries = 0` maybe.

**Comment by notantonia** [comment]
Sorry for the late response. After trying @sbdchd 's thing it still doesn't work, nor does using his with `buffer_output` set to 0, nor what I originally had with it set to 0.

`let g:neomake_oberon_obc_maker_remove_invalid_entries = 0` means no errors get caught.

I'm not too experienced with writing errorformats, so perhaps the problem could be there? Although then I'm not too sure why `:make` would work, but just in case, here's a sample of an error and a warning:

```
"temp.m", line 13: 'notReal' has not been declared
> notReal();
> ^^^^^^^

"temp.m", line 5: warning -- notUsed is declared but not used or exported
> PROCEDURE notUsed();
>           ^^^^^^^
```

I'm not really too bothered by this issue, since I was only really using the language for schoolwork, but I thought it would be useful to bring it up.

**Comment by blueyed** [comment]
I have not checked the "errorformat", but you can use `:let g:neomake_verbose` to see what is happening.

**Comment by blueyed** [comment]
Your initial problem sounds like it is related to "buffer_output" though really.
Make sure to set it correctly (for the maker).
https://github.com/neomake/neomake/pull/590#issuecomment-245764046

**Comment by blueyed** [comment]
Closing this: https://github.com/neomake/neomake/pull/607 is merged now.

Please create a new issue with up-to-date information in case there is still a problem.
Thanks.
