### ISSUE TITLE
Neomake only covers part of a long file

### ISSUE THREAD

**Issue by radoslawroszkowiak** [neomake/neomake#376]
Hi. I'm new to neovim (0.1.3) && neomake (installed via Vundle) and I'm trying to migrate from vim && syntastic. It works really fine (kudos to you) apart from one problem.

When I'm dealing with long files with lots of errors or warnings, only part of a file is covered. 

The signs (those gitgutter-like) are displayed fine to some line, and starting from that line there's nothing more. I encountered it for JS (eslint) and PHP (phpcs). Actually, it happens every time with big, full-of-mistakes files. Never happened to me with Python, but I don't deal with projects with so many errors and so long files there.

It's not just about displaying signs. When I run `:Neomake` and then `:lopen` the last error line displayed there is the exact line where the last sign is displayed.

There doesn't seem to be any fixed line / percentage starting from which neomake stops working. Sometimes it's working OK for 300 / 700 lines, sometimes 2300 / 3000. For comparison, syntastic in vim or neovim shows errors correctly for all the content (of course, there are lags).

Am I missing something? Is it a bug? Some configuration issue on my side?

**Comment by radoslawroszkowiak** [comment]
I'm not sure if it's not an issue of neovim itself, or rather the way the job output is processed. It vim with neomake this issue does not exist.

**Comment by bruschill** [comment]
Do you only see the error markers in the gutter for what is currently in the window, then when you scroll up or down you don't see any more error markers even though there should be?

If so, have you tried to save the file after you scroll? If the error markers show up after scrolling when you save, [check out this PR](https://github.com/ivalkeen/neomake/tree/place-all-signs).

**Comment by radoslawroszkowiak** [comment]
It's not really about the markers. This is most likely neovim's issue, which should potentially be fixed by this PR: https://github.com/neovim/neovim/pull/4646

**Comment by justinmk** [comment]
This should be fixed in neovim HEAD now. Thanks for providing clear repro steps @radoslawroszkowiak.

**Comment by blueyed** [comment]
Thanks, closing the issue in neomake then.

Please re-open if this still happens with the latest neovim.
