### ISSUE TITLE
Use either linter with no error if none found

### ISSUE THREAD

**Issue by FuzzOli87** [neomake/neomake#377]
Hello!

I work on projects that have either eslint or jshint. It becomes really annoying when there is no eslint exe for example (I run everything from the local installs) and I get an error every time I save a file because there is no eslint installed. Same situation with jshint.

How can I configure it so it uses whatever is in it's path and it doesn't give me an error when it can't find it?

**Comment by blueyed** [comment]
It should only use the makers when they are in the path.
Or do you configure them to be used explicitly?
Please post your neomake config.

How do you install the tools?  By some wrapper like pyenv maybe?

**Comment by FuzzOli87** [comment]
I'm a sucker. I always configured linters because I thought I had to make it choose per language. As in, if I wanted it to use eslint, I would have to configure it. I just removed the makers for javascript and it works like you explained. Thanks!
