### ISSUE TITLE
Underline error position

### ISSUE THREAD

**Issue by JelteF** [neomake/neomake#378]
I've been using neomake quite happily and miss almost nothing from switching from Syntastic. There is one thing that I miss quite a lot though: The underline for the error position.
That way it is directly clear what variable mistyped. Especially since the error messages that are shown sometimes do not specify it themselves.

**Comment by blueyed** [comment]
See #361.
Feedback would be appreciated there.

**Comment by blueyed** [comment]
#361 is in, and has been improved already.
Closing.
