### ISSUE TITLE
Neomake stops running linter after period of time

### ISSUE THREAD

**Issue by retrone** [neomake/neomake#388]
I consistently have issues where neomake will work fine (using eslint for javascript), and then at some point will stop working in an extended neovim session (30 mins to a few hours) - there is no status message that the linter is run like there was when neovim was initially opened. Restarting always fixes this - and neither the run on save or the `:Neomake` seems to work. I haven't been able to isolate to a particular thing that I do.

Has anyone has ever faced this? What would be the best way to debug?

**Comment by blueyed** [comment]
Set neomake_verbose=3.
If it still happens, please create a new issue using the issue template.
