### ISSUE TITLE
Stylelint format has changed

### ISSUE THREAD

**Issue by simonsmith** [neomake/neomake#389]
It seems in stylelint `^6.0.0` the format has changed:

*5.4.0*
```
Neomake: stylelint stdout: source/stylesheets/src/components/avatar.css
Neomake: stylelint stdout: 7:3^IExpected property "background-color" to come before property "border" (declaration-block-properties-order)
Neomake: stylelint stdout: 10:3^IExpected property "display" to come before property "width" (declaration-block-properties-order)
```

*6.0.0*
```
Neomake: stylelint stdout: source/stylesheets/src/components/avatar.css
Neomake: stylelint stdout:   7:3  ✖  Expected property "background-color" to come before property "border"   declaration-block-properties-order
Neomake: stylelint stdout:  10:3  ✖  Expected property "display" to come before property "width"             declaration-block-properties-order
```

I couldn't see any documentation on how the `errorFormat` works, otherwise I'd have a shot at updating it. Cheers

**Comment by brendanjerwin** [comment]
@simonsmith http://vim.wikia.com/wiki/Errorformats worked ok for me.
Its just normal Vim error formats.

**Comment by blueyed** [comment]
@simonsmith 
Have you looked into this some more?
A PR to fix this would be nice.

**Comment by simonsmith** [comment]
I haven't yet no. Not overly familiar with error  formats. I thought it might be better to parse the JSON like syntastic does as this is less likely to change.

**Comment by wederer** [comment]
Would be great if somebody could look into this some more. I have tried to create a "oneLineFormatter" for stylelint, but I still can not get the errorformat to work.

If anybody has information about how to write an errorformat for parsing JSON, I would be happy to create a pull request.

**Comment by simonsmith** [comment]
Hey @alex-ketch, noticed you added the original PR a while back. Would you perhaps be able to help with this?

**Comment by alex-ketch** [comment]
@simonsmith I don't use Vim much anymore and hadn't noticed it broke. The PR above should be enough, but if you want to spend time filtering the rule reference at the end of the warning, or changing based on the severity of warning, all my knowledge came from `:help errorformat`

Currently output looks like this:  
![screen shot 2016-06-22 at 22 44 50](https://cloud.githubusercontent.com/assets/1646307/16290471/93c7edd4-38cb-11e6-8a54-1b655ba0d27c.png)

**Comment by simonsmith** [comment]
@alex-ketch Appreciate that, thanks for spending the time. I struggled even with the documentation but I can see how that works now.
