### ISSUE TITLE
Parse gcc/clang "note:" as Info, not Error.

### ISSUE THREAD

**Issue by phcerdan** [neomake/neomake#396]
More than an Issue is just a question.
I have copied to my own maker, the errorformat from neomake clang maker (#36), it works nice, spotting warnings and errors with different symbols. But the "note: xxxxxx' output is parsed as an error, and I would like other symbol.

It is not clear to me how neomake differentiate warning from errors, do I have to modify errorformat of the maker? Or the postprocess?

**Comment by sbdchd** [comment]
You would have to change the errorformat a bit.

You can read up  on [errorformats](http://vimdoc.sourceforge.net/htmldoc/quickfix.html#errorformat), but it appears `%t` won't detect notes (only `i`fno, `w`arning, `e`rror), so you would have to use [`%I`](url) like the [errorformat for shellcheck](https://github.com/neomake/neomake/blob/47a88946b2d9dd9bb4718cab5ee24b47f5abf97f/autoload/neomake/makers/ft/sh.vim#L13).

Something like this should work, although I haven't [tested it with clang and neomake.](https://gist.github.com/sbdchd/6030a6d04cb54468ceeb0c4a32900c6f)
```viml
function! neomake#makers#cpp#clang()
    return {
        \ 'exe': 'clang++',
        \ 'args': ['-fsyntax-only'],
        \ 'errorformat':
            \ '%-G%f:%s:,' .
            \ '%f:%l:%c: %trror: %m,' .
            \ '%f:%l:%c: %tarning: %m,' .
            \ '%I%f:%l:%c: note %m,' .
            \ '%f:%l:%c: %m,'.
            \ '%f:%l: %trror: %m,'.
            \ '%f:%l: %tarning: %m,'.
            \ '%I%f:%l: note: %m,'.
            \ '%f:%l: %m',
        \ }
endfunction
```
