### ISSUE TITLE
Provide a wrapper / helper to run Neomake automatically

### ISSUE THREAD

**Issue by blueyed** [neomake/neomake#405]
Currently the README suggests the following to enable automatic checking:

```
autocmd! BufWritePost * Neomake
```

This is a bit brittle though, e.g. it will also run on `:w /some/other/path`, but on the current file.

I've created https://github.com/neomake/neomake/issues/404 as a first step into this direction.

**Comment by wsdjeg** [comment]
I also get this issue,should we use `<afile>` instead? also `:wa` command should not only check current buffer.
BTW we should provid a g:var for user do not run maker when use  `:wq` command!

what do you think?

**Comment by blueyed** [comment]
Yes, we should provide some function for this.

Here is what I am currently using: https://github.com/blueyed/dotfiles/commit/0c69796bb44674403ddb240be3475f04e0be9934.

`expand("<afile>")` seems to refer to the relative file, while `expand("<amatch>")` refers to the full path always.

**Comment by blueyed** [comment]
> BTW we should provid a g:var for user do not run maker when use :wq command!

That is not so easy I think, but we might be able to use `QuitPre` here and mark the window/buffer as not going to be processed.

**Comment by wsdjeg** [comment]
I am reading syntasc source code,and try to find a way to implement it.

**Comment by blueyed** [comment]
Something like this maybe? https://github.com/blueyed/dotfiles/commit/4c59098cc42766f61f7f67169fdf8d90bb8437cd

**Comment by blueyed** [comment]
#1167

**Comment by blueyed** [comment]
Closing in favor of #1167.
