### ISSUE TITLE
Neomake is severely broken in Vim (no longer shows loclist or warning-signs)

### ISSUE THREAD

**Issue by edwardsmit** [neomake/neomake#408]
As of the new behavior added in https://github.com/neomake/neomake/commit/9d7d3f8608c71f332e69753f8aea8f8450a21541 by @blueyed my loclist isn't showing anymore, neither do the warning-signs show.
My messages keep getting filled with the feedback message of Neomake that eslint exited with exit code 1.

I use the latest neovim from `master` branch, and configure neomake as:
```
" This setting will open the |loclist| or |quickfix| list (depending on whether
" it is operating on a file) when adding entries. A value of 2 will preserve the
" cursor position when the |loclist| or |quickfix| window is opened. Defaults to 0.
let g:neomake_open_list = 2

" Only use eslint
let g:neomake_javascript_enabled_makers = ['eslint']
" Use the fix option of eslint
let g:neomake_javascript_eslint_args = ['-f', 'compact', '--fix']

" Callback for reloading file in buffer when eslint has finished and maybe has
" autofixed some stuff
function! s:Neomake_callback(options)
  if (a:options.name ==? 'eslint') && (a:options.has_next == 0)
    checktime
  endif
endfunction

" Call neomake#Make directly instead of the Neomake provided command
autocmd BufWritePost,BufEnter * call neomake#Make(1, [], function('s:Neomake_callback'))
```
My current working workaround is pinning neomake at the commit before the changes applied in the above referenced commit

**Comment by blueyed** [comment]
@edwardsmit 
Thanks for the report and sorry for the trouble!

Can you check which of your setting causes this, please?

**Comment by junkblocker** [comment]
@blueyed : It's not that it's not highlighting, I think it may not be running at all or something. The reason I think it is so is that the ``:lwindow`` is empty in the case of ``HEAD`` while for ``4f2b11f`` it is not. Tried with a very minimalistic config on MacVim.

```vim
set nocompatible
set number                              " Show line numbers with auto width adjust
set backspace=2                         " Allow backspacing over to the previous lines. same as ":set backspace=indent,eol,start" but backwards compatible
set wildmenu                            " Command line completion shows a list of matches
set wildmode=list:longest,full          " Specified how command line completion works
set laststatus=2                        " Always show a status line
set whichwrap=b,s,<,>,[,]               " Allow cursor keys to move to previous/next line
set showcmd                             " Let me see what I type
syntax enable                           " Enable syntax AND do not override my settings
autocmd BufWritePost * Neomake
```

**Comment by blueyed** [comment]
@junkblocker 
It is working for me and others, and your example does not include any neomake config.
Do you mean it happens with the default config already for you, for every file, e.g. with filetype=shell?

**Comment by junkblocker** [comment]
Yes, I tested with just the config I listed on a:

1. shell script - gets the default ``shellcheck`` checker run on it.
2. HTML file - gets the default ``tidy`` checker run on it.

Here's [``verbose`` run output](https://gist.github.com/junkblocker/bec1ca4e89d5cbace99799ee049c379d) produced using

```vim
set verbose=100 verbosefile=/tmp/verbose | Neomake
```

on ``/tmp/foo`` which is a HTML file.

**Comment by Corebel** [comment]
same in ordinary vim/macvim  
👍

**Comment by kbarrette** [comment]
Same problem with homebrew vim, vimrc of:

```
set nocompatible
call plug#begin('~/.vim/plugged')
Plug 'neomake/neomake'
call plug#end()
```


```
$ uname -a
Darwin xxxxxx 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64

$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 15 2015 13:21:06)
MacOS X (unix) version
Included patches: 1-963
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: /usr/bin/clang   -L. -L/usr/local/lib -L/usr/local/lib -Wl,-headerpad_max_install_names -o vim        -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -framework Python   -lruby.2.0.0 -lobjc
$
```

**Comment by blueyed** [comment]
I can reproduce it now using Vim.

Is everybody here using Vim?

**Comment by blueyed** [comment]
@edwardsmit (OP) does not seem to use Vim, but Neovim though?!

**Comment by junkblocker** [comment]
@blueyed , you are right. It doesn't seem to happen with neovim. Since you asked, I used neovim for a while but decided it wasn't stable/beneficial enough for me yet. And now that Bram has finally ~~started playing catchup~~ added async job control to vim the reasons to switch for me have reduced further.

**Comment by blueyed** [comment]
Well, Neomake has not adopted the Vim way yet.. :D

I'm in the process of setting up a testing framework for Neomake currently, with the first test being this essential thing.. stay tuned.

Regarding this issue I'd say it's a good time to consider switching to Neovim.. ;)

**Comment by junkblocker** [comment]
> Regarding this issue I'd say it's a good time to consider switching to Neovim.. ;)

;) I know you say this half in jest but if it comes to that, I'd probably go back to using Syntastic. I have to/can/run/use vim on more diverse systems (OSes/versions) than neovim is currently practical to use at this point. These can be custom appliances without compilers which already have vim on them or I don't have install access on. If I constantly need to keep watching out for such downgraded cases where neovim is not available, it's less mental/habitual/configuration/maintenance overhead for me to just keep using vim. Usually I am on the newest version of everything I run but this is one reason which keeps me using vim over neovim and neobundle over dein.vim etc. So, already considered and had to go back to vim :)

Looking forward to the fix!

**Comment by blueyed** [comment]
@junkblocker 
Well, I get your rant, but the point is that you're one step ahead: it works with Neovim, but not Vim.. ;)

And I am certainly surprised about Vim-peeps using Neomake instead of Syntastic.  I consider the latter to still being more robust and feature-complete, and only moved over to Neomake (and became a maintainer) because of the async processing (which all Vim users are missing?!).

Why are Vim users using Neomake instead of Syntastic?

Anyway, I'm also looking forward to a fix, of course (and am sorry to have broken this).
And I would appreciate really if people would dig into the source and come up with a fix and PRs for things they notice - after all we're developers and should develop instead of +1'ing issues we're affected by.

Anyway, I recommend going back to https://github.com/neomake/neomake/commit/9d7d3f8608c71f332e69753f8aea8f8450a21541 for all Vim users, until this issue is resolved.
I will only start investigating when tests are working, and it's currently blocked by Vim and Neovim not behaving the same regarding to output (hopefully solved by https://github.com/junegunn/vader.vim/pull/72).

It's very frustrating that there are no tests currently (and that is true for most of the Vim plugins).

My current idea is to use Vader, based on the test framework I've developed for https://github.com/blueyed/vim-diminactive/.

**Comment by junkblocker** [comment]
> And I am certainly surprised about Vim-peeps using Neomake instead of Syntastic. I consider the latter to still being more robust and feature-complete, and only moved over to Neomake (and became a maintainer) because of the async processing (which all Vim users are missing?!).

I'd guess that's the reason for most everybody using neomake.

> Why are Vim users using Neomake instead of Syntastic?

Continuing from previous .. it is good enough, even if not equal or better, for most cases and also requires one less config to maintain. And when somebody does have a chance to, or checks back on neovim progress, they have the config ready to use.

**Comment by edwardsmit** [comment]
I use NVIM v0.1.5-292-gc17f6c5 in combination with Neomake latest, no other plugins.
I've narrowed it down to  the combination of an `autocmd` on `BufEnter` combined with `g:neomake_open_list` having the value of `2`, when setting the value to `1` I get stuck in the LocList and can't get out of that anymore (new Loclists get opened when changing the window). Setting the value to `0` won't cause a problem.
```
let g:neomake_open_list = 2
autocmd BufWritePost,BufEnter * Neomake
```
Tested this with both javascript (eslint) and bash-files (shellcheck)

**Comment by kbarrette** [comment]
> Continuing from previous .. it is good enough, even if not equal or better, for most cases and also requires one less config to maintain. And when somebody does have a chance to, or checks back on neovim progress, they have the config ready to use

This is exactly why I'm interested in Neomake. I HATE Syntastic blocking the UI, but I don't always use Neovim, and I don't want to maintain separate configs.

**Comment by blueyed** [comment]
JFI: I have a fix and (more importantly) a test (suite) for this.  Need to clean it up / refactor it, but it's expected to be fixed soonish.

**Comment by blueyed** [comment]
@kbarrette 
We might all be better off by adding async support to Syntastic.. at least that's what I've thought the last days - given that it's more mature altogether.

**Comment by blueyed** [comment]
#458 is ready for review.  It should fix this regression with Vim and adds a test suite to make sure this does not happen again.
