### ISSUE TITLE
Can't set gcc args

### ISSUE THREAD

**Issue by its-suun** [neomake/neomake#413]
I like to have C++14 features in Neomake and followed the instructions in the readme and added

``` vim
let g:neomake_cpp_enabled_makers = ["gcc"]
let g:neomake_cpp_gcc_makers = {
    \ 'args': ['-std=c++1y'],
    \ }
```

into my init.vim.

When running on `:Neomake!` on this file:

``` c++
int main() {
    int a {2};
    return 0;
}
```

I get the following warning at 2. file: `main.cxx:2:6: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]`

**Comment by blueyed** [comment]
I don't get the issue.
Isn't it because of you setting the `args` explicitly?

**Comment by its-suun** [comment]
The issue is that I like to add arguments to the gcc compiler so it compiles C++14 code. With the method I specified it does nothing and it still throws warnings.

**Comment by blueyed** [comment]
Do you mean to add instead of replacing them?
The default args are `'args': ['-fsyntax-only', '-Wall', '-Wextra'],`.
The warnings sounds to me like -std=c++11 or -std=gnu++11 should be used?

**Comment by its-suun** [comment]
Yes, I want to have additional `-std=c++1y`.
C++14 has C+11 features so that shouldn't be the problem.
Having this in init.vim still throws the warning:
```vim
let g:neomake_cpp_gcc_makers = {
	\ 'args': ['-fsyntax-only', '-Wall', '-Wextra', '-std=c++1y'],
	\ }
```

**Comment by dev-zero** [comment]
so, the question here is: how do I specify additional arguments for the individual makers?

I for example would like to add the following arguments to the `fortran_gfortran` maker: `-ffree-form -ffree-line-length-none'`. In Syntastic, this worked using `let g:syntastic_fortran_compiler_options = ' -ffree-form -ffree-line-length-none'`, what is the respective option for neomake?

**Comment by blueyed** [comment]
See `:h neomake-options`.

`let g:neomake_<ft>_<name>_<property>= …`, where `<property>` would be `args`.
So to strictly append, use `let g:neomake_fortran_gfortran_args = neomake#makers#ft#fortran#gfortran().args + ['-ffree-form', '-ffree-line-length-none']`.

A PR to improve the help (doc/neomake.txt) and/or the README in this regard would be appreciated - from any one being helped by this answer..!

**Comment by blueyed** [comment]
@its-suun 
With `let g:neomake_cpp_gcc_makers` the `<property>` parts is `makers`, which is not defined.
You want `let g:neomake_cpp_gcc_args = ['-fsyntax-only', '-Wall', '-Wextra', '-std=c++1y']`.

I agree btw that the format is a bit weird, and that something like a generic dictionary, to overwrite things might be better.
