### ISSUE TITLE
improve Python checks: detect dead code

### ISSUE THREAD

**Issue by jabbalaci** [neomake/neomake#419]
In Python, I would like to detect dead (unused) code pieces but currently they are not marked. Consider the following script:

```
#!/usr/bin/env python3


def unused():
    pass


def main():
    print('How to detect unused() is never called?')


main()
```

According to the README, makers provided by neomake as of this writing are: pep8, flake8, pyflakes, pylama, pylint, python. I tried them all in shell but none of them detected my unused function. Example:

```
$ flake8 dead.py 
$
```

Maybe I'm missing something, but it seems these makers cannot detect dead code. However, the project [vulture](https://bitbucket.org/jendrikseipp/vulture) can do exactly this:

```
$ vulture dead.py 
dead.py:4: Unused function 'unused'
```

Can we add _vulture_ as a supported maker?

**Comment by blueyed** [comment]
> Can we add vulture as a supported maker?

Yes, why not?

**Comment by jabbalaci** [comment]
OK, I made a pull request: https://github.com/neomake/neomake/pull/420 . 

How to use [vulture](https://bitbucket.org/jendrikseipp/vulture)?

1) Install it and verify that you cal call it from the shell. Example:

    $ vulture dead.py
    dead.py:6: Unused function 'unused'

2) Then enable it in your `init.vim` file. Mine looks like this:

```
Plug 'neomake/neomake'
" {{{
    let g:neomake_python_enabled_makers = ['flake8', 'pep8', 'vulture']
    let g:neomake_python_flake8_maker = { 'args': ['--ignore=E501,E266'], }
    let g:neomake_python_pep8_maker = { 'args': ['--max-line-length=100', '--ignore=E266'], }

    autocmd! BufWritePost * Neomake
" }}}
```

**Comment by blueyed** [comment]
#420 is merged, so I am closing this.
Thanks!

You might want to look at #596 probably for some improvements to the vulture maker.
