### ISSUE TITLE
Provide hook to populate quickfix/loclist through Vim function

### ISSUE THREAD

**Issue by yyadavalli** [neomake/neomake#428]
The `ensime-vim` plugin provides `EnTypeCheck` command to check scala files. 
Is there a way I can create a maker for neomake that uses the vim command?

P.S. I did not find any such mechanism on searching, want to make sure I did not miss something. I'd be willing send to a pull request if there is interest

**Comment by wsdjeg** [comment]
As I know neomake's maker is the tool in your PATH. you can run it in your terminal. I am not sure if there is a way to use the command in vim RTP

**Comment by blueyed** [comment]
@wsdjeg 
If I understand it correctly, the question is about using a Vim command instead of an executable.

@yyadavalli 
You'll have to investigate this yourself by looking at the code/doc - I don't know it myself without looking into it.
Should be possible in general, but might need some code changes.

**Comment by blueyed** [comment]
I think it would be useful in general (and also for the tests) to have a `func` setting/attribute, that would be preferred to `exe`.  This would call a function instead of an external program.
But that would not be async, since `jobstart` (in Neovim) and `job_start` (in Vim) is only meant for calling external programs..

**Comment by andreypopp** [comment]
The same is required to integrate with https://github.com/the-lambda-church/merlin

**Comment by blueyed** [comment]
@andreypopp 
How would the integration with merlin look like, i.e. which command/function would you like to use?

**Comment by andreypopp** [comment]
See how it is done for syntactic: https://github.com/the-lambda-church/merlin/blob/master/vim/merlin/syntax_checkers/ocaml/merlin.vim it calls a function.

**Comment by blueyed** [comment]
@andreypopp 
It seems to hook into getting the errors for the loclist though, not running a maker through a function.
That seems to be a more universal approach altogether.

And ensime-vim appears to use the same approach: https://github.com/ensime/ensime-vim/blob/98d52714333bf07c96f494d7b0879e6f56d2815b/plugin_integrations/syntastic/syntax_checkers/scala/ensime.vim#L8-L14.

So we should provide a way to skip running a maker, but have a hook/function being run to populate the quickfix / location list (for ensime-vim: https://github.com/ensime/ensime-vim/blob/c258770c2f0115e47a498b07a54bd01fd2a2d064/ensime_shared/typecheck.py#L49-L61).

**Comment by andreypopp** [comment]
Alright, any pointers on how to implement that?

**Comment by blueyed** [comment]
Not really, apart from what I wrote above.
I could imagine that it's possible already with the current callbacks (and you would have to use `true` as maker `exe`).

**Comment by aignas** [comment]
Just to add to the discussion above, that [omnisharp-vim](https://github.com/OmniSharp/omnisharp-vim) is also using the same hook mechanism.

**Comment by BonarBeavis** [comment]
I am trying to integrate ensime with neovim but my vimscript skills are marginal. I got so far:

```vim
" Hack so that b:ensime_notes gets populated
command SyntasticCheck :echo 0

function! Ensime_check(jobinfo)
  " Removing this line and running :EnTypeCheck by hand followed by :Neomake works.
  exe 'EnTypeCheck'
  return b:ensime_notes
endfunction

let g:neomake_scala_typecheck_maker = {
      \ 'exe': 'true',
      \ 'get_list_entries': function('Ensime_check')
      \ }
let g:neomake_scala_enabled_makers = ['scala_typecheck']
```

I think `exe EnTypeCheck` runs async, so b:ensime_notes is still empty when returned. How can I fix this?
