### ISSUE TITLE
autocmd BufEnter stuck in loclist

### ISSUE THREAD

**Issue by cycomanic** [neomake/neomake#441]
Hi, 

I'm having issues using autocmd BufEnter with `let g:neomake_open_list = 2` The loclist never shows up and I stop seeing my commandline. If I set open_list=1 I am stuck in the locationlist, i.e. as soon as I switch into the buffer which contains the code I'm send back to the loclist. This was mentioned by @ @edwardsmit in #408 . Tested with neovim 0.1.3 and pylint

**Comment by edwardsmit** [comment]
@cycomanic I think it's the *exact* same problem I'm seeing.

**Comment by tamorim** [comment]
@cycomanic @edwardsmit 
I had the same problem.
Switching to `BufWinEnter` solved for me!

**Comment by blueyed** [comment]
I assume this to be fixed by beb34c9.
