### ISSUE TITLE
Vint does not work for vim file.

### ISSUE THREAD

**Issue by wsdjeg** [neomake/neomake#442]
when save a vim file Neomake does not work;
I test the command in terminal ,the error can be shown.
```sh
✔ wsdjeg:DotFiles [ master | ✔  ] ➭ vint test/test.vim 
test/test.vim:1:3: unexpected token: <EOL> (see ynkdir/vim-vimlparser)
✘ wsdjeg:DotFiles [ master | ✔  ] ➭ vint --style-problem -f {file_path}:{line_number}:{column_number}:{severity}:{description} --enable-neovim test/test.vim 
test/test.vim:1:3:error:unexpected token: <EOL>
✘ wsdjeg:DotFiles [ master | ✔  ] ➭ 
```
but when edit this file, and run `:Neomake vint` or `:Neomake`, nothing shown, BTW, in cmd mode, I can complete vint after `Neomake`.

**Comment by blueyed** [comment]
Is it related to errors not showing up in general in Vim?
Are you using Neovim or Vim?

The vint maker works for me in general.

**Comment by wsdjeg** [comment]
I test in both vim and neovim, this situation only happen in my `DotFiles` repo, I do not know why.

**Comment by blueyed** [comment]
Can you provide steps to reproduce it by cloning your repo?

**Comment by wsdjeg** [comment]
@blueyed thanks, here is my reprodue step
```sh
cd ~
git clone https://github.com/wsdjeg/DotFiles.git
cd DotFiles
vim test/test.vim
```
then type into `if`, then `:w`

**Comment by wsdjeg** [comment]
@blueyed can you try with my new repo Github-api.vim, neomake still do not open locallist in this repo.
https://github.com/wsdjeg/GitHub-api.vim

**Comment by wsdjeg** [comment]
@blueyed I have fix it, it is due to colored out put.
this patch in my repo fix this issue; I think maybe neomake should also works well with color enable.
```diff
diff --git a/.vintrc.yaml b/.vintrc.yaml
index 0a60ef7..28269e6 100644
--- a/.vintrc.yaml
+++ b/.vintrc.yaml
@@ -2,9 +2,6 @@ cmdargs:
   # Checking more strictly
   severity: style_problem
 
-  # Enable coloring
-  color: true
-
 policies:
   ProhibitImplicitScopeVariable:
     enabled: false
```

**Comment by blueyed** [comment]
There does not seem to be a `--no-color` option that we could use to override a config value with `vint`, which seems to be required to fix this easily.

I could imagine having some helper / filter method in general though, which could be used to remove any ANSI color sequences etc for certain makers.
What do you think?

For reference, I am using the following shell function in scripts:

```sh
echo $1 | $sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,3})?)?[m|K]//g"
```

**Comment by wsdjeg** [comment]
LGTM,But will this cause another issue？maybe vint should support this option.

**Comment by blueyed** [comment]
Yeah, a feature request go for vint would be good.

**Comment by blueyed** [comment]
I've created https://github.com/Kuniwak/vint/issues/167 for Vint to have a `--no-color` flag.
Leaving this issue open for now.

**Comment by wsdjeg** [comment]
thanks for your work

**Comment by blueyed** [comment]
vint 0.3.7 got it.. :)
@wsdjeg 
Do you want to create a PR to use it in Neomake?
I think we could just assume the latest version is being used (which means no version check is required etc).

**Comment by wsdjeg** [comment]
@blueyed done, but I am not sure if there is anything else need to be changed

**Comment by blueyed** [comment]
Thanks!
Let's see.. :)  (should be good)
