### ISSUE TITLE
Chef Maker: Foodcritic works for Chef, but not for Ruby

### ISSUE THREAD

**Issue by rubbsdecvik** [neomake/neomake#444]
I am attempting to create a maker for Chef which runs [Foodcritic](http://www.foodcritic.io/). I have created a [branch](https://github.com/neomake/neomake/compare/master...rubbsdecvik:ChefPoC) which get something working, but I feel like it's an ugly hack.

I was looking through issue #116 which described what I was trying to do fairly accurately. So I made Chef a superset of Ruby, however after reviewing the PR #133, I noticed it expects the superset to also be able to check the subset. This is not the case with Chef.

For some background, Chef is valid Ruby code and can be linted with things like Rubocop, but is also a DSL which Foodcritic is best at linting. However Foodcritic is not Ruby aware, so as a work around I'm setting it to always pass on Ruby filetypes.

Is there a better way for me to enable checkers only on Chef, but allow for the type to be multiple filetypes?

**Comment by blueyed** [comment]
Should be fixed through https://github.com/neomake/neomake/pull/585 / #1201.
