### ISSUE TITLE
C header files (.h) don't use default maker

### ISSUE THREAD

**Issue by alekulyn** [neomake/neomake#447]
On my environment, I have both clang and gcc.  Since neomake uses clang as the default maker if one is not specified, in my init.vim, I have C files set using the gcc maker, like so:
```vim
let g:neomake_c_enabled_makers = ['gcc']
```
The problem is that, though it that setting works fine for .c filetypes, it doesn't for .h (C header) filetypes.  Only when I added
```vim
let g:neomake_cpp_enabled_makers = ['gcc']
```
do C header files compile with gcc.

**Comment by blueyed** [comment]
So the filetype of the header files is cpp?

**Comment by alekulyn** [comment]
Apparently.  I've also tried
```vim
let g:neomake_h_enabled_makers = ['gcc']
```
but that didn't work.

**Comment by blueyed** [comment]
What does `:echo &ft` give you for the `.h` file?

**Comment by alekulyn** [comment]
cpp

**Comment by blueyed** [comment]
That's why you need the `let g:neomake_cpp_enabled_makers = ['gcc']`.

Check `:verb set ft` to see where it's coming from.
And see https://github.com/vim/vim/blob/ef3abc6442260e9a0314970a532400b05571d3fe/runtime/filetype.vim#L380-L399 for how Vim sets this by default (it's configurable).

**Comment by blueyed** [comment]
Closing since it's not a Neomake issue really, but I can see that it's confusing.
However, Neomake itself only uses the filetype.

**Comment by blueyed** [comment]
OTOH I could imagine that Neomake would pick up some settings based on the file extension, where you then could map `.h` files to makers.  Not sure if that's really worth it.
Feel free to create a new issue, if you think it's feasible.

**Comment by alekulyn** [comment]
Before I create another issue, I want to see if the newest problem that popped up after I added ```let g:c_syntax_for_h = 1``` to my init.vim has anything to do with this.  My .h files started compiling with gcc as they were supposed to, but errors and their lines aren't displayed anymore.
![progress_update](https://cloud.githubusercontent.com/assets/3824241/15644490/0f2abb46-265c-11e6-9342-558a6dc853d2.png)
