### ISSUE TITLE
Clang is used for C++ instead of Clang++

### ISSUE THREAD

**Issue by rubik** [neomake/neomake#448]
In my `.vimrc` I have:
```viml
let g:neomake_c_enabled_makers = ['clang']
let g:neomake_c_clang_maker = {
   \ 'args': ['-Wall', '-Wextra', '-Weverything', '-pedantic'],
   \ }
let g:neomake_cpp_enabled_makers = ['clang']
let g:neomake_cpp_clang_maker = {
   \ 'args': ['-Wall', '-Wextra', '-Weverything', '-pedantic', '-Wno-sign-conversion'],
   \ }
```

But when I open a header file (which Neovim correctly identifies as cpp) Neomake shows the error:
```
geometry.h:4:10: fatal error: 'cstddef' file not found
```

Which is what you get by using Clang. I checked with

    clang++ -fsyntax-only geometry.h

and no warnings or errors were shown.

However, when I remove `g:neomake_cpp_clang_maker`, it works as expected. I don't understand why having different options for clang and clang++ would make it stop working.

**Comment by sbdchd** [comment]
When you are defining your maker, you did not include the `exe` field in the dict, which results in Neomake using the name of the maker, in this case let g:neomake_cpp_**clang**_maker, as the executable. See [readme](https://github.com/neomake/neomake/blob/0481248dcac0a67f747cfd7ad63b2bed7ce770eb/README.md#how-to-use-advanced) and [docs](https://github.com/neomake/neomake/blob/master/doc/neomake.txt#L65) for more info.

You could add the `exe` field and it should work - can't test it myself.
```viml
let g:neomake_cpp_enabled_makers = ['clang']
let g:neomake_cpp_clang_maker = {
   \ 'exe': 'clang++',
   \ 'args': ['-Wall', '-Wextra', '-Weverything', '-pedantic', '-Wno-sign-conversion'],
   \ }
```
I think the reason that it works when you remove it from your config is that Neomake defaults to the [predefined makers for c++](https://github.com/neomake/neomake/blob/5df13cc3d321765b4d57ce6191a96aedb748bfac/autoload/neomake/makers/ft/cpp.vim), which use `clang++`.

**Comment by rubik** [comment]
Oh was I dumb! Thanks, that worked!
