### ISSUE TITLE
No way to use `python3` instead of `python` to check code.

### ISSUE THREAD

**Issue by SquishyStrawberry** [neomake/neomake#449]
When running Neomake and writing Python 3 code, sometimes cod eis marked as incorrect when using Python 3 syntax instead of Python 2 syntax.

`python` points to Python2.7, and `python3` to Python3.5 in my system.

I will provide more information if needed.

**Comment by blueyed** [comment]
The workaround (and best practice in general) is to use a virtualenv / pyenv, so that `python` points at the Python version you're using.

**Comment by blueyed** [comment]
Otherwise, you have to configure the `_exe` setting(s) for the relevant makers.

**Comment by SquishyStrawberry** [comment]
How would I configure the `_exe` setting? Just as any other settings such as `args`?

**Comment by blueyed** [comment]
@SquishyStrawberry 
The `_exe` setting can be a callback/function, and there you can look at `getline(1)`.

**Comment by SquishyStrawberry** [comment]
@blueyed Thanks, you can close this now.

**Comment by dbrodie** [comment]
@SquishyStrawberry Could you please share the configuration that worked for you for future google searches?

**Comment by blueyed** [comment]
@dbrodie 
what problem do you have?
Also related to having a shebang that is different from `python`?

I think that you should work in an environment, where `python` is the Python you want to use.

Check out `:h neomake-options`.

But I can see that this could be improved to look at the shebang indeed - we're doing something in this regard for the `sh` maker already.

**Comment by dbrodie** [comment]
I am editing a project which contains some python3 and python2 code, and sadly would rather not have a separate instance of vim for each.

I'll play around with configuring it, but since this is the first result I found when searching in google, I think it would be better to [have the result for people who happen on this issue.](https://xkcd.com/979/)

**Comment by blueyed** [comment]
@dbrodie 
So are you using shebang lines then?!

**Comment by dbrodie** [comment]
Sorry for not being clearer, yes, I'm using them.

**Comment by kreedz** [comment]
I have exactly the same problem as described in the OP post.
And I'm not using any of pyenv or virtualenv.
I've installed pep8 for both python 2 and 3.
```
let g:neomake_python_pep8_exe = 'python3'
let g:neomake_python_enabled_makers = ['pep8']
```
This doesn't help, doesn't give any error, and not making any checking.
Next snippet only checking python2 rules.
`let g:neomake_python_enabled_makers = ['pep8']`

**Comment by blueyed** [comment]
@kreedz 
`let g:neomake_python_pep8_exe = 'python3'` will use `python3` for the program instead of `pep8`..!
Check `which pep8` from inside (Neo)Vim, e.g. `!which pep8`.
And to check which one gets used from Neomake, try `:NeomakeSh which pep8` and then `:copen`.

**Comment by kreedz** [comment]
Both of them
`!which pep8`
`:NeomakeSh which pep8`
gives me '/usr/local/bin/pep8'.
It's surely python2 package.
python3 pep8 now living in '.local/bin'

**Comment by blueyed** [comment]
@kreedz 
`which` does not look at your Neomake config, but only `$PATH`.
You might not have `~/.local/bin` in your `$PATH` at all, or after `/usr/local/bin`.
Try `:echo $PATH` in Vim, but it does not help when mixing py2/py3 there, of course.

I recommend defaulting to Python 3: pep8 installed for Python 3 should also handle Python 2 files etc.

**Comment by kreedz** [comment]
@blueyed 
I checked it out, I have `~/.local/bin` in my $PATH, it's after `/usr/local/bin` as you mentioned.
Mainly the issue was not with pep8 (it was just example, sorry for confusing), it was with linters like flake8. They finding python2 errors in the python3 files.

**Comment by blueyed** [comment]
> it was with linters like flake8. They finding python2 errors in the python3 files.

I think flake8 via py3 should also be fine with py2 files.. it's just the other way around that you get problems.
The same applies when using a program through Python 3.5 on a file with f-strings (added in 3.6).

**Comment by danihodovic** [comment]
> The _exe setting can be a callback/function, and there you can look at getline(1).

Do you have an example of this?

**Comment by blueyed** [comment]
@danihodovic 
See https://github.com/neomake/neomake/pull/1470 for a more generic approach - it sets the filetype to e.g. `python.python2` or `python.python3`, and you can configure `g:neomake_python_python3_exe` then, although I think it should need no more config then maybe - have not checked it.

Are you looking for something for the main "python" maker, or the python makers in general?
It would be easy for "python" I guess, but more involved for makers in general - although there it could just use `python -m flake8`, where `python` is the python from the shebang.

**Comment by danihodovic** [comment]
I write python scripts and they can be either python2 or python3 which is indicated by the shebang. I'd like neomake to infer the version for pylint. I was asking if you have a code example for using a lambda function in place of the `_exe` setting.

I'll have a look at #1470

**Comment by blueyed** [comment]
`exe` itself cannot be dynamic anymore (removed in b1e1c804), but `maker.fn(jobinfo)` can do it.  This is also what #2062 does.

**Comment by danihodovic** [comment]
#2062 looks good enough for me. thanks :+1:

**Comment by blueyed** [comment]
But it is not used with pylint.

Would using "detected python" + "-m pylint" work for you?

**Comment by blueyed** [comment]
https://github.com/neomake/neomake/pull/2064 (just merged) brings the documented InitForJobs callback.
