### ISSUE TITLE
Make possible real-time errors feedback.

### ISSUE THREAD

**Issue by purpleP** [neomake/neomake#452]
Until recently I thought that this is impossible to do with vim/neovim, but I've started to use git-gutter and realized that the guy behind it solved it somehow. I'm still in very early stages of learning vimscript, so I don't think I can understand how did he do that, but I'll try if no one will. But it would be great if you guys could work on porting this ability to your plugin. The good way would be to create another plugin which would abstract away the mechanism of asynchronously sending the contents of the buffer to another program.

**Comment by blueyed** [comment]
What do you mean exactly?
Neomake runs asynchronously already, and the trigger for that depends on how you configure it (e.g. when writing the buffer).

**Comment by purpleP** [comment]
@blueyed And please remove question tag as it's not a question.

**Comment by blueyed** [comment]
Well, I had a question.. :)

See https://github.com/neomake/neomake/pull/393 then.

Should we close this issue (given the PR)?!

**Comment by purpleP** [comment]
@blueyed Yes, we should
