### ISSUE TITLE
Add Objective-C(++) maker to the existing makers

### ISSUE THREAD

**Issue by HiPhish** [neomake/neomake#453]
There are makers for C and C++ included with Neomake, but no makers for Objective-C and Objective-C++. I have thrown together an Objective-C maker based on the existing in C maker, I'll play around with it a bit before submitting a PR.

**Comment by blueyed** [comment]
@HiPhish
Regarding the upvotes on your issue there seems to be interest.
Have you came up with something already?

**Comment by HiPhish** [comment]
@blueyed Oh, I had completely forgotten about this thing. I haven't used Objective-C since, so it slipped from my radar. The Objective-C maker is the same as the C maker, the tricky part is finding sensible defaults. For example, the C maker warns about unused function parameters, which is a reasonable choice, but in Objective-C is it common to ignore method arguments because of how the Cocoa API is designed. These are the sort of things that need to be worked out by someone who uses Objective-C a lot. Considering the upvotes, how about I just write the maker with what *I* think are sensible choices, and then the kinks can be worked out by other people? I think having a sub-optimal working Objective-C maker is better than having none at all.

**Comment by blueyed** [comment]
@HiPhish 
Sounds good.
