### ISSUE TITLE
"'errorformat' contains no pattern" for tex files

### ISSUE THREAD

**Issue by goerz** [neomake/neomake#454]
When I open a (La)tex file in vim or neovim and run `Neomake`, I get the following error:

```
:Neomake lacheck
Error detected while processing function neomake#Make..<SNR>74_Make:
line   18:
E378: 'errorformat' contains no pattern
```

Same for chktex. This is using the neomake plugin from the 'master' on github from a few days ago. I have no neomake-specific settings for `tex` in my `.vimrc`

**Comment by sbdchd** [comment]
Does the following produce an output?

`:set ft=tex | echom &efm`

**Comment by goerz** [comment]
Yes, it reports the errorformat `%f:%l: %m` that if have in `~/.vim/after/ftplugin/tex.vim`. I did find the culprit, though, because that same file also contained `compiler tex` which loaded [tex.vim](https://raw.githubusercontent.com/goerz/vimrc/157d004a4165f888e4275ff50f15d9639062528c/compiler/tex.vim). If I remove that, the error disappears.

**Comment by blueyed** [comment]
@goerz 
I assume this is fixed then?!

The error comes from Neomake, but there have been improvements in this regard.

Please re-open and let me/us know if there is still a problem.
