### ISSUE TITLE
javascript standard maker doesn't use configuration in package.json

### ISSUE THREAD

**Issue by caske33** [neomake/neomake#461]
The javascript standard maker runs `standard full-path-of-filename`, but if it were to run `cd directory-of-package.json-file && standard path-to-file`, it would use the configuration in package.json to run. This is especially useful when using flow in combination with standard, as it's necessary to remove the flow type annotations before standard runs.

Of course, I don't expect a search to a directory with a package.json, but it would be nice if standard runs from the current working directory, which it doesn't seem to do.

**Comment by blueyed** [comment]
@caske33 
Why was this closed?
Did it work out for you in the end?

**Comment by caske33** [comment]
I think it's working now, yes
