### ISSUE TITLE
Java classpaths are ignored when specified as a javac arg

### ISSUE THREAD

**Issue by DonnieWest** [neomake/neomake#462]
When specifying a classpath for a java project like so:

```let g:neomake_java_javac_args = ['-cp', 'some:classpath:here']```

It appears that Neomake is making the arguments silently vanish [here](https://github.com/neomake/neomake/blob/master/autoload/neomake.vim#L107) because the classpath is failing to expand and this results in an empty string

I've tried escaping the `:` as `\:` but that still seems to fail

Another way I've gotten around this is patching neomake locally by replacing the expansion with something that checks for an empty result and returns the plain string like so 

```
function! s:expandIfValid(arg) abort
        if expand(a:arg) != ""
            return expand(a:arg)
        else
            return a:arg
        endif
endfunction
call map(args, 's:expandIfValid(v:val)')
```

but this is a suboptimal solution. Any help would be appreciated!

**Comment by wsdjeg** [comment]
It is a bug，I will fix it.

**Comment by blueyed** [comment]
Hmm, I might be missing the point, but `:echo expand('some:classpath:here')` looks on in Vim?!

**Comment by wsdjeg** [comment]
@DonnieWest fixed, but for classpath, you should use `g:neomake_java_javac_classpath`.

for example `let g:neomake_java_javac_classpath = '~/test:./target/classes` in linux, in windows, you should use `let g:neomake_java_javac_classpath = "~\test;.\target\classes"`

**Comment by DonnieWest** [comment]
@wsdjeg that works quite well! Thank you so much! Looking forward to having it merged into neomake proper :)

@blueyed well, apparently some other symbol is causing the expansion to fail. This definitely explains why my efforts on my end have thus far failed

**Comment by blueyed** [comment]
@wsdjeg 
Just check the existing `sh.vader` file, which is the test by itself.
You need Vader also, of course: https://github.com/junegunn/vader.vim/
Tests can then be run in Vim by itself using `:Vader` - although I do not use this often myself.

The Makefile just wraps it for non-interactive use.
