### ISSUE TITLE
neomake E421 guifg guibg error with NVIM_TUI_ENABLE_TRUE_COLOR=1

### ISSUE THREAD

**Issue by chrzrdx** [neomake/neomake#467]
- `nvim --version`: 
```
NVIM 0.1.4
Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
```
- Operating system/version: Arch Linux, 64-bit
- Terminal name/version: st-0.6
- `$TERM`: `xterm-termite` and `st-256color` and `rxvt-unicode-256color`

### Actual behaviour

Enabling `Neomake` plugin causes error on every first write to file. (This is with the colorscheme `gruvbox` loaded)
```
"init.vim" 28L, 638C written
Error detected while processing function neomake#signs#DefineHighlights:
line   11:
E421: Color name or number not recognized: ctermfg=#fabd2f guifg=#fabd2f ctermbg=#3c3836 guibg=#3c3836
Press ENTER or type command to continue
```
If the `NVIM_TUI_ENABLE_TRUE_COLOR` flag is not set, Neomake doesn't complain. 

Minimal `init.vim` : 
```
" AUTOINSTALL VIM-PLUG {{{
if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif
"}}}

call plug#begin('~/.config/nvim/plugged')

let $NVIM_TUI_ENABLE_TRUE_COLOR=1

Plug 'benekastah/neomake', { 'on': ['Neomake'] }
autocmd! BufWritePost * Neomake

call plug#end()
```

### Expected behaviour

Should write file gracefully. Loaded colorschemes should enable ctermfg, guifg etc correctly

### Steps to reproduce using `nvim -u init.vim` (minimal init.vim provided)

On any of the three terminals above (`st`, `termite` with truecolour support and `rxvt` without it), execute : `nvim -u init.vim samplefile` and then save the file. Error message pops up.
```
"samplefile" [New] 0L, 0C written
Error detected while processing function neomake#signs#DefineHighlights:
line   11:
E421: Color name or number not recognized: ctermfg= guifg= ctermbg=Grey guibg=Grey
```

**Comment by Alok** [comment]
Same error with different colors.

**Comment by blueyed** [comment]
@chrzrdx 
It seems to come through gruvbox' GruvboxYellowBold in your case.
Are you using the dark bg variant?

What does `synIDattr(synIDtrans(hlID("GruvboxYellowBold")), 'fg')` say?

The strange thing is that it happens only on write, although the function gets called when loading the plugin already.

Please try `:debug call neomake#signs#DefineHighlights()` and inspect what is going wrong there.
(Use "s" to step into, "n" for next, and "echo var" to output some var)

**Comment by blueyed** [comment]
@Alok 
Another theme?
Are you also using NVIM_TUI_ENABLE_TRUE_COLOR?

**Comment by blueyed** [comment]
Can you try https://github.com/neomake/neomake/pull/469, please?

**Comment by blueyed** [comment]
Closing as per https://github.com/neomake/neomake/issues/468#issuecomment-226764584.
