### ISSUE TITLE
Problem: Cannot allocate color

### ISSUE THREAD

**Issue by sappo** [neomake/neomake#468]
Hi, 
the following problem occurred after upgrading to the latest version. I'm using airline and gitgutter as well if that's any help

    Error detected while processing function neomake#signs#DefineHighlights:
    line   11:
    E254: Cannot allocate color 64
    E254: Cannot allocate color 255

**Comment by sappo** [comment]
My vim version is (VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun  9 2016 09:35:16)) - This may be related to #467

**Comment by blueyed** [comment]
It's related, yes.

Can you please try `:debug call neomake#signs#DefineHighlights()` and inspect what is going wrong there, i.e. which command exactly fails.  
(Use "s" to step into, "n" for next, and "echo var" to output some var)

Are you using gvim?

**Comment by blueyed** [comment]
Can you try https://github.com/neomake/neomake/pull/469, please?

**Comment by sappo** [comment]
@blueyed tried #469 and it does fix the problem. Thanks!

**Comment by chrzrdx** [comment]
The problem is now fixed. Thanks!
