### ISSUE TITLE
Setting _exe to python3 in g:neomake_python_python_maker actually runs your code.

### ISSUE THREAD

**Issue by SquishyStrawberry** [neomake/neomake#473]
I was recently reccomended by what I presume to be a contributor to this project to use _exe for `python3` support in Neomake, however I found an interesting issue.

These are the lines added to my `init.vim`:

```
let g:neomake_python_python_maker = {
    \ '_exe': '/home/boring/bin/python3'
 \ }
```

However, when actually running `:Neomake` my code gets genuinely ran instead of just being checked.

I believe I would just need to pass extra keys to the maker, however either a standard way to use `python3` or an explanation of how to use the above properly would help.

------

Just for clarity, I was looking at the source code earlier, and I saw that the default python maker settings actually pass a bunch of code via `-c` at the command line; Would I need to "replicate" that code in my `init.vim` to have `python3` support work?

**Comment by davidosomething** [comment]
Don't override the whole maker dict, just use the exe override: `let g:neomake_python_python_exe = 'python3'`

Or if you choose to override the whole dict, you should copy over the rest of the keys and values too (add the `args` and `errorformat`)

**Comment by blueyed** [comment]
Yeah, it should be just `exe` as the key then also (when setting the whole dict).
I recommend using the `…_exe` global though.

**Comment by blueyed** [comment]
Closing this, since it appears to be a configuration issue / misunderstanding.

**Comment by SquishyStrawberry** [comment]
Thanks for the help @davidosomething @blueyed, I will be using the `g:neomake_python_python_exe` global, however I cannot find anywhere where it is documented that it's an option to use `g:neomake_{language}_{maker}_{option}` instead of setting it in the maker dictionary?

**Comment by davidosomething** [comment]
setting the maker dictionary is for defining new makers:
https://github.com/neomake/neomake/blob/master/doc/neomake.txt#L190

the python maker is already defined

to set properties:
https://github.com/neomake/neomake/blob/master/doc/neomake.txt#L193
