### ISSUE TITLE
Better default for TSC maker 

### ISSUE THREAD

**Issue by mhartington** [neomake/neomake#499]
By default, the arguments for TSC are pretty limited. 
https://github.com/neomake/neomake/blob/master/autoload/neomake/makers/ft/typescript.vim#L7

Only passing in a few options and not using a project tsconfig.json

What would be great is if it could be configured to use a projects tsconfig.json, and pass that with the `--project` flag.

From the command line you would do

```
tsc -p ./tsconfig.json
```

But this introduces another problem. Currently, all makers use the path of the current file when running the command.  But TSC needs an absolute path to the tsconfig.json.

So while `~/projects/main/app.ts` may work for the maker, it won't detect the tsconfig in `~/projects/`

Is it possible to set neomake up like this and configure the make correctly?

**Comment by blueyed** [comment]
You could use something like https://github.com/dbakker/vim-projectroot, which provides functions to get the project root and then configure the maker to use this in your vimrc (via overriding `args`).

OTOH `tsc` could get a feature to look upwards from the file to be linted for a config file, which is typically the case with linters.

**Comment by mhartington** [comment]
heh, it's been brought up before to give `tsc` a feature like this, but no luck yet. 
I'll see if I cant get something together without vim-projectroot and try to make a PR.

**Comment by mhartington** [comment]
Is there an example of using a function for `args`? According to the docs it should be able to accept one but I keep getting a warning that it's expecting a list. 

```
The 'exe' and 'args' entries can be a function (callback) or a dictionary with
an expected entry 'fn' (which has to be a function).
The function has to return a string, and receives no arguments.
```

```
  function! TSCPWD()
    return '-p ' . getcwd()
  endfunction
  function! neomake#makers#ft#typescript#tsc()
      return {
          \ 'args': (TSCPWD()),
          \ 'errorformat':
              \ '%E%f %#(%l\,%c): error %m,' .
              \ '%E%f %#(%l\,%c): %m,' .
              \ '%Eerror %m,' .
              \ '%C%\s%\+%m'
          \ }
  endfunction
```

**Comment by davidosomething** [comment]
`'args': function('TSCPWD()')`

change TSCPWD to return a VimL list (e.g. `return [ 'p' ]` )

**Comment by blueyed** [comment]
We should probably add an example to the docs..

**Comment by mhartington** [comment]
Hmm, looks like it's not currently possible. Since the commands end up being `tsc <%p> <args>`, it can't accept `--project` and a file at  the same time 😞

**Comment by mhartington** [comment]
For those curious, I have been able to get this working! 🎉 

```viml
  function! neomake#makers#ft#typescript#tsc()
      return {
            \ 'args': ['--project', getcwd(), '--noEmit'],
            \ 'append_file': 0,
            \ 'errorformat':
            \   '%E%f %#(%l\,%c): error %m,' .
            \   '%E%f %#(%l\,%c): %m,' .
            \   '%Eerror %m,' .
            \   '%C%\s%\+%m'
          \ }
  endfunction
```

The important part, which I originally missed was disabling `append_file` to the new function.

**Comment by chrisnicola** [comment]
FYI this is a huge usability fix and should submitted in a PR.
