### ISSUE TITLE
Disable a checker... 

### ISSUE THREAD

**Issue by kierun** [neomake/neomake#507]
I have some pieces of Python code that uses Twisted and others that use glib/gobject. Using pylint with those is a recipe for [yak shaving](http://www.urbandictionary.com/define.php?term=yak%20shaving) due to way too many false positives.

For example, `from glib import MainLoop` will cause a "module glib has no member MainLoop"... Well, actually, it does have one.

Is there a way to ignore pylint even if it is installed?

**Comment by davidosomething** [comment]
You can disable pylint all around by manually setting what makers you want:

```
let g:neomake_python_enabled_makers = ['pep8', 'frosted']
```
that will only use pep8 and frosted

When this PR is merged (scheduled for this weekend) you will be able to do it per-buffer, so you could check for files in `/glib/` or something if you needed: https://github.com/neomake/neomake/pull/503

**Comment by kierun** [comment]
Thank you! This works superbly.

Might I humbly suggest this was documented somewhere in the readme or FAQ?

**Comment by blueyed** [comment]
@kierun
Please consider creating a PR for it. The project lives from contributions.
