### ISSUE TITLE
Default to type=error for entries?

### ISSUE THREAD

**Issue by blueyed** [neomake/neomake#515]
Often makers do not define a type for errors.
Should we default to "error" in that case?
Or rather fix the makers that do not do so, e.g. autoload/neomake/makers/ft/lua.vim?

The signs module defaults to using the error sign for it already.

**Comment by davidosomething** [comment]
as a precendent, syntastic assumes Warn, and it is configured for that checker in particular: https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/lua/luacheck.vim#L56

Better to set a default on individual makers

**Comment by blueyed** [comment]
What about a default `g:neomake_default_error_type` setting (defaulting to `'E'`), and allow to override it per maker (although the latter should be probably just fixed by adjusting the errorformat)?
