### ISSUE TITLE
Keep old signs while processing.

### ISSUE THREAD

**Issue by sassanh** [neomake/neomake#516]
Thanks for this great extension.
It'd be great if there were an option to keep old signs (errors, warnings, etc) while `Neomake` is processing to find new signs. Is there already an option for this?

**Comment by jzelinskie** [comment]
I think this and #320 are duplicates.

Either way, is there something I can do to get this in? I'm not super familiar with vim internals, but if someone can describe what I need to do, I can probably do it.

**Comment by blueyed** [comment]
Also https://github.com/neomake/neomake/issues/741.

I think it would be OK to just change the behavior here.

I might come back to this in the next days, but otherwise just hacking and creating a PR is the way to go.. ;)

There are a lot of tests already.

**Comment by blueyed** [comment]
There is something cooking in https://github.com/neomake/neomake/pull/981.
The idea is to process/reset state only after the first job has some output, which includes the location/quickfix list.

**Comment by blueyed** [comment]
Can you test #981, please?

**Comment by sassanh** [comment]
It's working for me, thanks.

**Comment by blueyed** [comment]
@sassanh 
I'm glad it works.. :)
