### ISSUE TITLE
Error every time :Neomake is run

### ISSUE THREAD

**Issue by Morantron** [neomake/neomake#519]
I get this error everytime I run :Neomake or :Neomake!. I have a BufWritePost configured to run after saving, so I get this error every time I save:

```
Error detected while processing function neomake#Make[13]..<SNR>125_Make[85]..<SNR>125_MakeJob[50]..neomake#utils#LoudMessage[1]..neomake#utils#LogMessage:
line   15:
E121: Undefined variable: msg
E116: Invalid arguments for function writefile
Error detected while processing function neomake#Make[13]..<SNR>125_Make:
line   85:
E170: Missing :endfor
```

This happened with a `.js` file, but happens for all filetypes for me. Any idea how to debug?

Thanks! :dancers:

**Comment by davidosomething** [comment]
Confirm using regular global node eslint works first
took a guess and discovered this: https://github.com/Morantron/dotfiles/blob/master/bin/eslint

pretty sure your eslint is set up wrong
might be because you're passing in all args to eslint as a single string instead of args -- i.e. using `$*` instead of `$@`

**Comment by blueyed** [comment]
That is caused by having `neomake_logfile` set to something.
I've broken it in 0768f43.

**Comment by blueyed** [comment]
@Morantron 
> Any idea how to debug?

You would have to look for the function `neomake#utils#LogMessage` and then line 15 in it: https://github.com/neomake/neomake/blob/0768f431fe774615e9c2b994dfffbfd70ff1bb85/autoload/neomake/utils.vim#L19

From there you can see that it can actually happen that `msg` is undefined (which is the actual error).  Now it is fixed.
Thanks for the report!

**Comment by Morantron** [comment]
Awesome, it works now! Thanks a lot :clap: 

No idea why I had the `noemake_logfile` set any way lolololo
