### ISSUE TITLE
README should note installation instructions

### ISSUE THREAD

**Issue by treyhunner** [neomake/neomake#523]
README says:

Just set your `makeprg` and `errorformat` as normal, and run:

```
:Neomake!
```

I just installed neovim and was told by a friend that I should use NeoMake instead of syntastic. I do not know how to "set my `makeprg` or `errorformat` as normal". I assume I need to actually download this repository to a particular directory on my machine.

I'll be happy to update the documentation to link to an external resource with instructions once I can figure out what I'm supposed to be doing.

Thanks for the help! 😸

**Comment by treyhunner** [comment]
I think I figured out an installation process that works:

    $ git@github.com:neomake/neomake.git ~/.config/nvim/neomake
    $ cd ~/.config/nvim/
    $ ln -s neomake/autoload .
    $ ln -s neomake/doc .
    $ ln -s neomake/plugin .

**Comment by blueyed** [comment]
The section is about usage, not installation (which is missing).
The recommended method is to use a plugin manager like https://github.com/junegunn/vim-plug (or Pathogen etc).  I agree that this should be added as a section.

**Comment by blueyed** [comment]
Fixed by now: https://github.com/neomake/neomake#installation.
