### ISSUE TITLE
Add a syntax checker for Racket

### ISSUE THREAD

**Issue by HiPhish** [neomake/neomake#528]
Racket is a Lisp dialect:
http://racket-lang.org/

The PR is up at #527. My checker is using `raco expand` which is also used by the DrRacket IDE and won't have any side-effects, unlike the checker provided by Syntastic which uses `racket` directly to actually run the script and possibly execute its side-effects. The Syntastic checker can also produce false positives if a script prints text that matches the error format, which is not an issue here.

However, my maker still has a number of other issues, I would appreciate it very much if someone could help me iron out the kinks before merging.

**Comment by blueyed** [comment]
#527 has been merged, closing.
