### ISSUE TITLE
Add inline syntax keywords

### ISSUE THREAD

**Issue by mhartington** [neomake/neomake#538]
Besides adding syntax keywords to the gutter symbol, it would be great to add inline symbols to the effected line as well. Similar to Syntastic, you end being able to do 

``` vimL
highlight link SyntasticWarningLine Spellbad
highlight link SyntasticStyleErrorLine Spellbad
highlight link SyntasticStyleWarningLine Spellbad
```

And get something like 

![](https://raw.githubusercontent.com/jordwalke/VimBox/master/dotVim/images/VimJSXHint.png)

**Comment by blueyed** [comment]
We have this (highlighting of parts of the line) by now.
