### ISSUE TITLE
Overriding makers not getting applied

### ISSUE THREAD

**Issue by mhartington** [neomake/neomake#539]
According to the docs, it seems that this would be the correct way to override a maker

```vimL
    let g:neomake_typescript_tsc = {
        \ 'args': ['-m', 'commonjs', '--target', 'es5', '--emitDecoratorMetadata', '--experimentalDecorators'],
        \ 'errorformat': 'f:%l:%c: %m'
        \ }
```

But additional arguments are not being added. 

I did try 

```
function! neomake#makers#ft#typescript#tsc()
    return {
        \ 'args': [
            \ '-m', 'commonjs', '--target', 'es5', '--emitDecoratorMetadata', '--experimentalDecorators'
        \ ],
        \ 'errorformat':
                \ '%E%f %#(%l\,%c): error %m,' .
            \ '%E%f %#(%l\,%c): %m,' .
            \ '%Eerror %m,' .
            \ '%C%\s%\+%m'
        \ }
endfunction
``` 

But that ended up building all the typescript files instead of just typechecking them.
What would be the right way to do this? Happy to submit a PR if the docs are out of date at all.

**Comment by mhartington** [comment]
Alright, so solved one bit of it. The building of the file was an error on my part (missed a flag in the arguments). Still what works and what's in the docs does not match up still.

**Comment by blueyed** [comment]
You need `g:neomake_typescript_tsc_maker` (`_maker` at the end).
A PR to imrprove/fix the docs would be nice, but I think it's good already, isn't it?
