### ISSUE TITLE
No highlight of signs

### ISSUE THREAD

**Issue by mbudde** [neomake/neomake#540]
When I start nvim, neomake signs are colored white. If I source my config again the signs then gets properly highlighted.

I believe the problem is a logic error in `s:hlexists_and_is_not_cleared` [line 225](https://github.com/neomake/neomake/blob/27b803148dd16f48d1737acb4446ef1a1126ba52/autoload/neomake/signs.vim#L224-L226). When the highlight group does not exist the function returns 1 and thus the group will not be linked to the default highlight group. Changing the line to return `0` instead seems to fix the problem.

**Comment by blueyed** [comment]
Thanks for the report and fix.
Should be fixed by https://github.com/neomake/neomake/pull/542.
