### ISSUE TITLE
maker clang-tidy not sourced

### ISSUE THREAD

**Issue by CallumHoward** [neomake/neomake#541]
I have clang-tidy in my path,
```
$ which clang-tidy
/usr/local/Cellar/llvm/3.8.1/bin/clang-tidy
```
added in my `.zshrc`, and it runs correctly with:
```
$ clang-tidy WordLadder.cpp -checks="*" -- -std=c++14
```

I am using the latest release of NeoVim and neomake HEAD on OSX, and I have the following in my init.vim:
```viml
let g:neomake_cpp_enable_makers = ['clang', 'clangtidy']
let g:neomake_cpp_clangtidy_args = ['-checks="*"', '--', '-std=c++14']
let g:neomake_cpp_clang_args = ['-std=c++14', '-Wextra', '-Wall', '-Wno-unused-parameter', '-g']
```

My problem is clang-tidy doesn't seem to be run, and I can't spot why this would be from the Neomake source. Additionally, although `g:neomake_cpp_clang_args` works correctly, I am not certain that `g:neomake_cpp_clangtidy_args` is the right variable name.

I would appreciate any assistance!

@benekastah

**Comment by alexozer** [comment]
There's a typo: enable**d**_makers

So the first line of the vim config should be:

```vim
let g:neomake_cpp_enabled_makers = ['clang', 'clangtidy']
```

**Comment by blueyed** [comment]
Assuming this is fixed / caused by this typo.

Thanks, @alexozer!

**Comment by CallumHoward** [comment]
Thanks @alexozer, this did indeed fix the issue, silly me. For anyone who finds their way here, after much experimentation I found that these options worked:
```
let g:neomake_cpp_clangtidy_args = ['-extra-arg=-std=c++14', '-checks=\*']
```
The `--` stops the clangtidy maker working entirely, and without it the first line of the location list always reads "No compilation database found in {/Users/username/path} or any parent directory", even when no other warnings or errors are found. I will try and investigate this further.
