### ISSUE TITLE
New Rust error message format

### ISSUE THREAD

**Issue by antoyo** [neomake/neomake#549]
Hello.
Rust nightly now shows [errors in a new format](https://blog.rust-lang.org/2016/08/10/Shape-of-errors-to-come.html).
It would be nice to support it in neomake (if the new format is fixed).
Thanks.

**Comment by antoyo** [comment]
[The new format is now in Rust stable.](https://blog.rust-lang.org/2016/09/29/Rust-1.12.html)
So, I believe it we should switch to it now.
I currently use this `errorformat`, but it does not always work:
```vim
let g:neomake_rust_clippy_maker = {
    \ 'exe': 'cargo',
    \ 'args': ['clippy'],
    \ 'errorformat':
        \   '%-Gerror: Could not compile%.%#,'
        \.  '%-Gerror: aborting due to%.%#,'
        \.  '%Eerror[%.%#]: %m,%C\\s%#--> %f:%l:%c,'
        \.  '%Eerror: %m,%C\\s%#--> %f:%l:%c,'
        \.  '%Wwarning: %m,%C\\s%#--> %f:%l:%c,'
        \.  '%Ihelp: %m,'
        \.  '%I\\s%#= help: %m,'
        \.  '%I\\s%#= note: %m,'
        \,
    \ 'append_file': 0,
    \ }
```

**Comment by blueyed** [comment]
Check https://github.com/neomake/neomake/pull/613 I guess?!
Closing this in favor of #613.

**Comment by blueyed** [comment]
@antoyo 
Please provide feedback there, and then we can get it finalized/merged.
