### ISSUE TITLE
Fix vimlint errors with Java maker

### ISSUE THREAD

**Issue by blueyed** [neomake/neomake#569]
There are 3 issues with the Java maker:
```
./autoload/neomake/makers/ft/java.vim:137:31:Error: EVL103: unused argument `a:classpathFile`
./autoload/neomake/makers/ft/java.vim:369:65:Error: EVL104: variable may not be initialized on some execution path: `l:cp`
./autoload/neomake/makers/ft/java.vim:359:29:Error: EVL102: unused variable2 `l:classes`
```

@wsdjeg 
Can you take a look at them, please?

Ref: #437 

I'll look at the other ones that sneaked in, since this job is allowed to fail, which I'd like to change.

**Comment by wsdjeg** [comment]
@blueyed this issue can be closed.

**Comment by blueyed** [comment]
No:

```
% make vimlint-errors
build/vimlint/bin/vimlint.sh -E -l build/vimlint -p build/vimlparser ./plugin ./autoload
./autoload/neomake/makers/ft/java.vim:137:31:Error: EVL103: unused argument `a:classpathFile`
./autoload/neomake/makers/ft/java.vim:368:65:Error: EVL104: variable may not be initialized on some execution path: `l:cp`
./autoload/neomake/makers/ft/java.vim:358:29:Error: EVL102: unused variable2 `l:classes`
```

**Comment by blueyed** [comment]
@wsdjeg 
I would really appreciate if you would look into those finally.

**Comment by wsdjeg** [comment]
oh,sorry I will fix it tonight.

**Comment by wsdjeg** [comment]
line 137 and line 358 should has no error, it is the issue with vimlint. in line 137 `a:classpathFile` has been used in py command. in line 358 the classes as has been used by
```
for classes in out_putdir                           
       let cp .= s:ClassSep().classes
endfor
```
ok, line 368 is a error.

**Comment by blueyed** [comment]
FYI: I've deleted the TODO label.. it does not add much information, does it? ;)

**Comment by wsdjeg** [comment]
yeah, thanks
