### ISSUE TITLE
Endless loop with using BufEnter autocommand and neomake_open_list

### ISSUE THREAD

**Issue by CrashyBang** [neomake/neomake#578]
Could be related to [#323](https://github.com/neomake/neomake/issues/323)

Was not sure if this was the right place to log so also on [vi.stackexchange](http://vi.stackexchange.com/questions/9426/neomake-hanging-when-using-eslint)

I have been following the following two tutorials to try and set up `eslint` and `Neomake`:

 - [Linting code with Neomake and Neovim][1]
 - [Linting code with Neovim and Neomake - ESLint edition][2]

So I have the following minimal `init.vim`

    call plug#begin('~/.vim/plugged')
    
    Plug 'neomake/neomake'
    
    call plug#end()
    
    autocmd! BufWritePost,BufEnter * Neomake
    let g:neomake_verbose=3
    let g:neomake_open_list = 2
    let g:neomake_javascript_enabled_makers = ['eslint']
    
    " neomake
    nmap <Leader><Space>o :lopen<CR>      " open location window
    nmap <Leader><Space>c :lclose<CR>     " close location window
    nmap <Leader><Space>, :ll<CR>         " go to current error/warning
    nmap <Leader><Space>n :lnext<CR>      " next error/warning
    nmap <Leader><Space>p :lprev<CR>      " previous error/warning

The problem is when I save `Neomake` hangs with the following message:

`Neomake: Starting: eslint -f compact /home/otis/Developer/test/index.js`

If i run that command manually outside of `nvim` like so:

`eslint -f compact /home/otis/Developer/test/index.js`

I receive the following output:

    /home/otis/Developer/test/index.js: line 1, col 1, Error - Unexpected var, use let or const instead. (no-var)
    /home/otis/Developer/test/index.js: line 1, col 5, Error - 'a' is defined but never used. (no-unused-vars)
    /home/otis/Developer/test/index.js: line 1, col 9, Error - Strings must use singlequote. (quotes)
    
    3 problems

Which is good it means `eslint` is working but I am getting nothing back from `Neomake`.

If I run `:lopen` the window pops up and then instantly closes like below:

[![Window open then close][3]][3]

My `vim`/`nvim` knowledge is somewhat basic so please be explicit in responses.

  [1]: https://www.gregjs.com/vim/2015/linting-code-with-neomake-and-neovim/
  [2]: https://www.gregjs.com/vim/2015/linting-code-with-neovim-and-neomake-eslint-edition/
  [3]: http://i.stack.imgur.com/Rmoyt.gif

**Comment by blueyed** [comment]
It does not hang, does it?  You do not have to press `Ctrl-C` etc, right?

Please try it again with `let g:neomake_verbose = 3`, and post the output from `:mess` afterwards here.

**Comment by CrashyBang** [comment]
Sorry hangs is probably the wrong word what I more mean was the:

`Neomake: Starting: eslint -f compact /home/otis/Developer/test/index.js`

Sits there and does not appear to be doing anything, sorry for confusion.

Output of `:mess`:

```
Neomake: eslint completed with exit code 0                                                                                                            
"index.js" [New] 1L, 13C written                                                                                                                      
Neomake: eslint completed with exit code 1                                                                                                            
Neomake: eslint completed with exit code 1                                                                                                            
Neomake: eslint completed with exit code 1                                                                                                            
```

**Comment by blueyed** [comment]
That is without `let g:neomake_verbose = 3`, right?

**Comment by CrashyBang** [comment]
From the above snippet this is what I have enabled:
```vim
let g:neomake_verbose=3
let g:neomake_open_list = 2
let g:neomake_javascript_enabled_makers = ['eslint']
```

The other options would not be conflicting right?

I think it may be using the global `eslint` would this effect it in any way?

Cheers.

**Comment by blueyed** [comment]
My point is that `let g:neomake_verbose=3` should produce more output, not just the "Neomake: eslint completed with exit code X".
So please try it again.  You need to set it before running `:Neomake` of course.

But "exit code 1" indicates that it found some errors.  Then the entries are probably not being handled by the "errorformat" correctly.
There are probably some issues regarding eslint etc.  What version are you using?  Maybe the format has changed?

**Comment by CrashyBang** [comment]
Hey @blueyed,

Running `eslint` **v3.4.0**.

Okay first thing `let g:neomake_verbose=3` was being used after `:Neomake`.

So here is the output from `:mess` now:

```
Neomake: Starting: eslint -f compact /home/otis/Developer/test/index.js                                                                               
Neomake: [#2] stdout: eslint: ['/home/otis/Developer/test/index.js: line 1, col 1, Error - Unexpected var, use let or const instead. (no-var)', '/home
/otis/Developer/test/index.js: line 1, col 5, Error - ''a'' is defined but never used. (no-unused-vars)', '/home/otis/Developer/test/index.js: line 1,
 col 9, Error - Strings must use singlequote. (quotes)', '', '3 problems', '']                                                                        
Neomake: [#2] eslint: processing 5 lines of output.                                                                                                   
Neomake: File-level errors cleaned in buffer 1                                                                                                        
Neomake: [#2] Removing invalid entry: {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'maker_name': 'eslint', 'pattern'
: '', 'text': ''}                                                                                                                                     
Neomake: [#2] Removing invalid entry: {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'maker_name': 'eslint', 'pattern'
: '', 'text': '3 problems'}                                                                                                                           
Neomake: Nothing to make: no enabled makers.                                                                                                          
Neomake: [#2] exit: eslint: 1                                                                                                                         
Neomake: eslint completed with exit code 1                                                                                                            
Neomake: File-level errors cleaned in buffer 1                                                                                                        
Neomake: next makers [eslint]                                                                                                                         
Neomake: Starting: eslint -f compact /home/otis/Developer/test/index.js                                                                               
Neomake: [#3] stdout: eslint: ['/home/otis/Developer/test/index.js: line 1, col 1, Error - Unexpected var, use let or const instead. (no-var)', '/home
/otis/Developer/test/index.js: line 1, col 5, Error - ''a'' is defined but never used. (no-unused-vars)', '/home/otis/Developer/test/index.js: line 1,
 col 9, Error - Strings must use singlequote. (quotes)', '', '3 problems', '']                                                                        
Neomake: [#3] eslint: processing 5 lines of output.                                                                                                   
Neomake: File-level errors cleaned in buffer 1                                                                                                        
Neomake: [#3] Removing invalid entry: {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'maker_name': 'eslint', 'pattern'
: '', 'text': ''}                                                                                                                                     
Neomake: [#3] Removing invalid entry: {'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'maker_name': 'eslint', 'pattern'
: '', 'text': '3 problems'}                                                                                                                           
Neomake: Nothing to make: no enabled makers.                                                                                                          
Neomake: [#3] exit: eslint: 1                                                                                                                         
Neomake: eslint completed with exit code 1                                                                                                            
Neomake: File-level errors cleaned in buffer 1 
```

Furthermore it now keeps trying to run the lint command again and again `:mess` went on for ages but I only copied the chunk twice.

Just encase this helps this is the output when running: `eslint -f compact /home/otis/Developer/test/index.js` directly from the terminal:

```
/home/otis/Developer/test/index.js: line 1, col 1, Error - Unexpected var, use let or const instead. (no-var)
/home/otis/Developer/test/index.js: line 1, col 5, Error - 'a' is defined but never used. (no-unused-vars)
/home/otis/Developer/test/index.js: line 1, col 9, Error - Strings must use singlequote. (quotes)

3 problems
```

Cheers.

**Comment by blueyed** [comment]
The verbose output looks OK (it just removes the "3 problems" as invalid, and the empty line).

The "Neomake: next makers [eslint]" looks weird however: looks like there is chaining, which should not be the case I guess.  Also the "Neomake: Nothing to make: no enabled makers." inbetween.

Is your filetype just "javascript"?  See `:echom &ft`.

> Furthermore it now keeps trying to run the lint command again and again :mess went on for ages but I only copied the chunk twice.

That also should not happen.

Please try again in a new Neovim session, enable verbose mode (`let g:neomake_verbose = 3`), disable the "More" prompt (`:set nomore`) and then just call `:Neomake` once on the file.  Does it keep running then multiple times or even "forever"?
You can cancel it using `Ctrl-C` then.

Then please post the output from `:mess` here again.
You can use `:redir @+> | mess | redir END` to copy it to your clipboard.

**Comment by blueyed** [comment]
Also try it with `let g:neomake_open_list = 0` and 1 afterwards (without copying messages etc), just to see if that is a problem.

**Comment by blueyed** [comment]
Oh, your `autocmd! BufWritePost,BufEnter * Neomake` triggers Neomake for the location list apparently!

Try it just with `autocmd! BufWritePost * Neomake` for now.

**Comment by blueyed** [comment]
You should also group it:

```vim
augroup vimrc_neomake
  au!
  autocmd BufWritePost * Neomake
augroup END```

**Comment by CrashyBang** [comment]
Hey @blueyed will try this as soon as I get home and let you know what happens.

Cheers for all the information :).

Cheers.

**Comment by blueyed** [comment]
Yeah, the "BufEnter" together with `g:neomake_open_list = 2` totally borks it and goes into the loop also.
I will look into that.
It is also bad with `g:neomake_open_list = 1`, where you never can quit the location list then in case of errors.

**Comment by blueyed** [comment]
For reference, the problem comes from here: https://github.com/neomake/neomake/blob/19b637ebd9fc35b3a0fe1e0d52eadf66e03631d7/autoload/neomake.vim#L345-L359.

The `lwindow` and `wincmd p` in there trigger the `BufEnter` autocommand also.

**Comment by CrashyBang** [comment]
Hey @blueyed,

The following fixed the issue:

```
augroup vimrc_neomake
  au!
  autocmd BufWritePost * Neomake
augroup END
```

One question every time I write I get the following message `Press ENTER or type command to continue` and I have to press enter to continue, is this intended behaviour??? (Sorry still wrapping my head around vim).

Cheers.

**Comment by blueyed** [comment]
The hit-enter is caaused by `neomake_verbose = 3`. You should not enable it normally.
See also https://github.com/neomake/neomake/pull/580, in case you want to test a fix for this.

**Comment by CrashyBang** [comment]
Hey @blueyed,

Awesome cheers, do you want to close this or leave open until infinite loop issue is resolved?

Cheers.

**Comment by blueyed** [comment]
Let's leave it open: it is a very common issue after all, and there need to be improvements: for the beginning I think we should skip `:Neomake` if it's run via the open_list handling.

**Comment by blueyed** [comment]
Closing it in favor of https://github.com/neomake/neomake/issues/586 - which is clearer.. :)
