### ISSUE TITLE
Pass cwd to jobstart

### ISSUE THREAD

**Issue by blueyed** [neomake/neomake#582]
When a maker has a `cwd` argument, we can pass that to `jobstart` with Neovim directly.

This is not yet possible in Vim: https://github.com/vim/vim/issues/1024.

Should be done after https://github.com/neomake/neomake/pull/575 to avoid conflicts.

**Comment by blueyed** [comment]
It gets handled better by now, closing.
IIRC passing in `cwd` would be the same as `cd`ing manually before/after (what we're doing now).

**Comment by wsdjeg** [comment]
@blueyed `cd` will change the current dir of vim, I think it does not good enough.

**Comment by blueyed** [comment]
@wsdjeg 
We're cd'ing back of course.
Do you mean something else?
