### ISSUE TITLE
Skip Neomake run when being invoked during open_list handling

### ISSUE THREAD

**Issue by blueyed** [neomake/neomake#586]
We should have a lock in place to not run during the autocommands from our own `open_list` handling (i.e. when Neomake is configured to run on BufEnter and `open_list = {1,2}` is used..
Ref: https://github.com/neomake/neomake/issues/578.

**Comment by bounceme** [comment]
here was my workaround for a similar issue:
https://gist.github.com/bounceme/a2cb5c341af1b33c48689f64c678235f#file-neomakefly-vim-L6

neomake was being run in the command line window and giving errors (q:)

**Comment by bounceme** [comment]
here are the errors, 
```
Error detected while processing function neomake#MakeHandler[37]..<SNR>51_RegisterJobOutput[8]..<SNR>51_ProcessJobOutput:
line   14:
E11: Invalid in command-line window; <CR> executes, CTRL-C quits:             caddexpr a:lines
Error detected while processing function neomake#MakeHandler[37]..<SNR>51_RegisterJobOutput:
line    8:
E171: Missing :endif
Error detected while processing function neomake#MakeHandler:
line   37:
E171: Missing :endif
```
one way to reproduce:
1. :NeomakeSh brew update (or other slow command)
2. Open command line window quickly

**Comment by blueyed** [comment]
@bounceme 
I think those are a bit different issues: the 2nd one looks like we should/need to run this from the window where Neomake is invoked after all: this is relevant also for different/multiple tab pages, where the quickfix window of the original tab should be used.  Please create a new issue for that.

As for the 1st comment: I think that should be handled then by our wrapper indeed: only run for real files, so it's a valid point here.
