### ISSUE TITLE
Add maker for vim-vimhelplint

### ISSUE THREAD

**Issue by saaguero** [neomake/neomake#587]
Would be nice to have a maker for vim documentation files.

As per @blueyed recommendation, there is the project [vimhelplint](https://github.com/machakann/vim-vimhelplint) but as far as I know, it should provide us a wrapper kind of similar to the one from [vim-vimlint](https://github.com/syngan/vim-vimlint/blob/master/bin/vimlint.sh), or better yet a wrapper  in python such as in [vint](https://github.com/Kuniwak/vint/blob/master/bin/vint) so to make this work in Windows as well.

**Comment by blueyed** [comment]
I think this should hook in like it does with Syntastic - we could maybe even support (parts of) the same interface.  See https://github.com/neomake/neomake/issues/428.
But then it won't run async - for that we would need to be able running Vim functions via `jobstart()`.

**Comment by davidosomething** [comment]
there is alternatively `:VimhelpLintEcho`

If that was modified to use `echomsg` instead, you might be able to do:

`nvim -R -c "try | set nomore | redir>>/dev/stdout |  VimhelpLintEcho | redir END | finally | qall! | endtry" doc/neomake.txt` where `doc/neomake.txt` is the helpfile in question

**Comment by blueyed** [comment]
We have that in autoload/neomake/makers/ft/help.vim by now.
