### ISSUE TITLE
Rustc/cargo error format broken

### ISSUE THREAD

**Issue by SethDusek** [neomake/neomake#592]
The new nightly format is different from the previous format, hence the cargo maker does not work anymore

**Comment by blueyed** [comment]
Can you provide a PR, or at least more information about the before/after?

**Comment by SethDusek** [comment]
@blueyed https://blog.rust-lang.org/2016/08/10/Shape-of-errors-to-come.html I can't find the pull request that added this format, but will look for it

**Comment by blueyed** [comment]
Heh, I've meant a PR to fix it.. :)

**Comment by SethDusek** [comment]
Well I can try to fix it myself, but I'm not familiar with the neomake errorformat, where can I find docs on that?

**Comment by blueyed** [comment]
@SethDusek 
It is Vim's own errorformat, see `:h errorformat`.  It is not easy to grasp though.
Check out if there is anything better / fixed in Syntastic, too.
