### ISSUE TITLE
Spellcheck won't handle bash-files correctly anymore

### ISSUE THREAD

**Issue by edwardsmit** [neomake/neomake#602]
### Intro
Since the detection of the actual filetype has been lifted from Shellcheck to Neomake my bash-files are no longer checked correctly.

### Issue
I have bash-files in a shared repository which end on `*.sh` but are `bash` files by definition of a `#!/usr/bin/env bash`
Previously Spellcheck would figure this out, but since b918d4ad6f5735b7f575944e33abcc01c5dc5ef3 Neomake will tell Shellcheck that this is a `sh` file. Shellcheck won't try it's detection and uses `sh` rules which aren't the `bash` rules

### Steps to reproduce
1. Create a file`test.sh` with the following contents:
```shell
#!/usr/bin/env bash

test() {
  local test
  test=1
  echo $test
}

test
```
2. Neomake will complain about the usage of `local`
3. From the command line run `shellcheck -fgcc ./test.sh` so without the forced insertion of the `sh` filetype and see that it is error- and warning-free

### Output of the ":NeomakeInfo" command
```shell
= Neomake debug information =                                                                                                                                                                               
Async support: 1                                                                                                                                                                                            
Current filetype: sh                                                                                                                                                                                        
== Enabled makers ==                                                                                                                                                                                        
For the current filetype (with :Neomake): ['sh', 'shellcheck']
You can define g:neomake_sh_enabled_makers to configure it (or b:neomake_sh_enabled_makers).
For the project (with :Neomake!): []
You can define g:neomake_enabled_makers to configure it.
== Settings ==
g:neomake_open_list = 2
g:neomake_javascript_enabled_makers = ['eslint']
g:neomake_javascript_eslint_args = ['-f', 'compact', '--fix']
```

### Versions
```shell
NVIM v0.1.6-72-gfe06e2a
Build type: Dev
```

### Output from ":messages"
```shell
Neomake: sh completed with exit code 0
Neomake: shellcheck completed with exit code 1
```

**Comment by blueyed** [comment]
Thanks for the report.

I've assumed that Vim would set `ft=bash`, but apparently it is `ft=sh` with `b:is_bash=1`.

I suggest passing nothing to shellcheck in case there is a shebang line then.
