### ISSUE TITLE
No statusline info if g:neomake_*_maker dict is given

### ISSUE THREAD

**Issue by dajuno** [neomake/neomake#608]
# Issue
Using Neomake with python flake8, I don't get a statusline info (type E:23, W:43) if I specify options via

    let g:neomake_python_flake8_maker = {
        \ 'args': ['--ignore=F403,N806,N802,N803,E226']
    \ }

## Steps to reproduce

python3 + flake8 + python file, e.g.,
    
    import unknownpkg
    print('hi)

Minimal init.vim: 

    " load *neomake* with plugin manager of your choice!
    " ...
    set statusline+=%#ErrorMsg#%{neomake#statusline#LoclistStatus()}
    let g:neomake_python_enabled_makers = ['flake8']
    let g:neomake_python_flake8_maker = {
        \ 'args': ['--ignore=F403,N806,N802,N803,E226'],
        \ 'errorformat': '%f:%l:%c: %m'
    \ }

If the last 4 lines are commented, it works and there is a "E:1W:1" output in the statusline. Otherwise, no info in the statusline.

## Output of the ":NeomakeInfo" command
= Neomake debug information =
Async support: 1
Current filetype: python
== Enabled makers ==
For the current filetype (with :Neomake): ['flake8']
You can define g:neomake_python_enabled_makers to configure it (or b:neomake_python_enabled_makers).
For the project (with :Neomake!): []
You can define g:neomake_enabled_makers to configure it.
== Settings ==
g:neomake_python_flake8_maker = {'errorformat': '%f:%l:%c: %m', 'args': ['--ignore=F403,N806,N802,N803,E226']}
g:neomake_serialize = 1
g:neomake_python_enabled_makers = ['flake8']
g:neomake_verbose = 3

## Versions
NVIM 0.1.5
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -
Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/b
uild/config -I/build/neovim/src/neovim-0.1.5/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/
src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

## Output from ":messages"

Neomake: Starting: flake8 --ignore=F403,N806,N802,N803,E226 /home/david/work/fenics/nitsche/neomake_test.py
Neomake: [#1] stdout: flake8: ['/home/david/work/fenics/nitsche/neomake_test.py:1:13: E401 multiple imports on one line', '/home/david/work/fenics/nitsche/neomake_test.py
:3:15: E901 SyntaxError: EOL while scanning string literal', '']
Neomake: [#1] flake8: processing 2 lines of output.
Neomake: File-level errors cleaned in buffer 1
Neomake: Placing sign: sign place 5000 line=1 name=neomake_err buffer=1
Neomake: Placing sign: sign place 5001 line=3 name=neomake_err buffer=1
Neomake: [#1] exit: flake8: 1
Neomake: flake8 completed with exit code 1
Neomake: WideMessage echo flake8: E401 multiple imports on one line
Neomake: WideMessage echo flake8: E901 SyntaxError: EOL while scanning string literal

**Comment by blueyed** [comment]
That's because your custom errorformat does not specify the type for the errors.
(https://github.com/neomake/neomake/blob/f563e02e884cc5ff72fbc6da93081b91f9e6ac7b/autoload/neomake/makers/ft/python.vim#L60-L70)

You should only set `g:neomake_python_flake8_maker_args`.

**Comment by blueyed** [comment]
Closing, please re-open in case I was wrong.

**Comment by dajuno** [comment]
The setting `let g:neomake_python_flake8_maker_args = '[--ignore=F403,N806,N802,N803,E226']` is ignored. No `--ignore` arg is passed to flake8, according to `:messages`: 

    Neomake: Starting: flake8 --format=default path/to/file.py

**Comment by blueyed** [comment]
Sorry, it should be `g:neomake_python_flake8_args`, see `:h neomake-makers-properties`.
