### ISSUE TITLE
The airline statusline funcref function('airline#extensions#neomake#apply') has already been added.

### ISSUE THREAD

**Issue by l1Dan** [neomake/neomake#609]
The airline statusline funcref function('airline#extensions#neomake#apply') has already been added.

<img width="1060" alt="screen shot 2016-09-14 at 00 35 30" src="https://cloud.githubusercontent.com/assets/7961100/18482613/671e055a-7a13-11e6-8420-a7d14673b499.png">

How to fix it？

**Comment by Bipsy** [comment]
👍

**Comment by jwkvam** [comment]
this https://github.com/vim-airline/vim-airline/commit/3c33251ee79b80d4d93a0134783eed0ce55b70ef broke things for me so I pinned airline to the previous commit https://github.com/vim-airline/vim-airline/commit/1c052e39b15c3d4efd37f83cdf7f12ef3721741f

**Comment by saamalik** [comment]
@jwkvam could you please try again with the latest vim-airline and neomake plugins?

**Comment by jwkvam** [comment]
Yep working now, thanks 👍
