### ISSUE TITLE
Cannot customize clang maker.

### ISSUE THREAD

**Issue by Ron89** [neomake/neomake#611]
# Issue

Neomake don't read my `g:neomake_c_clang_maker` for maker options.
## Steps to reproduce

Please execute `:let g:neomake_verbose = 3` to enable verbose output, which
might help showing the issue already.  Please provide the output from
`:messages` afterwards (see below).
1. set the variable mid session by setting g:neomake_c_clang_maker to

'''
let g:neomake_c_clang_maker.args = g:neomake_c_clang_maker.args+[
            \ '-x', 'c', '',
            \ '-I', '''/usr/mewo/include''',
            \ '-I', '''/Users/meow/another_nice_kitten/include''',
            \ '-I', '''/Users/wong/bad_dog/include/''',
            \ '-Wall']
'''
2. enable clang maker by `g:neomake_c_enabled_maker=["clang"]`
3. open a c code. 

Then the default clang command without including any of the header files I want to include is called.

**Comment by dkasak** [comment]
Could you please supply:

- output of `:NeomakeInfo`
- output of `:version`
- output of `:messages` after `let g:neomake_verbose = 3` is set

**Comment by HiPhish** [comment]
Same problem here. I can't figure out how to pass new arguments to clang. Here is my attempt:
```vim
let g:neomake_c_clang_args = [
	\'-I/usr/local/Cellar/guile/2.0.12_1/include/guile/2.0',
	\'-I/usr/local/opt/gmp/include',
	\'-I/usr/local/opt/readline/include',
	\'-I/usr/local/Cellar/bdw-gc/7.6.0/include'
\] + g:neomake_c_clang_args
```
Vim complains that the variable does not exist, `E121: Undefined variable: g:neomake_c_clang_args`.

#### Neomake debug information
Async support: 1
Current filetype: c

##### Enabled makers
For the current filetype (with :Neomake):
 - clang
   errorformat: '%-G%f:%s:,%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%I%f:%l:%c: note: %m,%f:%l:%c: %m,%f:%l: %trror: %m,%f:%l: %tarning: %m,%I%f:%l: note: %m,%f:%l: %m'
   args: ['-fsyntax-only', '-Wall', '-Wextra']
   get_argv: function('364')
   exe: 'clang'
NOTE: you can define g:neomake_c_enabled_makers to configure it (or b:neomake_c_enabled_makers).

For the project (with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_open_list = 2
g:neomake_informational_sign = {'texthl': 'LineNr', 'text': 'ℹ︎ '}
g:neomake_error_sign = {'texthl': 'Error', 'text': '✕ '}
g:neomake_verbose = 0
g:neomake_place_signs = 1
g:neomake_message_sign = {'texthl': 'LineNr', 'text': '! '}
g:neomake_warning_sign = {'texthl': 'Error', 'text': '⚠︎ '}

shell: /bin/bash
shellcmdflag: -c
Windows: 0
```

My `:version`
```
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCL
UDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161130-24818-wueuur/neovim-0.1.7/build/config -I/tmp/neovim-20161130-24818-wueuur/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/lo
cal/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20161130-24818-wueuur/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20161130-24818-wueuur/neovim-0.1.7/build/include
Compiled by hiphish@Aleksandars-iMac.local

Optional features included (+) or not (-): +acl   +iconv    -jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.7/share/nvim"
```

**Comment by HiPhish** [comment]
BTW, if I copy the original settings in by hand it works:
```vim
let g:neomake_c_clang_args = [
	\'-fsyntax-only', '-Wall', '-Wextra',
	\'-I/usr/local/Cellar/guile/2.0.12_1/include/guile/2.0',
	\'-I/usr/local/opt/gmp/include',
	\'-I/usr/local/opt/readline/include',
	\'-I/usr/local/Cellar/bdw-gc/7.6.0/include'
\]
```
But this is not as robust has automatically pulling in the original arguments.

**Comment by tweekmonster** [comment]
@HiPhish You're using deoplete-clang2, right?  Does it not fill in the compile flags for you?

**Comment by HiPhish** [comment]
@tweekmonster I have been jumping back and forth between deoplete-clang and deoplete-clang2. Neither of them makes me really happy, both have something the other is lacking. This is off-topic, but I don't like the sorting in deoplete-clang2 and I like the extra-information deoplete-clang gives me.

**Comment by tweekmonster** [comment]
@HiPhish raise issues in my repo then.  deoplete-clang is no longer maintained.  Sorting can be worked on and deoplete-clang's type information is sometimes wrong 😕

Anyways, to contribute to the topic, there's an undocumented feature you can use:

```vim
let linter = neomake#makers#ft#c#clang()
function linter.fn(jobinfo) abort
  let maker = copy(self)
  if filereadable('.clang')
    let maker.args += split(join(readfile('.clang'), "\n"))
  endif
  return maker
endfunction

let g:neomake_c_clang_maker = linter
```

Then you could keep the flags in a `.clang` file (which deoplete-clang2 supports):

```
-I/usr/local/Cellar/guile/2.0.12_1/include/guile/2.0
-I/usr/local/opt/gmp/include
-I/usr/local/opt/readline/include
-I/usr/local/Cellar/bdw-gc/7.6.0/include
```

**Comment by blueyed** [comment]
Closing.

As for the original issue:
`let g:neomake_c_clang_maker.args` should have been `let g:neomake_c_clang_maker_args`.
