### ISSUE TITLE
Airline not updating (Neomake)

### ISSUE THREAD

**Issue by saad-cliqr** [neomake/neomake#617]
# Airline not updating (even for Neomake)

## Steps to reproduce

1. With the latest version of stable NeoVim and latest Airline
2. Edit any source file, e.g: sh file
3. Create a syntax error, e.g: append a closed ```fi``` at the end
4. Save the file, ```:w``` 
5. Run ```:Neomake```
6. Observe that Location list is updated with syntax error from NeoMake
7. However, Airline statusbar still doesn't show syntax error.
8. Even if ```:AirlineRefresh``` is called, still doesn't show any messages.

## Output of the ":NeomakeInfo" command
= Neomake debug information =
Async support: 1
Current filetype: sh
== Enabled makers ==
For the current filetype (with :Neomake): ['sh']
You can define g:neomake_sh_enabled_makers to configure it (or b:neomake_sh_enabled_makers).
For the project (with :Neomake!): []
You can define g:neomake_enabled_makers to configure it.
== Settings ==
g:neomake_verbose = 3

## Versions

:version
NVIM 0.1.5-dev
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector
-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160621-58830-10yzryr/build/config -I/tmp/neovim-20160621-58830-10yzryr/src -I/tmp/neovim-20160621-58830-10
yzryr/deps-build/usr/include -I/tmp/neovim-20160621-58830-10yzryr/deps-build/usr/include -I/tmp/neovim-20160621-58830-10yzryr/deps-build/usr/include -I/tmp/neovim-20160621-58830-10yzryr/deps-build/usr/inc
lude -I/tmp/neovim-20160621-58830-10yzryr/deps-build/usr/include -I/tmp/neovim-20160621-58830-10yzryr/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20
160621-58830-10yzryr/build/src/nvim/auto -I/tmp/neovim-20160621-58830-10yzryr/build/include
Compiled by saamalik@SAAMALIK-M-811J

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"

## Output from ":messages"
"sync-bundles.sh" 2L, 33C written
Neomake: Starting: /bin/sh -n /Users/saamalik/.vim/sync-bundles.sh
Neomake: [#3] stderr: sh: ['/Users/saamalik/.vim/sync-bundles.sh: line 2: syntax error near unexpected token `fi''', '/Users/saamalik/.vim/sync-bundles.sh: line 2: `fi''', '']
Neomake: [#3] sh: processing 2 lines of output.
Neomake: File-level errors cleaned in buffer 2
Neomake: Placing sign: sign place 5000 line=2 name=neomake_err buffer=2
Neomake: [#3] exit: sh: 2
Neomake: sh completed with exit code 2
= Neomake debug information =
Async support: 1
Current filetype: sh

**Comment by saad-cliqr** [comment]
@blueyed I'll try to debug this shortly, but any pointers on where to start?

**Comment by blueyed** [comment]
Not really.. use `let g:neomake_verbose = 3` and see what happens.
Then you can add new debug logging yourself.  You can then reload the file using `:source` and there are ways to debug calls / and/or set breakpoints, see `:debug`.  I recommend checking out https://github.com/tpope/vim-scriptease.

**Comment by saad-cliqr** [comment]
@blueyed I got Neomake error messages to display in airline (thanks for the hints on how to debug). I would recommend that we move the neomake extension to the [airline](https://github.com/vim-airline/vim-airline) repo (consistent with majority of airline extensions). If you're okay with this, the extension code really becomes as simple as this:

```vim
" vim: ts=4 sw=4 et

if exists('g:neomake_airline') && g:neomake_airline == 0
    finish
endif

function! airline#extensions#neomake#get_warnings()
    return neomake#statusline#LoclistStatus()
endfunction

function! airline#extensions#neomake#init(ext)
    call airline#parts#define_function('neomake', 'airline#extensions#neomake#get_warnings')
endfunction
```
_The code is missing a few parts of whether neomake exists or not, but this should be be trivial to add_. Anyway, let me know if you're okay with moving this portion to the airline repo; I'll create a PR for vim-airline first to include neomake extension and once/if it gets accepted I can send a PR to delete this source from Neomake.
