### ISSUE TITLE
Adding support for R

### ISSUE THREAD

**Issue by ghost** [neomake/neomake#619]
Big thanks for all your work with with NeoMake. 

I was wondering if you could consider adding support for linting R code - it's really popular among data analysts. It only requires a single checker that is already available for syntastic:

https://github.com/jimhester/lintr

Thanks in advance!

**Comment by blueyed** [comment]
Please consider creating a PR!
Especially since there is a Syntastic maker already, where you can extract the `'errorformat'` from.  There are plenty of makers already that can serve as an example.

**Comment by JLCCI** [comment]
Thanks I might try though I am absolutely new to vim and have little programming experience so it will not be easy.

**Comment by blueyed** [comment]
Consider it an exercise then.. :)
No rush.. you can create a PR, and we can work out from there.

**Comment by javiertury** [comment]
Just wanted to add that syntastic has disabled lintr and svtools by default because they are said to execute parts of the code they are checking(which is not very secure). The 3rd one, lint, is oudated and no longer in cran repos.

**Comment by FvD** [comment]
I have enabled `lintr` just by adding the following in my init.vim:

```
let g:neomake_r_lintr_maker = {
    \ 'exe': 'R',
    \ 'args': ['-e lintr::lint("%:p")'], 
    \ 'errorformat': 
        \ '%W%f:%l:%c: style: %m,' .
        \ '%W%f:%l:%c: warning: %m,' .
        \ '%E%f:%l:%c: error: %m,'
    \ }

let g:neomake_r_enabled_makers = ['lintr']
```

It works fine.

**Comment by blueyed** [comment]
@FvD 
Please consider creating a PR then to add it.
As per the previous comment it should not be enabled by default then?!
