### ISSUE TITLE
BufEnter and BufWinEnter holds the UI

### ISSUE THREAD

**Issue by azmeuk** [neomake/neomake#632]
Pylint can take some times to process. With `autocmd! BufEnter * Neomake`, when I am opening a file, I cannot see its content before pylint has finished to process. I suppose `BufEnterPost` would be perfect here but it seems it does not exist.

How can I do to instantly have a usable UI at opening, but let pylint process in background?

**Comment by blueyed** [comment]
Are you using Vim?

**Comment by blueyed** [comment]
Also check with `let g:neomake_verbose = 3` what is happening really.
It is all mentioned in the issue template btw.

**Comment by azmeuk** [comment]
Actually, nevermind, I was using vim.
