### ISSUE TITLE
Running docker locally?

### ISSUE THREAD

**Issue by davidosomething** [neomake/neomake#657]
I have docker for mac installed and running the docker daemon

When I run `make` to execute the test suite locally, I am running into this:

```
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
tmp=; \
	HOME=$tmp VADER_OUTPUT_FILE=/dev/stderr nvim --headless -nNu tests/vim/vimrc -i NONE '+Vader! tests/*.vader'
Error detected while processing /Users/davidosomething/.dotfiles/vim/plugin/completion.vim:
...
```

It's having trouble using `mktemp` -- which is BSD (darwin)'s mktemp

**Comment by blueyed** [comment]
`make` runs `make testvim` and `make testnvim` by default, which does not use Docker.
Use `make docker_test_all` to run all Dockerized tests, or
`make docker_test DOCKER_VIM=vim73` for Vim 7.3.x.

**Comment by blueyed** [comment]
Thanks for looking into this btw.. :)

I think there could be a small section in the README about this, i.e. that `make test` runs tests on Vim and Neovim, and that you can use `make docker_test_all` to run tests in all dockerized versions, which currently does not include Neovim though (see https://github.com/tweekmonster/vim-testbed/issues/1).

**Comment by davidosomething** [comment]
added to wiki https://github.com/neomake/neomake/wiki/Running-Neomake's-test-suite
