### ISSUE TITLE
filename argument

### ISSUE THREAD

**Issue by bounceme** [neomake/neomake#663]
### Issue type

- Feature request

### Description

Allow a file path to be given for the lint process.the lint output should be treated the same as when invoking a regular `:Neomake` and go to the same buffers loclist that invoked the command.
would allow things like https://github.com/neomake/neomake/issues/543#issuecomment-250374142

**Comment by davidosomething** [comment]
To clarify, @bounceme wants to be able to pass additional `args` to `g:neomake_x_maker.exe` via the `:Neomake` command, which presently only accepts the name of the maker

E.g. `:Neomake makername -- --additional-arg -x -y --clean` where the first `--` is simply a delimiter
This would yield the command`g:neomake_ft_makername.exe g:neomake_ft_makername.args commandargs` => `makerexe --defaultarg --commandarg`

**Comment by bounceme** [comment]
Yes, specific file to use instead of the current file when starting the maker

**Comment by saaguero** [comment]
If I understand correctly, one of the motivations around this feature request is to be able to support on-the-fly linting (ie: through the use of temp files.)

If that's the case, I would prefer an approach where these details are hidden, hence no filepath should be passed to Neomake commands.

Am I missing other scenarios?

**Comment by bounceme** [comment]
Sure, but having a function instead may remove the advantage this would bring when using the :neomake command, that all the config is already wrapped

**Comment by blueyed** [comment]
See #175 and #589.

1. Additional args is different from replacing args (check "append_file").
2. What happens in case of just `:Neomake -- --foo` and there are multiple makers enabled?
3. The on-the-fly linting when implemented should use functions and not commands.

A command to specify and imply "append_file = 0" would make sense.
The same as one that replaces existing args vs. appending to them.

I've started looking into what @davidosomething and me somehow agreed in https://github.com/neomake/neomake/issues/589#issuecomment-250189358.

I would say that we should create a new issue (or even "project") to tackle this: all use cases should be outlined and then being discussed on.  Currently it appears to be at least 3 issues discussing this already!

**Comment by bounceme** [comment]
Oh, I should have checked for related issues. Please close this if you want

**Comment by bounceme** [comment]
`The on-the-fly linting when implemented should use functions and not commands.`

In my opinion all of this can be done with the autocmds already available. Abstracting this into the plugin would be complicated, especially when people would then request to configure the on-the-fly behavior

**Comment by bounceme** [comment]
here is the my attempt without any real api:
```
augroup async
  au!
augroup END
function! MYIDE()
  au! async
  if exists('s:neomaketemp')
    silent! let tmp = index(neomake#GetMaker(neomake#makers#ft#{&ft}#EnabledMakers()[0],&ft)['args'],s:neomaketemp)
    call delete(s:neomaketemp) " kill process from other buffer if needed
    if tmp > -1
      call remove(neomake#GetMaker(neomake#makers#ft#{&ft}#EnabledMakers()[0],&ft)['args'],tmp)
    endif
  endif
  let s:neomaketemp = tempname() . '.' . expand('%:e')
  silent! call writefile(getline(1, '$'), s:neomaketemp)
  let maker = neomake#GetMaker(neomake#makers#ft#{&ft}#EnabledMakers()[0],&ft)
  let maker['append_file'] = 0
  if !exists('maker["args"]')
    let maker['args'] = []
  endif
  let maker['args'] += [s:neomaketemp]
  exe ':Neomake ' . neomake#makers#ft#{&ft}#EnabledMakers()[0]
endfunction
au bufenter * Neomake
au User NeomakeFinished au async textchanged * call MYIDE()

```
this isn't working (atleast for jshint) though the temp file is made and correctly added to the makers args. any idea what is happening?
