### ISSUE TITLE
Different maker per project?

### ISSUE THREAD

**Issue by nathanielks** [neomake/neomake#664]
### Issue type

- Feature request

### Description

Using Neomake primarily for javascript projects. Not all projects use the same maker: some use standard, some jshint, some eslint.

### Expected behavior

The ability to specify a maker per project would be ideal, either via some rcfile or .*lint file detection.

Thank you for such a great plugin!

**Comment by davidosomething** [comment]
You can currently use any of the vim localrc plugins + autocmds to set `b:neomake_*` vars for files in a project (e.g. `autocmd Filetype javascript let b:neomake_javascript_enabled_makers = ['eslint']` in the project's local vimrc)

local vimrc plugins https://www.google.com/search?q=vim+localrc

**Comment by nathanielks** [comment]
Ah, that's a great idea. Thanks for your time, @davidosomething!
