### ISSUE TITLE
Default `errorformat` not used with custom `makeprg` using scons

### ISSUE THREAD

**Issue by nivoliev** [neomake/neomake#715]
While using a customized `makeprg`, the errors in the quickfix window are not detected, and I cannot jump to them. I believe this is due to a wrong `errorformat`. Using `:make` with the default `errorformat`, My errors are well catched.

### Steps to reproduce

My project is C++ built with `scons`. The `makeprg` is modified via an autocmd: when I open a file in a certain directory, 

```vim
:autocmd WinEnter,BufEnter,BufRead,BufNewFile */TheDirectory/* call SetSconsRoot(expand("<amatch>:s?TheDirectory/.*?TheDirectory?"))
```

with 

```vim
function! SetSconsRoot(path)
  let &makeprg="scons -C ". a:path
endfunction
```

I configured neomake with `let g:neomake_open_list = 1` to see the quickfix window after the compilation, and I use `:Neomake!` for compilation. But in the quickfix, I just see the compilation log as if no error detection is used: 

```
|| scons: Entering directory `some_directory'
|| scons: Reading SConscript files ...
|| scons: done reading SConscript files.
|| scons: Building targets ...
|| Compiling shared ==> some_file
|| In file included from some_file:12:0:
|| some_file:18:1: error: 'toto' does not name a type
||  toto
||  ^~~~
|| scons: *** [build/some_file.os] Error 1

... some more lines with errors related to the one I introduced...

|| scons: building terminated because of errors.
```

### Expected behavior

Digging in neomake code, I found that modifying file `autoload/neomake/utils.vim` as

```vim
function! neomake#utils#MakerFromCommand(command) abort
    " XXX: use neomake#utils#ExpandArgs and/or remove it.
    "      Expansion should happen later already!
    let command = substitute(a:command, '%\(:[a-z]\)*',
                           \ '\=expand(submatch(0))', 'g')

"    ========= original version
"    return {
"        \ 'exe': &shell,
"        \ 'args': [&shellcmdflag, command],
"        \ 'remove_invalid_entries': 0,
"        \ 'errorformat': '%+G',
"        \ }
"    ========= modified version
    return {
        \ 'exe': &shell,
        \ 'args': [&shellcmdflag, command],
        \ }
endfunction
```
allows the errors to be detected and displayed in the quickfix:

```
some_file|18 col 1| error: 'toto' does not name a type
... some other errors related to the first one ...
```

The side bar with error markings appears as well on the side of the opened `some_file`.

#### Neomake debug information
Async support: 1
Current filetype: cpp

##### Enabled makers
For the current filetype (with :Neomake): ['clang', 'clangtidy', 'clangcheck']
NOTE: you can define g:neomake_cpp_enabled_makers to configure it (or b:neomake_cpp_enabled_makers).
For the project (with :Neomake!): []
NOTE: you can define g:neomake_enabled_makers to configure it.

##### Settings
g:neomake_open_list = 1
g:neomake_verbose = 3

#### :version

NVIM 0.1.5
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.5/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

**Comment by blueyed** [comment]
Thanks for the report, should be fixed now.
