### ISSUE TITLE
Minor issue in doc: suspicious *command* helptag

### ISSUE THREAD

**Issue by kiryph** [neomake/neomake#719]
https://github.com/neomake/neomake/blob/master/doc/neomake.txt#L360 contains following line
```
shell *command* according to 'shell'. |neomake#Sh| returns the single job id
```

Should this be
```
shell |command| according to 'shell'. |neomake#Sh| returns the single job id
```
?

I stumbled across this when I entered `:h command` and I was expecting getting `:h :command`

**Comment by davidosomething** [comment]
yea it should be backticks actually -- it is just for emphasis.

a few others too: "filemode"  and "makers"

open a PR!

**Comment by kiryph** [comment]
A search with`/\*.*\* reveals excluding those obviously intended:
```
346: all the *makers* specified, in order. If *filemode* is 1, then the current
360: shell *command* according to 'shell'. |neomake#Sh| returns the single job id
411: By default, *LoclistCounts* returns the counts for the current buffer (i.e.
```
I will create a PR even though I think that doesn't deserve a PR.
