### ISSUE TITLE
python maker does not work when using "exec" instead of "eval"

### ISSUE THREAD

**Issue by joanasleet** [neomake/neomake#737]
I run _:Neomake python_ on faulty code. Neomake reports no errors. Running _python test.py_ ( the faulty code ) obviously does.
### Expected behavior

If I understand the function correctly: the faulty line marked as error by Neomake.
### Output of the ":verb NeomakeInfo" command

`Neomake [893.062]: [6] Starting async job: ['python', '-c', 'from __future__ import print_function^Mfrom sys import argv, exit^Mif len(argv) != 2:^
M    exit(64)^Mtry:^M    compile(open(argv[1]).read(), argv[1], ''exec'', 0, 1)^Mexcept SyntaxError as err:^M    print(''%s:%s:%s: %s'' % (err.file
name, err.lineno, err.offset, err.msg))^M    exit(1)', '/home/alex/test.py']`

`
#### Neomake debug information

Async support: 1  
Current filetype: python                                             
##### Enabled makers

For the current filetype (with :Neomake): ['python']  
NOTE: you can define g:neomake_python_enabled_makers to configure it 
(or b:neomake_python_enabled_makers).  
For the project (with :Neomake!): []  
NOTE: you can define g:neomake_enabled_makers to configure it.       
##### Settings

```
g:neomake_verbose = 3                                                

shell: /bin/bash                                                     
shellcmdflag: -c                                                     
Windows: 0                                                           
```
#### :version

```
NVIM 0.1.5                                                           
Build type: RelWithDebInfo                                           
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fsta
ck-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -
pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -
fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_
DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/
config -I/build/neovim/src/neovim-0.1.5/src -I/usr/include -I/usr/inc
lude -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/u
sr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/sr
c/build/include                                                      
Compiled by builduser                                                

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
+tui                                                                 
For differences from Vim, see :help vim-differences                  

   system vimrc file: "$VIM/sysinit.vim"                             
  fall-back for $VIM: "/usr/share/nvim"                              
```

`

**Comment by blueyed** [comment]
There are some improvements necessary to the Python makers (have those stashed since a while locally), but it works in general..

What is your code?

What is the output of `:let g:neomake_verbose = 3 | Neomake | mess` with it?


With `t3.py` containing only `foo(` I get:

```
Neomake: python: completed with exit code 1.
Neomake: pylama: completed with exit code 1.
Neomake [15.271]: [#2] Running makers: ['python', 'pylama']
Neomake [15.272]: Calling User autocmd NeomakeCountsChanged with context: {'bufnr': 1, 'file_mode': 1}
Neomake [15.344]: [2] Starting async job: ['python', '-c', 'from __future__ import print_function^Mfrom sys import argv, exit^Mif len(argv) != 2:^M    exit(64)^Mtry
:^M    compile(open(argv[1]).read(), argv[1], ''exec'', 0, 1)^Mexcept SyntaxError as err:^M    print(''%s:%s:%s: %s'' % (err.filename, err.lineno, err.offset, err.m
sg))^M    exit(1)', '…/src/neomake/t3.py']
Neomake [15.364]: [2] Starting async job: ['pylama', '--format', 'pep8', '…/src/neomake/t3.py']
Neomake [16.820]: [2.5] stdout: python: ['…/src/neomake/t3.py:1:5: unexpected EOF while parsing', '']
Neomake [16.821]: [2.6] stdout: pylama: ['t3.py:1:5: unexpected EOF while parsing [pyflakes]', '']
Neomake [16.822]: [2.6] stdout: pylama: ['t3.py:2:1: E901 TokenError: EOF in multi-line statement [pep8]', '']
Neomake [16.822]: [2.5] exit: python: 1
Neomake [16.823]: [2.5] python: processing 1 lines of output.
Neomake [16.866]: File-level errors cleaned in buffer 1
Neomake [16.867]: Cleaning old signs in buffer 1:  {1: {1: 5000}}
Neomake [16.867]: Unplacing sign: sign unplace 5000 buffer=1
Neomake [16.869]: Calling User autocmd NeomakeCountsChanged with context: {'bufnr': 1, 'file_mode': 1}
Neomake [16.870]: Placing sign: sign place 5000 line=1 name=neomake_err buffer=1
Neomake [16.871]: python: completed with exit code 1.
Neomake [16.875]: WideMessage echo python: unexpected EOF while parsing
Neomake [16.881]: [2.6] exit: pylama: 1
Neomake [16.882]: [2.6] pylama: processing 2 lines of output.
Neomake [16.947]: Calling User autocmd NeomakeCountsChanged with context: {'bufnr': 1, 'file_mode': 1}
Neomake [16.949]: Placing sign: sign place 5000 name=neomake_err buffer=1
Neomake [16.950]: pylama: completed with exit code 1.
Neomake [16.953]: WideMessage echo python: unexpected EOF while parsing
Neomake [16.957]: Calling User autocmd NeomakeFinished with context: {'file_mode': 1}
```

Relevant lines:

```
Neomake [16.820]: [2.5] stdout: python: ['…/src/neomake/t3.py:1:5: unexpected EOF while parsing', '']
Neomake [16.822]: [2.5] exit: python: 1
Neomake [16.823]: [2.5] python: processing 1 lines of output.
```

**Comment by joanasleet** [comment]
My code is
`print("Test")
asd
print
`

the output is:

Neomake [42.749]: [#2] Running makers: ['python']                                                                                           
Neomake [42.752]: [2] Starting async job: ['python', '-c', 'from __future__ import print_function^Mfrom sys import argv, exit^Mif len(argv) != 2:^M
    exit(64)^Mtry:^M    compile(open(argv[1]).read(), argv[1], ''exec'', 0, 1)^Mexcept SyntaxError as err:^M    print(''%s:%s:%s: %s'' % (err.filen
ame, err.lineno, err.offset, err.msg))^M    exit(1)', '/home/alex/test.py']                                                                        
Neomake [54.038]: [2.2] exit: python: 0                                                                       
Neomake [54.038]: python: completed with exit code 0.
Neomake [54.039]: File-level errors cleaned in buffer 1

**Comment by blueyed** [comment]
Are you sure that's the same job?  There are 12 seconds in between.

I get this:
```
Neomake [67.677]: [#3] Running makers: ['python']
Neomake [67.678]: Calling User autocmd NeomakeCountsChanged with context: {'bufnr': 1, 'file_mode': 1}
Neomake [67.745]: [3] Starting async job: ['python', '-c', 'from __future__ import print_function^Mfrom sys import argv, exit^Mif len(argv) != 2:^M    exit(64)^Mtry
:^M    compile(open(argv[1]).read(), argv[1], ''exec'', 0, 1)^Mexcept SyntaxError as err:^M    print(''%s:%s:%s: %s'' % (err.filename, err.lineno, err.offset, err.m
sg))^M    exit(1)', '/home/daniel/src/neomake/t3.py']
Neomake [69.221]: [3.7] stdout: python: ['/home/daniel/src/neomake/t3.py:1:17: invalid syntax', '']
Neomake [69.223]: [3.7] exit: python: 1
Neomake [69.224]: [3.7] python: processing 1 lines of output.
```

**Comment by joanasleet** [comment]
_Sorry this the correct output:_

Neomake [4.047]: [#1] Running makers: ['python']                     
Neomake [4.048]: [1] Starting async job: ['python', '-c', 'from __fut
ure__ import print_function^Mfrom sys import argv, exit^Mif len(argv)
 != 2:^M    exit(64)^Mtry:^M    compile(open(argv[1]).read(), argv[1]
, ''exec'', 0, 1)^Mexcept SyntaxError as err:^M    print(''%s:%s:%s: 
%s'' % (err.filename, err.lineno, err.offset, err.msg))^M    exit(1)'
, '/home/alex/test.py']                                              
Neomake [5.190]: [1.1] exit: python: 0                               
Neomake [5.191]: python: completed with exit code 0.                 
Neomake [5.191]: File-level errors cleaned in buffer 1

**Comment by joanasleet** [comment]
Probably something dumb I'm missing...

**Comment by blueyed** [comment]
Which Python version?
Does it complain when you run it manually?!
```python -c "import sys; argv=sys.argv; compile(open(argv[1]).read(), argv[1], 'exec', 0, 1)" test.py```

**Comment by joanasleet** [comment]
Yes, when i run `python test.py` - doesn't complain with your cmd either.
`python2` and `python3` both don't complain with your cmd. I have python 3.5.2 linked as python.

**Comment by joanasleet** [comment]
It complains with `python -c "import sys; argv=sys.argv; compile(open(argv[1]).read(), argv[1], 'eval', 0, 1)" test.py`.

**Comment by blueyed** [comment]
That's weird.. I am using 3.5.2 by default also..
So `eval` instead of `exec` works for you then?
Which distro?  Custom built Python?

**Comment by joanasleet** [comment]
Current Archlinux. Python installed with pacman and official repos.
Yes eval seems complains, exec doesn't complain.

**Comment by blueyed** [comment]
I am using Arch myself, so that's really odd.
Will have to investigate, but that's a good find already.

For now I suggest using other checkers, which hopefully behave better with SyntaxErrors?!

**Comment by joanasleet** [comment]
Ok thanks for the quick help!

**Comment by joanasleet** [comment]
OK wait a sec. I just tried some lua code `print("Test"` to see if it works in general and it marks the errors correctly. Then I tried this python code `foo(` and it also marks the error. Could my test code above be a run-time error (NameError) vs. `foo(` SyntaxError ?
Sorry for the confusion.

**Comment by blueyed** [comment]
Any update on that?
With https://github.com/neomake/neomake/pull/1081 being merged, it should be a bit better by now.

Oh, regarding you last comment.

The following script does not cause an error:
```
print("Test")
asd
print
```

You had quoted it as `print("Test")
asd
print
` above though..!

I am considering the issue to be fixed then.
