### ISSUE TITLE
Quickfix/location list should not be cleared when starting makers

### ISSUE THREAD

**Issue by blueyed** [neomake/neomake#741]
I think that especially with long running makers it's better to keep the old results around, until the first maker finishes.

Should this be made configurable?!

**Comment by teto** [comment]
Or trigger an autocmd NeomakeStarted ? I could use that on projects that I know take a long time to display into i3bar for instance "Compiling".

**Comment by blueyed** [comment]
> Or trigger an autocmd NeomakeStarted

Good idea.  This would be triggered instead of the NeomakeCountsChanged that is being used currently (when resetting, and counts get reset because of this).

**Comment by blueyed** [comment]
I think this should be fixed/addressed before #831 to fix the first TODO there.

**Comment by blueyed** [comment]
Can you test #981, please?
