### ISSUE TITLE
Alternatives to autocmd for specifying when running makers

### ISSUE THREAD

**Issue by antoyo** [neomake/neomake#745]
Hello.
It would be nice to have a smarter way to specify when to run `:Neomake` than using `autocmd`.

The issue with using `autocmd` is the duplicate work, specially when using a directory maker:
you don't want to run the directory maker on every file save because if you save many files at once (with e.g. `:wa`), neovim will freezes for minutes.

So I think we need a smarter way to handle the autorun of a maker.
I don't know what would be the best, thought.

This would also fixes issues like [this one](https://github.com/neomake/neomake/issues/309).

Thanks.

**Comment by blueyed** [comment]
I think it's related to https://github.com/neomake/neomake/projects/1.

**Comment by blueyed** [comment]
#1167 has been merged, this should address this.
