### ISSUE TITLE
Java maker should use Gradle output directly

### ISSUE THREAD

**Issue by DonnieWest** [neomake/neomake#749]
When neomake runs the maker against Java code that has the Gradle build tool, instead of using the output of Gradle directly it pulls the classpath and runs it through the javac tool.

### Expected behavior

Neomake should use the Gradle output directly instead of relying upon javac output with the modified classpath

### Steps to reproduce

Run Neomake on any project that has the Gradle build tool

### Solution

Putting this in my vimrc seems to solve the problem for me.

```
let g:gradleBin = filereadable('./gradlew') ? './gradlew' : 'gradle'

let g:neomake_java_gradle_maker = {
    \ 'exe': g:gradleBin,
    \ 'append_file': 0,
    \ 'args': ['compileDebugSources', '--daemon'],
    \ 'errorformat': '\%+ATask\ %.%#\ not\ found\ %.%#.,'.
    \'%EExecution\ failed\ for\ task\ %m,'.
    \'findbugs:\ %tarning\ %f:%l:%c\ %m,'.
    \'pmd:\ %tarning\ %f:%l:%c\ %m,'.
    \'checkstyle:\ %tarning\ %f:%l:%c\ %m,'.
    \'lint:\ %tarning\ %f:%l:%c\ %m,'.
    \'%A>\ %f:%l:%c:\ %trror:\ %m,'.
    \'%A>\ %f:%l:%c:\ %tarning:\ %m,'.
    \'%A%f:%l:\ %trror:\ %m,'.
    \'%A%f:%l:\ %tarning:\ %m,'.
    \'%A%f:%l:\ %trror\ -\ %m,'.
    \'%A%f:%l:\ %tarning\ -\ %m,'.
    \'%E%f:%l\ :\ %m,'.
    \'%C>\ %m,'.
    \'%-G%p^,'.
    \'%+G\ \ %.%#,'.
    \'%-G%.%#'
    \ }
let g:neomake_java_enabled_makers = ['gradle']
```

Incidentally, when javac just uses the Gradle classpath I get strange segfaults from Neovim but I suspect that's out of the scope of this plugin. This solution results in a segfault free solution and may be useful to others.

I would create a pull request to add this but it seems like it may be controversial enough of a change that I'd want it affirmed by others before I continue and, honestly, the javac maker looks pretty daunting to modify as a first time contributor.

**Comment by blueyed** [comment]
Ping @wsdjeg, which seems to use this.

**Comment by wsdjeg** [comment]
gradle maker is for the whole project. it should same as maven maker, and it should be`autoload/neomake/makers/gradle.vim`, if you want to use gradle as maker, maybe you can disable javac.

**Comment by DonnieWest** [comment]
@wsdjeg I think I understand better. I shouldn't need to modify the javac maker since I can create a standalone maker like the maven one. Anyone who would want to use it would manually enable it in their vimrc?

**Comment by wsdjeg** [comment]
yeah, I think you can create a vim script in your rtp, `autoload/neomake/makers/gradle.vim`, then use `Neomake! gradle` to check the whole project.

**Comment by DonnieWest** [comment]
@wsdjeg thanks! I'll look to make a PR this weekend :)

**Comment by whossname** [comment]
How do we use this maker? It looks like with this change I should be able to just add the line 
`let g:neomake_java_enabled_makers = ['gradle']`
to my config file, but it isn't working.

**Comment by blueyed** [comment]
@whossname 
It is a project maker, so you need to call it using `Neomake!`.
What have you tried, i.e. how did you configure Neomake?

```vim
augroup neomake_gradle
  au!
  au BufWritePost *.java Neomake! gradle
augroup END
```

File/project mode is a bit messy, and I have plans to clean that up, but it might take a while.
Also configuration of Neomake (including autolinting) should get better soon through #1167.

**Comment by whossname** [comment]
I'm trying to use it with [neomake-autolint](https://github.com/dojoteef/neomake-autolint). I see that issue #1167 aims to replace that it. Should I just sit tight and wait until #1167 is finished? I don't really know vim script too well, but if there is something I can help with I can give it a go.

I already have it working with JavaScript (eslint), C++ (gcc), and elixir (mix, credo). Java was OK with javac, but it was giving the "cannot find symbol" error for references to any classes I wrote. 

I thought that it would work better if I used a build tool, so I'm trying out gradle. So far I can't get the gradle maker to lint anything at all.

Using the following settings:

```
let g:neomake_java_enabled_makers = ['gradle']

command Errors lopen

autocmd! BufWritePost,BufEnter * Neomake
autocmd BufEnter * syntax on
set autoread
let g:neomake_autolint_events = { 'InsertLeave': {'delay': 0} }
```
I get the error message "Maker not found (for filetype java): gradle." Adding the settings from the OP doesn't help either. There is no output at all from Neomake.

Honestly, I've forgotten what a bunch of this is for (notably `set autoread` and `command Errors lopen`).

**Comment by whossname** [comment]
BTW my vim files are here https://github.com/whossname/nvim-vimrc

I doubt this will help, the most relevant stuff is in assistance.vimrc

**Comment by blueyed** [comment]
@whossname 
Just try running `Neomake! gradle` manually first, and then see about integrating it.
`Neomake` does not know about `gradle`, but only `Neomake!`.

btw: `autocmd BufEnter * syntax on` seems a bit odd, and should not be needed.
`command Errors lopen` just defines an alias command for `:lopen`.

You should remove the `let g:neomake_java_enabled_makers = ['gradle']` for now.

Try my autocommand from above for gradle, if it works in general.

As for #1167, you could just give it a try (see https://help.github.com/articles/checking-out-pull-requests-locally/).

I am using it like this:
```
function! MyOnBattery()
  return readfile('/sys/class/power_supply/AC/online') == ['0']
endfunction

if MyOnBattery()
  call neomake#configure#automake('w', 500)
else
  call neomake#configure#automake('nrw', 500)
endif
```

You can just use `call neomake#configure#automake('nrw', 500)` to configure it in normal mode (changed text), and when reading/writing files.  With a delay of 500 (for the normal mode).
`i` would also be available for insert mode, and it can be configured in a similar way to neomake-autolint.

**Comment by whossname** [comment]
I put a few errors in the file I'm working with to test it out. Running Neomake manually without setting gradle as the maker:
`:Neomake! gradle` doesn't do anything. No linting, no output, no "Maker not found" error.
`:Neomake` lints in the way expected for the javac compiler, linting both errors and legitimate code referencing other classes I have written. 

The issue might be my gradle build file. It's 11:30 PM now, so I'll try it out tomorrow (I'll also try out #1167 ).

I think the point of `autocmd BufEnter * syntax on` was that when I changed buffers sometimes the syntax was disappearing. Can't remember if this was the fix or something else.

**Comment by blueyed** [comment]
You should use `let g:neomake_logfile = '/tmp/neomake.log'` and see what shows up there.

**Comment by whossname** [comment]
I got it to work, thanks for the help.

The issue was that the [gradle settings](https://github.com/neomake/neomake/blob/master/autoload/neomake/makers/gradle.vim) include a reference to the task 'compileDebugSources' which resulted an error being thrown 'Task ''compileDebugSources'' not found in root project'. Adding the following lines to my build.gradle file solved the issue for me:

```
task compileDebugSources { }
compileDebugSources.dependsOn classes
```

This basically aliases the classes task as compileDebugSources. I'm not sure what compileDebugSources was originally meant to do, but it might have something to do with android development.

**Comment by blueyed** [comment]
@DonnieWest 
Why is `compileDebugSources` there in the settings by default?
Looks like we should fix/improve this.

**Comment by blueyed** [comment]
@whossname 
Does the "Task ''compileDebugSources'' not found in root project" show up for you in `:copen` (without your workaround), i.e. is the issue by itself discoverable, or hidden/filtered completely?
Would be nice to get the whole output for debugging / improving the errorformat for it.

**Comment by whossname** [comment]
The contents of neomake.log:

```
18:50:28 [D +13.7] [4.-:3] Running makers: gradle.
18:50:28 [V      ] [4.1:3] Starting async job: ['./gradlew', 'compileDebugSources', '--daemon'].
18:50:28 [D      ] [4.1:3] cwd: /home/tyson/Dropbox/uni/Charles Sturt/Past Subjects/2016S1/ITC322-DataStructures/code/assignments/assignment3.
18:50:28 [D +0.65] [4.1:3] stderr: gradle: ['', ''].
18:50:28 [D      ] [4.1:3] stderr: gradle: ['FAILURE: Build failed with an exception.', '', '* What went wrong:', 'Task ''compileDebugSources'' not found in root project ''assignment3''.', '', '* Try:', ''].
18:50:28 [D      ] [4.1:3] stderr: gradle: ['Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.', ''].
18:50:28 [D      ] [4.1:3] stdout: gradle: ['', ''].
18:50:28 [D      ] [4.1:3] stdout: gradle: ['BUILD FAILED', '', 'Total time: 0.601 secs', ''].
18:50:29 [D +0.37] [4.1:3] exit: gradle: 1.
18:50:29 [D      ] [4.1:3] gradle: processing 4 lines of output.
18:50:29 [D      ] [4.1:3] Creating quickfix list.
18:50:29 [D      ] [4.1:3] Processing 0 entries.
18:50:29 [D      ] [4.1:3] gradle: processing 8 lines of output.
18:50:29 [D      ] [4.1:3] Processing 0 entries.
18:50:29 [D      ] [4.1:3] gradle: completed with exit code 1.
18:50:29 [D      ] [4.1:3] Cleaning jobinfo.
18:50:29 [D      ] Skipping User autocmd NeomakeJobFinished: no hooks.
18:50:29 [D      ] Removing signs: {file: {}, project: {}}.
18:50:29 [D      ] Skipping User autocmd NeomakeFinished: no hooks.
```

So it is pretty easy to figure out what is going on from this, but I'm not getting anything from :copen.

**Comment by whossname** [comment]
Also running `gradle compileDebugSources` from to command line in the root folder gives this:
```
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Task 'compileDebugSources' not found in root project 'assignment3'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.537 secs
```

**Comment by DonnieWest** [comment]
Ah, apparently that's my goof. This was originally built for Android developers where `compileDebugSources` is standard. I'll do some investigating tonight to see if I can more intelligently determine what to use based on project type or if there's a more standard task I can use

**Comment by blueyed** [comment]
@DonnieWest 
Thanks.
Let's move this to #1376 then.
