### ISSUE TITLE
Error with pandoc files: markdownlint not found

### ISSUE THREAD

**Issue by zyphrus** [neomake/neomake#761]
When using `:Neomake` in pandoc files an error occurs,  markdownlint not found (more below).

However there are no issues when running in a markdown file.

### Expected behaviour

To run `:Neomake` in a pandoc file without getting errors.

#### Neomake debug information

Async support: 1
Current filetype: pandoc

##### Enabled makers

```
Neomake: Maker not found: markdownlint
                                      Error detected while processing function neomake#DisplayInfo[7]..neomake#GetEnabledMakers[33]..neomake#utils#AvailableMakers[1]..neomake#utils#MakerIsAvailable:
line    8:
E716: Key not present in Dictionary: exe)
E116: Invalid arguments for function executable(maker.exe)
E15: Invalid expression: executable(maker.exe)
For the current filetype (with :Neomake): -1
```

### Additional Info

Tried on Linux and OSX with neovim 0.1.6 and vim 7.4 and markdownlint is not installed on any of them

Use with [vim-pandoc/vim-pandoc-syntax](https://github.com/vim-pandoc/vim-pandoc-syntax) and [full config here](https://github.com/zyphrus/nvim)

**Comment by blueyed** [comment]
Thanks for your report, should be fixed in #763 for now.

I wonder though, if `mdl` should be used at all - and if so, why `markdownlint` is not used (or is this an oversight (missing autoload function).
/cc @Alok (who submitted https://github.com/neomake/neomake/pull/746).

**Comment by zyphrus** [comment]
Thanks for getting this resolved so quickly. Just testing it again as a follow up from the latest master and getting a message for markdownlint not found.Not sure if this is suppose to happen but it is not as bad as it was before.

Normal markdown file type is still fine, this is just in pandoc file type.

### Output of the ":verb NeomakeInfo" command

#### Neomake debug information
Async support: 1
Current filetype: pandoc


##### Enabled makers
Neomake: Maker not found: markdownlint
For the current filetype (with :Neomake): []
NOTE: you can define g:neomake_pandoc_enabled_makers to configure it (or b:neomake_pandoc_enabled_makers).
For the project (with :Neomake!): []
NOTE: you can define g:neomake_enabled_makers to configure it.


##### Settings

```
shell: /bin/zsh
shellcmdflag: -c
Windows: 0
```


#### :version

```
NVIM 0.1.6
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161030-26568-1b2woqa/neovim-0.1.6/build/config -I/tmp/neovim-20161030-26568-1b2woqa/neovim-0.1.6/src -I/tmp/neovim-20161030-26568-1b2woqa/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161030-26568-1b2woqa/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161030-26568-1b2woqa/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161030-26568-1b2woqa/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161030-26568-1b2woqa/neovim-0.1.6/deps-build/usr/include -I/tmp/neovim-20161030-26568-1b2woqa/neovim-0.1.6/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20161030-26568-1b2woqa/neovim-0.1.6/build/src/nvim/auto -I/tmp/neovim-20161030-26568-1b2woqa/neovim-0.1.6/build/include
Compiled by drb@david.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.6/share/nvim"

```


#### :messages
```
"~/.config/nvim/README.md" 17L, 235C
"README.md" 17L, 235C written
Neomake: Maker not found: markdownlint
"README.md" 17L, 235C written
Neomake: Maker not found: markdownlint

```

**Comment by blueyed** [comment]
Yes, the pandoc maker needs to be fixed still: but I don't know if `markdownlint` (and `mdl`) should be returned here.  See my comment above.

**Comment by blueyed** [comment]
Closed via https://github.com/neomake/neomake/pull/771#issuecomment-260270825.
