### ISSUE TITLE
shellcheck on *.bash 

### ISSUE THREAD

**Issue by davidosomething** [neomake/neomake#776]
Not all bash scripts will have a shebang (e.g. sourced files ending in `.bash`, which might be sourced from a `.bashrc` and therefore should not have +x or a shebang to prevent spawning)

They should be assumed to be bash if the file extension is `.bash` and there is no shebang

I'm too lazy to PR right now, but here's my local fix:
https://github.com/davidosomething/dotfiles/blob/5732298ca163e6c4d0afc784c606eadc254bb9c4/vim/plugin/plug-neomake.vim#L321-L332

Perhaps a `g:neomake_shellcheck_perfer_posix` can be introduced if someone really wants to assume `.bash` should be `.sh` and POSIX compliant

**Comment by davidosomething** [comment]
also there is already `g:is_bash` from `$VIMRUNTIME/syntax/sh.vim`

**Comment by mhinz** [comment]
I'll look into it. It will pay attention to to `.bash`/`.ksh` extensions and the variables mentioned under `:h ft-sh-syntax`.

**Comment by davidosomething** [comment]
you're the man!
