### ISSUE TITLE
.sh ext should not be used to set local ft

### ISSUE THREAD

**Issue by mmlb** [neomake/neomake#786]
I think I have only ever seen `.bash` scripts in one project (https://github.com/golang/go/tree/master/src) almost all the bash scripts I've seen are named `.sh` and have `bash` in the shebang. Currently, neomake is treating bash shebanged files with .sh extensions as `ft=sh` instead of `ft=bash`. `ext ==# 'sh'` should not be used since it is common to write bash scripts with .sh extensions.

### Expected behavior
neomake does not use `ext ==# 'sh'` in any of the tests, which allows shell scripts to be `shellcheck`ed in the mode specified in the shebang line.

### Steps to reproduce

ensure shellcheck is used to check the following file named `test.sh`
```
#!/usr/bin/env bash

source somefile
```

shellcheck will complain about the use of `source` in a POSIX sh file.

#### Neomake debug information
Async support: 1
Current filetype: sh

##### Enabled makers
For the current filetype (with :Neomake): ['sh', 'shellcheck']
NOTE: you can define g:neomake_sh_enabled_makers to configure it (or b:neomake_sh_enabled_makers).
For the project (with :Neomake!): []
NOTE: you can define g:neomake_enabled_makers to configure it.

##### Settings
```


shell: /usr/bin/zsh
shellcmdflag: -c
Windows: 0
```

#### :version
```

NVIM v0.2.0-66-g0c799a8
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/manny/.cache/pacaur/neovim-git/src/neovim-git/build/config -I/home/manny/.cache/pacaur/neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/home/manny/.cache/pacaur/neovim-git/src/neovim-git/build/src/nvim/auto -I/home/manny/.cache/pacaur/neovim-git/src/neovim-git/build/include
Compiled by manny@manny

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

#### :messages
```
"../../rc.sh" 12L, 223C
```

**Comment by mmlb** [comment]
I have a local patch that removes the use of `ext ==# 'sh'` I can submit if this sounds like a good idea.

**Comment by blueyed** [comment]
Yes, this seems to be caused by https://github.com/neomake/neomake/pull/777.

I agree that the shebang should take precedence, but just removing the `ext ==# 'sh'` might not be the correct solution.

/cc @mhinz

**Comment by davidosomething** [comment]
It's not setting the ft for me...
The `let ft` is a `let l:ft`, not `set ft` or `let &ft` (https://github.com/neomake/neomake/blob/4c4a2dd0623cdd6d34e0e00a1eab3c62d738da17/autoload/neomake/makers/ft/sh.vim#L19)

There is no "bash" filetype in vim and neovim by default -- they use the "sh" filetype with flags to cater to various shell types.
`*.sh` and `*.bash` should always be `sh` filetype. Anything else is user defined.

**Comment by blueyed** [comment]
@mmlb 
With what file do you get the behavior?
It would also help to actually run `:let g:neomake_verbose = 3 | Neomake` to see what is being done in `:mess`.

**Comment by mmlb** [comment]
@davidosomething my `ft=sh` which is not the problem, it's the local var `ft` https://github.com/neomake/neomake/blob/41d6a5705bcb3b1b5dd4f2bdc7f81778cc5a11e7/autoload/neomake/makers/ft/sh.vim#L23 that is added to the `shellcheck` invocation that is a problem.

```
Neomake [6.714]: [1] Running makers: ['sh', 'shellcheck']                                                                                                                                                                                                                                                                                               Neomake [6.715]: [1] Starting async job: ['/usr/bin/env', 'bash', '-n', '/home/manny/t.sh']                                                                                                                                                                                                                                                             Neomake [6.718]: [1] Starting async job: ['shellcheck', '-fgcc', '-s', 'sh', '/home/manny/t.sh']                                                                                                                                                                                                                                                        Neomake [6.722]: [1.4] exit: sh: 0                                                                                                                                                                                                                                                                                                                      Neomake [6.723]: [1.4] sh: completed with exit code 0.                                                                                                                                                                                                                                                                                                  Neomake [6.723]: File-level errors cleaned in buffer 1                                                                                                                                                                                                                                                                                                  Neomake [6.724]: [1.5] stdout: shellcheck: ['/home/manny/t.sh:3:1: warning: In POSIX sh, ''source'' in place of ''.'' is undefined. [SC2039]', '/home/manny/t.sh:3:1: note: Not following: somefile was not specified as input (see shellcheck -x). [SC1091]', '']                                                                                      Neomake [6.726]: [1.5] exit: shellcheck: 1                                                                                                                                                                                                                                                                                                              Neomake [6.727]: [1.5] shellcheck: processing 2 lines of output.                                                                                                                                                                                                                                                                                        Neomake [6.728]: Placing sign: sign place 5000 line=3 name=neomake_warn buffer=1                                                                                                                                                                                                                                                                        Neomake [6.730]: [1.5] shellcheck: completed with exit code 1. 
```

**Comment by davidosomething** [comment]
oh okay I understand

here's a concise description:

### OBSERVED 

ext `.sh` + shebang `bash` = `shellcheck -s sh` (neomake decided based on shebang `getline()`)

### EXPECTED

ext `.sh` + shebang `bash` = `shellcheck` (no `-s` flag, `shellcheck` will read shebang, using bash or ash or dash or zsh if it finds one, and assume bash if not since that is the shellcheck default)

That is the one and only case that should change 

+@mhinz

**Comment by mmlb** [comment]
@davidosomething no you're observed is wrong. neomake decided based on `ext`

**Comment by davidosomething** [comment]
^ edited, either way, preferred is to remove `-s` completely for `.sh`

**Comment by mhinz** [comment]
Although shellcheck assumes the "bash dialect" if `-s` wasn't given, it will issue a warning about it nevertheless. Thus we'll always force if there's no valid shebang.

So, what about:

```vim
    if matchstr(getline(1), '\v^#!.*<%(sh|dash|bash|ksh)')
        " shellcheck reads the shebang by itself
    elseif ext ==# 'bash'
        let maker.args += ['-s', 'bash']
    elseif ext ==# 'ksh'
        let maker.args += ['-s', 'ksh']
    elseif ext ==# 'sh'
        if exists('g:is_sh')
            let maker.args += ['-s', 'sh']
        elseif exists('g:is_posix') || exists('g:is_kornshell')
            let maker.args += ['-s', 'ksh']
        else
            let maker.args += ['-s', 'bash']
        endif
    endif
```

**Comment by davidosomething** [comment]
why does is_posix default to korn shell? lgtm if theres a reason

**Comment by davidosomething** [comment]
ohh ksh is POSIX.2 compliant
lgtm

**Comment by mhinz** [comment]
Okay, please see if the latest master works as expected.

**Comment by mmlb** [comment]
+1 works for me

**Comment by mmlb** [comment]
Thanks a lot!
