### ISSUE TITLE
Cargo maker should show errors inside test code

### ISSUE THREAD

**Issue by jonhoo** [neomake/neomake#801]
The Cargo maker currently just runs `cargo build`, which doesn't build any unit or integration tests. For example, the following code is not annotated with any errors after running `:Neomake! cargo`, despite the error on line 5

```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        let x: bool = 42;
    }
}
```

As mentioned above, the reason this error isn't caught is that the maker only builds with `cargo build`, which doesn't hit all targets. There's been some discussion around this in rust-lang/cargo#2495, and the proposed solution seems to be to instead compile with `cargo test --no-run`.

**Comment by jonhoo** [comment]
I've actually found that the following `makers/cargo.vim` works quite well:
```vim
" vim: ts=4 sw=4 et

function! neomake#makers#cargo#cargo() abort
    return {
        \ 'exe': 'timeout',
        \ 'args': ['2s', 'cargo', 'test', '--no-run'],
        \ 'errorformat':
            \ neomake#makers#ft#rust#rustc()['errorformat'],
        \ }
endfunction
```
That is, build all code, including tests, but kill cargo after two seconds. This gives it enough time to print most errors, but doesn't force you to wait for compilation of your library, all binaries, and all your tests to complete.

**Comment by mhinz** [comment]
Hmm. That requires a coreutils tool which might not be installed on every system. @blueyed What do you think?

**Comment by jonhoo** [comment]
```vim
function! neomake#makers#cargo#cargo() abort
    return {
        \ 'args': ['test', '--no-run'],
        \ 'errorformat':
            \ neomake#makers#ft#rust#rustc()['errorformat'],
        \ }
endfunction
```

is still better than the current setup though, as it also catches errors within `#[cfg(test)]` blocks and in test files. I think your project has to be compiled twice when using `cargo test` though (once with `test` and once without), as a result of the way `cargo` works internally (it doesn't currently re-use the non-test build for a test build).

**Comment by mhinz** [comment]
Well, I'm no Rust user. If you say the way above is better than using `cargo build`, I'll add it.

**Comment by blueyed** [comment]
Same with me.

/cc @fuine  @euclio

**Comment by jonhoo** [comment]
`test --no-run` is definitely better than just `build`. I would prefer to include `timeout` to avoid waiting for a re-build of the entire project on every invocation (I wish `cargo` had support for early termination), but I understand the reluctance to rely on coreutils.

**Comment by mhinz** [comment]
Let's see how it works out!

**Comment by fuine** [comment]
Just a note: it can and most probably will make the cargo maker slower, as it will have to compile tests at least once, and then each time something is changed within test suite. I am not sure if this should be the default setting, or if it should  be an opt-in one.

**Comment by blueyed** [comment]
> understand the reluctance to rely on coreutils

We can detect if `timeout` exists (once), using `let s:has_timeout = executable('timeout')` (on demand).
But then 2 seconds also seems arbitrary?!

**Comment by fuine** [comment]
Yes, imho if we want to use timeout it should be left as an user defined option.

**Comment by jonhoo** [comment]
@blueyed yes, it is completely arbitrary. I chose 2s because, even for the relatively large project I'm working on, 2s is enough time to have all the warnings printed, yet short enough for the errors to feel somewhat interactive. Since errors are printed as rust encounters them, one could even make it shorter, at the cost of only revealing a subset of the compilation errors each time. Making it a user-define option (both the user of `timeout`, and the duration) seems like a good idea.

@fuine is completely correct that this will make the cargo maker slower. However, I think the observation that it will re-compile whenever the tests are changed is actually the behavior you want. You want cargo to re-run whenever you've changed something, so that you can get errors if there are any. Of course, ideally we want cargo to be smart about partial re-compilation, but this is something we don't have yet (though it's coming down the pipeline).
