### ISSUE TITLE
Visual selection gets lost when error list gets updated

### ISSUE THREAD

**Issue by blueyed** [neomake/neomake#805]
The visual selection gets lost when a maker finishes and the location list gets opened / changed.

This seems to be more an issue with Vim/Neovim (which has no command to really only open the window without going there), but we might want to postpone the update of the errors until there is no visual selection anymore?!

TEST CASE:
 - `let g:neomake_open_list = 2`
 - In a file with errors: `Neomake | norm! V`

**Comment by bounceme** [comment]
strange, how about just `norm! gv` after the errors are updated?

**Comment by blueyed** [comment]
Does not work.. it will only have a partial selection then.
I am trying to fix this in https://github.com/neomake/neomake/pull/831: the current idea being to only process output when in normal and insert mode.
