### ISSUE TITLE
Document fugitive :Gpush  and :Gfetch can be run asynchronously with the help of neomake

### ISSUE THREAD

**Issue by kiryph** [neomake/neomake#817]
I noticed following wikipage of the vim plugin asyncrun:

https://github.com/skywind3000/asyncrun.vim/wiki/Cooperate-with-famous-plugins#fugitive

which reminds that fugitive supports dispatch.vim via the definition of `:Make`.

Since dispatch.vim is today obsolete due to vim8 and neovim, you can define `:Make` using the plugin asyncrun in the following way:

    command! -bang -nargs=* -complete=file Make AsyncRun -program=make @ <args>

I think many people might have installed neomake and fugitive but simply do not know that they can facilitate neomake for fugitive without needing another plugin.

However, I am not sure if the following definition is correct:

    command! -bang -nargs=* -complete=file Make Neomake <args>

I miss the feedback of `:Gpush`.

**Comment by blueyed** [comment]
I am not sure what this issue is really about?!

Are you trying to use `command! -bang -nargs=* -complete=file Make Neomake <args>`, but are running into issues?!

The args for `:Neomake` are maker names currently only, so it is not a replacement for dispatch's `Make` really.

> Since dispatch.vim is today obsolete due to vim8 and neovim

There is https://github.com/radenling/vim-dispatch-neovim/ - I am using it myself, but with a decent set of local (or rotting in PRs) patches.

**Comment by kiryph** [comment]
Thanks for your feedback. Since you are not sure what this issue is about, I guess should elaborate on this a  bit more:

Motivation: How can I make :Gpush and :Gfetch non-blocking in vim using neomake?

Apparently, fugitive can use for this dispatch.vim.

My suggestion `command! -bang -nargs=* -complete=file Make Neomake <args>` does not push or does anything. Can you help me here?

Following code snippet illustrates how fugitive uses makeprg to dispatch `:Gpush` and `:Gfetch`.

```viml
function! s:Dispatch(bang, args)
  let cd = exists('*haslocaldir') && haslocaldir() ? 'lcd' : 'cd'
  let cwd = getcwd()
  let [mp, efm, cc] = [&l:mp, &l:efm, get(b:, 'current_compiler', '')]
  try
    let b:current_compiler = 'git'
    let &l:errorformat = s:common_efm
    let &l:makeprg = g:fugitive_git_executable . ' ' . a:args
    execute cd fnameescape(s:repo().tree())
    if exists(':Make') == 2
      noautocmd Make
    else
      silent noautocmd make!
      redraw!
      return 'call fugitive#cwindow()'
    endif
    return ''
  finally
    let [&l:mp, &l:efm, b:current_compiler] = [mp, efm, cc]
    if empty(cc) | unlet! b:current_compiler | endif
    execute cd fnameescape(cwd)
  endtry
endfunction
```

If there is a way to use Neomake for fugitive, I would add this to the docs.

**Comment by kiryph** [comment]
I have added a bang `!` to the Neomake, which now looks like

    command! -bang -nargs=* -complete=file Make Neomake! <args>

Now, it pushes and the quickfix window shows a report about a successful push.

If you like it, you could add this to `*neomake-faq*`.
