### ISSUE TITLE
python: flake8: highlighting of columns might be off

### ISSUE THREAD

**Issue by blueyed** [neomake/neomake#824]
With some raw `flake8` output like:

```
% flake8 foo/conftest.py
foo/conftest.py:1124:5: F401 'foo.bar.models.FooBar' imported but unused
```

and and original line of:
```
    from foo.bar.models import FooBar
```

The column will be highlighted from column 5, but only for the length of `foo.bar.models.FooBar`.

The problem is that `'foo.bar.models.FooBar'` is referenced in the error, but not in the line.
In think it should strictly match the string, and if that is not found the rest of the line should be matched from there (in case there is a string).  Or rather fall back to only matching the column itself?!

/cc @paretje @JelteF

**Comment by JelteF** [comment]
I think this should just be fixed in flake8 TBH, both the column and the string is incorrect.

**Comment by JelteF** [comment]
The error message should say:

```
foo/conftest.py:1124:27: F401 'foo.bar.models.FooBar' imported but unused
```

I had this issue myself as well, it's especially annoying when importing multiple things at once from a module.

**Comment by blueyed** [comment]
But with column 27, the string `'foo.bar.models.FooBar' ` would not be matched then still?!

**Comment by JelteF** [comment]
oops, I meant this:

foo/conftest.py:1124:27: F401 'FooBar' imported but unused

**Comment by blueyed** [comment]
I see.  Do you care to create an issue with them?
Although it might also involve pyflakes then, since it appears to come from there - but then pyflakes itself has no column information, does it?

**Comment by JelteF** [comment]
I'm now looking into creating a patch for pyflakes.

**Comment by JelteF** [comment]
Hmmm, I was able to quite easily change the error message to say FooBar instead of foo.bar.models.FooBar. However, I'm unable to easily fix the column, because the alias AST node does not have a col or line number.

**Comment by JelteF** [comment]
So I think I would need something like baron or redbaron for this.

**Comment by JelteF** [comment]
I just pushed a fix that handles this edge case in neomake. Although I still think it would be better if it was fixed in pyflakes, it's not really feasible without using a way more complicated setup because the python `ast` module is simply lacking here.

**Comment by blueyed** [comment]
Thanks, @JelteF.
Closing this for now.
