### ISSUE TITLE
[Enhancement] New option to show sign column when error lines haven't been displayed yet

### ISSUE THREAD

**Issue by javiertury** [neomake/neomake#834]
On vim with neomake, the sign column is only visible when there have been errors/warnings on one of the displayed lines. For example let's say that I just open a file which has an error on line 95 and only lines 1 to 10 have been displayed so far, then run neomake. What happens is that the sign column won't appear until you navigate and display the error line for the first time.

The same example with syntastic would have shown the sign column from the beginning, without needing to come across the error line. The importance of this issue is that seeing the sign column from the beginning tells you that there is an error/warning somewhere in the document, whereas with the current vim/neomake setup you can't tell.

I don't know if the current behavior is desired, maybe developers are looking forward to display the sign column only when there are errors/warnings on visible lines and hide the sign column otherwise. Maybe it's a consequence of the (great) async mechanism. However I think that if possible, it would be a good idea to provide an option to draw the sign column whenever there is an error/warning line anywhere on the document.

I am using vim 8 but I haven't tested this on neovim.

**Comment by blueyed** [comment]
See https://github.com/neomake/neomake/pull/471.

**Comment by chrisbra** [comment]
Note, that you can simply set the 'signcolumn' option

**Comment by javiertury** [comment]
But if you set signcolumn=yes, then it will be always visible. The point is that the sign column should appear when there is one error/warning anywhere in the document in order to know that you have made a mistake somewhere, and not appear when you haven't made any(or the checker hasn't detected any).
