### ISSUE TITLE
Feature request: maker value to not have args shellescaped

### ISSUE THREAD

**Issue by bounceme** [neomake/neomake#837]
`emacs path-to-broken.js --quick --batch --eval="(progn(package-initialize)(require 'js2-mode)(js2-mode)(js2-reparse t)(js2-display-error-list)(princ(with-current-buffer \"*js-lint*\"(buffer-substring-no-properties(point-min)(point-max)))))" 2>/dev/null` 

If you run that command, and you have emacs with js2-mode installed the errors printed to stdout will look like:
```
line 2: Undeclared variable or function 'f'
line 2: missing ; after statement
line 2: Undeclared variable or function 'exports'
line 2: Undeclared variable or function 'module'
line 3: Undeclared variable or function 'module'
line 4: syntax error
```
here is my attempt at a maker (which failed):
```
let g:neomake_javascript_emacs_maker = {
      \ 'args': ['%:p','--quick','--batch',
      \ '--eval="(progn(package-initialize)(require ''js2-mode)(js2-mode)(js2-reparse t)(js2-display-error-list)(princ(with-current-buffer \"*js-lint*\"(buffer-substring-no-properties(point-min)(point-max)))))"',
      \ '2>/dev/null'],
      \ 'errorformat': '%f line %l: %m',
      \ 'mapexpr': 'expand("%:p") . " " . v:val',
      \ }
```
any ideas?

**Comment by bounceme** [comment]
maybe some extra shell quoting happens to the args? it doesn't seem to invoke emacs at all

**Comment by mhinz** [comment]
Yup, `'--eval="(progn(package-initialize)(require ''js2-mode)(js2-m....` looks suspicious.

Should probably be something like `"--eval=\"(progn(package-initialize)(require '...`.

**Comment by bounceme** [comment]
thanks, i'll try later

**Comment by bounceme** [comment]
`      \ "--eval=\"(progn(package-initialize)(require 'js2-mode)(js2-mode)(js2-reparse t)(js2-display-error-list)(princ(with-current-buffer \\\"*js-lint*\\\"(buffer-substring-no-properties(point-min)(point-max)))))\"",
`
that didn't work either. my next guess is the elisp function not terminating output with a `\n`

**Comment by bounceme** [comment]
that isn't it but i fixed the newline issue ( if it is an issue ):
```
"--eval=\"(progn(package-initialize)(require 'js2-mode)(js2-mode)(js2-reparse t)(js2-display-error-list)(princ(with-current-buffer \\\"*js-lint*\\\"(buffer-substring-no-properties(point-min)(point-max))))(terpri))\""
```

**Comment by bounceme** [comment]
it seems that neomake uses string literals regardless, here is debug output:

#### Neomake debug information
Async support: 1
Current filetype: javascript

##### Enabled makers
For the current filetype (with :Neomake): ['emacs']
NOTE: you can define g:neomake_javascript_enabled_makers to configure it (or b:neomake_javascript_enabled_makers).
For the project (with :Neomake!): []
NOTE: you can define g:neomake_enabled_makers to configure it.

##### Settings
```
g:neomake_javascript_enabled_makers = ['emacs']
g:neomake_javascript_emacs_maker = {'errorformat': '%f line %l: %m', 'args': ['-nw', '%:p', '--quick', '--batch', '--eval="(progn(package-ini
tialize)(require ''js2-mode)(js2-mode)(js2-reparse t)(js2-display-error-list)(princ(with-current-buffer \"*js-lint*\"(buffer-substring-no-pro
perties(point-min)(point-max))))(terpri))"', '2>/dev/null'], 'mapexpr': 'expand("%:p") . " " . v:val'}
g:neomake_verbose = 3

shell: /bin/bash
shellcmdflag: -c
Windows: 0
```

**Comment by bounceme** [comment]
and this works somehow:
`echom system(join(['emacs', '~/Downloads/tota11y.js', '--quick', '--batch', '--eval="(progn(package-initialize)(require ''js2-mode)(js2-mode)(js2-reparse t)(js2-display-error-list)(princ(with-current-buffer \"*js-lint*\"(buffer-substring-no-properties(point-min)(point-max))))(terpri))"', '2>/dev/null']))
`

**Comment by bounceme** [comment]
here is :messages with non-async vim
```
Neomake [3.141]: [2] Running makers: ['emacs']
Neomake [3.143]: Running synchronously
Neomake [3.143]: Starting: emacs '/Users/mac/Downloads/tota11y.js' '--quick' '--batch' '--eval="(progn(package-initialize)(require '\''js2-mo
de)(js2-mode)(js2-reparse t)(js2-display-error-list)(princ(with-current-buffer \"*js-lint*\"(buffer-substring-no-properties(point-min)(point-
max))))(terpri))"' '2>/dev/null'
Neomake [3.420]: [2.2] stdout: emacs: ['']
Neomake [3.421]: [2.2] exit: emacs: 0
Neomake [3.423]: File-level errors cleaned in buffer 1
```

**Comment by bounceme** [comment]
so it appears to be the quoting of arguments, any workaround?

**Comment by bounceme** [comment]
Partial solution! remove the map on this line:
https://github.com/neomake/neomake/blob/master/autoload/neomake.vim#L235

now everything works BUT, for some reason, only on non async vim
