### ISSUE TITLE
Do not handle stderr for errorformat processing, but for error indication

### ISSUE THREAD

**Issue by blueyed** [neomake/neomake#850]
We should not consider `stderr` for the `errorformat` processing by default, but rather use it as an indication that the maker failed / had issues.

Makers could still redirect `stderr` to `stdout` in case the output is meant to come there, and/or we would have a maker option for that.

E.g. a new setting `process_stderr` could be added, and when it is `0` we would connect the job's stderr to a custom/internal handler, that would collect the output from there, and display it as a warning message when the job finishes.

Via https://github.com/neomake/neomake/pull/848#issuecomment-267207411, where a custom maker redirects `stderr` to `/dev/null`, and therefore(?) cannot use `append_file=1`.

**Comment by bounceme** [comment]
should this be solved in the handler?I guess users could remove stderr in the mapexpr, but the empty lines of output would be an issue

**Comment by blueyed** [comment]
Yes, I think it makes sense in the core, and maker vars can indicate which channel they are interested in.
I've seen that ALE does something similar (but no error handling based on it).
The idea is that if there is nothing on stdout, but only stderr it might indicate an issue with the maker etc.

There are a lot of issues where it's visible from the debug log output, but apparently not prominent enough.

**Comment by blueyed** [comment]
Addressed in https://github.com/neomake/neomake/pull/1344.
Makers need to adopt it.
