### ISSUE TITLE
Flow maker broken

### ISSUE THREAD

**Issue by juanolon** [neomake/neomake#876]
Flow maker stop working. it's because of the last update facebook/flow#2844, the option `--old-output-format` has been remove. And the flow maker relies on that option #265 

### Steps to reproduce
save file with ft=javascript and have flow enabled.

 `:message` with option `:let g:neomake_verbose = 3`

`Neomake [20.814]: [1.5] stderr: flow: ['flow: unknown option ''--old-output-format''.', 'Usage: flow [COMMAND] ', '', 'Valid values for COMMAND:', '  ast             Print the AST', '  autoc
omplete    Queries autocompletion information', '  check`...

output trimmed. it ouput the help text from flow. Neomake will remove the rest of the entry anyway, as it is not a valid error format. see:
`Neomake [20.836]: [1.5] Removing invalid entry: flow: unknown option '--old-output-format'. ({'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'type': '', 'maker_name': 'flow', 'pattern': ''})` 

### Flow version
Flow, a static type checker for JavaScript, version 0.37.0

**Comment by blueyed** [comment]
Can you create a PR to fix it, please?
