### ISSUE TITLE
Cargo maker does not populate the locationlist

### ISSUE THREAD

**Issue by ChrisBuchholz** [neomake/neomake#901]
I'm using the cargo maker with the following set up:

```rust
function! neomake#makers#cargo#cargo() abort
    return {
        \ 'args': ['check'],
        \ 'errorformat':
            \ neomake#makers#ft#rust#rustc()['errorformat'],
        \ }
endfunction

au BufReadPre,BufWritePost *.rs Neomake! cargo
```

It works fine populating the quickfixlist, but the locationlist is never populated. Using the flake8 maker with python projects, the locationlist is also used, which makes my Airline bar show the errors/warnings, which is what I'd like to get working with cargo projects too.

How come the locationlist is not used by the cargo maker?

**Comment by blueyed** [comment]
It is a project/directory maker.

As for the airline integration you have found https://github.com/vim-airline/vim-airline/pull/1275#issuecomment-269466210 already.
Closing this issue here then for now.
