### ISSUE TITLE
indicator that neomake is running

### ISSUE THREAD

**Issue by nhooyr** [neomake/neomake#915]
If there is no linter defined, only then should `:Neomake` produce no output. Otherwise, it should give a little message that it is running so I know that something is happening.

**Comment by blueyed** [comment]
I would find this too spammy, but maybe increasing/adjusting `g:neomake_verbose` helps you / could be tamed to fit this use case better.

There is certainly a difference though between running it manually or automatically, which makes it belong to https://github.com/neomake/neomake/projects/1 somehow.

I am using an indicator myself in the statusline: https://github.com/blueyed/dotfiles/blob/ce42f6c9b67642582d490014765e47d94c1cf7a7/vim/plugin/statusline.vim#L402-L413

**Comment by blueyed** [comment]
Related: #337 (also from you).

**Comment by ahstro** [comment]
Would love this, either as part of the plugin, a separate plugin, or in my own statusline. Haven't taken the time to figure out VimScript yet though, so I can't grok enough of your solution to insert it into my own flow, @blueyed. `g:neomake_verbose` is not doing the trick for me, unfortunately.

**Comment by davidosomething** [comment]
i use this:

https://github.com/davidosomething/dotfiles/blob/d6adee60eed5074efedf409ca07b3b332daaa2ae/vim/autoload/dkostatus.vim#L117-L124

in my status as:

https://github.com/davidosomething/dotfiles/blob/d6adee60eed5074efedf409ca07b3b332daaa2ae/vim/autoload/dkostatus.vim#L69

the output is like this:

https://cl.ly/3g301i0M3B3N/Image%202017-05-18%20at%209.23.27%20AM.public.png

**Comment by blueyed** [comment]
Included in #1416.

Not merged yet though - you might want to provide feedback there.

**Comment by blueyed** [comment]
#1416 has been merged.
