### ISSUE TITLE
errorformat conflict with markprg's format

### ISSUE THREAD

**Issue by drinksober** [neomake/neomake#921]
my python neomake configs as follow
" neomake {{{
    let g:neomake_python_flake8_maker = {
        \ 'args': ['--verbose'],
        \ 'errorformat': '%A%f: line %l\, col %v\, %m \(%t%*\d\)',
        \ }
    let g:neomake_python_enabled_makers = ['flake8']
    let g:neomake_python_flake8_maker = { 'args': ['--ignore=E115,E266,E501,E265']}

and my python's makeprg config as follow
    function SetPyMake()
        let s:efm  = '%+GTraceback%.%#,'
        let s:efm .= '%E  File "%f"\, line %l\,%m%\C,'
        let s:efm .= '%E  File "%f"\, line %l%\C,'
        let s:efm .= '%C%p^,'
        let s:efm .= '%+C    %.%#,'
        let s:efm .= '%+C  %.%#,'
        let s:efm .= '%Z%\S%\&%m,'
        let s:efm .= '%-G%.%#'
        let &errorformat = s:efm
        setlocal makeprg=python
    endfunction
    autocmd FileType python call SetPyMake()

when I edit a python script, neomake will use makeprg's errorformat, 
How can I solove the conflict between neomake and makeprg ??? thx.

**Comment by blueyed** [comment]
You are not defining an error format with g:neomake_python_flake8_maker.
