### ISSUE TITLE
buffer local maker configuration

### ISSUE THREAD

**Issue by mmlb** [neomake/neomake#944]
### Expected behavior

It would be great if I could configure a maker with buffer local options instead of global options. My use case is the shellcheck maker for sh filetype. I have some projects that extract common functions into a separate file, and some projects that don't. The projects that do have common functionality don't generally name them the same name. I currently use `LucHermitte/local_vimrc` to configure project specific settings like so:
```
let g:neomake_sh_shellcheck_args = neomake#makers#ft#sh#shellcheck()['args'] + ['-x', expand('%:p:h') . 'functions.sh']
```
The contents of the file mess with `g:neomake_sh_shellcheck_args`, it would be nice if neomake could also check for `b:neomake_sh_shellcheck_args` and let it override `g:neomake...`.

### Steps to reproduce

Try to configure a neomake maker differently based on subdir or similar, see that its not possible.

#### Neomake debug information
Async support: 1
Current filetype: sh

##### Enabled makers
For the current filetype (with :Neomake):
 - sh
   errorformat: '%f: line %l: %m,%f: %l: %m'
   args: ['bash', '-n']
   get_argv: function('59', {'get_argv': function('59')})
   exe: '/usr/bin/env'
 - shellcheck
   errorformat: '%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%I%f:%l:%c: Note: %m'
   args: ['-fgcc', '-x', '/home/manny/src/github.com/**SNIPPED**/functions.sh']
   get_argv: function('59', {'get_argv': function('59')})
   exe: 'shellcheck'
NOTE: you can define g:neomake_sh_enabled_makers to configure it (or b:neomake_sh_enabled_makers).

For the project (with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_sh_shellcheck_args = ['-fgcc', '-x', '/home/manny/src/github.com/**SNIPPED**/functions.sh']
g:neomake_place_signs = 1


shell: /bin/zsh
shellcmdflag: -c
Windows: 0
```

#### :version
```

NVIM v0.2.0-379-g207ba359b
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/manny/.cache/pacaur/neovim-git/src/neovim-git/build/config -I/home/manny/.cache/pacaur/neovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/home/manny/.cache/pacaur/neovim-git/src/neovim-git/build/src/nvim/auto -I/home/manny/.cache/pacaur/neovim-git/src/neovim-git/build/include
Compiled by manny@manny

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

#### :messages
```
"functions.sh" 88L, 1891C
```

**Comment by blueyed** [comment]
That should be the case already.

**Comment by mmlb** [comment]
Ohh man, I do believe you may be right @blueyed, I'm going to look a bit more but I may end up closing this.

**Comment by blueyed** [comment]
If you miss it in the documentation, please consider improving it.. :)

**Comment by mmlb** [comment]
oh man you are absolutely right! Apologies. It seems that I misread shellcheck's `-x` argument as allowing it to whitelist certain files for "source"ing, and not what it really meant which is to allow shellcheck to follow the line to any sourced file.

Then later when I added the `-x` arg I still get an error, but this time its because I'm not in the correct directory (neomake isn't cd'ing into the directory before calling `shellcheck`, going to read docs). I just assumed it was shellcheck not wanting to source the file, and that led me down a path to wanting `b:` and not finding it.

Yup I will take a look at the documentation and see how I missed it and how I can possibly make it better.

**Comment by mmlb** [comment]
Hmm indeed the buffer local is documented, and it seems fine. I think I assumed `g:` only since I dove right into the source and saw nothing on it... :disappointed: My only suggestion re docs would be to expand all 6 properties x2 for `g:` and `b:` in the list at https://github.com/neomake/neomake/blob/master/doc/neomake.txt#L243

**Comment by blueyed** [comment]
> My only suggestion re docs would be to expand all 6 properties x2 for g: and b:

What about a list of properties only there additionally? But should be in the TOC then.
(Fully expanding would not cover the ft part)
Would you like to create a PR?
