### ISSUE TITLE
Neomake causes neovim to close quite slowly.

### ISSUE THREAD

**Issue by chrbau2711** [neomake/neomake#946]
First of all, thanks for a very handy plugin! Second, I don't really know how to debug neovim's closing procedure, so if one has any ideas on how to do it I would be pleased to dive into this problem.

### Expected behavior

Neovim closes and one can immediately type bash commands.

### Steps to reproduce

1. Open neovim.
2. Load neomake.
3. Close neovim.
4. See that you have to wait round about 2 seconds for neovim to close.

#### Neomake debug information
Async support: 1
Current filetype: 

##### Enabled makers
For the current filetype (with :Neomake): None.
NOTE: the current buffer does not have a filetype.

For the project (with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 1
 - buffer_output: 1

##### Settings
```
g:neomake_place_signs = 1


shell: /bin/zsh
shellcmdflag: -c
Windows: 0
```

#### :version
```

NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20170102-28468-abikw3/neovim-0.1.7/build/config -I/tmp/neovim-20170102-28468-abikw3/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -I/tmp/neovim-20170102-28468-abikw3/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20170102-28468-abikw3/neovim-0.1.7/build/include
Compiled by cbauer@Christians-MBP.lan

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.7/share/nvim"

```

#### :messages
```
```

**Comment by blueyed** [comment]
Which maker?  Please expand on the "Load neomake." step.

After `:NeomakeSh sleep 5` I can quit immediately.

> Neovim closes and one can immediately type bash commands.
> …
> shell: /bin/zsh

?! ;)

**Comment by chrbau2711** [comment]
It has really nothing to do with any makers. It's just the "closing mechanism". My guess is that some autocommands which are run on the `VimLeave` event causes the problem. The `init.vim` I tested with looks like this:

```
call plug#begin()
" Plug 'benekastah/neomake' " Linter and maker.
call plug#end()
```

so maybe it's a vim-plug related bug. However, with other plugins enabled neovim closes normally. And there is another plugin which causes neovim to close slowly: vim-airline. But that shouldn't be discussed in here, I believe..

**Comment by blueyed** [comment]
We're not hooking into `VimLeave`.
So with the minimal setup it also happens for you?

**Comment by blueyed** [comment]
Try `:set verb=9` (or higher) when quitting and see where it hangs and/or what it does more compared to when not running Neomake.
Do you say that just having Neomake without it being have run and/or when all makers have finished is slow?

Does my example also hang for you?  Also with the minimal config?

**Comment by chrbau2711** [comment]
OK, tried it with a completely fresh config and now neovim closes correctly, i. e. fast. Sorry for the inconvenience. Thanks for your help, though!

**Comment by blueyed** [comment]
Good to hear.
So it is not even Neomake related then?
I will close the issue, please tell me more when you find something.

**Comment by chrbau2711** [comment]
> So it is not even Neomake related then?

No it's not. 

> I will close the issue, please tell me more when you find something.

It was actually me "cleaning" my `init.vim` and somehow, during this process, I managed to install vim-plug into `~/.nvim/autoload` instead of `~/.config/nvim/autoload`.
