### ISSUE TITLE
Rust: Accumulating error signs

### ISSUE THREAD

**Issue by Ploppz** [neomake/neomake#947]
Using neomake for Rust, after a system update, the error signs don't get cleared after rebuilding (having fixed some errors and maybe gotten other errors).
They are accumulating: http://imgur.com/a/mpDIF - and persist even after I have fixed all errors and it compiles fine.

You can easily **reproduce** by creating a new project `cargo init --bin something`, write some erroneous stuff in `src/main.rs`, `:w`, write more erroneous stuff somewhere else, `:w`.

```
$ rustc --version
rustc 1.16.0-nightly (ff591b6dc 2017-01-15

$ cargo --version
cargo 0.17.0-nightly (6c79cf9 2017-01-13)
```

`Arch Linux, 4.8.13-1-ARCH`

## Config:
```
" Neomake
let g:neomake_echo_current_error=1
let g:neomake_verbose=0
autocmd! BufWritePost *.rs NeomakeProject cargo
```

**Comment by blueyed** [comment]
Is is specific to Rust?
Are you using master?
Sounds like https://github.com/neomake/neomake/pull/940.

**Comment by Ploppz** [comment]
Yes I believe I am using master, since I have `Plug 'neomake/neomake'`, using `Plugged`. Not sure if specific to Rust.. I guess I can check C or something later. I don't know what to make from that PR.

**Comment by blueyed** [comment]
That PR was meant to fix a similar issue / regression.

Do you know your way around git-bisect?
Then you could use it to find where it broke.

**Comment by Ploppz** [comment]
Sorry - I updated by `:PlugUpdate` and now I don't have the issue anymore. Thanks anyway.
