### ISSUE TITLE
NeomakeSh command not found

### ISSUE THREAD

**Issue by codeinabox** [neomake/neomake#955]
### Expected behavior

I was having a play with NeomakeSh and it works fine if I do something like `NeomakeSh "ls"` but if I do something like `NeomakeSh "nwb test"` I get the error:

> || /usr/local/bin/bash: nwb test: command not found

If do `which nwb` it reports /usr/local/bin/nwb

**Comment by blueyed** [comment]
Leave away the quotes. `which "nwb test"` will also give you `nwb test not found`.
