### ISSUE TITLE
Compilation errors after the end of the file

### ISSUE THREAD

**Issue by epilgrim** [neomake/neomake#960]
When using the `mix` maker for elixir, when there is an unclosed block, `mix compile` attaches the error to a line outside of the current file.
Eg:
```elixir
defmodule Test do
  def something do
end
```
the `mix compile` output will be:
```
== Compilation error on file web/test.ex ==
** (TokenMissingError) web/test.ex:4: missing terminator: end (for "do" starting at line 1)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

As things stand now, that line is outside the file (the file has 3 lines, the error is in line 4) and therefore no error is shown in vim in the sign column
![image](https://cloud.githubusercontent.com/assets/203349/22250532/9170f1ea-e247-11e6-83fe-a31e70685b97.png)

Is there anything that can be done here?

#### Neomake debug information
Async support: 1
Current filetype: elixir

##### Enabled makers
For the current filetype (with :Neomake):
 - mix
   errorformat: '** %s %f:%l: %m,%f:%l: warning: %m'
   args: ['exec', 'sylar_web_console', 'mix', 'compile', '--warnings-as-errors']
   get_argv: function('317')
   exe: 'docker'
 - credo
   errorformat: '[%t] %. %f:%l:%c %m,[%t] %. %f:%l %m'
   args: ['exec', 'sylar_web_console', 'mix', 'credo', 'list', '%', '--format=oneline', '-i', 'readability']
   get_argv: function('317')
   exe: 'docker'
NOTE: you can define g:neomake_elixir_enabled_makers to configure it (or b:neomake_elixir_enabled_makers).

For the project (with :Neomake!): None.
NOTE: you can define g:neomake_enabled_makers to configure it.

Default maker settings:
 - remove_invalid_entries: 0
 - buffer_output: 1

##### Settings
```
g:neomake_elixir_mix_exe = 'docker'
g:neomake_elixir_mix_args = ['exec', 'sylar_web_console', 'mix', 'compile', '--warnings-as-errors']
g:neomake_elixir_credo_args = ['exec', 'sylar_web_console', 'mix', 'credo', 'list', '%', '--format=oneline', '-i', 'readability']
g:neomake_elixir_enabled_makers = ['mix', 'credo']
g:neomake_elixir_credo_exe = 'docker'
g:neomake_place_signs = 1

shell: /bin/zsh
shellcmdflag: -c
Windows: 0
```

#### :version
```
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic
 -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/t
mp/neovim-20170114-6966-1oxvkia/neovim-0.1.7/build/config -I/tmp/neovim-20170114-6966-1oxvkia/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/loc
al/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20170114-696
6-1oxvkia/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20170114-6966-1oxvkia/neovim-0.1.7/build/include
Compiled by jperi@peri166332AL.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.7/share/nvim"
```

**Comment by blueyed** [comment]
We could have generic postprocess to not use a linenr greater than the line of buffers?
But since it's relevant for only some of the makers, it should not be used in general maybe.

**Comment by epilgrim** [comment]
if I'm not mistaken, in a postprocess I will get an entry with something like:
```
[2017-01-25T09:14:32+0100 @90.780, debug] Modified list entry (postprocess): lnum: 10 => 'lnum: ''1'' => ''0''' bufnr: 1 => 'bufnr: ''1'' => ''''' col: 0 => 'col: ''0'' => ''''' valid: 1 => 'valid: ''1'' => ''''' vcol: 0 => 'vcol: ''0'' => ''''' nr: -1 => 'nr: ''-'' => ''1''' type: '' => 'type: '''' => ''''' maker_name: 'mix' => 'maker_name: ''m'' => ''i''' pattern: '^\V(TokenMissingError)\$' => 'pattern: ''^'' => ''\''' text: 'missing terminator: end (for "do" starting at line 1)' => 'text: ''m'' => ''i'''
```
that takes me to how to get the length of a buffer.
I know that with line('$') I get the number of lines in a buffer.... but do you happen to know how to get it from an arbitrary buffer?

**Comment by blueyed** [comment]
The postprocess gets executed in the context of the affected window/buffer - at least IIRC.
