### ISSUE TITLE
Python MyPy Bug

### ISSUE THREAD

**Issue by Integralist** [neomake/neomake#997]
Raising a new issue ticket in case GitHub doesn't notify the author of my following comment:

https://github.com/neomake/neomake/pull/938/commits/4bbf20e8000f7ec4a01d5b8b9797f51aa4462143#r99601944

> @blueyed apologies but I've just come back to this and I realised there was a mistake in your refactor.  
> We only wanted to add `--fast-parser` for non-Windows user,
> where as your refactor looks to add it if you are a Windows user

**Comment by blueyed** [comment]
Thanks for reporting it, should be fixed now.
